### ISSUE TITLE
Documentation links are not secure and asus routers report them as malware

### ISSUE THREAD

**Issue by jeffreytgilbert** [fkhadra/react-toastify#1001]
Dead link because no https connection can be made
https://fkhadra.github.io/react-toastify/introduction

Malware reported by router
http://fkhadra.github.io/react-toastify/introduction

[Screenshot of malware warning](https://i.postimg.cc/xj3nZxwL/Screenshot-2023-09-19-at-11-27-41-PM.png)

**Comment by fkhadra** [comment]
Sounds weird to me, most likely something with your router. I'm using Github pages, nothing that can be done on my side.
