### ISSUE TITLE
ReactToastify.css.map not found in Next 13 (/app folder)

### ISSUE THREAD

**Issue by Lucasmm016** [fkhadra/react-toastify#1002]
**Do you want to request a *feature* or report a *bug*?**
- bug

**What is the current behavior?**
- When trying to import the css from the React-tostify lib `import 'react-toastify/dist/ReactToastify.css'` I receive the following error in the console:
- `Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/_next/static/css/app/ReactToastify.css.map`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
- Everything works normally, but the error message appears in the console only when importing the styling.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- All

- Note: All toast components and their styles seem to work normally for me, everything goes well as well as transitions, styles and everything else, the only problem is the error message that appears in the console, even when running Next 13 in development or production. I tested importing the React-Tostify css style within my root layout (layout.tsx) and also within my common page (page.tsx).

**Comment by parth305** [comment]
copy all the code of ReactToastify.css file and paste into new css file of your own. then import that file.
