### ISSUE TITLE
when i set limit 1 , showing extra notifications 

### ISSUE THREAD

**Issue by MehulFreelancing** [fkhadra/react-toastify#1006]
Hear is my simple code
import logo from './logo.svg';
import './App.css';
import { toast } from 'react-toastify';
import { useState } from 'react';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

function App() {
  const notify = ()=>{
      toast.success("hello")

  }

  return (
    <div className="App">
        <button onClick={notify}>Notify!</button>
      <ToastContainer autoClose={1000} limit={1}/>
    </div>
  );
}

export default App;

**Comment by fkhadra** [comment]
Should be fixed in v10 releasing soon
