### ISSUE TITLE
Duplicate declaration encountered during compilation

### ISSUE THREAD

**Issue by yunstv** [fkhadra/react-toastify#1013]
In the compiled dist file, there is a duplicate declaration of 'use strict'.
<img width="805" alt="image" src="https://github.com/fkhadra/react-toastify/assets/17945292/834dcfaf-8ede-4dba-85e8-4a82063518b8">

I think it should be a bug caused by **prepend-use-client.sh** in the source file.
![image](https://github.com/fkhadra/react-toastify/assets/17945292/863f9f0f-a6d5-4664-84b0-a50c97e51f2b)

**Comment by fkhadra** [comment]
No sure to understand what the issue is. `use client` is added to each output file.

**Comment by yunstv** [comment]
> No sure to understand what the issue is. `use client` is added to each output file.

Oh, my mistake, I thought there was duplicate code. I'm sorry for the interruption.
