### ISSUE TITLE
toast styles/css not working in iframes or shadow-dom

### ISSUE THREAD

**Issue by Adnan-Saleem-93** [fkhadra/react-toastify#1014]
I'm using react-toastify in a Chrome Extension Content Script. The App is built using React JS. To isolate the CSS of my app, I have to use either ShadowDOM or iFrames in the extension. Everything is working fine except that the styling of roast-toastify is not working. Neither in ShadowDOM nor in iFrames. How can I use/enable the styling inside them?

**Comment by fkhadra** [comment]
Hey @Adnan-Saleem-93 have you tried https://fkhadra.github.io/react-toastify/how-to-style/#inject-style-on-demand ?
