### ISSUE TITLE
Add Data as generic type

### ISSUE THREAD

**Issue by julioflima** [fkhadra/react-toastify#1017]
## Enhancement

You could add the Data type as generic to the component ToastContainer, since this global.

Look at this example:
```jsx
  function Form() {
    // ...
  
    return (
      <Select<string>
        options={targets}
        value={target}
        onChange={setTarget}
      />
    );
  }
```

https://mariusschulz.com/blog/passing-generics-to-jsx-elements-in-typescript

**Comment by fkhadra** [comment]
Kind of linked to #991
