### ISSUE TITLE
Pass a component like icon to override the content

### ISSUE THREAD

**Issue by julioflima** [fkhadra/react-toastify#1018]
## Feature

To implement a personalized toasts like in below:

I had to override all `toast.error` and `toast.success`

```javascript
toast.error(DataToast, {
     data: { content: t('account_details.phone_number_verification.attempt_failed') }
});
```

So the solution to achieve this, maybe could be passing a general component, to achieve change in all toasts the dev just gonna have to update in one place.

I'd like to thank you about this awesome lib, in special passing the status of the type triggered as prop.

![image](https://github.com/fkhadra/react-toastify/assets/17098382/d5095b6c-9780-4dba-9e81-f7e1250d6b0f)

**Comment by fkhadra** [comment]
Hey @julioflima not sure to fully understand your request, could you share more details please?
