### ISSUE TITLE
Conditionally prevent toast on error with toast.promise?

### ISSUE THREAD

**Issue by shueja** [fkhadra/react-toastify#1023]
I'm using `toast.promise()` with success and error messages. For most errors, I have the toast show the error message. However, if the error message contains "User_Requested_Stop", I want no toast to show. Is there something I can return from the `error` callback in toast.promise() to not actually show a toast?

**Comment by makibat** [comment]
Have you tried this approach 
```
       error: {
          render({ toastProps, data }) {
            if (data.message === "User_Requested_Stop") {
              toastProps.style = { visibility: 'hidden' };
            }

            return data.message;
          }
        }

```

**Comment by shueja** [comment]
I’d missed the `toastProps` option. That should work well for this, thanks!
