### ISSUE TITLE
`onClick` prop for toast is deprecated. What is equal replacement?

### ISSUE THREAD

**Issue by cybertino** [fkhadra/react-toastify#1024]
When you use the prop, comment says: `You can pass a react component with you handler instead.` but this handler only applies to the content component.

Is there any handler that is applicable to the whole toast element? If not, should it be deprecated then?

Also documentation does not reflect that this prop is deprecated.

**Comment by fkhadra** [comment]
Hey @cybertino, I'll publish a patch version to remove the deprecated notice. I don't have a suitable alternative for now, so I'll rollback my decision.

**Comment by cybertino** [comment]
Thanks @fkhadra!
