### ISSUE TITLE
Error typescript check ref.current

### ISSUE THREAD

**Issue by rullymartanto** [fkhadra/react-toastify#1025]
I tried using it  in a React TypeScript project and attempted to add programmatic closing functionality, but encountered this ts error, anybody get the same issue?

![image](https://github.com/fkhadra/react-toastify/assets/5577057/233e22cb-6771-44b6-ae10-4233afe3c5e7)

**Comment by fkhadra** [comment]
Hey @rullymartanto your ref is typed as `null`. Do as follow
```ts
useRef<number|string>()
```
