### ISSUE TITLE
css doesn't work in 3.1.0

### ISSUE THREAD

**Issue by yq314** [fkhadra/react-toastify#103]
setting css with glamor doesn't work in 3.1.0, tried the example in document, no effect at all.

**Comment by fkhadra** [comment]
Hey @yq314 ,

Could you share a sample ? It will be easier to troubleshoot.

Thanks

**Comment by yq314** [comment]
Hi @fkhadra ,

I just ran a simple react app with this code:
```
 import React from 'react';
 import { ToastContainer, toast } from 'react-toastify';
 import { css } from 'glamor';

 class App extends React.Component {
     closeAfter15 = () => toast("YOLO", { autoClose: 15000, className: css({
         background: "black"
       }) });

     closeAfter7 = () => toast("7 Kingdoms", { autoClose: 15000 })

     render(){
         return (
             <div>
             <button onClick={this.closeAfter15}>Close after 15 seconds</button>
             <button onClick={this.closeAfter7}>Close after 7 seconds</button>
             <ToastContainer autoClose={8000} />
             </div>
         );
     }
 }

 export default App;
```
click on the two buttons trigger the same toast with the default color, however the first one is supposed to be black.

**Comment by fkhadra** [comment]
@yq314 you have to use `backgroundColor` instead of `background`. My mistake, I'll fix the doc right now.

Here is a working snippet:
[![Edit React-toastify fix issue #103](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xo41ym8x9p)

**Comment by fkhadra** [comment]
@yq314 I updated the doc btw 😁

**Comment by yq314** [comment]
![react toastify fix issue 103 codesandbox](https://user-images.githubusercontent.com/2336852/33998090-7ba787fa-e121-11e7-9050-db9e9afb2bba.png)
The CodeSandbox example doesn't seem to work for me?

**Comment by yq314** [comment]
I'm using Chrome 62.0.3202.94 btw

**Comment by fkhadra** [comment]
We are using the same version. It's working for me. Could you try to refresh ? Maybe a cache issue.
![image](https://user-images.githubusercontent.com/5574267/33998254-4b2a621c-e0e7-11e7-9ed4-90d6e04e6081.png)

**Comment by yq314** [comment]
hmm, so weird, I cleared cache still no luck, tried in incognito mode also same...

**Comment by yq314** [comment]
it doesn't work for me on both my PC and Mac...

**Comment by fkhadra** [comment]
I'll try with create-react-app to see what's going on

**Comment by fkhadra** [comment]
Classes are not merged correctly.

**Comment by fkhadra** [comment]
@yq314 got a fix.

**Comment by yq314** [comment]
thanks for the quick action! @fkhadra

**Comment by fkhadra** [comment]
@yq314 the new release is live 🚀

**Comment by yq314** [comment]
marvellous, this saved my life thanks @fkhadra
