### ISSUE TITLE
v9  limit  problem

### ISSUE THREAD

**Issue by lzt-T** [fkhadra/react-toastify#1030]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug
**What is the current behavior?**
limit =3 .
Before 3 is correct, but after 3 there is obviously a repeat popup.
After 3, all the pop-up Windows are displayed one by one, and there is no case of showing three at the same time.

![image](https://github.com/fkhadra/react-toastify/assets/87354337/c1022d5f-3a45-4061-b766-3700ff384f81)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by fkhadra** [comment]
I beleive it should have been fixed with the latest release.
