### ISSUE TITLE
Please bump clsx

### ISSUE THREAD

**Issue by maybephilipp** [fkhadra/react-toastify#1033]
**Do you want to request a *feature* or report a *bug*?**

I'm requesting bug? maybe feature 😄 

**What is the current behavior?**

react-toastify requires clsx@1

**What is the expected behavior?**

Could you please bump or allow clsx@2 to be used/installed? What I have now is that it forces all my mini-repos in monorepo to use their own copy of clsx@2 in each, which is awful.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All

**Comment by fkhadra** [comment]
Hey @maybephilipp  just published v10. It bumps all dependencies.
