### ISSUE TITLE
Console warning: React does not recognize the `isLoading` prop on a DOM element

### ISSUE THREAD

**Issue by cduff** [fkhadra/react-toastify#1035]
New issue in v10.0.0.

Seems to be related to new feature: https://fkhadra.github.io/react-toastify/migration-v10#iconprops-now-receives-isloading

Minimal reproduction:
- https://codesandbox.io/p/sandbox/react-toastify-isloading-issue-svhc3m
- Open console
- Click "toast" button
- See warning logged to console:

```
Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
  at svg
  ...
```

**Comment by fkhadra** [comment]
Addressed with the latest patch
