### ISSUE TITLE
dismiss / dismissAll for TS

### ISSUE THREAD

**Issue by keljond27** [fkhadra/react-toastify#104]
TS interface for toast doesn't allow for dismiss argument to be optional - 
current: `dismiss(toastId: number): void;` 
should be: `dismiss(toastId?: number): void;`

This would allow user to forgo using toastId and enable dismissing all active toast messages

**Comment by fkhadra** [comment]
Thank @keljond27  for reporting the issue. It's fixed and will be live soon.

**Comment by fkhadra** [comment]
@keljond27 the new release is live 🚀
