### ISSUE TITLE
How do fully customize everything?

### ISSUE THREAD

**Issue by guikaua12** [fkhadra/react-toastify#1046]
Hi, how do i fully customize everything? Like, place progress where i want, style progress parent, etc
I have this design where the progress is place on the side of that left div with a icon:
![image](https://github.com/fkhadra/react-toastify/assets/33811154/1d941257-c6ad-4104-8808-bbbddee7f82d)

**Comment by jocanola** [comment]
@guikaua12 you can create your on component and use it this way
`
      toast(
        <NotificationMessage
          status="success"
          title="Forget Password"
          description={response.data.message}
        />,
      );`
      
 And If you want to customize the container or anything you can checkout [Override css variables](styling https://fkhadra.github.io/react-toastify/how-to-style)

**Comment by guikaua12** [comment]
> @guikaua12 you can create your on component and use it this way ` toast( <NotificationMessage status="success" title="Forget Password" description={response.data.message} />, );`
> 
> And If you want to customize the container or anything you can checkout [Override css variables](styling https://fkhadra.github.io/react-toastify/how-to-style)
> 
> Notification component is the custom component I created

Hi, thank you, but i need to modify the "left" property of the progress bar wrapper, there is no css variable to modify that
