### ISSUE TITLE
Not working properly with picocss

### ISSUE THREAD

**Issue by dracu-lah** [fkhadra/react-toastify#1052]
i have configured react-toastify with picocss and it seems to be not working properly with picocss. Fixing this would be helpful

**Comment by fkhadra** [comment]
Hey @dracu-lah, may I ask you to reproduce your issue using codesanbox or stackblitz? That would be super helpful thank you.

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
