### ISSUE TITLE
Cannot read properties of undefined (reading 'props') at deleteToast

### ISSUE THREAD

**Issue by jeymus** [fkhadra/react-toastify#1053]
# :bug:Bug
```
TypeError: Cannot read properties of undefined (reading 'props') at deleteToast in withTranslation.js
```
This error appears on [v10.0.0](https://github.com/fkhadra/react-toastify/releases/tag/v10.0.0) and above, and is triggered when the toast is dismissed immediately after rendering.
This is a similar issue to one that was previously fixed in [v9.1.3](https://github.com/fkhadra/react-toastify/releases/tag/v9.1.3) but it has now appeared again. I have tested on [v9.1.3](https://github.com/fkhadra/react-toastify/releases/tag/v9.1.3) with no issues.
**[v9.1.3](https://github.com/fkhadra/react-toastify/releases/tag/v9.1.3)'s release note:**
> Partially address `Toast is undefined || Uncaught TypeError: Cannot read properties of undefined (reading 'content')` #858 #952 

**Basic example:**
```
const handleClick = async (e) => {
    const toastId = toast.loading('Loading')
    try {
        return console.log('Test log')
    }
    catch (error) {
        console.error(error)
    }
    finally {
        toast.dismiss(toastId)
    }
}
```

**Comment by duythinh-dev** [comment]
Any solution on this?
I'm facing the same problem

**Comment by arenier** [comment]
Same issue here

**Comment by gajraj-gan** [comment]
Same

**Comment by abdullahhjiim** [comment]
same issue here

**Comment by dolev7** [comment]
same

**Comment by bhimeshchauhan** [comment]
bump

**Comment by Souvik2003K** [comment]
wherever in your code you want to manually close the toast just put this code(mine worked) - 
```javascript
if (toast.isActive(null)) { // Check if any toast is active
    toast.dismiss();
} else {
    console.warn("Toast not found for dismissal");
}
```

**Comment by bhimeshchauhan** [comment]
For me, the issue was:
- There were multiple toasts being created in the container
  - Adding `enableMultiContainer` and `containerId="<unique-id>"` helped
- The toast was being closed before it opened
  - Adding timeout to close, helped
