### ISSUE TITLE
The documentation gives an example of an error

### ISSUE THREAD

**Issue by mihilt** [fkhadra/react-toastify#1054]
https://fkhadra.github.io/react-toastify/introduction/#the-playground

In this documentation, I noticed that if I change some options below, it shows the changed code directly.
So I set some options to make what I wanted to use.

But I found only the `translation` attribute had the `:`(colon) like a javascript object.
Even after changing the `transition` setting, this issue still occurred.

<kbd>![image](https://github.com/fkhadra/react-toastify/assets/50368758/c81a1eb5-ce39-4134-a9c2-f918e7e42d22)</kbd>

I guess this example should be changed this way.

```jsx
<ToastContainer
	// other props...
  transition={Bounce}
  />
```

**Comment by fkhadra** [comment]
The documentation will get a refresh soon.
