### ISSUE TITLE
Add generic onOpen and onClose event handles to ToastContainer

### ISSUE THREAD

**Issue by jonluca** [fkhadra/react-toastify#1059]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There are no event handlers on <ToastContainer />

It would be nice to able to log every toast that appears

**Comment by fkhadra** [comment]
Closing as this can be accomplished on outside the library with `toast.onChange`

**Comment by jonluca** [comment]
https://github.com/fkhadra/react-toastify/pull/1060/files this is the implementation I was talking about. But sounds good, no worries
