### ISSUE TITLE
Add support for functions as content

### ISSUE THREAD

**Issue by giocodes** [fkhadra/react-toastify#106]
Hello! First of all, THANK YOU this is a great library. 👏 X1000
I want to suggest adding support for functions as content. Example:
```javascript
toast(({ closeToast }) =>
  <div>
    <p onClick={handlerX}>Do something</p>
    <p onClick={closeToast}>Close</p>
  </div>
);
```
I believe this currently returns nothing.

**Comment by fkhadra** [comment]
Hello @giocodes,

Glad you like it.

When you call the `toast` function it returns a `toastId`. That one can be used to dismiss or to update the toast.

Anyway, I will probably allow this pattern in the next release. I'll let you know as soon as it's available.

**Comment by fkhadra** [comment]
Feature released.

**Comment by giocodes** [comment]
Awesome! Thanks
