### ISSUE TITLE
Toast Timers Reset on New Toast Addition with newestOnTop/Bottom-Right/useEffect Configuration

### ISSUE THREAD

**Issue by orenk1** [fkhadra/react-toastify#1063]
**Do you want to request a *feature* or report a *bug*?**
Bug

Request Type: Bug Report

Description of the Issue:
When utilizing toast() within a useEffect hook to display toast notifications with the configuration set to position: "bottom-right" and newestOnTop: true, the timers of all existing toasts are reset to match the timer of the newest toast, starting from the addition of the third toast onward. This issue leads to unexpected behavior where all toasts synchronize their countdowns with each newly added toast, rather than each toast counting down independently as expected. **Removing the newestOnTop configuration resolves the issue**, suggesting a specific interaction problem between these settings.

Steps to Reproduce:

- Create a React component that uses useEffect to trigger toast() notifications.
- Configure the ToastContainer with position="bottom-right" and newestOnTop={true}.
- Dynamically add toast notifications, observing the behavior from the third toast addition onwards.
- Notice that with each new toast added, the countdown timers of all previous toasts are reset.

Expected Behavior:
Each toast should countdown independently, without affecting the timers of previously displayed toasts, regardless of the number of toasts added.

Current Behavior:
From the third toast onwards, any new toast addition resets the countdown timers of all existing toasts.

Minimal Reproduction Demo:
https://codesandbox.io/p/devbox/ttfy-2snj3w?file=%2Fsrc%2FApp.js%3A40%2C20

Affected Environments:
 All desktop browsers

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
