### ISSUE TITLE
Toaster is not rendered when ToasterContainer is at the root i.e App.tsx

### ISSUE THREAD

**Issue by naivecoder786** [fkhadra/react-toastify#1064]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
![image](https://github.com/fkhadra/react-toastify/assets/117038957/a05aa792-1e2a-4bf1-b4bb-28c1fdd0d986)
I am facing an issue when the **ToasterContainer** is placed at the root i.e **App.tsx** the toaster doesnt get rendered at all, but when placed inside the MuiBox-root it works just fine. 

PS: I cant place it inside the MuiBox-root since it creates a tight coupling between them and I am planning to publish those MuiComponents as library so dont want the ToasterContainer in it !

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Will try to create and post in the following comments soon enough

**What is the expected behavior?**
Should work just fine without any issues

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 18

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
