### ISSUE TITLE
how i can use this with next js 14

### ISSUE THREAD

**Issue by Satyaaam** [fkhadra/react-toastify#1065]
i have to 
 import { ToastContainer, toast } from 'react-toastify';

in every page, can anyone tell me, how to get rid of this

**Comment by slackerzz** [comment]
add the `<ToastContainer ... />` in the root layout of you app

**Comment by Satyaaam** [comment]
But there is not root directory in it I guess. Will adding this in page.js of app folder work ????

**Comment by slackerzz** [comment]
take a look here: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required
