### ISSUE TITLE
Ability to add positioning offset

### ISSUE THREAD

**Issue by jwheeler-gs** [fkhadra/react-toastify#108]
It looks like with the current setup, there is no way to add an offset to the toast container. For example, when I open a toast in "TOP_RIGHT", it's always 1em from top and 1em from right.

My application has a couple of menu bars at the top that I'd like to position the toast below, so I'd like to be able to specify a top offset of "110px" instead of 1em, but only for toasts positioned in TOP_. I can work around this right now by overriding the container style to always have a top offset of 110px, but that fails if I position any toasts using BOTTOM_.

**Comment by fkhadra** [comment]
Hey @jwheeler-gs,

What do you think if I allow defining those settings via the style helper? For instance:

```js
import { style } from 'react-toastify';

style({
  TOP_LEFT: { top: '110px', right '110px' },
  BOTTOM_RIGHT: {/* style goes here and so on */ }
});
```

What do you think about the api ?

**Comment by jwheeler-gs** [comment]
Yes, I think that would be fine. :D  That's actually what I originally tried to do before looking at the code and seeing that it was not supported.

**Comment by fkhadra** [comment]
Feature released.

**Comment by jwheeler-gs** [comment]
Excellent. Thanks @fkhadra!
