### ISSUE TITLE
Issue with Progress Bar Positioning After Update in Safari Version 10

### ISSUE THREAD

**Issue by abhishekantala24** [fkhadra/react-toastify#1083]
**Do you want to request a *feature* or report a *bug*?**
Bugs

**What is the current behavior?**
Before the update, specifically in Safari version 10, the progress bar was not functioning properly. After the update, I attempted to set the position to top-right in the existing code. However, upon installation, the toastify appeared at the top-left instead.

**What is the expected behavior?**
The progress bar should function correctly after the update, with its position set to top-right as intended.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This issue occurred after installing the latest version.

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
