### ISSUE TITLE
Support for max() and env() functions in older browsers

### ISSUE THREAD

**Issue by abhishekantala24** [fkhadra/react-toastify#1086]
**Do you want to request a *feature* or report a *bug*?**
bugs

**What is the current behavior?**
 The positioning of elements is not working as expected in older browsers such as Safari 10 and 11. This is due to the use of the max() and env() CSS functions, which are not supported in these browsers. As a result, the layout and positioning defined in the CSS are not being applied correctly, leading to inconsistencies and rendering issues.

This description highlights the specific issue related to positioning and explains the cause, which is the lack of support for modern CSS functions in older browsers.

**What is the expected behavior?**
The max() and env() functions should be supported in older browsers to ensure consistent rendering and layout across different browser versions.

**Which versions of React, and which browser / OS is affected by this issue? Did this work in previous versions of React?**
React: 18
Browsers Affected: old Browser
Operating System: OS

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
