### ISSUE TITLE
Syntax Error or a Bug in documentation

### ISSUE THREAD

**Issue by arnavnagpurkar** [fkhadra/react-toastify#1091]
Bug

**What is the current behavior**
In the website https://fkhadra.github.io/react-toastify/introduction/ The "Toast Container" has a bug.
![image](https://github.com/fkhadra/react-toastify/assets/84492896/96e449a7-7008-4dcf-ac47-0d288f5f7289)
in the `<ToastContainer/>` there is a attribute `transition` where `:` semicolon is added instead of `=` equal too sign.
When we assign value to attributes we need to insert `=` sign instead of `:` semicolons as in JSON.
And the value `Bounce` must also be enclosed in the quotes or double quotes.
If user will copy from this documentation then he'll face errors.

**expected behaviour**
User should not face error.
We need to updated it in the documentation to:
```html
<ToastContainer
  position="top-right"
  autoClose={5000}
  hideProgressBar={false}
  newestOnTop={false}
  closeOnClick
  rtl={false}
  pauseOnFocusLoss
  draggable
  pauseOnHover
  theme="light"
  transition="Bounce",
/>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This issue is applicable to all versions of react and next.js

**Comment by cjboco** [comment]
I believe is should be:

```
import { ToastContainer, Bounce } from 'react-toastify';

<ToastContainer
position="top-right"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition={Bounce}
/>
{/* Same as */}
<ToastContainer />
```

transition needs a ToastTransition | undefined

**Comment by ethubert** [comment]
I agree, it's a bug.

**Comment by fkhadra** [comment]
The documentation will get a refresh soon thanks for reporting.
