### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useReducer')

### ISSUE THREAD

**Issue by Ignem12** [fkhadra/react-toastify#1095]
I am trying to learn React and build a frontend for a contract and the following error keeps appearing:
![Screenshot 2024-04-02 135247](https://github.com/fkhadra/react-toastify/assets/150669971/4ec7dc2f-d966-46c3-bb27-27ed55d55a12)

Dependencies:
`"dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.93",
    "@types/react": "^18.2.73",
    "@types/react-dom": "^18.2.23",
    "ethers": "5.6.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  }`

```
import React from 'react';
import { ChainId, DAppProvider } from '@usedapp/core';

function App() {
  return (
  <DAppProvider config={{
    supportedChains: [ChainId.Sepolia]
  }}>
    <div>Hi!</div>
  </DAppProvider>
  );
}

export default App;
```

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
