### ISSUE TITLE
types definitions issue

### ISSUE THREAD

**Issue by TonticiOleg** [fkhadra/react-toastify#110]
wanted to create a pull request but..

In type definitions file - method signature declaration is wrong - mean cannot be compiled
type ToastContent = React.ReactNode | () => void;      instead of
type ToastContent = React.ReactNode | { () : void };

**Comment by fkhadra** [comment]
Hey @TonticiOleg,

Thank you for reporting the issue. Just pushed a new build. It will be live in a few minute.
