### ISSUE TITLE
Toast Conflicting or loading infinite in promise at concurrent requests

### ISSUE THREAD

**Issue by vikassharmasat** [fkhadra/react-toastify#1101]
The toast don't close if API Request function is centralized and in scenario of concurrent requests. It will process only one result others will be in infinite.

there are some screenshots please check

`
import { Bounce, toast } from "react-toastify";

export class ToastUtil {
    constructor( unique_key ) {
        this.toast_id = {};
        this.unique_key = unique_key;
        this.toastify_options = {
            position: "top-right",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
            theme: "colored",
            transition: Bounce,
            isLoading: false,
        };
        this.toast = toast;
    }

    showToast() {
        console.log( this.toast_id, 'this is toast id' )
        this.toast_id[this.unique_key] = this.toast.loading( `Please wait success...` );
    }

    updateToast( message, type ) {
        this.toast.update( this.toast_id[this.unique_key], {
            render: message,
            type,
            ...this.toastify_options,
        } );
        this.hideToast();
    }

    hideToast() {
        // this.toast.clearWaitingQueue();
        // this.toast_id = null;
       // delete this.toast_id[this.unique_key];
        console.log( Object.keys( this.toast_id ) );
       setTimeout(() => {
           Object.keys(this.toast_id).forEach(key => toast.dismiss(key));
       },5000);
    }
}

<img width="605" alt="api call" src="https://github.com/fkhadra/react-toastify/assets/73014787/cee39203-23be-4d66-9bdf-1238bce71cfa">
<img width="307" alt="infinite progress" src="https://github.com/fkhadra/react-toastify/assets/73014787/ad153524-6968-419c-b719-c8b820b0af86">
<img width="391" alt="network tab" src="https://github.com/fkhadra/react-toastify/assets/73014787/9f17d4e4-12f7-46b2-87f1-d45c405737e9">
<img width="557" alt="all keys are avaialbe" src="https://github.com/fkhadra/react-toastify/assets/73014787/50aff74c-ba1e-41f1-955f-e29339a8a2d3">
`

**Comment by kathanshah1206** [comment]
Here is the solution:-
(call the toast first )
![image](https://github.com/fkhadra/react-toastify/assets/97287116/3c8c8e69-bb74-4159-b336-786f1f967a34)
