### ISSUE TITLE
Toast doesn't work when using with axios and redux-thunk

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [fkhadra/react-toastify#111]
When I try to show a toast with a function **that has** a action dispatcher with axios along with redux-thunk, the toast doesnt appear. but when I just comment out the action dispatcher It works fine. note ( It doesnt matter whether I fire before or after the action dispatch call )

![screen shot 2017-12-23 at 1 49 54 am](https://user-images.githubusercontent.com/21335564/34311463-c1ec6092-e783-11e7-9dde-abc1e3925ee9.png) ---- works fine with action dispatch commented
![screen shot 2017-12-23 at 1 50 14 am](https://user-images.githubusercontent.com/21335564/34311464-c22d2c1c-e783-11e7-981e-14c5053954fd.png) ----  doesnt work with action dispatch
![screen shot 2017-12-23 at 1 50 21 am](https://user-images.githubusercontent.com/21335564/34311465-c2575906-e783-11e7-99bd-936473dcc25f.png)   --- my action dispatch

**Comment by fkhadra** [comment]
Hey @GaudamThiyagarajan,

I'll try to reproduce the issue.

**Comment by fkhadra** [comment]
Hello @GaudamThiyagarajan,

Could you provide me the following information's so I can try to reproduce the issue:
- react version
- redux version
- react-toastify version

Thanks

**Comment by heyhujiao** [comment]
I can verify this issue occurs for me too. Using reduxThunk as middleware

**Comment by fkhadra** [comment]
Thank for the feedback. I'll to find a boilerplate to reproduce the issue

**Comment by heyhujiao** [comment]
If it helps, these are my packages version.

"react": "^15.6.2",   
"redux": "^3.0.4",
"react-toastify": "^3.2.2"

**Comment by fkhadra** [comment]
Thanks guys. I'll work on it this week.

**Comment by fkhadra** [comment]
I tried to reproduce the issue using this [boilerplate](https://github.com/Angelfire/React-Redux-Thunk-Boilerplate) without success.

Could you suggest me another boilerplate to try ?

**Comment by GaudamThiyagarajan** [comment]
Did you try with same versions of react redux and axios as I have mentioned?

Please try following similar versions.

**Comment by fkhadra** [comment]
@GaudamThiyagarajan I never had an issue combining axios and react-toastify. 
I don't use redux for state management, this is way I used a boilerplate found on github. If you can setup a boilerplate on codesanbox it will help me to find what's going on.

**Comment by fkhadra** [comment]
Hey @GaudamThiyagarajan,

Could you update to the latest version v3.3.4 and tell me if it fixes your issue, please.

Thank you

**Comment by SaeedSheikhi** [comment]
Hello @GaudamThiyagarajan 

i think you are involved with hard coding,
previously i was working with redux thunk and axios upload progress event listener,  toastify could intergrate with that in an awesome super easy way.


it's better to take this approach
in your action func

```javascript
const updateLogout = () => dispatch => {
    try {
       const res = await axios.post('/logout');
       // nice, we dont have any error and status code is OK so no error will catch, go to the next line
       toast.success('logged out successfully')
        updateLogginOut();
    }
    catch(err){
        //ops internal server err or bad status code is occured
        toast.error('somthing went wrong, sry about that')
    }
}
```


and then move your if statement in [componentWillUpdate](https://medium.com/@baphemot/understanding-reactjs-component-life-cycle-823a640b3e8d)and everythink will be ok, i hope :D

and :D sry for any typo...

**Comment by GaudamThiyagarajan** [comment]
**@SaeedSheikhi**  thanks for the suggestion let me check.
 **@fkhadra**  will update to version you specified and let you know if it works. 
Sorry Im currently busy working on something else right now.

Thanks for your help guys

**Comment by TravisKool** [comment]
I am having the same issue with these versions:
    "react-scripts": "3.0.0",    
    "react-toastify": "5.3.1"
    "redux": "4.0.4"
    "redux-thunk": "2.3.0"

It seems to be intermittent. sometimes it works. sometimes it only shows the loading toast. 'IM HERE' always shows.

```
function getPosts() {
  return dispatch => {
    dispatch(getPostsPending());
    toast.info("Loading posts...", { autoClose: 2000 });

    postService.getPosts().then(
      posts => {
        dispatch(getPostsSuccess(posts));
        console.log('IM HERE');
        toast.success("Enjoy!", {autoClose: 2000 });
      },
      error => {
        dispatch(getPostsError(error));
      }
    );
  };
}
```
