### ISSUE TITLE
The timer stops

### ISSUE THREAD

**Issue by Dodolist** [fkhadra/react-toastify#1115]
**Do you want to request a *feature* or report a *bug*?**
Bug

---

**What is the current behavior?**
When I drag and release the toast message, the timer works if my finger is outside the toast message area, but the timer stops when I place my finger inside the toast message area.

---

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

---

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested in Chrome and Safari(iOS)

If my issue

**Comment by fkhadra** [comment]
Hey @Dodolist I believe you have to set `pauseOnHover` to false to disable that behavior.
