### ISSUE TITLE
word wrap

### ISSUE THREAD

**Issue by neetocode** [fkhadra/react-toastify#112]
How i do it?

`toast.warn("Error 400\nField text invalid")`

`\n` and `<br/>` not wrapping text.

**Comment by fkhadra** [comment]
Hello @neetocode,

You could use jsx instead as follow:

```js
toast.warn(<div>Error 400 <br />Field text invalid<div>)
```
Quote are not needed with jsx.

**Comment by neetocode** [comment]
cool!

**Comment by kingleuther** [comment]
How about if we are using .js? How are we going to have a new line

**Comment by Navaruban** [comment]
So, How to pass a variable inside toast
for example
var msg= 'Hello World';
i passed this msg varible into toastr like this...
toast.error(<div>msg<div>)

the toaster is showing "msg" not "Hello World".
 someone give the right solution pls

**Comment by fkhadra** [comment]
@Navaruban you could do as follow:

```js
let msg = "Hello";

toast.error(() => <div>${msg}</div>);
```

**Comment by Teenterror** [comment]
I have a long text like  

` toast.success("MYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESS");`

The above text is not getting word wrap. The text is beyond the display part of toast. 
![asdfasdfScreenshot from 2020-04-02 20-02-19](https://user-images.githubusercontent.com/40669850/78262924-ea624980-751e-11ea-940a-1caa899a2e4e.png)

**Comment by biswaranjannaik** [comment]
> I have a long text like
> 
> ` toast.success("MYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESS");`
> 
> The above text is not getting word wrap. The text is beyond the display part of toast.
> 
> Need the second toast to be word wrap
> 
> ![asdfasdfScreenshot from 2020-04-02 20-02-19](https://user-images.githubusercontent.com/40669850/78262924-ea624980-751e-11ea-940a-1caa899a2e4e.png)

Did you find any solution for this @fkhadra ?

**Comment by alierdogan7** [comment]
I've found a solution. Just override `.Toastify__toast-body` CSS class by adding `word-break: break-word;` CSS property as instructed in the [documentation](https://fkhadra.github.io/react-toastify/how-to-style#override-existing-css-classes). It has successfully wrapped the text inside the toast container.

**Comment by alierdogan7** [comment]
> > I have a long text like
> > ` toast.success("MYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESSMYSUCCESS");`
> > The above text is not getting word wrap. The text is beyond the display part of toast.
> > Need the second toast to be word wrap
> > ![asdfasdfScreenshot from 2020-04-02 20-02-19](https://user-images.githubusercontent.com/40669850/78262924-ea624980-751e-11ea-940a-1caa899a2e4e.png)
> 
> Did you find any solution for this @fkhadra ?

I've found a solution. Just override `.Toastify__toast-body` CSS class by adding `word-break: break-word;` or `break-all` CSS property as instructed in the [documentation](https://fkhadra.github.io/react-toastify/how-to-style#override-existing-css-classes). It has successfully wrapped the text inside the toast container.

**Comment by kthakor-vn** [comment]
@alierdogan7  How can i override that class 
throw toast(error.response.data.error, { className: "toast-message" });

My external css file is 
.toast-message {
  background: darkblue;
  color: #fff;
  font-size: 20px;
  width: 34vw;
  padding: 30px 20px;
 word-break: normal;
}
