### ISSUE TITLE
Update Readme for addons > useNotificationCenter

### ISSUE THREAD

**Issue by adityadevx** [fkhadra/react-toastify#1123]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
  When importing useNotificationCenter it gives a error module not found. 

**What is the expected behavior?**
It should have imported the  useNotificationCenter from "react-toastify/addons/useNotificationCenter"

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 "react":"^18"

**Comment by KamuiMaster** [comment]
in case you dont know what changed: start by changing the import from:

import { useNotificationCenter } from "react-toastify/addons/useNotificationCenter";

to:

import { useNotificationCenter } from "react-toastify/addons/use-notification-center";
