### ISSUE TITLE
`newestOnTop` Property in `react-toastify` Reversed Behavior

### ISSUE THREAD

**Issue by BunnyBharath91** [fkhadra/react-toastify#1132]
**Issue: `newestOnTop` Property Behavior Reversed**

The `newestOnTop` property in `react-toastify` behaves in reverse. Setting `newestOnTop` to `true` makes new toasts appear at the bottom, while setting it to `false` makes them appear at the top.

#### Expected Behavior

- `newestOnTop: true` → New toasts should appear at the top.
- `newestOnTop: false` → New toasts should appear at the bottom.

#### Actual Behavior

- `newestOnTop: true` → New toasts appear at the bottom.
- `newestOnTop: false` → New toasts appear at the top.

Thank you!

**Comment by fkhadra** [comment]
The issue has been solved with the latest release.
