### ISSUE TITLE
Toast.dimiss() not working probably

### ISSUE THREAD

**Issue by demonzmahmood** [fkhadra/react-toastify#1134]
Hi everyone ,

I want to use toast.dismiss() but I received undefined reading of property "Props".
The solution was to remove React Strict Mode but I need it since it helps me solve my issues.

Thanks

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
