### ISSUE TITLE
Toast does not look right on mobile

### ISSUE THREAD

**Issue by dmbrooking** [fkhadra/react-toastify#114]
A few things.. when mobile, the toast does not take over the entire view width.  Also, I have my toast set to be positioned in the bottom right, but when mobile, it shows on the bottom left.

I am guessing this is due to some style I have in my css that is conflicting with this component... just not sure where or what.

Could someone point in the right direction of what might be conflicting? Or is there something I need to set?

**Comment by fkhadra** [comment]
Hey @dmbrooking,

Could you tell me which version are you using please ? 
On which device are you testing ?

Thanks.

**Comment by dmbrooking** [comment]
I am using the latest version.. 3.2.1 I think.

Honestly, I think I figured it out. It's like all issues - you fight with something for hours and then you finally decide to ask for help and you figure it out a few minutes later.  The previous developer on my project did not have the meta tag setting initial scale to 1. When I set that, it appears to have fixed the issue. It also broke the entire rest of the page, but that't not your issue :)

I think we're good here.

**Comment by fkhadra** [comment]
haha 😂 I know that feeling. Good luck then. I'll close the issue. Feel free to ask for help.

**Comment by SaeedSheikhi** [comment]
Thanks for the awesome project!
on rtl content, there is a small bug,
when mobile, the toast does not take over the entire view width
![image](https://user-images.githubusercontent.com/30556349/35649468-6d0aca48-06ee-11e8-8942-844b1ac4e5af.png)

by injecting right : 0; into the css, the issue will be fixed.
![image](https://user-images.githubusercontent.com/30556349/35649699-27588b1a-06ef-11e8-9cbe-b223d468d38f.png)

**Comment by fkhadra** [comment]
Hello @SaeedSheikhi,

Glad you like it! Thanks for the feedback. 
I created a new [issue here](https://github.com/fkhadra/react-toastify/issues/128) to fix RTL support. 😄
