### ISSUE TITLE
[BUG]: newestOnTop prop is not working on production build

### ISSUE THREAD

**Issue by socker210** [fkhadra/react-toastify#1140]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Toast stacked like newestOnTop={false} on production build

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Set newestOnTop={true} to ToastContainer
2. Run build command with Vite
3. Run preview command
4. Then you can see newestOnTop prop is not working as expected

**What is the expected behavior?**
Toast will stack like newestOnTop={true} on production build

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React: ^18.3.1
- Browser: Chrome(126.0.6478.183)
- OS: MacOS(14.4)
- React-Toastify: ^10.0.5

**Comment by mylesadawson** [comment]
I'm also running into this exact same issue. It appears like newestOnTop works on localhost but not after a build:

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: ^18.2.0
Chrome: 126.0
MacOS: 14.3
Vite: 5.1.4 (using esbuild)
React-Toastify: ^10.0.5

**Comment by VariabileAleatoria** [comment]
any update on this issue?

**Comment by socker210** [comment]
> any update on this issue?

No updates since I issued 🥲

**Comment by cpfnickhoward** [comment]
My previous comment wouldn't fix it, it caused more trouble. I do think I found a fix though. I'm not sure if it's the best approach, but it seems to work.

**Comment by fkhadra** [comment]
Looking into it

**Comment by fkhadra** [comment]
The fix has been released.
