### ISSUE TITLE
Unexpected Application Error! 

### ISSUE THREAD

**Issue by Shahjahan009** [fkhadra/react-toastify#1144]
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/0458bdf6-cb9d-494b-bfd0-86abe2fc4f35">

When I click cancel icon on toast notification it is throwing error.

Cannot set properties of undefined (setting 'toggle') TypeError: Cannot set properties of undefined (setting 'toggle')

**Comment by AmitSutradhar001** [comment]
i have a solution for this error. I was also facing the same error ... if you are showing the tost for 3 s then  use >>>
 setTimeout(() => {
          navigate("/");
        }, 2000);
after the tost and dont return the tost use thhe tost and then use return ...this error will be gon.

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
