### ISSUE TITLE
Show error in Toast Container

### ISSUE THREAD

**Issue by mk016** [fkhadra/react-toastify#1145]
The ToastContainer example in the react-toastify documentation has a syntax error. The transition prop is incorrectly assigned using the colon : instead of the equals = sign, which causes a syntax error.

Incorrect Code Example
<ToastContainer
  position="top-right"
  autoClose={5000}
  hideProgressBar={false}
  newestOnTop={false}
  closeOnClick
  rtl={false}
  pauseOnFocusLoss
  draggable
  pauseOnHover
  theme="light"
  transition: Bounce,
/>
{/* Same as */}
<ToastContainer />

Correction
The transition prop should be assigned using the equals = sign and the value should be enclosed in quotes.

Correct Code Example

<ToastContainer
  position="top-right"
  autoClose={5000}
  hideProgressBar={false}
  newestOnTop={false}
  closeOnClick
  rtl={false}
  pauseOnFocusLoss
  draggable
  pauseOnHover
  theme="light"
  transition="Bounce"
/>
{/* Same as */}
<ToastContainer />

Steps to Reproduce
Copy the incorrect code example from the documentation.
Attempt to use it in a React component.
Observe the syntax error related to the transition prop.
Suggested Fix
Update the documentation to use the correct syntax for the transition prop as shown in the correct code example above.

<img width="270" alt="Screenshot 2024-08-06 at 1 05 35 PM" src="https://github.com/user-attachments/assets/c11abe79-c2c5-427d-b09a-23ca7140b210">
<img width="349" alt="Screenshot 2024-08-06 at 1 05 57 PM" src="https://github.com/user-attachments/assets/84acb116-cd7c-4bf5-b305-f8033f50b27f">

**Comment by fkhadra** [comment]
The documentation will get a refresh soon thanks for reporting.
