### ISSUE TITLE
Problem in Next15 RC

### ISSUE THREAD

**Issue by mohammadgarmroodi** [fkhadra/react-toastify#1149]
Bug
 when i use react toastify in next js version 15 rc it shows me a error like this:
 
 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.  Check the render method of `N`.

when i comment the <ToastCotnainer ,the project runs correctly !

**Comment by ganicus** [comment]
Any update on this?

**Comment by raphaelbadawi** [comment]
Confirmed on my side

**Comment by notDemian** [comment]
any update? im experiencing the same issue

**Comment by Alioo11** [comment]
i encountered the same issue.
updating the react-toastify version to `10.0.5` fixed it for me.

**Comment by creativehabib** [comment]
Same Problem
