### ISSUE TITLE
ncaught (in promise) InvalidStateError: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed

### ISSUE THREAD

**Issue by prathap255** [fkhadra/react-toastify#1155]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
I updated React App from 17 to 18.3.1 and react-toastify to 10.0.5. After this I am having the issue of `Uncaught (in promise) InvalidStateError: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 18.3.1
react-toastify: 10.0.5
Browser: Edge/Chrome
OS: WIndows
Yes it worked with previous version of React

**Comment by fkhadra** [comment]
The library does not use `postMessage`, most likely related to your project.
