### ISSUE TITLE
toast.POSITION.BOTTOM_LEFT is Undefined in Version 10.0.5

### ISSUE THREAD

**Issue by otaku0304** [fkhadra/react-toastify#1156]
I encountered an issue with react-toastify version 10.0.5 where the toast.POSITION.BOTTOM_LEFT constant is undefined. The error occurs when attempting to use this constant to set the position property in the ToastContainer component. The error message is:

![image](https://github.com/user-attachments/assets/80a38bdb-0ed3-465b-bcce-14cfab5f5bcb)

I did not experience this issue with version 9.1.3, where toast.POSITION.BOTTOM_LEFT was properly recognized and functional. The problem appears to be specific to version 10.0.5.

To reproduce the issue:

Install react-toastify version 10.0.5.
Use toast.POSITION.BOTTOM_LEFT in the ToastContainer component.
Observe the error in the console.
I suspect there may be a regression or breaking change in version 10.0.5 related to how the POSITION constants are being exported or accessed. Any guidance or fix on this would be greatly appreciated.

**Comment by afjusto** [comment]
This is [documented](https://fkhadra.github.io/react-toastify/migration-v10#the-toastposition-and-toasttype-constants-have-been-removed) in the migration guide.
