### ISSUE TITLE
`onChange` callback runs multiple times for a single toast

### ISSUE THREAD

**Issue by Mehdi-Hemmatyar** [fkhadra/react-toastify#1159]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I want to logout user when there is an Auth error
But `onChange` callback runs multiple times for a single toast

```javascript
  const handleAuthError = toast.onChange((payload) => {
    console.log(payload);
    if(payload.id === 'oauth-err' && payload.status === 'removed'){
        federatedLogout(pathname)
    }
  });

  useEffect(() => {
    handleAuthError();
  }, []);
``` 
this is an test Toast!
check the console
![toastAdd](https://github.com/user-attachments/assets/606e4611-6218-43c2-93d6-15e394a26d9f)

![toastRemove](https://github.com/user-attachments/assets/7cd244d2-9fd0-41df-b0ef-a89fd468f7cb)

**Comment by aaamenezes** [comment]
Hello.

I tested your code and notice that the `onchange` event is fired when the toast enter and leave the page. So, the value in the console is printed just twice per fire.

For my console is equal of your it, I need to fired the toast a lot of times.

![image](https://github.com/user-attachments/assets/2cc232d6-f890-45c9-b0cb-a2590e47b428)
![image](https://github.com/user-attachments/assets/7571bc09-e0d0-4978-a39e-1b9e577aad68)
![image](https://github.com/user-attachments/assets/c081e920-b53f-4f50-adc8-b368959b6ebd)

[There's a breaking change on the `onchange` event](https://fkhadra.github.io/react-toastify/migration-v9#toastonchange) from the v8 to v9.

I'd test insert the `handleAuthError` in the use effect's dependencies array

```js
useEffect(() => {
    handleAuthError();
  }, [handleAuthError]);
```

What's yout React Toastify version?
