### ISSUE TITLE
Bug in Toast behaviour on adding toastId

### ISSUE THREAD

**Issue by Kumud246** [fkhadra/react-toastify#1161]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Adding toastId to toast() does not show the same toast() until the previous one is there in the DOM.  

`useEffect(() => {
    if (success) {
      toast.success('Message Success', { toastId: 'successMsg'});
    }
  }, [success]);`

This if condition is running if success is true but new toaster does not comes if toastId is there and already there is a toaster.

**CodeSandbox example:**
https://codesandbox.io/p/sandbox/priceless-wescoff-6czxmt

**What is the expected behavior?**
Should work same as it works when we don't add toastId, show toast message as many times it comes to toast.success('Message Success')

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version- 18.2.0
react-toastify version - 9.1.3

**Comment by fkhadra** [comment]
Hey, this behavior is documented here https://fkhadra.github.io/react-toastify/prevent-duplicate/#simply-provide-a-toast-id, you can call `toast.update` for your use case instead

**Comment by Fabioni** [comment]
This behaviour is unexpected. If I do 

`toast.info('lorem', { toastId: 'myid });`
...
`toast.info('ipsum', { toastId: 'myid });`

one would expect that the toast automatically takes the newest value so 'ipsum'
