### ISSUE TITLE
`CloseButtonProps` are no longer exported from types in version 10

### ISSUE THREAD

**Issue by gustaff-weldon** [fkhadra/react-toastify#1165]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`CloseButtonProps` were previously exported in `index.ts` in version 9. From version 10 they are missing. One has to import them from `import type { CloseButtonProps } from 'react-toastify/dist/components';` which is prone to breaking if structure changes.

**What is the expected behavior?**
```import type { CloseButtonProps } from 'react-toastify';```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 18.3.1, toastify 10.0.5

**Comment by fkhadra** [comment]
Hey @gustaff-weldon , I've released a new major version, please read the release note before upgrading  🙏🏽
