### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'toggle')

### ISSUE THREAD

**Issue by Harshu29-09** [fkhadra/react-toastify#1170]
I'm encountering a problem with the toast notification in my application. After triggering a toast.success message, the toast appears as expected. However, if I click anywhere on the screen while the toast is displayed, the same toast notification reappears. Additionally, when I attempt to dismiss the toast, I receive the following runtime error:

TypeError: Cannot set properties of undefined (setting 'toggle')

I would appreciate any insights or solutions from the community on how to resolve this issue. Thank you!

**Comment by abhishekbansal2312** [comment]
I am also getting this same problem.

**Comment by ManrahulBajwa** [comment]
Facing same issue in Next.js production build.
Unable to reproduce it in development mode in Nex.tjs
Crashing production application 
<img width="987" alt="image" src="https://github.com/user-attachments/assets/3b46b5dd-2440-4853-9ae7-87c1f886610d">
<img width="484" alt="image" src="https://github.com/user-attachments/assets/a6a6140d-2540-4736-ad74-39e4ba281aac">

**Comment by fkhadra** [comment]
Hey, I've released a new major version, please read the release note before upgrading  🙏🏽

**Comment by Harshu29-09** [comment]
> Hey, I've released a new major version, please read the release note before upgrading 🙏🏽
Great work @fkhadra
