### ISSUE TITLE
BUG - newestOnTop flag is still not working...

### ISSUE THREAD

**Issue by YahavTheKing123** [fkhadra/react-toastify#1176]
Please see pen here:

react-toastify version 10.0.6

https://stackblitz.com/edit/react-s2w7c6?file=src%2FApp.js,src%2Findex.js

**Comment by Gabriel27109812362** [comment]
I confirm that, issue still exists I check previous version 10.0.5 and there is no bug

**Comment by YahavTheKing123** [comment]
@Gabriel27109812362 You are right. 
For now downgrading to 10.0.5 solve the issue for me..

Thanks you
