### ISSUE TITLE
React dependency Issue

### ISSUE THREAD

**Issue by insivika** [fkhadra/react-toastify#1177]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
npm resolution error 

While resolving: cfc_ui@0.1.0
Found: react@19.0.0-rc-66855b96-20241106

Could not resolve dependency:
peer react@">=18" from react-toastify@10.0.6

Trying to install with  --force or --legacy-peer-deps breaks other packages

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Try installing using the latest react version

**What is the expected behavior?**
It should install 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@19.0.0-rc-66855b96-20241106

**Comment by coreyafunk** [comment]
The latest production release of React is 18.3.1, the version you have installed is the v19 Release Candidate. 

The maintainers are not likely to offer support for beta React releases. 

You will either need to downgrade your version of React to the latest official release (v18.3.1), or if for some reason you must use the React RC version, do as the error message suggests and use the `--force` or `--legacy-peer-deps` flag and accept that there may be potential issues in your app.

**Comment by Adityapanther** [comment]
I am facing the same issue

**Comment by Badestrand** [comment]
I have the same problem.

As a note, this is from a default Next.js installation which appearently uses React 19.

**Comment by fkhadra** [comment]
i'm preparing the v11 that will address this issue

**Comment by shehi** [comment]
Need that as well. This essential for those who want to upgrade to Next.js 15, which uses React-19.

**Comment by Adityapanther** [comment]
@fkhadra any update ?

**Comment by fkhadra** [comment]
@Adityapanther almost there https://github.com/fkhadra/react-toastify/pull/1178, I have a couple of test to fix and hopefully next week I can release

**Comment by therealsras** [comment]
@fkhadra , waiting. just upgrade to NextJS 15

**Comment by canercalskan** [comment]
@fkhadra waiting to hear from u about this update, thanks for your efforts!

**Comment by fkhadra** [comment]
Hey, I've released a new major version, please read the release note before upgrading  🙏🏽
