### ISSUE TITLE
onClose delay

### ISSUE THREAD

**Issue by jihea-park** [fkhadra/react-toastify#1179]
Hi,

I know the onClose event handler has 1s delay because of transition.
But I think we need `onCloseStart` event handler to improve ui.

https://github.com/fkhadra/react-toastify/issues/685

I want to show `Clear all` button if toasts exist.
And not show the button if toast not exist....

Is there any solution about that?
Please help me.

**Comment by fkhadra** [comment]
Hey @jihea-park, starting v11 https://github.com/fkhadra/react-toastify/pull/1178 `onClose` will be called as soon as the notification is closed and won't wait for the exit transition to complete

**Comment by jihea-park** [comment]
@fkhadra 
WOW! AMAZINGGGGGGGG!!!!!!

**Comment by fkhadra** [comment]
Hey @jihea-park, I've released a new major version, please read the release note before upgrading  🙏🏽
