### ISSUE TITLE
how can I install and use it on Next.js 15

### ISSUE THREAD

**Issue by AndrianarivoAlpha** [fkhadra/react-toastify#1181]
Hello everyone,
I want to add react-tostify on my Nextjs app but it have error

$ npm install --save react-toastify
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: web@0.1.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error
npm error Could not resolve dependency:      
npm error peer react@">=18" from react-toastify@10.0.6
npm error node_modules/react-toastify        
npm error   react-toastify@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error

How can I install it on Nextjs 15 app please?

**Comment by Michael-Forson** [comment]
I am also facing the same problem

**Comment by Adityapanther** [comment]
same issue reported at https://github.com/fkhadra/react-toastify/issues/1177

**Comment by fkhadra** [comment]
Hey, I've released a new major version, please read the release note before upgrading  🙏🏽. There is also an example on stackblitz with nextjs
