### ISSUE TITLE
The `transition: Bounce;` property is returning an error, please fix this ASAP.

### ISSUE THREAD

**Issue by juwwad** [fkhadra/react-toastify#1182]

**Comment by fkhadra** [comment]
Sorry but without a proper description and reproduction I cannot do much.

**Comment by juwwad** [comment]
`<ToastContainer
position="top-right"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition: Bounce,
/>
{/* Same as */}
<ToastContainer />`

Since it is a jsx file the `transition: Bounce` should be written as `transition= "Bounce"` to fix the issue.
