### ISSUE TITLE
404 page not found in documentation

### ISSUE THREAD

**Issue by Yohannfra** [fkhadra/react-toastify#1190]
Hi, just to let you know that this link in to documentation leads to a 404 page.

On this page : https://fkhadra.github.io/react-toastify/how-to-style/

![image](https://github.com/user-attachments/assets/00378230-478a-4020-832c-30b80d0809d2)

the broken link: https://fkhadra.github.io/react-toastify/how-to-style/use-your-own-component

Thank you for this package, I've been using it daily for my project and never had an issue :)

**Comment by fkhadra** [comment]
Thanks @Yohannfra for reporting, I pushed a fix
