### ISSUE TITLE
Error: "cannot set properties of undefined (setting 'toggle')" when closing a toast after page navigation in Next.js

### ISSUE THREAD

**Issue by salmannnsajid** [fkhadra/react-toastify#1191]
**Description:**
I encountered an issue with React Toastify in my Next.js project. The problem occurs when I navigate from one page to another and attempt to close a toast that was displayed on the previous page. The following error appears in the console:

**TypeError: cannot set properties of undefined (setting 'toggle')**

**Reproduction Steps:**

Display a toast on Page A after an API response.
Use next/navigation to navigate to Page B.
Attempt to close the toast while on Page B.

**Expected Behavior:**
The toast should close gracefully without any errors, regardless of page navigation.

**Actual Behavior:**
Closing the toast results in the following error:
![image](https://github.com/user-attachments/assets/04d1a601-ab47-4c27-8d83-13250b80bdaa)

**Environment Details:**

React Toastify version: ^10.0.6
Next.js version: 14.2.15
React version: ^18
Browser: Chrome

**Comment by fkhadra** [comment]
Hey @salmannnsajid, the latest version v11, should address that issue. Closing the issue for now, let me know if you still have the issue after upgrading.

**Comment by salmannnsajid** [comment]
Hi @fkhadra, thanks! It's fixed now.
