### ISSUE TITLE
BUG: v11: can't hide toast after changing route

### ISSUE THREAD

**Issue by spradlin-dev** [fkhadra/react-toastify#1194]
**Do you want to request a _feature_ or report a _bug_?**
BUG

**What is the current behavior?**
If you display a toast, then change routes multiple times in quick succession (like by clicking around through the navigation), react-toastify will copy any displayed toasts for the new route.  As it does this for multiple routes, it is very easy for react toastify to lose track of the toast that is currently displayed, then it becomes impossible to hide because:

Firefox: `can't access property "removalReason", c.get(...) is undefined`
Chrome: `Uncaught TypeError: Cannot set properties of undefined (setting 'removalReason')`
Safari: `TypeError: undefined is not an object (evaluating 'c.get(u).removalReason = D')`

at 
<img width="329" alt="image" src="https://github.com/user-attachments/assets/6e68125e-f491-49a2-8569-1ab81d49d973" />

**What is the expected behavior?**
Toast is always closeable, and will still close itself when its timer runs out

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react 18.3.1
react-toastify ^11.0.2
Firefox on MacOS AND Chrome on MacOS AND Safari on MacOS

**Comment by fkhadra** [comment]
@spradlin-dev could you reproduce the issue in stackblitz? 
Where is your `ToastContainer` rendered?

**Comment by spradlin-dev** [comment]
our toast container is rendered in our main application OUTSIDE of our redux store and OUTSIDE of our router.  I have even tried moving it to be a sibling to the outermost app component, so that it has only one parent element in the whole application.  

This issue doesn't seem to be related to where the container is mounted, but to how toasts are (for some reason) automatically dismissed and re-added on route change.  Every time we change routes, if there are open toasts, they will dismiss (despite not being out of time yet) and come back immediately.  They still work fine when this happens UNLESS you change pages multiple times in quick succession.  Then it seems that the code that keeps track of new and old toasts loses track of the old, old toasts and cannot dismiss them anymore.  Then when I change routes again one more time, they get dismissed somehow, but not re-added (if they have run out of time).

I will try to put together a stackblitz, but i haven't even used it before so who knows what kind of success i'll have.

**Comment by fkhadra** [comment]
@spradlin-dev let me know if you are able to put a stackbliz together or share a repository. Hard to guess what could be the issue.

**Comment by spradlin-dev** [comment]
In trying to recreate the minimal amount of components necessary to reproduce the error, I stumbled upon a bug in our code.

We had the `<ToastContainer/>` at the outermost point, as I commented above, but I found another instance of `<ToastContainer/>` mounted inside of the router.  So there were two toast containers, one inside and one outside of the router.  Deleting the one inside the router resolved the issue (of course).

**Comment by fkhadra** [comment]
Glad you found the issue

**Comment by macabeus** [comment]
> We had the `<ToastContainer/>` at the outermost point, as I commented above, but I found another instance of `<ToastContainer/>` mounted inside of the router. So there were two toast containers, one inside and one outside of the router. Deleting the one inside the router resolved the issue (of course).

It might be good to mention it in this page doc: https://fkhadra.github.io/react-toastify/prevent-duplicate
I had this same mistake in my codebase, and after removing the duplicated `<ToastContainer/>` fixed the issue.
