### ISSUE TITLE
Toast is not showing inside the viewport

### ISSUE THREAD

**Issue by sankhaBA** [fkhadra/react-toastify#1197]
I used react-toastify with my next.js project as follows. But it is showing in extreme bottom of the page, not inside the current viewport even I am not scrolled down to the bottom. Code is as follows.

Dependencies and versions:

```
    "@headlessui/react": "2.1.10",
    "axios": "1.7.7",
    "classnames": "2.5.1",
    "jsonwebtoken": "9.0.2",
    "next": "14.2.15",
    "react": "18",
    "react-dom": "18",
    "react-icons": "5.3.0",
    "react-responsive-carousel": "3.2.23",
    "react-spinners": "0.14.1",
    "react-toastify": "10.0.6"
```

I've created a reusable component with the settings for my toast as follows and placed it in components

```
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

/**
 * Toast component renders a ToastContainer with predefined settings.
 *
 * @returns {JSX.Element} The rendered Toast component.
 */
const Toast: React.FC = () => {
  return (
    <ToastContainer
      position="bottom-center"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="dark"
      style={{ zIndex: 9999 }}
    />
  );
};

export default Toast;
```

Then I used them in pages as follows. I placed them in the parent folder as I can access it from child  components

```
import Hero from "@/components/Hero";
import AnnouncementsSummaryCardList from "@/components/AnnouncementsSummaryCardList";
import AboutSection from "@/components/AboutSection";
import VisionMissionGoalsSection from "@/components/VisionMissionGoalsSection";
import FacilitiesSection from "@/components/FacilitiesSection";
import DocumentsSection from "@/components/DocumentsSection";
import EmployeesSection from "@/components/EmployeesSection";
import VisitorFooter from "@/components/VisitorFooter";
import CoursesSection from "@/components/CoursesSection";
import ArticleSection from "@/components/ArticleSection";
import IntakesSection from "@/components/IntakesSection";
import ContactSection from "@/components/ContactSection";
import Toast from "@/components/Toast";
import { AnnouncementTypeEnum } from "@/interfaces/announcementInterface";

export default function Home() {
  return (
    <div className="bg-white text-black-primary min-h-screen">
      <Hero heroType="general" />
      <AnnouncementsSummaryCardList
        announcementType={AnnouncementTypeEnum.GENERAL}
      />
      <AboutSection />
      <VisionMissionGoalsSection />
      <IntakesSection />
      <CoursesSection />
      <ArticleSection />
      <FacilitiesSection />
      <DocumentsSection />
      <EmployeesSection />
      <ContactSection />
      <VisitorFooter />
      <Toast />
    </div>
  );
}
```

I displayed toast using toast.error() or toast.success commands in few of the components mentioned above (ContactSection, DocumentsSection...etc) as follows

`toast.success("Contact request submitted successfully!");`

However, when I displayed toast in ContactSection using the above command, it is displayed in the bottom of the page, even I am scrolled the page only to ContactSection.  Even if I am in the top of the page without scrolled, if I clicked the button that display the toast from there, toast is displayed in extreme bottom of the page

I want to show the toast wherever the user currently scrolled, not in the extreme bottom or top.

How to do that?

**Comment by fkhadra** [comment]
Hey @sankhaBA I see no issue on my side https://stackblitz.com/edit/react-toastify-getting-started-rotuiwte?file=src%2FApp.tsx. Could you try to reproduce your issue on stackblitz, this way I can help. Thank you

**Comment by sankhaBA** [comment]
I update the code in https://stackblitz.com/edit/react-toastify-getting-started-kkgynxze?file=src%2FApp.tsx with an exact same portion of codes my app. It works fine in stackblitz but not in my app 😢 

I am using next.js. Will that be an issue? I cannot see any other critical difference

**Comment by fkhadra** [comment]
I don't think that would make any difference, I'll try with nextjs as well when I'm back home.  Could it be that you override some of the css styles ? Also the latest version of the library is v11 could you give it a try? The latest version doesn't require you to import the css file

**Comment by Deboracgs** [comment]
i'm having the same problem using the nextjs and using the version 11.0.5
