### ISSUE TITLE
Error in IE 11

### ISSUE THREAD

**Issue by eabovsky** [fkhadra/react-toastify#120]
When I try to use this component on IE 11, I get the following bug when the component is first being added:

> ToastContainer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

It works fine on Edge and other browsers. Tested on the latest version (3.2.2) as well as an older build (1.7.0).

**Comment by fkhadra** [comment]
Hey @eabovsky,

Could you show me a snippet please ?

**Comment by eabovsky** [comment]
My mistake... this was only an issue in 1.7.0 - I had some caching problems when testing 3.2.2. The issue seems to be resolved in 3.2.2.
