### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#128]
Original post:
> Thanks for the awesome project!
on rtl content, there is a small bug,
when mobile, the toast does not take over the entire view width
![image](https://user-images.githubusercontent.com/30556349/35649468-6d0aca48-06ee-11e8-8942-844b1ac4e5af.png)

> by injecting right : 0; into the css, the issue will be fixed.
![image](https://user-images.githubusercontent.com/30556349/35649841-81e9e3a8-06ef-11e8-8ace-a3afde974e76.png)

**Comment by fkhadra** [comment]
Hello @SaeedSheikhi,

Got a question regarding the rtl support. Does the progress bar on the bottom need to be inverted as well ?

Thanks

**Comment by SaeedSheikhi** [comment]
Hello @fkhadra, 

it would be better for progress bar to be inverted

Thanks for your point of view
i appreciate it

**Comment by fkhadra** [comment]
Hello @SaeedSheikhi,

Rtl support is available with v3.4.0. Check the [doc](https://github.com/fkhadra/react-toastify#right-to-left-support) to enable it.

Cheers.

**Comment by SaeedSheikhi** [comment]
Hello @fkhadra 

unfortunately issue is still remaining
├─ react-toastify@3.4.0
├─ react@16.2.0
```javascript
render () {
      return (
        <div>
          <ToastContainer
            closeButton={<CloseButton />}
            bodyClassName={css({
              marginBottom: '.6em',
            })}
            rtl
          />
          {this.props.children}
        </div>
      );
    }
```
![ezgif-4-d0b4c5010b](https://user-images.githubusercontent.com/30556349/37223718-a1e40fda-23e6-11e8-93d2-7152740f7eb4.gif)

**Comment by fkhadra** [comment]
Hello @SaeedSheikhi,

I'm not able to reproduce the issue. I also tested on different mobile without the emulator, it works as expected. 

There may be a css rule somewhere that break the rendering.

**Comment by SaeedSheikhi** [comment]
Hello @fkhadra
 
i reproduce the issue, 
body direction should be rtl, in index.html
and here is where direction breaks the rendering

[SandBox - RTL](https://codesandbox.io/s/2oym5l1w6n)

**Comment by fkhadra** [comment]
Thanks @SaeedSheikhi, I'll have a look and get back to you

**Comment by fkhadra** [comment]
@SaeedSheikhi I'm inexperienced with rtl layout I forgot to put `direction: rtl` on the body. Now I clearly see the issue. 

The fix is coming.

**Comment by SaeedSheikhi** [comment]
#145 Great work @fkhadra 
Thanks, it's now perfectly compatible with rtl.

Cheers
