### ISSUE TITLE
Clear all toast support

### ISSUE THREAD

**Issue by NehaAB** [fkhadra/react-toastify#132]
We have `dismissAll = () => toast.dismiss()` option to clear all toasts, but structurally is it possible to include a `Clear All button` within the **Toast-Container** ?

**Comment by fkhadra** [comment]
Hello @NehaAB,

If I understand your request correctly, in place of a toast you want to display a button to remove all the active toast, is that right?

**Comment by NehaAB** [comment]
Yes. If we can have a button it would be easy for us to use this functionality.

**Comment by fkhadra** [comment]
@NehaAB the good news is that a toast can display anything you want. Here is a working example:

[![Edit React-toastify: Issue 132](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04n063qnkn)

Please let me know if it help you.

**Comment by NehaAB** [comment]
Your code seems to be fine. 
But consider a case where dynamically multiple toasts appear one by one but logically this `Remove All` button shoulg be at the bottom or top, but it has to be fixed somewhere.
Now handling this thing using your way is difficult.

For example, consider any mobile phone notifications that appear one by one and you have a fixed button to clear all the notifications somewhere at bottom or top of your notification panel.

**Comment by fkhadra** [comment]
I understand your need. I don't think that it is the responsibility of the lib to provide that kind of feature. But, I will think about it. 

If your `remove all button` need to be fixed you could use a floating action button instead. It will be definitely easier to manage.

If you want to know when a new toast appears on the screen you can use the hooks as follow:
```js
class MyComponent extends Component {
  toastCounter = 0;
  
displayToast = () =>{
  toast('Hello', {
    onOpen: () => this.toastCounter++,
    onClose: () => this.toastCounter-- 
  });
}

render(){
  return (
    <button onClick={this.displayToast}>Click Me</button>
  );
}
}
```

Please let me know if I miss something.

**Comment by NehaAB** [comment]
It is absolutely correct.
But, again if you consider a complex react-app wherein if we need to fire toasts from different components, it is difficult to manage the toastCounter.

**Comment by fkhadra** [comment]
I'll close this issue since I'm not gonna implement that kind of functionality. In the meantime I added a way to track the numbers of displayed toasts: https://github.com/fkhadra/react-toastify#listen-for-change

**Comment by ccallendar** [comment]
I know this is an old thread, but if anyone ends up here and is looking for a solution, this is what I did:
https://codesandbox.io/p/sandbox/react-toastify-close-all-toast-9v7flp?file=%2Fsrc%2FApp.js

It's pretty much what fkhadra suggested - keeping track of the open toast count, and displaying a custom toast when there are 2 or more active toasts.

**Comment by LazZiya** [comment]
`toast.dismiss()` will clear all open toasts.
