### ISSUE TITLE
Support Multiple ToastContainers

### ISSUE THREAD

**Issue by MichaelMarcialis** [fkhadra/react-toastify#134]
Hello. Forgive me in advance, as I'm a bit of a React noob. 

I have a situation on my current project where I would like to have two separate ToastContainers, and would like the option to direct individual toasts to one of those two ToastContainers (or both, simultaneously). In short, my hope is to direct one set of notifications to can be fixed positioned (as this does by default), and also be able to direct another set of notifications to be housed in a "notification history" type drawer for users to view at a later time.

Currently, none of the props provided seem to support what I'm attempting above, but perhaps I missed something. Is this something that this module can support currently (or in the future)?

**Comment by fkhadra** [comment]
Hello @MichaelMarcialis,

Don't apologize for being a "noob". I've been a noob also 👍 .

Supporting multiple `ToastContainer` will require reviewing the internal design. I don't see any particular use case for having 2 `ToastContainer`  except yours.

But, I'll definitely check how I can support multiple `ToastContainer`

**Comment by Zukye** [comment]
Any updates on this? I could use a functionality like this as well.

**Comment by fkhadra** [comment]
Hello @Zukye,

I'm looking for a way to provide such functionality for the next major release. The library will also switch from glamor to css. Doing so, it will be easier to customize the components to fit your needs.

**Comment by Zukye** [comment]
awesome! Thanks for the quick reply :) 
That's good work you doin!

**Comment by fkhadra** [comment]
Thanks appreciate

**Comment by Burlik** [comment]
Was this functionality (several ToastContainer) added in version 4? Thanks.

**Comment by fkhadra** [comment]
hello @Burlik,

Not yet, unfortunately.

**Comment by snehjogani** [comment]
any updates on the functionality? @fkhadra

**Comment by BoyWithSilverWings** [comment]
@fkhadra Until this feature is added to the library, can we add the placement of `ToastContainer` to the documentation. There seems to be repeated cases where `ToastContainer` is rendered repeatedly, may be also suggest to render it at the root of the application?

**Comment by fkhadra** [comment]
@BoyWithSilverWings indeed it's a good idea. I opened an issue to add a section in the readme. Would you like to work on it ? https://github.com/fkhadra/react-toastify/issues/285

**Comment by SergeyWebDeveloper** [comment]
Hey. I would like to know when to expect the support of several ToastContainer?

**Comment by fkhadra** [comment]
I finally decided to not add the support for multiple `ToastContainer`. 

Instead the `ToastContainer` will be optional. Doing so a user can call `toast('hello')` directly and if a `ToastContainer` is not mounted the lib will take care of it.
