### ISSUE TITLE
Notification not appearing

### ISSUE THREAD

**Issue by marios50** [fkhadra/react-toastify#137]
Imported:
import { ToastContainer, toast } from 'react-toastify';

and called toast("some text");

But I cannot get the notification? Missing something obvious?

**Comment by fkhadra** [comment]
Hey @marios50,

You found how to fix your issue?

**Comment by marios50** [comment]
Hi,

Yes it was an issue on my rendering :)

**Comment by fkhadra** [comment]
Perfect 😄
