### ISSUE TITLE
Toast shows behind modal

### ISSUE THREAD

**Issue by colinricardo** [fkhadra/react-toastify#139]
I'm using a [modal](https://reactstrap.github.io/components/modals/), with a `zIndex` of `1000`. I have a toast as follows: 

```
toast.error(errorMessage, {
  zIndex: 9999,
  hideProgressBar: true,
  autoClose: 2000,
  position: toast.POSITION.TOP_CENTER,
});
```

However, the toast shows behind the modal:

<img width="507" alt="omdal" src="https://user-images.githubusercontent.com/21294951/36641019-2c3e4008-1a21-11e8-9b19-3906d2539071.png">

The component hierarchy is: 

```
<Toaster>
  <RootContainer />
</Toaster>
```

The `<Toaster />` component is just a wrapper for `<ToastContainer />`. 
The modal is opened in the `<RootContainer />`.

**Comment by fkhadra** [comment]
Hello @colinricardo,

Which version are you using? Regarding the modal, could you give me the options you uses so I can reproduce the issue?

Thanks

**Comment by colinricardo** [comment]
The relevant versions are: 

```    
"react-toastify": "3.3.4",
"reactstrap": "5.0.0-beta",
```

I've since changed my code, but I was just using a basic toast as shown above, and had it open on the same page as a [basic modal](http://reactstrap.github.io/components/modals/). Sorry for the lack of details!

**Comment by fkhadra** [comment]
Thanks for the input @colinricardo:

I made a sandbox but I can't reproduce the issue. Could you modify it?

[![Edit vmkykx6817](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmkykx6817)

I removed the autoClose on toast voluntary. So first, I display the toast then the modal. Could you share your scenario? Thanks a lot

**Comment by colinricardo** [comment]
Strange, I can't reproduce, even when I introduce multiple components. I'll close this for now, and if it crops up again I'll include steps to reproduce. Thanks!

**Comment by mortezashojaei** [comment]
I have same problem in modals created by react portal

**Comment by gvsakhil** [comment]
Add this piece of code to fix it 

.Toastify__toast-container {
 z-index: 200000;
}

**Comment by MrFarhan** [comment]
> Thanks for the input @colinricardo:
> 
> I made a sandbox but I can't reproduce the issue. Could you modify it?
> 
> [![Edit vmkykx6817](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/vmkykx6817)
> 
> I removed the autoClose on toast voluntary. So first, I display the toast then the modal. Could you share your scenario? Thanks a lot

@fkhadra  I am unable to find your sandbox on given link, can you again send me the link ?

![image](https://user-images.githubusercontent.com/26528236/125622564-e6983795-99f8-41db-9676-e9df4093bb39.png)

**Comment by alajmo** [comment]
If you're using react-modal, then you can simply set the same parent for both the react-modal and ToastContainer.

```jsx
<div id="app">
    <ToastContainer />
    <ReactModal parentSelector={() => document.querySelector('#app')}></ReactModal>
</div>
```

and workout the z-index.

**Comment by khuram-ingenetic** [comment]
I just add the Toast container on my index.js after the <APP /> and it fixed for me
below the index.js file

```
const container = document.getElementById("root");
const root = createRoot(container!);
root.render(
  <React.StrictMode>
    <App />
    <ToastContainer
      position="top-center"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
    />
  </React.StrictMode>
);

```

**Comment by mrkhuram** [comment]
I just add the Toast container on my index.js after the <APP /> and it fixed for me
below the index.js file
it worked for Material UI modal and ReactStrap Modal.

```
const container = document.getElementById("root");
const root = createRoot(container!);
root.render(
  <React.StrictMode>
    <App />
    <ToastContainer
      position="top-center"
      autoClose={5000}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
    />
  </React.StrictMode>
);

```

**Comment by BlackBeardo** [comment]
`<AuthProvider>
          <SettingsProvider {...(setConfig ? { pageSettings: setConfig() } : {})}>
            <SettingsConsumer>
              {({ settings }) => {
                return (
                  <ThemeComponent settings={settings}>
                    <WindowWrapper>
                      <Guard authGuard={authGuard} guestGuard={guestGuard}>
                        <AclGuard aclAbilities={aclAbilities} guestGuard={guestGuard}>
                          {getLayout(<Component {...pageProps} />)}
                        </AclGuard>
                      </Guard>
                    </WindowWrapper>
                    <ReactHotToast>
                      <Toaster position={settings.toastPosition} toastOptions={{ className: 'react-hot-toast' }} />
                    </ReactHotToast>
                  </ThemeComponent>
                )
              }}
            </SettingsConsumer>
          </SettingsProvider>
        </AuthProvider>
      </CacheProvider>
    </Provider>`
    
    I am using MUI Drawer and my ReactHotToast is NOT showing above the Drawer. I want to show notification of actions done in drawer without closing Drawer.
    
    Can Anyone help.?

**Comment by BlackBeardo** [comment]
I am using MUI Drawer and my ReactHotToast is NOT showing above the Drawer. I want to show notification of actions done in drawer without closing Drawer.

Can Anyone help.?

```
<AuthProvider>
          <SettingsProvider {...(setConfig ? { pageSettings: setConfig() } : {})}>
            <SettingsConsumer>
              {({ settings }) => {
                return (
                  <ThemeComponent settings={settings}>
                    <WindowWrapper>
                      <Guard authGuard={authGuard} guestGuard={guestGuard}>
                        <AclGuard aclAbilities={aclAbilities} guestGuard={guestGuard}>
                          {getLayout(<Component {...pageProps} />)}
                        </AclGuard>
                      </Guard>
                    </WindowWrapper>
                    <ReactHotToast>
                      <Toaster position={settings.toastPosition} toastOptions={{ className: 'react-hot-toast' }} />
                    </ReactHotToast>
                  </ThemeComponent>
                )
              }}
            </SettingsConsumer>
          </SettingsProvider>
        </AuthProvider>
      </CacheProvider>
    </Provider>
```

**Comment by BlackBeardo** [comment]
> Hey @BlackBeardo, this is the repo of react-toastify for react-hot-toast you can check https://react-hot-toast.com/ :)

Thank you for guidance, I visited there and found solution.

I just have to add container style and style in toast option.

Like this:

```
<Toaster
 containerStyle={{
        zIndex: '9999 !important'
      }}
      position={settings.toastPosition}
      toastOptions={{
        className: 'react-hot-toast',
        style: {
          zIndex: '9999 !important'
        }
      }}
    />
```

I know this is out of topic here, but just for knowledge.

**Comment by diegohaz** [comment]
For what it's worth, I created an example of an accessible modal dialog that works with React-Toastify and other toast libraries using [Ariakit](https://github.com/ariakit/ariakit):

https://ariakit.org/examples/dialog-react-toastify

**Comment by abdullah-txfusion** [comment]
zIndex doesn't work. I have a daisy-ui modal with backdrop filter, and toast appears behind it.

**Comment by fedotovdev** [comment]
> zIndex doesn't work. I have a daisy-ui modal with backdrop filter, and toast appears behind it.

The same. Have you fixed it?

**Comment by abdullah-txfusion** [comment]
@fedotovdev No, tried every fix in this thread and similar threads on SO but none worked.

**Comment by vivrkerror404** [comment]
Here is the code that worked in my case (in my case toast messages are hidden behind other elements in my web page like form, div containers etc):

**I simply override the toast styles using class selector**

You can take reference from code snippets below:

```
const configuration = {
  toast: {
    className: "custom-toast",
  },
};
  import {  toast } from "react-toastify";
  const { error } = toast;
  const errorToast = error(message, configuration?.toast)

```
CSS File code:
```
body .custom-toast {
  z-index: 9999999!important;
  background-color: red;
}
```

**Comment by Tom-DK** [comment]
For daisyUI users:

Simply place the ToasterContainer also within the <dialog> element of your dialog.

**Comment by phntm7** [comment]
For MUI Dialog, use the container property (inherited from Modal) to place the Dialog in a DOM element below the Toast container.

**Comment by ADTC** [comment]
The way I fixed this is by adding some simple CSS for the modal:

```scss
.ReactModalPortal {
  position: relative;
  z-index: 9999; // this value should be lower than ToastContainer
}
```

And for the toast container to have these styles:

```scss
.ToastContainer {
  // !important is necessary to override inline styles
  z-index: 10000 !important; // this value should be higher than ReactModalPortal
}
```

It worked because both are siblings to each other, and the direct children of `body` so they are in the same stacking context. You can use any `z-index` values as long as the modal's value is lower than the toast's value.

_Disclaimer: YMMV. Please read up about stacking contexts._

**Comment by wujingfei1990** [comment]
> For daisyUI users:
> 
> Simply place the ToasterContainer also within the element of your dialog.
> 
> ```js
> <dialog ref={ref} className="modal">
>         <form method="dialog" className="modal-backdrop">
>             <button onClick={() => setRender(false)}>close</button>
>         </form>
>         <div className="modal-box">
>             <form method="dialog">
>                 <button className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
>                         onClick={() => setRender(false)}>✕
>                 </button>
>             </form>
>             {children}
>         </div>
>         {/* Allow toasts to show up */}
>         <ToastContainer/>
>     </dialog>;
> ```

 daisyUI  打开Modal状态下，ToastContainer放在dialog里面，关闭Modal状态下，ToastContainer放在dialog外面，完美解决

**Comment by wujingfei1990** [comment]
`"use client"
import useSession from "@/hooks/useSession"
import { useEffect, useState } from "react"
import Login from "@/components/Form/Login"
import Signup from "@/components/Form/Signup"
import ToastModalContainer from "../Toast/ToastModalContainer"
type Props = {
  isOpen: boolean //是否打开登录弹窗
  onClose: () => void //关闭登录弹窗
}
export default function LoginModal({ isOpen, onClose }: Props) {
  const [table, setTable] = useState("login") // login or singup
  const { session, login } = useSession()
  //监听操作打开选择器
  useEffect(() => {
    if (isOpen) {
      const handle = document.getElementById("my_modal") as HTMLDialogElement
      handle.showModal()
    }
  }, [isOpen])

  //监听ESC键关闭选择器
  useEffect(() => {
    const handle = document.getElementById("my_modal") as HTMLDialogElement
    const handleEsc = (event: any) => {
      if (event.keyCode === 27) {
        handle.close()
        onClose()
      }
    }
    document.addEventListener("keydown", handleEsc)
    return () => {
      document.removeEventListener("keydown", handleEsc)
    }
  }, [onClose])

  //关闭方法
  const close = () => {
    onClose()
    const handle = document.getElementById("my_modal") as HTMLDialogElement
    handle.close()
  }
  return (
    <>
      <dialog id="my_modal" className="modal">
        <div className="modal-box max-w-4xl">
          <button
            className="btn btn-sm btn-circle btn-ghost absolute right-2 top-2"
            onClick={close}
          >
            ✕
          </button>
          {table === "signup" ? (
            // 注册表单
            <div className=" max-w-xl mx-auto -mt-16">
              <Signup
                switchForm={() => {
                  setTable("login")
                }}
                onClose={close}
              />
            </div>
          ) : (
            // 登录表单
            <div className=" max-w-xl mx-auto -mt-16">
              <Login
                switchForm={() => {
                  setTable("signup")
                }}
                onClose={close}
              />
            </div>
          )}
        </div>
        {isOpen && <ToastModalContainer />}
      </dialog>
      {!isOpen && <ToastModalContainer />}
    </>
  )
}`

**daisyUI**，打开Modal状态，ToastContainer在dialog里面，关闭状态则在dialog外面，完美解决

**Comment by wujingfei1990** [comment]
daisyUI，打开Modal状态，ToastContainer在dialog里面，关闭状态则在dialog外面，完美解决
![image](https://github.com/user-attachments/assets/3b9dd543-2f70-4f39-80b5-37f0aafe6326)

**Comment by yassmittal** [comment]
If you are using Next.js use your layout like this

```

import "@radix-ui/themes/styles.css";
import "../../public/font/font.css";
import "./globals.css";
import "reflect-metadata";
import { Theme } from "@radix-ui/themes";
import { Footer } from "@/components/Footer";
import { ClientLayout } from "./ClientLayout";
import { PHProvider } from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "TileVille",
  description: "On-chain city development arcade game built on MINA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="gradient-bg min-h-screen">
        <Theme
          accentColor="green"
          grayColor="olive"
          panelBackground="solid"
          scaling="100%"
          radius="large"
        >
          <PHProvider>
            <div className="gradient-bg min-h-screen !bg-fixed">
              <ClientLayout>
                <div className="">{children}</div>
              </ClientLayout>
            </div>
          </PHProvider>
        </Theme>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}



```

**Comment by ChenBri** [comment]
My solution was adding a `Container` at inside the Modal:
```html
import Container from 'toastify-react-native';

    <Modal
        isVisible={visible}
        style={styles.modalContainer}
        propagateSwipe
        useNativeDriver
        animationInTiming={300}
        animationOutTiming={300}
        animationIn={animationIn}
        animationOut={animationOut}
        onBackdropPress={hide}
        onBackButtonPress={hide}
        backdropOpacity={backdropOpacity}
        statusBarTranslucent={screenMode !== 'full'}
        onShow={() => onShow && onShow()}
      >
        <Container
          position='top'
          style={ToastStyle}
          textStyle={ToastTextStyle}
        />
        <View style={styles.contentWrapper}>
          <GestureHandlerRootView style={styles.gestureHandler}>
            <BottomSheetModalProvider>{children}</BottomSheetModalProvider>
          </GestureHandlerRootView>
        </View>
      </Modal>
```
