### ISSUE TITLE
Uncaught Error: The element you provided cannot be rendered.

### ISSUE THREAD

**Issue by albert-olive** [fkhadra/react-toastify#148]
Hi,

I'm having this error after one toast has been shown:

```
ToastContainer.js:201 Uncaught Error: The element you provided cannot be rendered. You provided an element of type undefined
    at ToastContainer.show (ToastContainer.js:201)
    at Object.<anonymous> (ToastContainer.js:140)
    at EventManager.js:39
``` 

In ```App.js``` I do this:

```
componentWillReceiveProps(nextProps) {
    if (nextProps.errorMessage !== '') toast.error(nextProps.errorMessage);
  }
```

and the render: 

```
render() {
    const { isAuthenticated } = this.props;

    return (
      <Fragment>
        <ToastContainer position="bottom-right" />
        <Geolocation />
        <App isAuthenticated={isAuthenticated} />
      </Fragment>
    );
  }
```

Thanks

**Comment by fkhadra** [comment]
Hello @albert-olive,

The issue is coming from here I guess:

```js
componentWillReceiveProps(nextProps) {
    if (nextProps.errorMessage !== '') toast.error(nextProps.errorMessage);
}
```
It looks like `nextProps.errorMessage` is undefined. Could you check it?

**Comment by albert-olive** [comment]
Hi, thank you for the response. No, it's always a text. Don't know why I'm having this error. I have checked all the documentation and seems correct

**Comment by fkhadra** [comment]
Hmm strange. The test that fail is the following:

```js
React.isValidElement(content) ||
      typeof content === 'string' ||
      typeof content === 'number' ||
      this.isFunction(content)
```

To be sure could you do:

```js
componentWillReceiveProps(nextProps) {
    console.log(nextProps.errorMessage);
    if (nextProps.errorMessage !== '') toast.error(nextProps.errorMessage);
}
```
Just to be sure that nothing strange happend on your side.

**Comment by albert-olive** [comment]
Yes, errorMessage is always a string. Also I have checked if it's undefined. I have notice that the first time I don't have that error. 

One question, what's content? 

Thanks

**Comment by albert-olive** [comment]
Ok, yes I have checked properly If error is undefined. I had a weir case that happens. So I close the issue. Thanks for your support
