### ISSUE TITLE
Position option in toast don´t work.

### ISSUE THREAD

**Issue by janbuerling** [fkhadra/react-toastify#15]
To set the position option in the ToastContainer works. If the position is set to the toastr directly, it doesn´t.

**Comment by fkhadra** [comment]
Hello @janbuerling, if you refer to the documentation there is no options to set the position for a toast itself.
I can think to add that feature to a next release maybe. I have to think about the best way to implement it.

**Comment by janbuerling** [comment]
Okay thanks.
