### ISSUE TITLE
Jest test

### ISSUE THREAD

**Issue by AndreiCalazans** [fkhadra/react-toastify#150]
While trying to test my component using Jest, I'm getting this error from ToastContainer.

```  
 console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5530
      The above error occurred in the <Transition> component:
          in Transition (created by DefaultTransition)
          in DefaultTransition (created by Toast)
          in Toast (created by ToastContainer)
          in div (created by TransitionGroup)
          in TransitionGroup (created by ToastContainer)
          in div (created by ToastContainer)
          in ToastContainer (at AddPost.js:42)

```

The error happens exactly when we create a toast event
`this.alertBox = toast('Loading...', { autoClose: false });`

Any ideas how we can overcome this?

**Comment by AndreiCalazans** [comment]
Well for it to work I mocked the library, I don't  know if that is the best way to go.

**Comment by fkhadra** [comment]
Hey @AndreiCalazans ,

Could you share the test?

Thanks

**Comment by AndreiCalazans** [comment]
I can't share it, I was able to work around it by completely mocking react-toastify. At the end that was the best approach for me including for testability.


You should be able to reproduce it by simply using the versions below then running some component rendering it using react-test-renderer. 

"react-toastify": "^3.3.5",
"jest-cli": "^20.0.4"


I'm using toast as follow.

**Method inside component**
```
 handleSubmit = (email, password) => {
    const { firebase } = this.props;
    const msg = toast('Loading', { autoClose: false });
    firebase.login({ email, password }).then(
      () => {},
      () => {
        toast.update(msg, {
          render: 'Sorry, email or password is incorrect',
          type: toast.TYPE.ERROR,
          autoClose: 3000
        });
      }
    );
```


then by rendering it using react-test-renderer you should get the same error.
