### ISSUE TITLE
Position centered toasts shifting towards the right in mobile screens

### ISSUE THREAD

**Issue by sriksm19** [fkhadra/react-toastify#151]
after the latest update, the position centered toasts seems to have shifted to the right, probably due to overriding of the margins (`margin-left: -160px` gets overridden by `margin: 0` with media query). better use `transform: translateX(-50%);` instead

**Comment by fkhadra** [comment]
Indeed the bug was introduced because of my laziness

**Comment by fkhadra** [comment]
The fix is live
