### ISSUE TITLE
Shouldn't `react` and `react-dom` be listed as peer dependencies?

### ISSUE THREAD

**Issue by lorenzos** [fkhadra/react-toastify#16]
`react` is currently a normal dependency, and `react-dom` a development one. Shouldn't they be listed as peer dependencies?

**Comment by fkhadra** [comment]
Hello @lorenzos,
Last week I was asking myself: "react should be considered a dependency or a peer dependency ?" 
Then I forgot about it 😮. 

If I define react as a peer dependency, it means that when you install the package you always get the latest version of react? Am I right?

**Comment by fkhadra** [comment]
I guess `react-dom` need to set as a peerDependency as well.

**Comment by lorenzos** [comment]
> If I define react as a peer dependency, it means that when you install the package you always get the latest version of react? Am I right?

I can be wrong, but I think you're **exactly not right** :smile: The peer dependency is made exactly for the purpose of **not** be downloaded as a required dependency of your package. It means something like *this package should go along this one, but it'll be the user of my package to specify it as a dependency of **her** app*. And, thinking about it, that's what all React components should do (and in fact, everyone else do).

**Comment by fkhadra** [comment]
Thanks for the precision, I understand better know 😁. I'll fix it tonight.

**Comment by fkhadra** [comment]
@lorenzos package updated thanks for the advice !
