### ISSUE TITLE
Statements are not allowed in ambient contexts

### ISSUE THREAD

**Issue by SDSLeon** [fkhadra/react-toastify#165]
![image](https://user-images.githubusercontent.com/6071034/38795403-ceeabf82-4160-11e8-9c41-f745ec016085.png)

Typescript version 2.8.1
toastify version 4.0.0-rc2

**Comment by fkhadra** [comment]
@SDSLeon I published the fix. Is there any way to test a definition file with typescript ?

**Comment by SDSLeon** [comment]
@fkhadra 

import { Slide, Zoom, Flip, Bounce } from 'react-toastify';

also should be added to index.d.ts;

![image](https://user-images.githubusercontent.com/6071034/38797542-7ec05ac4-4167-11e8-9d67-cc9760595dc8.png)

**Comment by fkhadra** [comment]
@SDSLeon thanks a lot:

Is that ok if I do the following for each component:
```js
export Class Slide extends Components<any, any>{}
```
I'm a typescript noob btw

**Comment by SDSLeon** [comment]
@fkhadra 

1. In CommonOptions we have 
`transition?: Transition;`
We need to change it to:
`transition?: React.ComponentType;`

and now 
`export const Slide: React.ComponentType;
`

So now transition will expect 
`ComponentClass<P> | StatelessComponent<P>`

So now we can pass custom animation like this
![image](https://user-images.githubusercontent.com/6071034/38799942-89a5cd82-416e-11e8-9ea6-c8f5d540cf27.png)

and default one (Slide)

**Comment by fkhadra** [comment]
@SDSLeon thanks a lot for your help, I appreciate. 

I published the fix, I hope this time it's ok 😀

**Comment by SDSLeon** [comment]
@fkhadra excellent. For me all works as expected right now.

**Comment by fkhadra** [comment]
Thanks again
