### ISSUE TITLE
Parceljs Hot Reloading causing Toast Not To Show

### ISSUE THREAD

**Issue by SC7639** [fkhadra/react-toastify#169]
When using parcel js and Toast has been shown once then hot reloaded no toast is displayed and the below is shown in the console
```
<SHOW_TOAST> Event is not registered. Did you forgot to bind the event ?
```

**Comment by fkhadra** [comment]
Hello @SC7639 ,

I never used parcel. Could you share a snippet on codesandbox ?

Thanks
