### ISSUE TITLE
Styles defined by classes seem to be overridden by cx

### ISSUE THREAD

**Issue by prmichaelsen** [fkhadra/react-toastify#170]
If I create my toast like so:
```
	return toast('toast', {
		className: 'my-toast',
	});
```
with scss
```
.my-toast {
    border-radius: 4;
}
```

The final resulting Toast has my styles applied and then the `Toastify__toast` style applied on top of that.

**Comment by fkhadra** [comment]
Hello @prmichaelsen,

classNames library preserve css order. In the sample below, the class `foobar` is applied last:
[![Edit mzk8zkj9l8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzk8zkj9l8)

Can you try to replicate the issue on codesandbox?

Thanks

**Comment by prmichaelsen** [comment]
Hello @fkhadra, thank you for the fast response. I will try to recreate the issue for you by EOD

**Comment by prmichaelsen** [comment]
Here is a code sandbox:
[![Edit oqz4xkw3o9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oqz4xkw3o9)

I added the `border-radius` attribute to the css for `foobar`. I applied the class to both `className` and `bodyClassName` options and saw results with neither.

**Comment by fkhadra** [comment]
Hey @prmichaelsen,

Thanks for the feedback. The file `style.css` was loaded before `ReactToastify.css`, you need to load `ReactToastify.css` first:

```js
import 'react-toastify/dist/ReactToastify.css';
import './style.css';
```

[![Edit nnkpxor770](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nnkpxor770)

**Comment by prmichaelsen** [comment]
Ok, I see that you are correct. Thank you again for the help.
