### ISSUE TITLE
Option to not pause autoclose when page is in background

### ISSUE THREAD

**Issue by Gaabe** [fkhadra/react-toastify#171]
I searched through the documentation and examples, but didn't find an option to keep the autoclose timer running when the window is in background. Is such option implemented yet? If not, it would be an interesting feature

**Comment by fkhadra** [comment]
Hey @Gaabel,

I think that you are looking for the `pauseOnVisibilityChange` props. It's only documented on in the api section of ToastContainer [here](https://github.com/fkhadra/react-toastify#toastcontainer).

I'll add more details to the documentation regarding this feature.

**Comment by Gaabe** [comment]
I tried setting the pauseOnVisibilityChange prop to false, but it only works when I switch to another window, if i just switch to another tab, the timer still stops.

**Comment by fkhadra** [comment]
Hey @Gaabe,

Since the latest version  `pauseOnVisibilityChange`  has been replaced by `pauseOnFocusLoss` you can find more detail [here](https://github.com/fkhadra/react-toastify#pause-toast-timer-when-the-window-loses-focus)
