### ISSUE TITLE
Is it possible to change the width and absolute position of the toast

### ISSUE THREAD

**Issue by bioslikk** [fkhadra/react-toastify#173]
I have a sidebar on the left and I want the toasts to show on the bottom-left as well but as if they are inside the sidebar. The toasts are wider, have padding and a different position than the one I would like. I still want the toast on the bottom-left position, but is it possible to change that position and size of toast just a little bit ?

**Comment by fkhadra** [comment]
Hello @bioslikk,

Did you try to override the default css rules?

**Comment by fkhadra** [comment]
Hey @bioslikk ,

Did you solve your issue?

**Comment by bioslikk** [comment]
Yes, thank you very much for your help.
