### ISSUE TITLE
Sound feature?

### ISSUE THREAD

**Issue by jorgecuesta** [fkhadra/react-toastify#174]
Hi, your component work perfect for me, thanks to share it with the world!
Just minor things, have some way to add sounds?

**Comment by fkhadra** [comment]
Hey @jorgecuesta,

Thank for the support.😁  

Check the sample:
[![Edit 4z6p980orx](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4z6p980orx)

Don't forget to turn up the sound

**Comment by jorgecuesta** [comment]
Thanks for the answer @fkhadra that was the same I does to implement it, I just was looking for a general implementation over TestContainer maybe? like something used by props that is used no matter if I pass callbacks to open/close.

**Comment by fkhadra** [comment]
Hey @jorgecuesta ,
I'll think about it for sure.

**Comment by jorgecuesta** [comment]
Thanks @fkhadra sorry my delay to answer you but here (Argentina) was long weekend 😄

**Comment by fkhadra** [comment]
Hello @jorgecuesta,

I'll close the issue for the moment. I'll create a new one if I plan to support this feature by default. 
BTW thanks for the idea.
