### ISSUE TITLE
different toast types class name

### ISSUE THREAD

**Issue by andylaci** [fkhadra/react-toastify#175]
it is hard to work with this lib, if not using glamor or whatever, global classes that can be set in container would be really nice

example:
``` javascript
<ToastContainer
  infoClassName="toast-info"
  warningClassName="toast-warning"
/>
```

it is really hard even to just remove that gay default color from white toast

**Comment by fkhadra** [comment]
Hello @andylaci ,

Since the v4 glamor is not used anymore. The lib is back to css

**Comment by andylaci** [comment]
@fkhadra thank you, this is perfect, now, it took me 10 sec to restyle it to my own need! good job! 

_didn't notice, when the lib updated, I was little bit confused_
