### ISSUE TITLE
Custom toastId

### ISSUE THREAD

**Issue by gtsiokos** [fkhadra/react-toastify#177]
I keep a list of pending external API requests statuses with custom uuids on a reducer.
Each item updates the API call status from PENDING to SUCCESS or ERROR and i'm looking for a way to update the respective toast message to the resolved type.

 Is there a way to fire toast instances with custom uuids to be used later for updating its TYPE?

**Comment by fkhadra** [comment]
Hello @gtsiokos,

For the moment, the toast ids are handled by the library there is no way to pass a custom one. Maybe you could keep a map of the uuid associated to the correct toastId.

 If you can share a sample, maybe I'll be able to help you better.
