### ISSUE TITLE
How do I use this with Grunt? 

### ISSUE THREAD

**Issue by bwoodlt** [fkhadra/react-toastify#178]
I'm having issues importing injecting css into my jsx as grunt doesnt like this. How do I get around this issue to use react-toasify successfully?

**Comment by fkhadra** [comment]
@bwoodlt I'll close the issue fill free to respond if your still have an issue.

**Comment by bwoodlt** [comment]
Thanks Fadi! Have been able to sort this issue. I needed to import into my style.less file like so incase someone had similar question:

`@import (less) "../node_modules/react-toastify/dist/ReactToastify.css`

Thanks again!
________________________________
