### ISSUE TITLE
Nodejs v10 compatibility

### ISSUE THREAD

**Issue by thousight** [fkhadra/react-toastify#179]
I am running Nodejs v10, and react-toastify blocks me from installing it through yarn as it is compatible from v6 to v9. Please make sure it works with v10 and update the restriction on npm. Thanks

**Comment by fkhadra** [comment]
Hello @thousight, 

Are you running node v10 on osx ? If yes I encounter the same issue with every packages I tried to install using npm.

I got a weird output like:

```js
> fsevents@1.1.2 install /Users/gugu/works/ttt/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/gugu/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
```
 
To solve the issue I upgraded node to v10.1, then I upgraded also npm:

```js
sudo npm update npm -g
```

**Comment by thousight** [comment]
Hmmm I am running node v10 on OSX. I tried your method by upgrading node and npm to the latest, and I tried installing react-toastify again. I found out that with npm it works, but not with yarn, yarn still blocks it.

**Comment by fkhadra** [comment]
@thousight I'll close the issue, cause it's not related to the library. Feel free to respond if you need more help.
