### ISSUE TITLE
Enhancement: Assignable Toast ID & Dismiss

### ISSUE THREAD

**Issue by mtompkins** [fkhadra/react-toastify#18]
One set of the features missing from this lovely module is the ability to identify and close existing toasts programmatically. Example: a timer is running and then there is a reason to dismiss it - like a download completes quicker than an expiring timer and you'd like to replace with a completed notification.

**Comment by fkhadra** [comment]
Indeed, good idea !  I'll will add that feature to the next release

**Comment by fkhadra** [comment]
@mtompkins the feature is now available!
toast function now returns a toastId. You can use it to remove the toast:
```javascript
//somewhere 
const toastId = toast('hello');

//somewhere else
toast.dismiss(toastId);
```

**Comment by mtompkins** [comment]
Awesome ! TY
