### ISSUE TITLE
missing scss file after 2.2

### ISSUE THREAD

**Issue by pkellner** [fkhadra/react-toastify#180]
I did see a note regarding scss but did not understand.  My sass build uses the scss file that is in the distribution in 2.2 and now that file is gone.  Is there something I can do to get it back or achieve the same thing?  I use node-sass-chokidar to generate my css from scss and I can't figure how to keep that working and upgrade to the latest at the same time.

**Comment by fkhadra** [comment]
Hello @pkellner,

Which version are you currently using?
