### ISSUE TITLE
Call a function on close

### ISSUE THREAD

**Issue by jitheshkt** [fkhadra/react-toastify#181]
Please don't kill me for asking this. I know it is totally noob question. Here is the code I am using:

```
toast.success('Logged in!', {
                position: "bottom-right",
                autoClose: 3000,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                onClose: this.toastClosed()
            });
```

As you can see, I want to call a function once the toast is closed. Problem what I am facing now is the function is being called even before the toast is rendered (I know why it is, I have gone through the doc). So how to properly get this auto close event.?

**Comment by fkhadra** [comment]
Hello @jitheshkt,

When you do as shown below, you call the function:

```js
onClose: this.toastClosed() // with parenthesis you call the function
```

To pass a function you need to do as follow:
```js
onClose: this.toastClosed
```

**Comment by gylandon** [comment]
Hey team,

why the onClose function is not working for me? onOpen is good. Below is my code:

toastSuccess: (message) => {
    const options = {
      position: toast.POSITION.BOTTOM_CENTER,
      onClose: () => window.alert('Called when I close')
    };
    return toast.success(message, options);
  }
Nothing happened when the toast disappears. Neither click the close button nor auto-close. I am wondering is my way to close toast wrong or something else.

**Comment by fkhadra** [comment]
Hey @gylandon, did you upgrade to the latest version ?

**Comment by gylandon** [comment]
@fkhadra err...nope. my version is 6.0.2. ill upgrade and try it again
