### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by mrjack88** [fkhadra/react-toastify#184]
I am getting this error
` ERROR in [at-loader] ./node_modules/react-toastify/index.d.ts:89:16
          TS2314: Generic type 'ComponentType' requires 1 type argument(s).`
I am using react-toastify v4.0.1, and typescript 2.4.1.

I have used v3.2.2 in a previous project using typescript 2.4.1 and everything was ok. I'll try v3.2.2 again, and will let you know

**Comment by mrjack88** [comment]
I can confirm that I can use 3.2.2 with typescript, no problems

**Comment by fkhadra** [comment]
Hey @mrjack88,

Could you share a snippet so I can reproduce the issue ? 

Thanks

**Comment by NetrushGarrett** [comment]
I am experiencing this same issue with typescript react. I was able to remedy it by editing the index.d.ts file and changing anything of type `React.ComponentType` to `React.ComponentType<any>`.

**Comment by fkhadra** [comment]
@NetrushGarrett should I replace React.ComponentType by React.ComponentType<any> then ?

**Comment by NetrushGarrett** [comment]
@fkhadra You could try it, I don't see how it could hurt but I'm also not an expert so I don't know if it would have any adverse effects on other people's environment I just know what got it working for my environment. Sorry I couldn't be of more help.

**Comment by fkhadra** [comment]
I'll bootstrap a typescript project to see exactly what is going on.

**Comment by fkhadra** [comment]
@NetrushGarrett could you modify my sample so I can reproduce the issue:
[![Edit 3vp23vmxvm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3vp23vmxvm)

Thanks

**Comment by NetrushGarrett** [comment]
@fkhadra So after looking at your Sandbox I saw you were using react 16.4.0 I realized I was using v15 so once I updated to v16 it works just fine.

**Comment by fkhadra** [comment]
@NetrushGarrett good catch !

**Comment by Girish-git** [comment]
Hi fkhadra,

regarding the same issue, I am using react 15.6 and don't want to upgrade react to 16.
what version of react-toastify can Í use without getting this error? I saw the type definition history and you added the ComponentType on 16th Apr 2018.
right now ,I am using react-toastify v4.0.1, and typescript 2.4.1.

Please help.
