### ISSUE TITLE
removeCloseButton not working?

### ISSUE THREAD

**Issue by martinmckenna** [fkhadra/react-toastify#19]
My code

`<ToastContainer
                    className="toast-container"
                    removeCloseButton={true}
                    autoClose={1500}/>`

autoClose is working fine along with other props that I try. Can't get removeCloseButton to work for the life of me

**Comment by fkhadra** [comment]
Hello @martinmckenna,

Sorry I made a typo into the documentation, I will fix it. There is no such prop `removeCloseButton` :face_with_head_bandage: 

To hide the close button you have to set `closeButton={false}` : 

`<ToastContainer className="toast-container" closeButton={false} autoClose={1500}/>`

**Comment by martinmckenna** [comment]
hahah. I thought I was losing my mind. Thanks!

**Comment by fkhadra** [comment]
Haha sorry mate 😁
