### ISSUE TITLE
Put button with onClick inside toast

### ISSUE THREAD

**Issue by ivanasetiawan** [fkhadra/react-toastify#190]
Is it possible to add a button with onClick behaviour inside the notification?

**Comment by fkhadra** [comment]
You can use any react component to do so: https://github.com/fkhadra/react-toastify#render-a-component

**Comment by vittxr** [comment]
the section was removed from repo's readme. 

correct link: [https://fkhadra.github.io/react-toastify/render-what-you-want](https://fkhadra.github.io/react-toastify/render-what-you-want)

**Comment by AmalDoskhoev** [comment]
> the section was removed from repo's readme.
> 
> correct link: https://fkhadra.github.io/react-toastify/render-what-you-want

Page Not Found
