### ISSUE TITLE
Update toast draggable to true does nothing

### ISSUE THREAD

**Issue by LouisCuvelier** [fkhadra/react-toastify#192]
Hi,

Thanks for this lib !

I'm experiencing a weird problem when I want to update a toast that was created with `draggable: false`

Here's my code to update the toast :

```javascript
toast.update(toastId, {
  render: `I'm updated`,
  type: toast.TYPE.SUCCESS,
  autoClose: true,
  closeButton: true,
  closeOnClick: true,
  draggable: true
 });
```

Everything works perfectly except for the `draggable`. The toast can't be drag even with `draggable `set to true.

Is that a bug ?
Thanks for your help !

**Comment by fkhadra** [comment]
Hello @LouisCuvelier,

You just spotted a bug well done 👌.

For the draggable props, I bound the events inside `componentDidMount` but in the case of an update `componentDidMount` is not called. This is why the draggable props is not working.

I'll work on a fix.

Thanks

**Comment by fkhadra** [comment]
@LouisCuvelier I published the fix

**Comment by LouisCuvelier** [comment]
Thank you @fkhadra for this reactivity !
