### ISSUE TITLE
Toaster not working properly in Firefox and IE11

### ISSUE THREAD

**Issue by Englund0110** [fkhadra/react-toastify#193]
I just updated react-toastify from 3.4.3 to 4.1.0, but somehow it is not working as expected in Firefox and IE11. There are no problems when using Chrome. 

Versions:
Firefox 60.0.2
Internet Explorer 11
Chrome 66

Screenshot of toaster in IE11: 
![image](https://user-images.githubusercontent.com/6859869/41399700-4fc0405e-6fbb-11e8-80ce-7495a855e3f5.png)

Code: 
```
import { ToastContainer, toast } from "react-toastify"

toast("Some error")

<ToastContainer
   position="bottom-center"
   autoClose={7000}
   hideProgressBar={true}
   newestOnTop={false}
   closeOnClick
   pauseOnHover
/>
```

**Comment by fkhadra** [comment]
Hello @Englund0110 ,

Did you include the css also ?

```js
import 'react-toastify/dist/ReactToastify.css';
```

**Comment by Englund0110** [comment]
I didn't.

I added this line of code to the top of my index.less, and it worked. 
```
@import '../../../node_modules/react-toastify/dist/ReactToastify.min.css';
```

Thank you for the help and quick response!
