### ISSUE TITLE
App Build fails (dev works) when calling toast() from different file than where it's rendered

### ISSUE THREAD

**Issue by MrPolymath** [fkhadra/react-toastify#194]
I render the toast container in the root of the application.
Then, in a redux action I'm calling the `toast()` function.

For some reason that I haven't been able to figure out by myself, everything works when developing but then the build doesn't. (The build compiles without errors, but then I get a blank page when running it).

I suspect it might have to do with babel doing something weird when compiling but then I don't understand why it works when using the `toast()` in the same root file and not when using it in another file.

I'm using the latest version of Create React App `1.1.4`, react `^16.2.0` and node `8.10.0`.

**Comment by fkhadra** [comment]
Hello @MrPolymath,

Did you eject CRA config?

**Comment by MrPolymath** [comment]
I did not @fkhadra

**Comment by fkhadra** [comment]
Hello @MrPolymath,

Is your project accessible or could you share a piece of code? I'm not able to reproduce the issue ☹️

**Comment by MrPolymath** [comment]
Hi @fkhadra ,
Unfortunately the project isn't open :( . 
Don't worry about the issue right now.
When I find time I'll try to reproduce it in an open demo and post it here so that we can reopen this.
Thanks a lot!

**Comment by fkhadra** [comment]
Thanks @MrPolymath , I'll close the ticket open a new one when needed.

Have a good day

**Comment by jmfadeley** [comment]
We just encountered the same issue. Minified project screams about this. https://reactjs.org/docs/error-decoder.html?invariant=44

Situation cannot be reproduced in development, just production. However, we're on react-toastify 3.4.3.

**Comment by gatoratemylips** [comment]
Same here. Any solution?
