### ISSUE TITLE
Not possible to set the background anymore ?

### ISSUE THREAD

**Issue by BenNG** [fkhadra/react-toastify#197]
with version 4.1.0 (and 4.0.1) with this kind of code I can't set the background properly:
notice that the `bodyClassName` and `progressClassName` seems to have the good behavior but not `className`
```
    toast('Custom style', {
        className: 'bg-red',
        bodyClassName: 'grow-font-size',
        progressClassName: 'fancy-progress-bar',
    });
```

**Comment by fkhadra** [comment]
Hello @BenNG,

I'm not able to reproduce the issue. In my case, it's working as expected. 
[![Edit 9ll40lvymr](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9ll40lvymr)

Could you try to reproduce the issue based on my sample?

Thanks
