### ISSUE TITLE
Reopen a toast via toastId

### ISSUE THREAD

**Issue by laxa88** [fkhadra/react-toastify#199]
Just wondering if there's a feature, or if not, whether it's feasible to add the feature:

Since we get a `toastId` when toasting, is it possible to allow the ability to use the toastId to reopen the toast?

E.g.

```
let toastId;

const open = () => {
  return toastId = toast('some message');
};

const reopen = () => {
  return toast('new message message', {
    id: toastId
  });
}

...

<button onClick={open}>Toast !</button>
<button onClick={reopen}>Reopen Toast !</button>
<ToastContainer />
```

The reason I'm asking is, I was thinking of using the time-travelling feature of redux to debug stuff, and I dispatch an action to toast messages, then dispatch a separate action to dismiss it based on the stored toastId.

If I were to time-travel back to a previously toasted message, the toastId would be different, so I won't be able to dismiss it as I move along the history.

Hopefully this makes sense?

**Comment by fkhadra** [comment]
Hello @laxa88,

Unfortunately,  this is not possible. The toast id can be provided only when we call `toast.update`.
Maybe I could allow to define the `toastId`. I'll think about it.
