### ISSUE TITLE
Error in react-toastify/dist/ReactToastify.css Module parse failed

### ISSUE THREAD

**Issue by billtlee** [fkhadra/react-toastify#200]
Hi, I am trying to use this package.  However, I am running this issue with importing the css file.  I am using nextjs and semantic-ui.  Is it not compatible?  thx!

Error in react-toastify/dist/ReactToastify.css
Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type. | .Toastify__toast-container { | z-index: 9999; | position: fixed;
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .Toastify__toast-container {
|   z-index: 9999;
|   position: fixed;

**Comment by billtlee** [comment]
@fkhadra 
Thanks! Got it to work with your suggestion.

**Comment by wilfredonoyola** [comment]
I fixed this using  with Next JS 8.

`import 'react-toastify/scss/main.scss' `

I think this the best way!

Let me know what do you think

**Comment by huytruongdac** [comment]
I'm having this issue with Typescript, can someone help me? pls.

**Comment by utiq** [comment]
Hi @wilfredonoyola, where did you add that import?
How did you do for ToastContainer to not look for the css version?

**Comment by martinkollie** [comment]
```
2021/04/20 21:11:31.845	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
```

These types of errors are caused by hot reloading

**Comment by MuhammadAflah** [comment]
i have the same error in react js, how can i fix it ?
