### ISSUE TITLE
Do you support new line ? 

### ISSUE THREAD

**Issue by kingleuther** [fkhadra/react-toastify#201]
`toast.error(this.trans.invalid + '\n' + 'sorry', 
                        {
                            position: toast.POSITION.UPPER_RIGHT
                        });`

**Comment by fkhadra** [comment]
@kingleuther why not use jsx like so:

```js
toast.error(<div>{this.trans.invalid}<br /> sorry</div>, { position: toast.POSITION.UPPER_RIGHT });
```

You can render any component in place of string

**Comment by vitaliyhayda** [comment]
or just add
`white-space: pre-line;`
to
`.Toastify__toast-body`

**Comment by moonniketan** [comment]
Thanks @vitaliyhayda

**Comment by ZENALC** [comment]
Just as a heads up for others, @vitaliyhayda means to add that in the CSS of your project.

**Comment by mmospanenko** [comment]
doesn't work, added tag and added style. I think this is important functionality

**Comment by mdodge-ecgrow** [comment]
Just tried this with open/close div tags around my text and a br tag in the middle and it literally prints the br tag.
