### ISSUE TITLE
Toast style is not working correctly

### ISSUE THREAD

**Issue by JaLe29** [fkhadra/react-toastify#202]
I installed last version of react-toastify.

When I use simple demo toast:

```
     toast.error("TEST", {
                position: toast.POSITION.BOTTOM_LEFT
            });
```

There is not "red" style - see image, why? What is wrong with my code?

In another component I have a  `<ToastContainer />` container.

![image](https://user-images.githubusercontent.com/22296816/42371530-0a48f712-8110-11e8-8ed3-17c70533012d.png)

**Comment by fkhadra** [comment]
You need to import the CSS file.

**Comment by yasir-rafiq** [comment]
I import still not working!

**Comment by Monkey-D-Code** [comment]
Working for me in the development but not after building
Developement Server : 
![image](https://user-images.githubusercontent.com/45763998/62409376-da8f1000-b5f3-11e9-9951-b405133630ee.png)
After Build In production : 
![image](https://user-images.githubusercontent.com/45763998/62409392-01e5dd00-b5f4-11e9-8f77-eb241953202f.png)

**Comment by Kordrad** [comment]
I have the same issue. 

In my project, I made a new file `toast.css` and pasted styles from this path: `node_modules/react-toastify/dist/ReactToastify.css`.

And in my file I import something like this:

> import './toast.css';
> import 'react-toastify/dist/ReactToastify.css';

Then i can build my app with styles from Toastify.

**Comment by pavlobu** [comment]
I have same issue. 

No, simply importing css does not help at all.

It seams tricky to add react-toastify to already mature react app.
Seems the only way to make it work is to add it to your react app from very beginning when you just started building your app, otherwise it is not working straight out of the box.

**Comment by fkhadra** [comment]
please open an issue next time. If the issue has been already closed it's hard for me to keep track. @kiily this is more likely an issue with your toolchain. It should just work with nextjs. An alternative solution would be to inject the stye on demand https://fkhadra.github.io/react-toastify/how-to-style/#inject-style-on-demand

**Comment by kiily** [comment]
It was what we suspected, tailwind purgecss issue. After adding the `react-toastify` styles to the array it started working again

```
purge: {
    mode: 'all',
    content: [
      './{components,pages,layout}/**/*.{jsx,tsx}',
      'node_modules/react-toastify/dist/ReactToastify.css',
    ],
  },
```

For the record, prior to this error, I had seen no issues with the `react-toastify` lib and using it in Next.js.

**Comment by sainiankit** [comment]
`import 'react-toastify/dist/ReactToastify.min.css';`
instead of 
`import 'react-toastify/dist/ReactToastify.css';`

Solved it for me. (Was not able to see proper css in Production Builds)

**Comment by iraqwarvet31** [comment]
Having same exact issue. @sainiankit did not solve my issue though. No css styles are being applied and I suspect it has something to do with bootstrap overriding them. We definintely need a fix here.

**Comment by Snapperfish** [comment]
I switched to [Red Hot Toast](https://github.com/timolins/react-hot-toast).

**Comment by johnnytolengo** [comment]
The same issue here, after build there are not css styles. I don't know how to fix it. :(

**Comment by techiekarthick** [comment]
The same issue here.. css not loading.. can i help me how to fx ;(

**Comment by ru-zxr** [comment]
I removed PurgeCSSPlugin from my webpack config and the toast style is working.

**Comment by contactodohgerald** [comment]
this actually worked for me, thanks @fkhadra

**Comment by Aleksandr60rus** [comment]
I just imported this file:  import 'react-toastify/dist/ReactToastify.css' 

and i solved my issue

**Comment by Aleksandr60rus** [comment]
> The same issue here.. css not loading.. can i help me how to fx ;(
I just imported this file: import 'react-toastify/dist/ReactToastify.css'

and i solved my issue

**Comment by ayushsgithub** [comment]
> You need to import the CSS file.
> 
> > import 'react-toastify/dist/ReactToastify.css';

Thank You, it's working now!

**Comment by yasuracreation** [comment]
> > You need to import the CSS file.
> > > import 'react-toastify/dist/ReactToastify.css';
> 
> Thank You, it's working now!

did this worked in prod build , I am having CSS loading issue in production

**Comment by Divyanshukothari** [comment]
@sainiankit this worked thanks

**Comment by debfw** [comment]
@fkhadra this worked, Santa!

**Comment by MDFARHYN** [comment]
I faced the same issue when switching from dark mode to light mode. In dark mode, it worked fine, but when switching to light mode, the toast notification appeared as plain text. After switching to [react-hot-toast](https://www.npmjs.com/package/react-hot-toast), my problem was solved.

**Comment by andersr** [comment]
I see no mention of the need to import the css in the [installation instructions](https://fkhadra.github.io/react-toastify/installation).

**Comment by andersr** [comment]
Oh, I see in the migrate to v11 docs that importing styles is no longer required.
