### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by MartinCerny-awin** [fkhadra/react-toastify#205]
It is good practice to include changelog when releasing a new version of library. It would help developers identify any (possibly breaking) changes without looking into commits. The changelog can be added to releases version in releases tab on GitHub or a new file called CHANGELOG could be created for ability to read changes offline.

https://keepachangelog.com/en/1.0.0/

**Comment by fkhadra** [comment]
Hey @MartinCerny-awin, 

 Changelogs are live now. I'll try to improve the content when I got free time.
