### ISSUE TITLE
Flickering and other visual artifacts when running under electron

### ISSUE THREAD

**Issue by jeffersoneagley** [fkhadra/react-toastify#207]
### Setup
I'm running a CRA/electron/react app:
reactstrap version `#6.3.0`
react version `#16.4.1`
bootstrap version `#4.1.2`
electron `#2.0.3`
react-toastify `#4.1.0`

### Issue
I had a few toasts pop up over top of a reactstrap (bootstrap 4) modal, this was the result:

![image](https://user-images.githubusercontent.com/15936010/42907727-8e203384-8a93-11e8-9d56-74815bc443a3.png)

![image](https://user-images.githubusercontent.com/15936010/42907699-79862974-8a93-11e8-84fe-40980a2f0747.png)

![image](https://user-images.githubusercontent.com/15936010/42907745-9d5977e8-8a93-11e8-8d3b-2a42c756154a.png)

### Steps to reproduce issue

1. Set up an electron+CRA app with reactstrap & react-toastify
2. Add a modal
3. Add a button to the modal to create random toasts
4. Launch the app, trigger the modal, then trigger the toastify toast a couple times.
5. Enjoy the flashing lights

Carried over from #109

**Comment by jeffersoneagley** [comment]
Apparently this is a known bug with chrome (which electron uses). Add the following CSS to your app as a workaround:
`.modal {
    transform: translate3d(0, 0, 0);
}`

**Comment by fkhadra** [comment]
Hello @jeffersoneagley,

Thank you for sharing your solution, appreciate.
