### ISSUE TITLE
Styles doesn't apply when using with CSS Modules

### ISSUE THREAD

**Issue by osnysantos** [fkhadra/react-toastify#208]
I've tried using the sample code: https://github.com/fkhadra/react-toastify#usage in my React app (which is using CSS Modules) but the styles are not being applied.

This line `import 'react-toastify/dist/ReactToastify.css';` points to a CSS file which is already processed and converted to plain CSS class names.

Note: Removing CSS Modules config it works fine!

Now I wonder what I'm missing from the docs to put this to work in my react app.

**Comment by jeffersoneagley** [comment]
Did you add a <ToastContainer/> component to your app somewhere? (not just import) 
Does anything show up at all, or does it just not show anything?
Can you go into inspector and see if theres a <div> with the class "Toastify" present in the DOM?

**Comment by osnysantos** [comment]
Did you add a component to your app somewhere? (not just import)
A: Yes

Does anything show up at all, or does it just not show anything?
A: Yes, the elements from toast show up but with no styles

Can you go into inspector and see if theres a with the class "Toastify" present in the DOM?
A: Yes, exist. Please see image:
<img width="1228" alt="screen shot 2018-07-19 at 7 01 00 pm" src="https://user-images.githubusercontent.com/710567/42972586-61a1146a-8b86-11e8-9b23-349b060e112d.png">

**Comment by fkhadra** [comment]
Hello @osnysantos,

I don't have that much with css modules. I found [this article](https://medium.com/@vuong.qnguyen10/using-css-module-with-external-ui-library-in-create-react-app-bdd1495615c4). Maybe it could help ?

**Comment by fkhadra** [comment]
Hello @osnysantos,

Were you able to make it works ?

**Comment by Petar-np** [comment]
@fkhadra It worked for me :) tnx

**Comment by fkhadra** [comment]
Thanks for the feedback, i'll close the issue then.

**Comment by nikolalukovic** [comment]
I believe the readme file should be updated with these information here to give a heads up to those who use css modules.

**Comment by eyalkapah** [comment]
this is not an optimal solution since it means I have to exclude node_modules which i can't really do... is there any better solution ?
