### ISSUE TITLE
Feature Question - Possible to open a Toast Programatically?

### ISSUE THREAD

**Issue by samyoungnyc** [fkhadra/react-toastify#209]
This isn't an issue but a question. I've looked through the docs and haven't found any way to open a programatically (i.e not using `onClick`)

I want to pass a flag i.e `this.props.loading` to my component (using redux),  and if that is `true` - render the toast. Is this possible?

**Comment by fkhadra** [comment]
Hello @samyoungnyc,

You can use whatever you want to display a toast. You simply have to call the toast function as shown below: 
```js
toast("Hello !");
```
