### ISSUE TITLE
css-modules

### ISSUE THREAD

**Issue by Kotpes** [fkhadra/react-toastify#21]
Great module! Any plans making it work with css-modules out of the box?

**Comment by fkhadra** [comment]
Hey @Kotpes appreciate. I'll think about it, it can be a good idea

**Comment by fkhadra** [comment]
Any good example to make it works with css module ?

**Comment by Kotpes** [comment]
Yeah, react-day-picker supports it: http://react-day-picker.js.org/docs/styling.html

**Comment by fkhadra** [comment]
Thanks ! Got a starting point :+1:

**Comment by fkhadra** [comment]
@Kotpes from what I understand, all I need to do is to expose a className property right ?

**Comment by Kotpes** [comment]
For `<ToastContainer />` component, yes, looks like it will do the trick

**Comment by fkhadra** [comment]
Actually the ToastContainer already accept a className property.
But I Will also give a way to set the className for toast and toast body
