### ISSUE TITLE
Toast not showing

### ISSUE THREAD

**Issue by alb3ric** [fkhadra/react-toastify#212]
Hello,

I'm facing a problem displaying my toast.
I have a main project wich as another project as a dependency. This project is a minified library that i referenced with npm.
In the main project I set the <ToastContainer/> somewhere.
If I call the method toast() from the library the toast is not display. It is display if I call toast from the main project.
I tried to things : 
- If I add a <ToastContainer/> in the library the toast from the library are displayed. But I have then 2 toastcontainer...
- Other solution I found is passing the toast object imported in the main project as a reference to the library then the toast are displayed (without adding the toastcontainer in the library).

I think the Toaster doesn't find the ToastContainer in the main project when the toast() is imported in the 
library.

Do you have any clue?
For the moment I'm passing the toast() as a props to my library but I don't like it...

**Comment by fkhadra** [comment]
Hello @alb3ric ,

Is it possible to reproduce your setup?

The lib doesn't work with 2 `ToastContainer` for the moment .

**Comment by alb3ric** [comment]
Hello @fkhadra 

I did 2 test repository. 
You can find the repository for the library here : https://github.com/alb3ric/ToastLib.git
And a repository with a project consuming the library : https://github.com/alb3ric/ToastTest.git

The ToastTest project reference the ToastLib library using : yarn add https://github.com/alb3ric/ToastLib.git

Launching TestToast :
* Use >yarn to get the dependencies
* Start debug : npm start

If you execute the ToastTest you can see that the toast is not showing when clicking the test button but showing is clicking the button "test ref".

Hope it helps :)

**Comment by fkhadra** [comment]
Thanks @alb3ric, I'll try to have a look at this ASAP.

**Comment by fkhadra** [comment]
Hello @alb3ric,

The ToastTest project is not working as expected because it seems that 2 instances of `react-toastify` are running. You can see that after having a look at the webpack bundle generated by the ToastTest project:

<img width="579" alt="screen shot 2018-08-06 at 16 46 10" src="https://user-images.githubusercontent.com/5574267/43723863-fb7df86c-9998-11e8-9c78-4fa0b3dd7d24.png">
<img width="433" alt="screen shot 2018-08-06 at 16 46 35" src="https://user-images.githubusercontent.com/5574267/43723864-fba528f6-9998-11e8-8bdd-6d0a4f94b236.png">


The library uses an event manager(just a pubsub in fact) to dispatch the notifications. The so-called event manager is bound to the `toast` object. With the current setup 2 `toast` object are created.

Maybe you need to adapt the webpack config of ToastLib. I found an interesting issue [here](https:github.com/webpack/webpack/issues/2134).

I'll try to dig more.

**Comment by alb3ric** [comment]
Hello @fkhadra

Thx for the input. I'm currently on holidays, I ll try that as soon as I come back! I keep you in touch! 

Best regards and thanks for your great work!

**Comment by fkhadra** [comment]
You're welcome @alb3ric  bonne vacances!

**Comment by MartinYounghoonKim** [comment]
@fkhadra is this issue solved ?

**Comment by vbtux** [comment]
I have the same problem

**Comment by SathishSaminathanFlyer** [comment]
Before declaring your class, add the following line:

toast.configure();

**Comment by CesarMurilloS** [comment]
> Before declaring your class, add the following line:
> 
> toast.configure();

This solved my problem! THANKS A LOT!

**Comment by Gyappu** [comment]
> Before declaring your class, add the following line:
> 
> toast.configure();

Thank you so much for this!
I did everything correctly in my project and it didn't work at all. I'm curious as to why some need to add this function and others do not, though.

**Comment by kimgysen** [comment]
Shouldn't make sense to glorify a solution nobody understands.

**Comment by wmahmood1984** [comment]
hi, 

when i am doing toast.configure before app component. i am getting this error

react_toastify__WEBPACK_IMPORTED_MODULE_10__.toast.configure is not a function

Can any one help with this please

**Comment by fkhadra** [comment]
Configure has been removed, you should use the ToastContainer instead 
> hi, 
> 
> 
> 
> when i am doing toast.configure before app component. i am getting this error
> 
> 
> 
> react_toastify__WEBPACK_IMPORTED_MODULE_10__.toast.configure is not a function
> 
> 
> 
> Can any one help with this please

**Comment by crrobinson14** [comment]
For anyone that lands here as I did looking for the same solve, there is a very stupid thing you can do that will also make toasts not appear. _They will not appear blank._ If you call `toast(undefined)` no toast will be shown, and no error will be logged in the console.

Now why would one do that? Well, assume "not me, it was a friend, honest" is tired and tries to do a simple `toast(error.message)` in a try/catch block. And assume your friend is using a library that can throw things other than standard `Error` objects, so there is no message property. Your friend might very well sit for 30 mins trying to figure out why the toast library isn't working. Just saying...
