### ISSUE TITLE
when i moving next page it is gone

### ISSUE THREAD

**Issue by manimurugank** [fkhadra/react-toastify#214]
when i moving next page it is gone

**Comment by AugustinLF** [comment]
This will happen if the component that renders the `<Toast />` is unmounted when you change your page. You should render the `<Toast />` at the root of your app, on a component that will be kept when you change of page.

**Comment by fkhadra** [comment]
Hello @manimurugank ,

I didn't take the time to respond. @AugustinLF is right. If you render the `ToastContainer` at the root of your app you should not encounter this issue.
