### ISSUE TITLE
The styles seem to be missing with the most basic setup.

### ISSUE THREAD

**Issue by NoMercy235** [fkhadra/react-toastify#216]
Hello! I have set up a playground here https://stackblitz.com/edit/nomercy235-react-pg-bo6ddb?embed=1&file=index.js to test the library in a more confined environment since I'm having the same issue in my main project. I have done the installation and usage steps, but, no matter what, the toaster looks like that. Does anyone have any idea why that happens?

![image](https://user-images.githubusercontent.com/24717857/43709886-be7f7b2e-9976-11e8-9bbd-4e7381cf2011.png)

**Comment by fkhadra** [comment]
Hello @NoMercy235,

You need to import the style as well:
```js
import 'react-toastify/dist/ReactToastify.css';
```

**Comment by NoMercy235** [comment]
Ah... Thank you! Is that specified somewhere in the docs? I couldn't find anything written about this.

**Comment by fkhadra** [comment]
Yes under the Usage section [here](https://github.com/fkhadra/react-toastify#usage)

Maybe I'll need to highlight it.

**Comment by NoMercy235** [comment]
Oh, it was in the comment section. 😄 Sorry, I totally missed it.

**Comment by liranh85** [comment]
Completely missed it as well! Thanks
