### ISSUE TITLE
Style object not applied ?

### ISSUE THREAD

**Issue by mtompkins** [fkhadra/react-toastify#22]
I was trying to pass a style object with the balance of options as:

```
const UpAvlOpts = {
  type: 'info',
  autoClose: false,
  style: {
    color: 'black',
  }
};
```

Yet the style wouldn't apply. Is there a different way we should pass the inline object?
The balance of options are working as expected.

**Comment by fkhadra** [comment]
@mtompkins  there is no style option for the toast. The easiest way to set your style would be to override the default toast class.
Do you think that adding a style option can be useful?

**Comment by mtompkins** [comment]
I think it is likely a necessary feature because without the ability to adjust the content within the toast appearance can suffer. For example, when an icon is significantly bigger than the provided text, alignment can look off. Or in my case, ... Below is a screenshot.

The top toast looks awesome, icon size and text alignment. (margin above and below icon & text is equal)
The bottom toast looks poor, and I wanted to match the size of the upper (min-height was my approach) then center the text likely with a `@mixin` or some other CSS manner.  (margins different and text not vertically centered)
That lower toast icon is animated which gives great effect - but it also makes you notice the alignment.

![screenshot from 2017-05-28 16-57-58](https://cloud.githubusercontent.com/assets/4105910/26532156/788ac4f8-43c7-11e7-95e0-8c41852c75ad.png)

**Comment by fkhadra** [comment]
So the reference you mentioned it's only for the `ToastContainer` component not for the toast. Just to give you an idea imagine I do that: `<ToastContainer autoClose={false} style={{border: '1px solid red'}} />`
Here is what it looks like
 ![toast-container-style](https://cloud.githubusercontent.com/assets/5574267/26532294/f1331754-43fc-11e7-9ce3-68f4f6af37ba.png)

In your case, you want to adjust the content. When you render a toast you can get the desired effect by  styling the toast:

`toast(<div style or className here>more tag</div>)`

Do I miss something ?

**Comment by mtompkins** [comment]
Nope - great explanation and makes sense. Thanks so much - the more I use this little thing the move I love it...especially that dismiss by assignment you pushed!

**Comment by fkhadra** [comment]
Thank you :grin: I close this issue then
