### ISSUE TITLE
"Symbol" ist undefiniert error in IE 11

### ISSUE THREAD

**Issue by TarikHuber** [fkhadra/react-toastify#222]
Browser: IE 11 (it works on other browsers I tested like Chrome, Firefox, Edge)
react-toastify version: 4.2.0 

Error message:
"Symbol" ist undefiniert

The error is gone wehen falling back to 4.1.0

**Comment by fkhadra** [comment]
Hello @TarikHuber ,

Thanks for the feedback. I'll fix it asap.

**Comment by TarikHuber** [comment]
Thx @fkhadra for the fast response. We just use the older version untill the fix arrives. Not a big problem. A Browserstack test that failed showed us the problem. Maybe a solution for this project to. It's free for open source projects.

**Comment by fkhadra** [comment]
Perfect. I'll publish the fix during this week. 

Indeed, Browerstack is a really good idea. I'll see how to add it to my stack.

**Comment by TarikHuber** [comment]
Hi @fkhadra,

Maybe this example of a project with browserstack can help: https://github.com/TarikHuber/react-most-wanted

That is the one that detected this issue. It checks only the version of the project that is already deployed but better than nothing. Need to fix that to to check on localhost at Travis.

**Comment by fkhadra** [comment]
Hey @TarikHuber,

Thanks. I already fixed the issue but I wanted to add an additional feature for the next release.

I'm gonna publish a patch release with that fix first. So It fixes the bug first.

**Comment by fkhadra** [comment]
Hey @TarikHuber,

I published the v4.2.1. Should be ok now :)
