### ISSUE TITLE
Warning: React does not recognize the `closeToast` on using custom css classes 

### ISSUE THREAD

**Issue by caype** [fkhadra/react-toastify#224]
Hello,

I'm using custom css classes in my web-app to style the default toastr message. The resultant toastr message looks like this: 

![toastr-screenshot](https://user-images.githubusercontent.com/6301204/44467420-d63f3200-a5f0-11e8-863f-8066a529528e.png)

and I am using the following code to display a toastr and everything works well.

`toast.success(`We have successfully updated your preference.`, {
                className: "toasterSuccess",
            });`

But, React throws me this warning whenever a toastr message is displayed on the screen:

**Warning: React does not recognize the `closeToast` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closetoast` instead. If you accidentally passed it from a parent component, remove it from the DOM element.**

Can someone help me in suppressing these warnings?

**Comment by fkhadra** [comment]
Hello @caype,

Could you share a code snippet on codesanbox for instance.

Which version of react are you using ?

Thanks

**Comment by caype** [comment]
Hey @fkhadra ,

I'm using React 16.3.2. you can find the behaviour in [this](https://codesandbox.io/s/jlm4kz3709) sandbox.

screenshot of the error on codesandbox.io:

![image](https://user-images.githubusercontent.com/6301204/44483273-a1df6c00-a618-11e8-87d2-4f9d6e5e36b3.png)

Thanks in Advance.

**Comment by caype** [comment]
I understood what's going wrong. Instead of implementing a **component** for the **closeButton** prop, I'm directly passing in an Image tag for that prop.

Thanks again for the library 👍

**Comment by fkhadra** [comment]
@caype I was about to answer. I'm glad you solved the issue. 

> Thanks again for the library 👍

My pleasure 😁

**Comment by alish1129** [comment]
What's the answer to this error? I am getting it but I haven't used any closeButton or closeToast prop.

**Comment by afozbek** [comment]
If anyone still doesnt understand the solution, all you have to do that create a React element as a wrapper for toastContent.

### Old Code
```js
// toast component
import { toast as alert } from "react-toastify";

const toast = (message, hasSuccess = true) => {
  // destructuring props

  // state

  // effect

  // other variables/functions
  let toastIcon = hasSuccess ? <i className="icon-success"></i> : <i className="icon-exclamation"></i>;
  let toastType = hasSuccess ? TOAST_TYPES.SUCCESS : TOAST_TYPES.ERROR;
  // render
  const toastContent = (
      <Col className="toast-content-wrapper">
        <div className="toast-icon">{toastIcon}</div>
        <div className="toast-message">{message}</div>
      </Col>
  );
  
  // toastType -> success | error -> toast.success | toast.error
  return (
    alert[toastType](toastContent)
  );
};
```

### New Code

```js
import { toast as alert } from "react-toastify";
// This container required for the first parameter of the toast function
const Container = (props) => <div>{props.children}</div>;

const toast = (message, hasSuccess = true) => {
  // destructuring props

  // state

  // effect

  // other variables/functions
  let toastIcon = hasSuccess ? <i className="icon-success"></i> : <i className="icon-exclamation"></i>;
  let toastType = hasSuccess ? TOAST_TYPES.SUCCESS : TOAST_TYPES.ERROR;
  // render
  const toastContent = (
    <Container>
      <Col className="toast-content-wrapper">
        <div className="toast-icon">{toastIcon}</div>
        <div className="toast-message">{message}</div>
      </Col>
    </Container>
  );
  return (
    alert[toastType](toastContent)
  );
};
```

**Comment by engineforce** [comment]
A simpler solution is to use an anonymous component

```ts
import { toast } from "react-toastify";

function App() {
  toast(() => <Col className="toast-content-wrapper">
        <div className="toast-icon">{toastIcon}</div>
        <div className="toast-message">{message}</div>
      </Col>
  )
 
  ...
}

```

**Comment by regivaldo-ciandt** [comment]
Thanks a lot!

I did it this way, using `<></>` and it worked.

```typescript
import { toast } from "react-toastify";

function App() {
  toast(
      <>
        <Col className="toast-content-wrapper">
          <div className="toast-icon">{toastIcon}</div>
          <div className="toast-message">{message}</div>
        </Col>
      </>,
      options,
    );

  ...
}
```

**Comment by regivaldo** [comment]
Thanks a lot!

I tried two manner and both resolved:

Using `<></>` and anonymous component.

```typescript
toast(
      () => (
        <Col className="toast-content-wrapper">
          <div className="toast-icon">{toastIcon}</div>
          <div className="toast-message">{message}</div>
        </Col>
      ),
      options,
    );
```

```typescript
toast(
      <>
        <Col className="toast-content-wrapper">
          <div className="toast-icon">{toastIcon}</div>
          <div className="toast-message">{message}</div>
        </Col>
      </>,
      options,
    );
```

**Comment by phazei** [comment]
Those solutions are all kind of workarounds.  It expects a specific component:

```jsx
import { toast, ToastContent, ToastContentProps, ToastOptions, TypeOptions } from 'react-toastify'
...

        const content: ToastContent = (props: ToastContentProps) => (
            <Col className="toast-content-wrapper">
                <div className="toast-icon">{toastIcon}</div>
                <div className="toast-message">{message}</div>
            </Col>
        )

        // Call toast with the computed type
        toast(content, options)

```

Without it it injects all these as html attributes into the dom:
```ts
interface ToastContentProps<Data = unknown> {
    closeToast: CloseToastFunc;
    toastProps: ToastProps;
    isPaused: boolean;
    data: Data;
}
```
