### ISSUE TITLE
Position property in options to toast object

### ISSUE THREAD

**Issue by aseem2625** [fkhadra/react-toastify#23]
Just found this library and used it. Absolutely loved it. Only feature I felt missing was `position` property in options to `toast` object.

Is it limitation by design?

**Comment by fkhadra** [comment]
Glad you liked it! To be honest, I thought about it but I always wondered if it made sense from a user POV.
Anyway, it can be useful :grin:

**Comment by aseem2625** [comment]
@fkhadra Yes, absolutely useful. API related success/failure can be shown in bottom-left. Other app level notifications can be shown on top-center (and lot other combination as what user wants).

I will go through your code in 1-2 days and see if I can send PR to support this.

**Comment by fkhadra** [comment]
Thanks for the details. I already have an idea how to implement it. I'll also try in 1 or 2 days depending on free time.

**Comment by fkhadra** [comment]
Hey @aseem2625,

I had the time to implement it during the lunch!
![image](https://cloud.githubusercontent.com/assets/5574267/26548235/72a3f2ba-4473-11e7-85b9-8de1af8a3244.png)

I will try to push it today or tomorrow

**Comment by aseem2625** [comment]
@fkhadra 
Haha looks nice.. you're fast 😄

**Comment by fkhadra** [comment]
@aseem2625 feature available in [v1.7.0](https://github.com/fkhadra/react-toastify/tree/v1.7.0)

**Comment by aseem2625** [comment]
@fkhadra Aah great. Going to update it soon. Thank you 😄

**Comment by aseem2625** [comment]
Hey @fkhadra 
Great work.. Works fine.

Just a thing i noticed.

![image](https://cloud.githubusercontent.com/assets/6055628/26673149/7d620de6-46d9-11e7-9f52-90d0739834d7.png)


The space in of left boxes from window & right boxes from window is different.
It's due to `left: 1em` given to left boxes and `right: 2em` given to right boxes.

**Comment by fkhadra** [comment]
Hey @aseem2625 I created an issue to fix it. Thanks for the feedback
