### ISSUE TITLE
IE11 -- showing  object expected error 

### ISSUE THREAD

**Issue by sureshbakshi** [fkhadra/react-toastify#232]
![ie11issue](https://user-images.githubusercontent.com/19382918/45167038-f4727800-b215-11e8-80b9-5e202775429f.PNG)

Added polyfills :  <script src="https://cdn.polyfill.io/v2/polyfill.js"></script>

**Comment by fkhadra** [comment]
Hello @sureshbakshi,

I think your issue is somewhere else. You can find below a working sandbox with the polyfills you provided:
[![Edit 189kvok053](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/189kvok053)
