### ISSUE TITLE
Auto-close timer continues to run with pauseOnHover=true when hovering the close button

### ISSUE THREAD

**Issue by BloodShura** [fkhadra/react-toastify#237]
Version **4.3.1**.

With *autoClose* set to a defined duration, and *pauseOnHover* set to true, when the mouse enters the component, it correctly stops the autoClose timer.

**However**, if the mouse enters the **close button** (or any other custom component added to the notification component besides text), the timer continues to run, and won't stop again if the mouse **exists the whole component and enters again**.

**Comment by fkhadra** [comment]
Hello @BloodShura,

Indeed, when hovering the close button the toast don't pause. I agree it should be the case.

**Comment by ketysek** [comment]
I would love to see this fixed, have links in toasts but it sometimes disappears even sooner than the user clicks on it - it doesn't pause the timer on hover over the <Link> component in my code
```
const ToastContent = ({ text, route }) =>
  route ? (
    <span className="toast-text flex">
      <span className="text">{text}</span>
      <Link to={route} className="link">
        View <FontAwesomeIcon icon={["far", "chevron-right"]} />
      </Link>
    </span>
  ) : (
    <span className="toast-text">{text}</span>
  )
```

**Comment by adamwade2384** [comment]
I am seeing this issue again in react-toastify:^9.1.1 on Chrome Version 108.0.5359.98 (Official Build) (x86_64)

**Comment by mohitvijay** [comment]
I am also seeing this issue again in react-toastify:^9.1.1
