### ISSUE TITLE
Such a great utility!

### ISSUE THREAD

**Issue by iorrah** [fkhadra/react-toastify#238]
This is not an issue I just wanted to acknowledge you guys for creating such a useful utility and for doing an amazing job. It's so cool how this dependency just works so well out-of-the-box and the documentation is so descriptive and easy to understand. Appreciate all the effort, thanks!

**Comment by nickluger** [comment]
Thank you, from my side, as well. Excellent job. 👍

**Comment by fkhadra** [comment]
Thanks for the support guys! Appreciate!
