### ISSUE TITLE
Stacking toasts vertically

### ISSUE THREAD

**Issue by cihati** [fkhadra/react-toastify#242]
Hi,

First of all, thanks for the great library!

Currently, if you have multiple toasts, the stack horizontally (and looks quite ugly in mobile as they go over each other) I was wondering if it's possible to expose a setting to make them stack vertically?

Thanks!

**Comment by cihati** [comment]
That's very weird! They do stack horizontally for me: 

![image](https://user-images.githubusercontent.com/461998/46002330-bc888300-c0a5-11e8-8a84-173dcf28dd7f.png)

I wonder why..

**Comment by fkhadra** [comment]
oww xD it's very weird indeed. Could you reproduce the issue on codesandbox ?

**Comment by blu3printchris** [comment]
Can't imagine the CSS properties of your parent div are affecting the positioning of the ToastContainer?

**Comment by fkhadra** [comment]
I closed the issue due to inactivity. Also I don't get much request to choose the stack direction.

**Comment by waleedbutt98** [comment]
add this in toast container component
```
<ToastContainer
  style={{
    display: 'flex',
    flexDirection: 'column',
    width: "max-content"
  }}
/>
```

Works Fine For Me!
