### ISSUE TITLE
Add Title Field to toast

### ISSUE THREAD

**Issue by kenshinman** [fkhadra/react-toastify#243]
Hi This is a feature request, Can you please allow for toast title parameter to be added to this package? Thanks

**Comment by fkhadra** [comment]
Hey @kenshinman,

You can pass a react component, more detail [here](https://github.com/fkhadra/react-toastify#render-a-component).

```js
import React from 'react';
import { ToastContainer, toast } from "react-toastify";

const Msg = ({ closeToast }) => (
  <div>
   <h2> My title</h2>
   <p> Some test </p>
  </div>
)

const App = () => (
  <div>
    <button onClick={() => toast(<Msg />)}>notify</button>
    <ToastContainer />
  </div>
);
```

**Comment by kenshinman** [comment]
Thanks @fkhadra. I later found this in the doc. Didn't know it had been updated. Been a while since I used it
