### ISSUE TITLE
Disable backdrop of toast notification?

### ISSUE THREAD

**Issue by benprofit** [fkhadra/react-toastify#244]
is there any way of disabling actions such as clicks and scrolls on the background/ backdrop when the notification appears? I want to disable the page to force user to click notification.

**Comment by fkhadra** [comment]
Hello @benprofit,

You can use the `onOpen` and the `onClose` callback I think to do that. Doc [here](https://github.com/fkhadra/react-toastify#define-callback). 
If it's not what you are looking for, tell me and I'll try to dig more around it.

**Comment by benprofit** [comment]
customizing the callback worked. thank you !

**Comment by thisKeeWord** [comment]
@unknouun How did you get it to work? It's almost 3 years after the initial post, so if you don't recall, that's very much understandable.

**Comment by amithashenoy** [comment]
@thisKeeWord  : Hi are you able to resolve it ?

**Comment by thisKeeWord** [comment]
I don't think I ended up finding a solution.
