### ISSUE TITLE
Bind callback to the notification container.

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#248]
> Follow up [issue 160](https://github.com/fkhadra/react-toastify/issues/160#issuecomment-426634754)

> Original post:

> @fkhadra  unfortunatelly, with your solution user can click outside the rendered  span/div, and just close toast without being redirected to other page.  Having onClick for toast would be very great for that case.

> Hey @Strate,
You want to redirect the user or perform any action when the user closes the toast right ?

> @Strate
Strate commented 13 minutes ago

> @fkhadra not exactly.
If user closes toast by clicking on x button, toast should dismiss.
If user clicks on toast, then I want to perform some action (redirect to page, for example).
Chrome notifications work like I want to implement on page.

@Strate I created a new issue. It's easier for me to follow 😆.

**Comment by alexluong** [comment]
I'd like to help out with this issue.

**Comment by alexluong** [comment]
#253

**Comment by rtman** [comment]
Would like to see this feature implemented
