### ISSUE TITLE
Default toast type

### ISSUE THREAD

**Issue by alexluong** [fkhadra/react-toastify#251]
Hi. I just found out about `react-toastify` and absolutely adore it.

In my use case, most of the time the toast is gonna be of type `TYPE.ERROR`. Is there any way for me to set it as the default type so that I don't have to set it every time I toast?

Also, I'd be happy to add this in if it's not already there in the spirit of Hacktoberfest!! Regardless, thanks for creating such a great library.

**Comment by fkhadra** [comment]
Hey @alexluong,

Glad you like it. 

Did you know that you can call a toast as follow? You can find all shortcut [here](https://github.com/fkhadra/react-toastify#toast)
```js
toast.error("hello");
```
Another solution would be to reexport your own toast function. This give you more control and better abstraction:

```js
import { toast } from 'react-toastify';

export const myToast = toast.error; 

//somewhere else
import { myToast } from './myToast';

myToast('hello');
```

That answers your question?

**Comment by alexluong** [comment]
Hi @fkhadra,

Thanks for your super fast response. The `toast.error` function does it for me.

**Comment by fkhadra** [comment]
Perfect !
