### ISSUE TITLE
toast.update re-init progressBar

### ISSUE THREAD

**Issue by Bastorx** [fkhadra/react-toastify#255]
Hello there,

I would like to launch a toast.update without change the time left and without restart the progressbar.

Is it possible?

Thanks

**Comment by PhilipGarnero** [comment]
You can implement that yourself using the new progress feature

**Comment by fkhadra** [comment]
I think this is what you are looking for: https://github.com/fkhadra/react-toastify#use-a-controlled-progress-bar
