### ISSUE TITLE
add browser Compatibility list

### ISSUE THREAD

**Issue by Niphery** [fkhadra/react-toastify#26]
I've tested a basic example on:
Firefox
Chrome
Safari
Edge
without issue.
However it seems that IE 11 didn't work.

**Comment by fkhadra** [comment]
You're right. 

For ie11 we need to polyfill `Object.prototype.includes` method and also prefix some css classes.

I'll fix that

**Comment by Niphery** [comment]
Hello @fkhadra 
Would you have any feedback on your progression toward the v1.7.1 ?

**Comment by fkhadra** [comment]
Hello @Niphery,

I asked [BrowserStack](https://www.browserstack.com) to let me use their tool to test the compatibility. 

They activated my account today. So I expect to release the v1.7.1 this week Saturday or Sunday. I'll let you know as soon as I deploy the new release.

The new release will also include a new design by default. [issue 28](https://github.com/fkhadra/react-toastify/issues/28). I would like to have your opinion if you don't mind 😀

**Comment by fkhadra** [comment]
I published the v2. I'll fix the animation bug for ie11 this week

**Comment by Niphery** [comment]
Great news! Good job on your work btw 👍

**Comment by fkhadra** [comment]
Thanks, appreciate the support :grin:
