### ISSUE TITLE
Option to not start autoClose timer until page has focus

### ISSUE THREAD

**Issue by evansjohnson** [fkhadra/react-toastify#261]
Similar to `pauseOnFocusLoss`.  Perhaps named `pauseUntilFocus`.

If a user navigates away from my app and receives a notification, I would like to not start the countdown timer until the page has focus.  I could do this on my end by queuing up notifications that I fire when the page has focus but imagine this could be helpful to other users of this library.

I can look into making a PR for this if you'd like!

**Comment by fkhadra** [comment]
Hey @evansjohnson,

This is not already the case with `pauseOnFocusLoss` ?

**Comment by evansjohnson** [comment]
Running Chrome 67 on Linux and I am observing a notification appear and the autoClose progress bar start counting down when the page isn't focused.

I imagine whatever check is being done for `pauseOnFocusLoss` can also be performed when launching a notification.  I can try to file a PR for this - do you want to say this is a bug with `pauseOnFocusLoss` or introduce a new prop `pauseUntilFocus`?

**Comment by fkhadra** [comment]
closing for housekeeping purpose
