### ISSUE TITLE
Cannot update toastId

### ISSUE THREAD

**Issue by evansjohnson** [fkhadra/react-toastify#264]
I assume this is expected behavior but didn't see anything in the docs about not being able to update the toastId with the `toast.update` method.

I am calling `update` and am seeing all the new options reflected, but when I call `isActive` with the new `toastId` I passed in I get `false`, and `true` for the old `toastId`.

In my use case I have 3 types of notifications that update sequentially and for other updating purposes it would help me if the `toastId` reflected the current updated state of the notification.

I'm not sure if this would be a feasible refactor since I'm sure `toastId` is baked into the code everywhere but would love to hear your thoughts on this - perhaps I should be using a different pattern or you are aware of a simple way for me to support this outside the library.

reproducer - open console to see output of `isActive`
https://codesandbox.io/s/p3j839m9ym

Thanks!

**Comment by evansjohnson** [comment]
This is working for me in my app now.  You may find a cleaner way of doing it but the crux is to generate a key to use to track the toast independent of the toastId.

The key refers to a toast over its lifetime, persistent over `update` calls, and the user need not know of it's existence.  A `toastId` is how a user refers to the toast, which may now change over time.

Consider this simplified example:
-I launch a toast with id "pendingConfirmation".
-The reason I use this id is so I can aggregate multiple pending confirmation messages into the same "pendingConfirmation" toast.
-I update the "pendingConfirmation" toast to a success message.
-I need to update the id to "successfulConfirmation", so that I can aggregate successful confirmations in the same toast.
-I also need to be able to update the id so that I can once again start aggregating "pendingConfirmation" messages in the "pendingConfirmation" toast.

I understand if you're busy and don't get to this for awhile but would love to hear your thoughts if you get a chance @fkhadra thanks!

**Comment by fkhadra** [comment]
Hello @evansjohnson,

Sorry for the delay. Following your example it makes a lot of sense to be able to update the `toastId`. It is the case for the other options.

Your sentence is very relevant. It clearly show that using a `toastId` as a `key` is a design issue. So thank you for pointing this out. 
> The key refers to a toast over its lifetime, persistent over update calls, and the user need not know of it's existence. A toastId is how a user refers to the toast, which may now change over time.

**Comment by evansjohnson** [comment]
Thanks for the reply @fkhadra - #268 is the corresponding PR I made for this if you get around to trying it out.  I've got my project pointing to a custom build in the meantime so no rush from me 🙂
