### ISSUE TITLE
TransitionGroup error in IE11

### ISSUE THREAD

**Issue by martinmcneela** [fkhadra/react-toastify#265]
Get the following waring when using the most basic example of this in IE11: **_Warning: Failed prop type: Invalid prop `children` supplied to `TransitionGroup`, expected a ReactNode._**

I have added `<ToastContainer />` and then call a notification using `toast('Is it working?');`

**Comment by fkhadra** [comment]
Hey @martinmcneela,

Thanks i'll check asap

**Comment by belgi** [comment]
Hi, any progress on this one?

**Comment by fkhadra** [comment]
Hello @belgi,

Not yet. Does it occur with the latest version ?

**Comment by NerdCowboy** [comment]
@fkhadra Can confirm this is still happening with the latest version
