### ISSUE TITLE
New toast not appearing after when created just after calling toast.dismiss()

### ISSUE THREAD

**Issue by liegeandlief** [fkhadra/react-toastify#270]
I want to be able to dismiss all existing toasts when a submit button is clicked and then if there are any errors with the submission show new toasts.

But currently if I call `toast.dismiss()` and then create a new toast very shortly afterwards, the new toast never appears.

Perhaps the delay in dismissing the toasts means that the new toast is actually created before toasts are dismissed and therefore the new toast gets dismissed too.

**Comment by fkhadra** [comment]
Hey @liegeandlief,

Could you reproduce your issue with codesandbox please ?

Thank you

**Comment by liegeandlief** [comment]
Hey @fkhadra,

On further investigation it appears that this happens because `toast.isActive(id)` does not immediately report `false` for a particular ID after calling `toast.dismiss()`.

I use `toast.isActive(id)` to determine whether to create a new toast or update an existing one. But sometimes after calling 'toast.dismiss()` , `toast.isActive(id)` still returns `true` for a particular ID if `isActive` is called quickly enough after `dismiss`. My code then tries to update the toast rather than creating a new toast albeit with the same ID.

This can be seen in the following Code Sandbox (https://codesandbox.io/s/4xrr6307k7) by opening the console, pressing the `Make initial toasts` button to reveal three toasts, and then pressing the `Dismiss toasts and check active status` button.

In the console you will see `true, false, false`. Instead of `false, false, false` as expected.

**Comment by liegeandlief** [comment]
Thanks for the explanation @fkhadra and thanks for the super fast replies! Now I understand how it is working under the hood I should be able to refactor my code appropriately.
