### ISSUE TITLE
Remove const enum from ts interface

### ISSUE THREAD

**Issue by Svehla** [fkhadra/react-toastify#272]
# Remove const enum from ts interface

first of all react-toastify is awesome

Now we update our CRA (create-react-app) to the newer version. New CRA does not support const enums 😢 
source: https://facebook.github.io/create-react-app/docs/adding-typescript

I think that a lot of user as me will use the newest CRA in their react projects. 

Do you think that there is an option to remove const enum and repalce it with normal enum? (only remove const from ToastPosition ToastType)
ttps://github.com/fkhadra/react-toastify/blob/master/index.d.ts#L3

Thx and have a nice day

**Comment by fkhadra** [comment]
Hey sure, there is already a PR for that. I'm busy merging all the PR. 
Thanks for your feedback

**Comment by Svehla** [comment]
Okey sorry for that ^^ 
I didn't look to PR section

**Comment by fkhadra** [comment]
It's fine don't worry. I'll let you know when it's done

**Comment by tjugg** [comment]
Same issue, good that it's being worked on :). Will you be merging the PR soon?

**Comment by fkhadra** [comment]
Hello @Svehla, @tjugg, 

The PR has been merged and the fix is live. Thanks for the patience. 

Thanks for the support also.
