### ISSUE TITLE
Prevent duplicate with custom toastId - buggy toast appears that does not auto-close.

### ISSUE THREAD

**Issue by JanuszBartosz** [fkhadra/react-toastify#274]
Hello!
I am trying to prevent showing duplicated toasts using custom toastId. I am using autoClose option (2000ms).  After multiple calls to e.g. toast.error() with same toastId feature works perfectly - only the first toast is being displayed. However, when autoClose time is finished and toast is ready to be closed - calling the toast.error() function results with showing the same toast once again, but this time with no autoClose timer. I deducted from experiments, that this occurs precisely when toast function is called **during closing animation** of the previous toast. Here is CodeSandbox snippet - to reproduce just start hitting 'Toast' button near active toast timer finish. 

[![Edit 7j5r23pykj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7j5r23pykj)

This bug does not appear when I am using isActive() function to prevent duplicates, however combining isActive() and setting custom toastId still causes above unwanted behaviour. For the design reasons it is important for me to be able to prevent duplicates using custom toastId, cause managing auto generated ids will quickly become quite a pain.

isActive() version:
[![Edit jp5wprpyz5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jp5wprpyz5)

Thanks in advance!

**Comment by brucem1976** [comment]
I see the same behaviour if the following is called in quick succession. The .dismiss(2) call is not working consistently. (I think it might be the same issue?)
```
  notifyWarn(msg: string) {
    if (msg === "") {
      toast.dismiss(2);
    } else if (!toast.isActive(2)) {
      toast(msg, { toastId: 2, type: toast.TYPE.WARNING });
    } else {
      toast.update(2, { render: msg, type: toast.TYPE.WARNING });
    }
  }
```

**Comment by raRaRa** [comment]
Same issue here. After the toast disappears automatically and I try to show it again quickly after, then it won't show up with animation and autoClose doesn't work on it, and the progress bar doesn't show up. This only happens if I try to show the toast again quickly after the first one auto closes.

```
            if (!toast.isActive('designer_refresh')) {
                toast('test', {
                    toastId: 'designer_refresh',
                    position: 'top-right',
                    autoClose: 2000,
                    hideProgressBar: false,
                    closeOnClick: true,
                    // pauseOnHover: true,
                    draggable: true,
                    className: 'notificationToolTip',
                });
            }
```

**Comment by fkhadra** [comment]
Hello everyone,

I think I know where the bug is coming from. I'll be able to work on it in 2 weeks.

**Comment by raRaRa** [comment]
Hi. Any update on this? Thanks!

**Comment by phamvanlinh20111993** [comment]
i have same problem, when i click more one time and consecutive, toast do not disappear although i'm using {autoClose:4000} ? thanks

**Comment by phamvanlinh20111993** [comment]
i update new version, problem fix. Thanks so much.

**Comment by JanuszBartosz** [comment]
Yes, it works alright now :slightly_smiling_face: Thank you for your support!

**Comment by raRaRa** [comment]
Thank you @fkhadra, much appreciated!
