### ISSUE TITLE
Support for controlled progress bar, PR #281

### ISSUE THREAD

**Issue by Ugzuzg** [fkhadra/react-toastify#280]
I'd like to use toasts for uploading purposes like in this example from README.md, but also showing an upload progress on it:  
![](https://user-images.githubusercontent.com/5574267/33761953-1ce2e0ea-dc0b-11e7-8967-a63c1185ce0e.gif)

As I see it:
- provide `progress` option for toasts
- if `progress` is set, it takes preference over `autoClose` and just renders progress bar at the position specified
- you can update your toast to unset `progress` and start `autoClose` timer

What do you think?

Thanks!

**Comment by fkhadra** [comment]
Hey @Ugzuzg,

Indeed it could be a good idea. I'll starting to iterate on the next release in 2 weeks. I'll see what can be done in this area.

**Comment by Ugzuzg** [comment]
@fkhadra, here are my changes to achieve this: https://github.com/fkhadra/react-toastify/pull/281
