### ISSUE TITLE
Redux example shows anti-pattern

### ISSUE THREAD

**Issue by Levino** [fkhadra/react-toastify#283]
In the redux-demo you create a side effect from the reducers:
```js
import { toast } from "react-toastify";

const initialState = {
  value: 0
};

function addReducer(state = initialState, action) {
  switch (action.type) {
    case "INCREMENT":
      toast.success("INCREMENT");
      return { ...state, value: state.value + 1 };
    case "DECREASE":
      toast.warn("DECREASE");
      return { ...state, value: state.value - 1 };
    default:
      return state;
  }
}

export default addReducer;
```
You should never do this, this is a total anti-pattern. I suggest triggering these side effects in a thunk (where you do not await the result, but still it is more transparent to create a side effect from a thunk than from a reducer). The current example will make people adopt this bad style.

**Comment by fkhadra** [comment]
Hey @Levino,

I don't use redux at all so you are probably right. I made the example based on the basic example provided by the redux documentation.

The purpose of my example is just to demonstrate that the library can work with redux. I want to keep the example as simple as possible. 

Please feel free to open a PR with a better example.

**Comment by Levino** [comment]
Where is the source? I only see the fiddle...

**Comment by fkhadra** [comment]
Hello @Levino,

Sorry for the late reply. What you can do is to create a codesanbox and add the link to the README.
