### ISSUE TITLE
Error while generating a build with v 4.4.3

### ISSUE THREAD

**Issue by muhammad-asad-26** [fkhadra/react-toastify#287]
Failed to compile.

./node_modules/react-toastify/dist/ReactToastify.min.css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at Array.forEach (<anonymous>)

error Command failed with exit code 1.

**Comment by amrendraw3** [comment]
I am getting the same error while building my React app:
`Node: 8.12.0`
`react-toastify: 4.5.2`

**Comment by fkhadra** [comment]
Could you provide more details like your setup `create-react-app`, webpack ?

**Comment by amrendraw3** [comment]
The issue had been gone after removing `node_modules` folder and installing it again using `npm install`. I also commented the code where it import the `css` file (`// import 'react-toastify/dist/ReactToastify.css';`) for this toastify and paste the `css` into my own file.

**Comment by fkhadra** [comment]
Perfect I close the issue then.
