### ISSUE TITLE
Would you be so kind to publish typings for this?

### ISSUE THREAD

**Issue by kabaluk** [fkhadra/react-toastify#29]
Really wanted to use this with Typescript.
Would be really nice if you could add Typings and publish to @types

**Comment by fkhadra** [comment]
Hello @kabaluk,

I have to rewrite the lib using Typescript or is just something like typescript definition?
I don't know too much about typescript ecosystem.

**Comment by kabaluk** [comment]
just the typecript definition would suffice and be very appreciated I am sure. 

    On Tuesday, 27 June 2017, 11:52, Fadi Khadra <notifications@github.com> wrote:
 

 Hello @kabaluk,I have to rewrite the lib using Typescript or is just something like typescript definition?
I don't know too much about typescript ecosystem.—

**Comment by midori0507** [comment]
@kabaluk just create custom typing for it, in types folder under `rootDir`, have folder with `react-toastify` and `index.d.ts` inside

For example i only use ToastContainer and toast
```
declare module 'react-toastify' {
    const content: any 
    export const ToastContainer: any
    export const toast: any
    export default content
}
```

**Comment by fkhadra** [comment]
Hey @kabaluk,  the typescript definition is on my todo list.

**Comment by talend-jphautin** [comment]
the one I am using until the official one. not perfect but could be a good start.
`declare module 'react-toastify' {

    export let toast:Toast;

    interface Toast {
        success(content:React.ReactNode, options?:ToastOptions):number
        info(content:React.ReactNode, options?:ToastOptions):number
        warn(content:React.ReactNode, options?:ToastOptions):number
        error(content:React.ReactNode, options?:ToastOptions):number
        isActive(toastId:number):boolean;
        dismiss(toastId:number):void;
        (content:React.ReactNode, options?:ToastOptions):void
    }

    interface CommonOptions {
        pauseOnHover?:boolean;
        closeOnClick?:boolean;
        autoClose?:number;
        position?:string;

    }

    interface ToastOptions extends CommonOptions {
        onOpen?:() => void;
        onClose?:() => void;
        closeButton?:React.ReactNode;
        className?:string;
        progressClassName?:string;
        pauseOnHover?:boolean;
        closeOnClick?:boolean;
    }

    interface ToastContainerProps extends CommonOptions {
        type?:string
        hideProgressBar?:boolean;
        newestOnTop?:boolean;
    }

    export class ToastContainer extends React.Component<ToastContainerProps> {
    }

}`

**Comment by fkhadra** [comment]
Hey @talend-jphautin ,

I appreciate a lot!  Merci 😀 . It's definitely a good start. I'll work on it this weekend. Thank you again.

**Comment by kabaluk** [comment]
Heya.
We did end up auto generating one with dts-gen. 
But the tool is not great and everything is any which kind beats the point.
the one from @talend-jphautin seems much nicer.

Thanks all for this.

**Comment by fkhadra** [comment]
In typescript is it possible to do something like:

```js
interface CommonOptions {
...
    closeButton?: React.ReactNode|false; // Can be a node or false
...
}
```

**Comment by fkhadra** [comment]
Hello,

May I ask for help, please. I wrote the definition file. The types hinting seems to works
<img width="401" alt="type hinting" src="https://user-images.githubusercontent.com/5574267/31671546-7d353c74-b35a-11e7-9337-d6662e5f57ba.png">

I'm wondering why I can't see the shape of the `ToastOptions`. Did I miss something?
