### ISSUE TITLE
How to add "id" attribute for testing purpose?

### ISSUE THREAD

**Issue by CrispusDH** [fkhadra/react-toastify#292]
Hello, I do not find a good way for adding unique "id" attribute for the `toast` and `toast body`. Currently, I work within `className` but would be great to have optional parameter `id`. Thanks

**Comment by fkhadra** [comment]
Hey @CrispusDH,

Could you share which kind of test you would like to implement ?

**Comment by CrispusDH** [comment]
I write e2e UI automation tests using Protractor framework. Currently, I'm using `className` and `bodyClassName` for identifying Toast element and text inside. But, best practice is to add `id` attributes and use them. @fkhadra , thanks for fast response.

**Comment by CrispusDH** [comment]
@fkhadra , any updates? :)

**Comment by fkhadra** [comment]
Hello @CrispusDH,

The end of the year is quite busy for me at work 😞 . I'll get back to you as soon as possible, sorry for that.

**Comment by CrispusDH** [comment]
@fkhadra , If you need some more information just let me know. Thanks

**Comment by CrispusDH** [comment]
Close, due to @fkhadra inactivity

**Comment by fkhadra** [comment]
Hi all,

I have a suggestion for this one.
If you define an id on `ToastContainer`, this `id` will be used:
```js
<ToastContainer id="foo"> -> <div id="foo" {...othersProps}>...<div/>
```

For the toast, I suggest to use the `toastId` as the htmlid:
```js
toast('hello', {
  toastId: 'xxx'
});
<div id="xxx" {...othersProps}>...<div/>
```

Is that what you are looking for ?

**Comment by JulianoGTZ** [comment]
The End to end test has implemented with Cypress? 

Where I work, the shared function was implemented like this

```javascript
Cypress.Commands.add('checkToastMessage', (message) => {
    cy.get('.Toastify__toast').should('contain', message);
    cy.closeAllAlertMessages();
});
```

**Comment by PierrickG34** [comment]
Hi, thanks for your example @JulianoGTZ.
We can improve it with `toastId` option like this : 

1. Create toast : 
` toast.success("hello" , {toastId: "my-toastId"});`

2. Cypress command for check :
```
Cypress.Commands.add('checkToastMessage', (toastId, message) => {
  cy.get(`[id=${toastId}]`).should('contain', message);
  // ...
});
```

3. Use it : 
`cy.checkToastMessage("my-toastId", "hello")`
