### ISSUE TITLE
First toast showed toast.update always trigger toast destruction

### ISSUE THREAD

**Issue by PhilipGarnero** [fkhadra/react-toastify#294]
Currently, the first toast displayed at load flickers when you try to update it.
This is due to the Toast component being destroyed then recreated.

I thought it was on my part so I investigated the issue and found the bug. It was a long task but the bug itself is pretty trivial:
When creating a toast, you assign them a key in order to provide react with the key attribute [here](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.js#L335). The problem is that the first key is 0 and in the case of an update, while the first key is effectively retrieved from the ToastContainer, it does not pass this check [here](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.js#L239) resulting in the key not being used and being incremented instead. The fix would simply be to set [toastKey here](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.js#L145) to 1 instead of 0.

To reproduce, simply create a single toast, and try to update it before it vanishes. It should call onClose and cause a flicker and the screen. Sorry for not providing code but you have the fix instead ;)

**Comment by fkhadra** [comment]
Hey @PhilipGarnero,

I feel dumb 😭. It's so obvious, thank for the feedback, appreciate!

**Comment by fkhadra** [comment]
@PhilipGarnero fix released

**Comment by PhilipGarnero** [comment]
> I feel dumb

Well don't. This was an edge case and it could happen to anyone.
I know how hard and time consuming maintaining an open-source project is
Thank you for your reactivity
Keep up the good work !

**Comment by ndravikumar** [comment]
I am using react-toastify and i am getting this bug please can you help.
I am using this version "react-toastify": "^5.5.0",
