### ISSUE TITLE
Number is being displayed on the right side of the page

### ISSUE THREAD

**Issue by terancet** [fkhadra/react-toastify#295]
Here is the screenshot of what do I have

![toaster_issue](https://user-images.githubusercontent.com/2099309/50280610-a34d6380-0455-11e9-9aa0-f681ca1eb7eb.png)

The issue is that the number "1" should not be redendered at all

Here is how I use the Toaster component

```
class ViewErrorsComponent extends React.Component {
    constructor(props) {
        super(props);
    }

    notify = errorMessage => toast.error(errorMessage, {
        position: toast.POSITION.TOP_RIGHT
    });

    render() {
        const {error} = this.props;
        if (Array.isArray(error)) {
            return null;
        }
        return (
            <React.Fragment>
                {this.notify(error.errorMessage)}
                <ToastContainer />
            </React.Fragment>
        );
    }
}

const mapStateToProps = state => {
    return {
        error: state.errors
    }
};

export default connect(mapStateToProps)(ViewErrorsComponent)

```

Any ideas on how can I remove number "1"?

**Comment by fkhadra** [comment]
Hello @terancet,
The number 1 is not coming from the library. Check your html maybe. If i'm wrong could you reproduce the issue on codesanbox please.

Thanks

**Comment by terancet** [comment]
@fkhadra 

Sorry for the disturbence. I've used the 'react-toastify' incorrectly. Found the bug in my code.
