### ISSUE TITLE
Feat: Limit the number of toast displayed at the same time 

### ISSUE THREAD

**Issue by popuguytheparrot** [fkhadra/react-toastify#298]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
No limited on showing

**What is the expected behavior?**
Props to limited toast showing 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.7

**Comment by fkhadra** [comment]
Hello @popugang,

You can already pass a component and limit the output. For instance, lets do it with css and a functional component.

```css
 .limited-output{
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 200px;
}
``` 

```js
// somewhere in your app
toast(() => (
  <div className="limited-output">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt rem odit quis quaerat. In dolorem 
  praesentium velit ea esse consequuntur cum fugit sequi voluptas ut possimus voluptatibus deserunt 
  nisi eveniet!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem voluptates vel dolorum 
  autem ex repudiandae iste quasi. Minima explicabo qui necessitatibus porro nihil aliquid deleniti ullam 
  repudiandae
</div>
);
```

You can find more about rendering a component [here](https://github.com/fkhadra/react-toastify#render-a-component)

**Comment by popugang** [comment]
@fkhadra You do not understand me. I want to limit the notification output.

**Comment by fkhadra** [comment]
Hello @popugang,

You mean limit the number of toast displayed at the same time ?

**Comment by popugang** [comment]
> Hello @popugang,
> 
> You mean limit the number of toast displayed at the same time ?

exactly

**Comment by popugang** [comment]
@fkhadra what can do with it ?

**Comment by popugang** [comment]
@fkhadra thank you very much

**Comment by headfire94** [comment]
Will be cool to have a buffer that will store delayed notifications until we can show them

**Comment by Rafi993** [comment]
It would be awesome if this is available as an option in the toast container

**Comment by mudrila** [comment]
@fkhadra Any progress on that so far? Maybe, you would need additional help?

**Comment by marcosandri-dev** [comment]
I need this feature too, to me it would be super cool to have n toasters and having the old ones to close automatically as the new ones appear!

**Comment by mrnguyentrantam** [comment]
I also need this feature

**Comment by Unforgiven-wanda** [comment]
I would love such a feature as well. Have to handle this myself for now.

**Comment by zslucky** [comment]
I faced same issue

**Comment by fkhadra** [comment]
Hello guys,

I'm rewriting the library, maybe I'll port it to typescript. The goal is to reduce the bundle size and also to lower the barrier for newcomers. I'll see how to add this feature.

**Comment by ramiasg** [comment]
also i need this feature

**Comment by shubhamappstec** [comment]
also i need this feature

**Comment by taimoorgit** [comment]
+1; I'd love to have a `maxCount` I can pass to `toast.configure()`

**Comment by fkhadra** [comment]
Hey, a v6 release candidate is available including that feature. You can try it [here](https://github.com/fkhadra/react-toastify/releases/tag/v6.0.0-rc.0)

**Comment by zslucky** [comment]
@fkhadra great release, thank you so much. I have a scenario that need to display the latest limited toasts, and hide the oldest toasts, as my site need to push the latest real-time messages to users, queued toasts may delay some important informations... is it necessary support 2 modes for count limit? LRU and Queued?

**Comment by fkhadra** [comment]
@zslucky the v6(not RC) is now live. Maybe this can help https://fkhadra.github.io/react-toastify/limit-the-number-of-toast-displayed/#how-to-clear-the-waiting-queue

**Comment by zslucky** [comment]
@fkhadra thanks, this can be a solution. 👍

**Comment by mmesar** [comment]
Do we, maybe, have access to that que. I am interested in number of notifications in que. Or, and I know this is not the topic, can we get number of currently displayed notifications. For example, I would like to display "dismiss all" button inside notification only when there is more than 3 notifications displayed.

**Comment by Shielsy** [comment]
I'm not using the ToastContainer but there doesn't seem a way to set the limit property programmatically. Will this be added? Also, a dismiss all button would be nice as mentioned above
