### ISSUE TITLE
[Question] How to override default position/duration throughout the app?

### ISSUE THREAD

**Issue by SeongwoonHong** [fkhadra/react-toastify#299]
Currently, default position is on the top right of the browser. but I want all of my toaster messages to be bottom of the browser.
I don't want to explicitly set position to all of my toast.
Is there any way to do this?
Thank you.

could you also tell me how to override default duration thank you

**Comment by JacobCooley** [comment]
<ToastContainer position={toast.POSITION.TOP_CENTER}  autoClose={4000}/>

**Comment by JacobCooley** [comment]
<ToastContainer position={toast.POSITION.TOP_CENTER} autoClose={4000} />

**Comment by JacobCooley** [comment]
```<ToastContainer position={toast.POSITION.TOP_CENTER} autoClose={4000} pauseOnFocusLoss={false}/>```

**Comment by fkhadra** [comment]
Hey @SeongwoonHong,

Do as @JacobCooley said. Check the playground to see which props can be defined on the `ToastContainer` https://fkhadra.github.io/react-toastify/.

You can also check the api for the `ToastContainer` [here](https://github.com/fkhadra/react-toastify#toastcontainer)
