### ISSUE TITLE
can we show a background colour/image to the toasts appearing.

### ISSUE THREAD

**Issue by ibmkaga** [fkhadra/react-toastify#30]
currently, the toast messages are coming in a white background popup, is there a way to customize the colour/background image of the same to match it with the application theme or some custom requirement.

Regards,
Kapil.

**Comment by fkhadra** [comment]
Hey @ibmkaga,

Yes, you can. Add the following style for instance:

```css
.toastify-content{
 background: red;
}
```
You will probably need to override other styles as well to match your need. I'll review the style with the version 2 which is coming soon.

**Comment by ibmkaga** [comment]
aha ok, gr8. how about a long message, its overflowing the popup in open area right now. Can the toast size be customized based on the content size.

**Comment by fkhadra** [comment]
The easiest things to do is to wrap your message with a div or whatever you want and apply a custom style.
I have to admit that it's not user-friendly at all.
 
As mentioned [there](https://github.com/fkhadra/react-toastify/issues/28), the default design is not usable out of the box if you don't want to waste time with styling. 

Sorry for that 😬
