### ISSUE TITLE
PROBLEM - random string inserted to the page automatically

### ISSUE THREAD

**Issue by dvash999** [fkhadra/react-toastify#301]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
getting random letters when activating toastify, number changing randomly everytime I call the toastify

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
`class ThankYou extends Component {

    render() {
        return (
          <React.Fragment>
                {toast.warn("We'll be in touch!")}
                <ToastContainer
                    position="top-right"
                    autoClose={3000}
                    hideProgressBar
                    // newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnVisibilityChange
                    draggable
                    pauseOnHover/>
          </React.Fragment>
        );
    }
}`

the code render is in another component with a simple state change toggle

**What is the expected behavior?**
just a notification

<img width="480" alt="screen shot 2019-01-07 at 21 59 51" src="https://user-images.githubusercontent.com/38922816/50790734-63e19c80-12c8-11e9-8825-f41e8a225562.png">

**Comment by fkhadra** [comment]
Hello @dvash999,

You are calling  ```js {toast.warn("We'll be in touch!")}``` inside the render method, `toast` return the `toastId` this is why you get the id rendered.

You should trigger the toast from an action. If you want to display the toast when the user click on the send button, you can do it as follow for example.

```js
class MyComponent extends Component {

render() {
    return (
      <React.Fragment>
            <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar
                // newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnVisibilityChange
                draggable
                pauseOnHover/>
        <button onClick={() =>  toast.warn("We'll be in touch!"}>Send</button>
      </React.Fragment>
    );
}
```

**Comment by dvash999** [comment]
hmm great got it!
thank you!

**Comment by fkhadra** [comment]
@dvash999  you're welcome. Don't hesitate to check the documentation for more examples. 
PS: Really nice font 👌

**Comment by NishargShah** [comment]
I need to do with JS thing `{toast.warn("We'll be in touch!")}`. How can I achieve it without showing toastId

**Comment by NishargShah** [comment]
> Hello @dvash999,
> 
> You are calling `js {toast.warn("We'll be in touch!")}` inside the render method, `toast` return the `toastId` this is why you get the id rendered.
> 
> You should trigger the toast from an action. If you want to display the toast when the user click on the send button, you can do it as follow for example.
> 
> ```js
> class MyComponent extends Component {
> 
> render() {
>     return (
>       <React.Fragment>
>             <ToastContainer
>                 position="top-right"
>                 autoClose={3000}
>                 hideProgressBar
>                 // newestOnTop={false}
>                 closeOnClick
>                 rtl={false}
>                 pauseOnVisibilityChange
>                 draggable
>                 pauseOnHover/>
>         <button onClick={() =>  toast.warn("We'll be in touch!"}>Send</button>
>       </React.Fragment>
>     );
> }
> ```

I need to do with JS thing {toast.warn("We'll be in touch!")}. How can I achieve it without showing toastId?

**Comment by BushraNikhat** [comment]
@NishargShah , did you get the solution to your question?

**Comment by nisharg-openxcell** [comment]
It's been more than 2 years so I didn't remember whether I resolved that or not.

**Comment by nisharg-openxcell** [comment]
Hello @BushraNikhat 

It's been more than 2 years now, and I actually didn't remember whether I resolved it or not.

**Comment by NishargShah** [comment]
Hello @BushraNikhat 

It's been more than 2 years now, and I actually didn't remember whether I resolved it or not.

**Comment by MaralNajafi** [comment]
Hi, I have the same problem with toast. It shows the id number inside my component. And I don't want to use the toast on an action(like onClick or whatever), but to check  whether a state is true to trigger the toast, how can I solve this?
This is what It want --> { isSubmitted && notify( ) }
