### ISSUE TITLE
Feature: 🔥Animate toast notification position changes

### ISSUE THREAD

**Issue by Semmu** [fkhadra/react-toastify#303]
**Do you want to request a *feature* or report a *bug*?**

*Request a feature.*

**What is the current behavior?**

Existing toast notifications are jumping on screen when a new one enters or leaves.

**What is the expected behavior?**

Animation when the position of existing toast notifications' changes.

---

Hi!

First of all thanks for this library, it's really flexible and easy to use!
I have a feature request or question regarding an issue when new toast notifications are created or some leave: existing notifications on the screen are immediately moved to their new position and are not animated. This is not a big deal in itself, but since the whole library is pretty polished and even the enter/leave animations can be customized, this is something that I think really hurts the general polish.

Is there an easy way to do it or are you planning to implement it somehow?

Thanks!

**Comment by fkhadra** [comment]
Hello,

Thank you for the feedback.

I know what you are talking about. This is something I always wanted to tackle. It is not so hard to implement but I was running out of time.

I'll definitely work on it for the next patch or minor release.  I hope I'll be able to release it during the end of January.

Anyway I'll pin the issue so you can follow the progress.

**Comment by Semmu** [comment]
Awesome, thanks for the quick response and your work!

**Comment by fkhadra** [comment]
WIP
![toast-collapse](https://user-images.githubusercontent.com/5574267/54467444-627b9700-4785-11e9-9f89-683139d240ec.gif)

**Comment by eyalap** [comment]
@fkhadra Thanks for fixing it, Can I test your v4.6 branch somewhere? and when is it expected to be released ?

**Comment by fkhadra** [comment]
Hello @eyalap,

I'm working on the documentation and it should be ready for release. I hope to release it today or tomorrow. 

All the changes are tracked by the next branch, you can pull it and experiment with the playground(`yarn start`).

Here is the change log https://github.com/fkhadra/react-toastify/releases/tag/untagged-e93a05b31ebdb23bfd5c
