### ISSUE TITLE
Queue multiple Toasts with delay between them

### ISSUE THREAD

**Issue by curiousily** [fkhadra/react-toastify#304]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Showing multiple toasts results in them displayed all at once.

**What is the expected behavior?**

I want to *queue* their entrance by adding delay. 

E.g. 
Toast 1 -> show now
Toast 2 -> show after 500ms
etc.

```javascript
toast("I am shown now")
toast("I am shown later", {delay: 500})
```

Thanks for making this awesome library!

**Comment by fkhadra** [comment]
Hello @curiousily,

Sorry for the late reply. You could do this with `setTimeout`:
```js
toast("I am shown now");
setTimeout(() =>toast("I am shown later"), 500);
```
Am I missing something ?  I admit that having a property like delay is more elegant.

**Comment by fkhadra** [comment]
@curiousily , So I decided to add an option to enable that. However I decided to call it `wait` instead of `delay`. What do you think about the api ?
```js
toast('Hello', { wait: 500 })
```

**Comment by spostad7** [comment]
hi @fkhadra ,
I didn't find any 'wait' option in the api. is it still an option in v8.0.2?
