### ISSUE TITLE
Feature: Allow end users to replace the progressBar by a custom component

### ISSUE THREAD

**Issue by baleeds** [fkhadra/react-toastify#305]
I would like to have access to the progress variable that drives the progress bar for use in a custom component.  Our app has circular progress bars that I would like to mimic.

Thanks!

**Comment by baleeds** [comment]
Or really the ability to pass any data through a toast and into the custom content, with a way to update that information.

**Comment by fkhadra** [comment]
Hello @baleeds,

This was something I was thinking about. I would like to let the user pass a component to replace the `progressBar` like it's done for the `CloseButton` component.

The only issue know is that I'm running out of time. I won't be able to work on the next release before the end of the month 😭.

If you want to submit a PR please do!

**Comment by baleeds** [comment]
@fkhadra that is a good idea, but I a little different than what I had in mind.  I ended up solving my use case by replacing the entire toast component with a component that had progress each time progress changed.

![image](https://user-images.githubusercontent.com/9682964/51544731-87f7be80-1e2e-11e9-99b9-747784dfb4b2.png)

I worry about the performance here though.  Ideally, I could update the state of the component itself and then it would rerender my component and pass it the state through. 

![image](https://user-images.githubusercontent.com/9682964/51544819-b07fb880-1e2e-11e9-91ac-9d31b38ba657.png)

Then I could just rely on the toast state to inflate the custom notification I'm making.
