### ISSUE TITLE
Feature: Option to stop notifications from collapsing when user is hovering in the notifications area

### ISSUE THREAD

**Issue by baleeds** [fkhadra/react-toastify#306]
Reasoning is that from a UX perspective, it's not desirable when the notifications are shifting while trying to click the 'x' buttons.  I think the ideal behavior would be for the notifications to dismiss, but not collapse until the user moves the mouse out of the area.  
An alternative is to stop all of them from collapsing for 2 seconds after one of them is dismissed.

What do you think?

**Comment by fkhadra** [comment]
Hello @baleeds,

Sorry for the late reply. I agree with you but I'm wondering if it's not too much work.
