### ISSUE TITLE
How can I specify font-family or inherit from the body ?

### ISSUE THREAD

**Issue by khaoptimist97** [fkhadra/react-toastify#307]
Hi every one, 

I've just started with this library and been confused because it doesn inherit the font family specified in the body. 

I've tried setting ToastContainer like this but not work: 

    <ToastContainer
          style={{ fontFamily: 'Patrick Hand' }}
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnVisibilityChange
          draggable
          pauseOnHover
          transition={Zoom}
        />
I'm using google font Patrick Hand. Any help is appreciated. Please suggest me.

**Comment by khaoptimist97** [comment]
I specify the index.css file of my project: `.Toastify__toast-body {
  font-family: 'Patrick Hand';
}`. So it change the font as I expected.

**Comment by sgehrman** [comment]
didn't work

**Comment by ceconcarlsen** [comment]
> I specify the index.css file of my project: `.Toastify__toast-body { font-family: 'Patrick Hand'; }`. So it change the font as I expected.

Thanks, worked for me !!!

**Comment by nippysky** [comment]
Worked perfectly. thank you very much for this. God Bless you
