### ISSUE TITLE
Display close button per toast after disabling it by default

### ISSUE THREAD

**Issue by hazmah0** [fkhadra/react-toastify#310]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Lets say that I don't want a close button for 99% of all toast that I'm displaying so I have the following code: `<ToastContainer closeButton={false} />;`
Is it then possible to display the close button for a specific toast only?

https://codesandbox.io/s/mzq1nn3z4p

**Comment by alanlima** [comment]
You can set a React Element like [CloseButton](https://github.com/fkhadra/react-toastify/blob/master/src/components/CloseButton.js) for a specific toast.

**Comment by hazmah0** [comment]
Sorry for not being specific enough. Just like you say I could do that, just like the typings suggest: `React.ReactNode | false`

But what I meant was if after setting `<ToastContainer closeButton={false} />` if its possible to just use the regular built in close button (the one you linked actually)? 

Otherwise, I'll just pass in my own.

**Comment by alanlima** [comment]
Currently, not.
But I forked the source code and made a few changes to allow this feature, have a look here: https://codesandbox.io/s/71nxwjky2j
sourcecode: https://github.com/alanlima/react-toastify

If the owners agree, I can send a pull request with those changes.

**Comment by hazmah0** [comment]
It's not a huge problem. Would be nice though since you can have the default close button on all toasts by default, and then remove the close button on specific ones by passing `closeButton: false`, but the other way around, which is my case, you can't really do as it is now.

**Comment by fkhadra** [comment]
This [PR](https://github.com/fkhadra/react-toastify/pull/313) from @alanlima address this issue. Will be merged next release.
