### ISSUE TITLE
Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by manavpandya** [fkhadra/react-toastify#311]
Recently I have installed this package and when I'm trying to load the toast at that time getting below error

![screenshot_12](https://user-images.githubusercontent.com/20809376/52336990-669cf200-2a2c-11e9-839d-32523d548f7f.png)

Do let me know that why it's happening, and below is the stalkblitz code

https://stackblitz.com/edit/toast-notification-using-react?embed=1&file=Demo.js&view=preview

**Comment by alanlima** [comment]
I update the react-dom library on stackblitz and it is working.
Just remove the react-dom and the stackblitz will ask to install the missing dependency.
Try it.

**Comment by fkhadra** [comment]
@alanlima thanks a lot
