### ISSUE TITLE
it more a question than issue.

### ISSUE THREAD

**Issue by yerassylad** [fkhadra/react-toastify#314]
What pattern you used when wrote "toast" function? There is a relationship between ToastContainer and toast function. I've met this technology a lot. Could you please tell what pattern or technology is.

**Comment by fkhadra** [comment]
@yerassylad are you talking about the event emitter things ?

**Comment by yerassylad** [comment]
yes

**Comment by fkhadra** [comment]
Sure. I really like this article by Addy Osmani https://msdn.microsoft.com/en-us/magazine/hh201955.aspx.

You can also check that link https://www.datchley.name/es6-eventemitter/. The implementation is written in es6.

Try to implement yours, it's really to do when you understand how the pattern behave.
