### ISSUE TITLE
Dismiss is not working with 0

### ISSUE THREAD

**Issue by Hoijof** [fkhadra/react-toastify#316]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If you try to dismiss a toast with id 0 it treats it as a falsy value and dismisses all the toasts ;D

because of this: https://github.com/fkhadra/react-toastify/blob/48deb57ae26f3829eea47d0c6084874f385030a9/src/components/ToastContainer.js#L159
**What is the expected behavior?**

Should treat 0 like a proper number :(

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Irrelevant.

**Comment by fkhadra** [comment]
Hello @Hoijof,

Thank you for reporting the issue.

**Comment by alanlima** [comment]
Hi @fkhadra and @Hoijof 

I am looking to contribute, and I can fix it if you don't mind. 🤗
