### ISSUE TITLE
Close toast without a delay

### ISSUE THREAD

**Issue by tylergaugler16** [fkhadra/react-toastify#317]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When clicking the close button, there is a delay from when the alert actually closes. 

**What is the expected behavior?**
That when the close button is clicked, the alert element immediately gets closed.

**Comment by fkhadra** [comment]
Hello @tylergaugler16,

I'm not able to reproduce your issue. Could you share a codesanbox for that ? Thanks
