### ISSUE TITLE
Autoclose not working if progressbar hidden via display non

### ISSUE THREAD

**Issue by Ledzz** [fkhadra/react-toastify#320]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Toast not autocloses if progress bar is hidden via `display: none`.
Hiding it by default method (opacity) is not working because of IE11 flexbug (https://github.com/philipwalton/flexbugs/issues/111).

**Comment by adithyaBellary** [comment]
The progress bar styling needs to be there. The way that I hid the progress bar was by setting the `hideProgressBar` param to `false`.

**Comment by craigkovatch** [comment]
You must include the `ReactToastify.minimal.css` styles for this to work. The auto-close feature is dependent internally on the ProgessBar component, which does not properly fire the event necessary to trigger the feature unless those styles are present.

IMO this should be refactored or made much more clear.

**Comment by craigkovatch** [comment]
Not an IE11 issue btw @fkhadra

**Comment by craigkovatch** [comment]
FYI I am solving the problem without importing CSS by using TypeStyle, although any CSS injection tool will do:

```js
const progressClassName = TypeStyle.style({
  animation: `${TypeStyle.keyframes({
    from: { transform: 'scaleX(1)' },
    to: { transform: 'scaleX(0)' },
  })} linear 1 forwards`
});

toast.configure({
  autoClose: 5000,
  hideProgressBar: true,
  progressClassName, // necessary for autoClose to work properly due to implementation details of react-toastify
});
```

**Comment by puopg** [comment]
I must agree, an element that must be rendered in the page that we can easily remove using css affecting the behavior of the toast is wild. 

Please document this somewhere in the autoClose section: https://fkhadra.github.io/react-toastify/autoClose

**Comment by gajraj-gan** [comment]
I encountered this as well, weird!
