### ISSUE TITLE
Smooth out current toast animation when a new one pops up

### ISSUE THREAD

**Issue by Giggleball** [fkhadra/react-toastify#321]
**Do you want to request a *feature* or report a *bug*?**
Question (bug?)

**What is the current behavior?**
We are using the toast from the bottom center with a Slide transition & have noticed that when you get multiple toast stacked up, the 'open' toast(s) moved up faster than the new one coming in. 

We read through the documentation, but are not sure how to smooth out the current opened toast(s) to match the same speed as the new one coming in.

If we missed it, could you point us in the right direction?

**What is the expected behaviour?**
That the animation is as smoothly as when you have the newestOnTop, but the newest comes from the bottom.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
"react": "16.6.3", Chrome macOS High Sierra

**Comment by fkhadra** [comment]
Hello @Giggleball,

I think that your issue is related to this [issue](https://github.com/fkhadra/react-toastify/issues/303). I started to work on next release. I'll see how I can handle this issue. 

Thank you for the feedback

**Comment by fkhadra** [comment]
Hey @Giggleball,
Do you expect something as shown below ?
![toast-collapse](https://user-images.githubusercontent.com/5574267/54467514-dc138500-4785-11e9-9366-43e2b8cd3456.gif)

**Comment by Giggleball** [comment]
Hi @fkhadra,

Thank you for your fast reply! I checked out the other issue, and I think you are right that we mean the same.

Umm, not completely. 

For when the toast has expired, yes. That they move together in that fashion.

But when they come in, we would like it for them to all come in at the same speed like when you choose the setting newest on top.

I hope you get what I mean.

We won't have many scenarios where you can have multiple toasts stacked on top each other, but if we do, we would like it for them to look slightly different.

Thanks again for your help & have a nice weekend.

**Comment by fkhadra** [comment]
Hey @Giggleball,

I understand now thank you. I need to think how I can solve this issue.

**Comment by brightMarco** [comment]
Might be related but when you have the newestOnTop active, with the Slide animation it isn't smooth when you have multiple. Here's a gif showing what is happening:

![ezgif-2-4527a8b0d5ad](https://user-images.githubusercontent.com/45400038/69058958-85450600-0a0c-11ea-9f59-05d3fa83d993.gif)

As you can see the new one has animation but the others just move down without any smoothing which looks not very nice. Anyone have a quick fix?

**Comment by VitaliiPyvovar** [comment]
Any updates on this one?
It's still not smooth on version 5.5 with `newestOnTop: true`

![toast-behavior](https://user-images.githubusercontent.com/22331371/76307085-cbcab300-62d0-11ea-95fe-5364ccd0422a.gif)

**Comment by fkhadra** [comment]
`newestOnTop` work well when the toast are positionned at the bottom.

**Comment by rus-yurchenko** [comment]
@fkhadra is possible to smoothly shift visible toasts to the bottom with `newestOnTop` enabled? The current behavior is still  'jumping' when new elements are added from the top like it's shown in the last gif.
