### ISSUE TITLE
Allow library to work with css modules

### ISSUE THREAD

**Issue by timneyens** [fkhadra/react-toastify#325]
I noticed that when I use css modules, the classes within the library are not being scoped. Would this be a usefull feature to add to the library? I would create a new file with all the default classnames in an object and add the possibility to pass a custom object with the scoped classes. These can then be used in the library if defined.

**Comment by fkhadra** [comment]
Hello @timneyens,

I'm not experienced with CSS modules at all. Could you share a library that expose this kind of feature ?

Thanks

**Comment by timneyens** [comment]
Hello, thanks for the fast reply, react-day-picker uses it (https://github.com/gpbl/react-day-picker). There is a file called classnames.js. This exports an object from which the props are used as default class names. You can override these classes with passing a similar object to the component. By overriding you can add your own classNames to any part of the component and so add the generated class names of the css modules. I hope this explains it 🙂

**Comment by fkhadra** [comment]
Thank you, i'll have a look at it

**Comment by timneyens** [comment]
Thank you very much! It would be very helpful to have this feature for a project I am doing. If you need any help or have questions, don't hesitate!

**Comment by timneyens** [comment]
Thank you very much! It would be very helpful to have this feature for a project I am doing. If you need any help or have questions, don't hesitate!

**Comment by timneyens** [comment]
Hello @fkhadra , is this something I can create a PR for?

**Comment by fkhadra** [comment]
Hello @timneyens,

Sure. You better start from the [next branch](https://github.com/fkhadra/react-toastify/tree/next).
There is a lot of changes.
