### ISSUE TITLE
The toastId type returned from toast(content, options)

### ISSUE THREAD

**Issue by github0013** [fkhadra/react-toastify#327]
As of v 4.5.2
https://github.com/fkhadra/react-toastify/blob/v4.5.2/index.d.ts#L295
It is a number.

@types/react-toastify
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-toastify/index.d.ts#L146
It is a string.

```js
// should the toastId be string, number or ToastId type?
const toastId = toast("Wow so easy !")
```

**Comment by fkhadra** [comment]
Hello @github0013,

The toastId is a number or a string. The type `ToastId` is just an alias to `number | string`
https://github.com/fkhadra/react-toastify/blob/v4.5.2/index.d.ts#L74

The @types/react-toastify is not maintained by me.

**Comment by github0013** [comment]
https://github.com/fkhadra/react-toastify/blob/v4.5.2/index.d.ts#L295
This line defines the return value type is a number.   If it is your case, shouldn't the function return a ToastId type?

**Comment by fkhadra** [comment]
Sorry, I just figured out what you were talking about. I fixed this issue for the next release.
