### ISSUE TITLE
Re-render toast component issues

### ISSUE THREAD

**Issue by KiranKumar-KV** [fkhadra/react-toastify#328]
I was using this library I was declared ToastContainer in root component and toast in different component first time I was getting one toast and if I change the component and return back I will get multiple toasts.

**Comment by fkhadra** [comment]
Hello @KiranKumar-KV,

May I ask you to make a codesanbox snippet with the issue.

Thanks

**Comment by augustolima** [comment]
I have a similar issue.

If I navigate to the view which is calling `toast()`, everything works fine. But, if I refresh the page, I get 2 'toastrs', one is my customized toastr and the other one is a mix of a customized and default theme.

**Comment by augustolima** [comment]
Ok, I managed to fix this creating a util file which calls the `toast` after `toast.useLazyContainer(false)`. I don't know if there's a way to make `useLazyContainer = false` somewhere else.

**Comment by fkhadra** [comment]
Hello @augustolima, 

Could you share your setup or a codesandbox please ? Normally you just need to call  `toast.useLazyContainer(false)` once.
