### ISSUE TITLE
Wrong NPM version published?

### ISSUE THREAD

**Issue by raRaRa** [fkhadra/react-toastify#330]
Hey. According to NPM https://www.npmjs.com/package/react-toastify then `5.0.0-rc.3` is the latest version. But according to https://github.com/fkhadra/react-toastify/releases then 5.0.0 is the latest. Was there a problem publishing 5.0.0 to NPM?

Thanks.

**Comment by fkhadra** [comment]
Hey @raRaRa 
I haven't published the v5 yet to npm.  Most of the time when this is a major version bump I prefer to publish release candidate during one week.

I'll probably publish the v5 during the weekend.

**Comment by raRaRa** [comment]
Ah gotcha, no problem. Thanks!
