### ISSUE TITLE
Stereo toasts

### ISSUE THREAD

**Issue by HenrikBechmann** [fkhadra/react-toastify#332]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
react-toastify ignores manually inserted ToastContainer (with parameters), and inserts its own. This causes two versions of toasts to appear, one applying the passed paramaters, and one not.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
one version of toasts
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
latest; MacOS

worked in previous (4.x) versions of toastify

I had to do this
```
import { ToastContainer, toast } from 'react-toastify'
toast.useLazyContainer(false)
```

in spite of having this in the same (top-most) module (containing ToastContainer)

```
        return (

            <SystemDataContext.Provider value = {systemdata}>
                <UserDataContext.Provider value = {userdata}>

                    <ToastContainer position = {toast.POSITION.BOTTOM_LEFT} autoClose = {3000} 
                    hideProgressBar />

                    <MainView globalmessage={globalmessage}
                        className = {classes.mainviewstyle} 
                    />
                    
                </UserDataContext.Provider>
            </SystemDataContext.Provider>

        )
```

**Comment by fkhadra** [comment]
Hey thank you for submitting the issue. I'll try to reproduce it. In the meantime I'm wondering if it's not better to make the lazy container an opt-in option

**Comment by HenrikBechmann** [comment]
... or drop it altogether? It's pretty common to have a high level provider for utilities like yours... and I'm guessing most people would want to set some global parms anyway. But you obviously have a way better view of this than I do.

Congrats on a very useful product btw!!

**Comment by fkhadra** [comment]
I published a new RC. The lazy container is opt-in now.
