### ISSUE TITLE
Meta: v5 changelog missing.

### ISSUE THREAD

**Issue by SimonSchick** [fkhadra/react-toastify#336]
Can you post those please? :)

**Comment by fkhadra** [comment]
Hey @SimonSchick,

What do you mean by the meta ? Are you talking about the RC ?

Thanks

**Comment by SimonSchick** [comment]
I used `meta` in this context since it's not an issue with the package itself.
Also is it still an RC? You published `v5.0.0` which doesn't look like an RC. 😛

**Comment by fkhadra** [comment]
I understand now 😁 . I'll do that ASAP.

This is the stable release that is published now.

**Comment by ksocha** [comment]
What's the breaking change?

**Comment by fkhadra** [comment]
Hello @ksocha,

There is no breaking change from the v4 to v5. The bump to the major version number is due to the fact that I updated the build tools.

- @babel/runtime is a new dependency. This help reduce bundle size
- Single file build just like react and react-router.
- Add a pre-optimized production builds.
- Add esm modules. The lib is now "tree-shakable"

**Comment by SimonSchick** [comment]
@fkhadra something must have changed, toasts no longer work, the CSS is not bundled correctly anymore.

**Comment by fkhadra** [comment]
@SimonSchick  could you share your issue on codesanbox ? It's working for me: https://codesandbox.io/s/k2jv5x1k1v?fontsize=14

**Comment by SimonSchick** [comment]
Not having a whole lot of luck boiling it down.
But I think it's https://github.com/fkhadra/react-toastify/issues/334

**Comment by fkhadra** [comment]
@SimonSchick can you share your project ? Or at least a minimal repo with that issue. 

Thank you

**Comment by fkhadra** [comment]
@SimonSchick not issue with CRA when I built it.

**Comment by SimonSchick** [comment]
@fkhadra again, it's the same issue as #334 we have changed nothing in our project, I'm going to close this issue in favor of 334.
