### ISSUE TITLE
Bug related to toast.isActive

### ISSUE THREAD

**Issue by raRaRa** [fkhadra/react-toastify#338]
**What is the current behavior?**
`toast.isActive("test")` returns undefined or false during startup of the app after opening a toast with the toastId test.

**A demo that shows the issue. I call the function `test()` twice which should only display the toast once, but it tries to display it twice because isActive is not working as expected**
https://codesandbox.io/s/r79m28v97q

**What is the expected behavior?**
`toast.isActive("test")` should return true

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest version of React & react-toastify.

**Comment by fkhadra** [comment]
Hello @raRaRa,

The thing is that your are calling ```toast.isActive``` before the App component get mounted. I updated your sample. ```toast.isActive``` will work as soon as the Container is mounted. 

https://codesandbox.io/s/9z9p6j105p?fontsize=14
