### ISSUE TITLE
Best approach to use in a Design System

### ISSUE THREAD

**Issue by ajayns** [fkhadra/react-toastify#340]
For toasts of consistent styling in a design system, I've added the ToastContainer to it with custom styling and props passed for the particular use case. This works great internally cause we can also call the `toast` function in the design system itself as the library is imported.

But when using this in apps, the problem arises cause you need access to the `toast` function and it is not available unless toastify is imported. Since it's bundled with the design system, adding another one wouldn't make sense.

The solution I came up with was passing the `toast` function to all direct children of the Toast design system component. This again caused issues as for different components that required Toasts it added multiple ToastContainer components making things messy.

Current implementation:
Toast (design system component): Returns styled, custom props ToastContainer along with its children (toast is passed to them as a prop)

Please let me know if there's any recommended approach for this? Also any existing cases I can take a look at and possibly use.

**Comment by fkhadra** [comment]
Hello @ajayns,

Sorry for the late reply. I never used the library like that. Do you have a repository to share ?

**Comment by ayushraj17** [comment]
Facing the same problem. I defined the toast function in my design system. Exported it but it doesn't work where my design system is installed. It silently fails
