### ISSUE TITLE
When I redirect to another page toaster not come

### ISSUE THREAD

**Issue by fintegri** [fkhadra/react-toastify#343]
import {toast,ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

//Onclick function

 toast.success(getresult.Message, {
      position: toast.POSITION.TOP_RIGHT
    });

 this.props.history.push('/'); // When I use redirect toaster not come please help me

**Comment by fkhadra** [comment]
Hello @fintegri,

Please reproduce the issue with codesanbox. Thank you

**Comment by arananegra** [comment]
I have been also dealing with this problem in my codebase whenever I have to use any history action from React-Router. I will try to provide a codesandbox. 

Basically my config is a ToastContainer per page with an unique ID and then in the thunks when I try for example:

```
//More code inside the thunk
await signUp();
history.push('/login');
toast.success('Sign up email sent', {containerId: loginComponentIds.loginComponent});
```

Technically the toast should be rendering in the login page but it doesn't.

Any ideas while I try to reproduce it?

**Comment by fkhadra** [comment]
I would suggest to render the `ToastContainer` at the root of your app. Outside of react-router if possible

**Comment by arananegra** [comment]
Ok, it was definitely some  `ToastContainer ` messing up somewhere in the code. 

I will refactor and remove those custom  `ToastContainer ` per page components. I was using them so I don't have to duplicate the special toast configuration on each toast call. 

Thanks for your quick reply.

**Comment by fkhadra** [comment]
Hppy it solved your issue !

**Comment by ayoubaayoub** [comment]
thanks, Mr @fkhadra fkhadra . is solved my issue!

**Comment by DanielKucal** [comment]
Same problem with newest Next.js router, <ToastContainer> is placed in _app.tsx besides main app container (it doesn't work at all when placed in _document.tsx). I had to add setTimeout for the toast to appear after the route change is complete, otherwise the toast content was immediately gone.

**Comment by zanzlender** [comment]
I'm just posting this in case anyone else gets this bug with NextJS.

I was using the getLayout function as described in the docs for when want to use layouts [NextJS Layouts](https://nextjs.org/docs/basic-features/layouts). And then my _app.tsx looked something like this: 

```
 return (
    getLayout(
      <SessionProvider session={session}>
        <AlertManager />
        <Component {...pageProps} />
      </SessionProvider>
    )
  );
```

The problem lies in the function because it's called on every page it resets react-toastify. 

The workaround is quire simple, you just remove the container out of it like so:

```
  return (
    <>
      <AlertManager />
      {
        getLayout(
          <SessionProvider session={session}>
            <Component {...pageProps} />
          </SessionProvider>
        )
      }
    </>
  );
```

Now it works again 👍

**Comment by naivecoder786** [comment]
![image](https://github.com/fkhadra/react-toastify/assets/117038957/0272d609-6240-44a2-b031-5b0ad390ff90)
I am facing a similar issue but with the MUI when rendered inside the MuiBox-root it works just fine but when taken at the root it just doesnt seem to work at all

**Comment by Tuscan-blue** [comment]
![image](https://github.com/fkhadra/react-toastify/assets/141131070/f4bca05a-29ee-494f-855b-3eca3a2e052c)
![image](https://github.com/fkhadra/react-toastify/assets/141131070/a7a8da94-e421-4168-8b59-995f5b7d155b)
![image](https://github.com/fkhadra/react-toastify/assets/141131070/ed5e348e-f660-4ef7-a5ed-d48bd831100c)

 
I had a similar problem. It jumps to the new page without showing any toaster.
