### ISSUE TITLE
index.d.ts breaks build

### ISSUE THREAD

**Issue by suledisha** [fkhadra/react-toastify#344]
index.d.ts breaks the build with the error:
../../node_modules/@types/react-toastify/index.d.ts(139,23): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s)

**Comment by fkhadra** [comment]
Hello @suledisha,

It looks like you are using ```@types/react-toastify```. You don't need it. A type definition is already provided with the package.

**Comment by suledisha** [comment]
Works well without @types/react-toastify. Thanks @fkhadra
