### ISSUE TITLE
Update content not working when using multi container

### ISSUE THREAD

**Issue by ohayojp** [fkhadra/react-toastify#345]
When using multi toast container content is not updated. Removing enableMultiContainer and leaving only one <ToastContainer /> fixes it.
Unfortunatly multi container is a must (as updating toasts), so could you take a look at this issue? Thanks

**Comment by fkhadra** [comment]
Hello @ohayojp,

Could you reproduce the issue on codesanbox please?

Thanks

**Comment by ohayojp** [comment]
@fkhadra sure, here is a quick fork reproducing the issue:
https://codesandbox.io/s/13jqr3xkvj

Remove enableMultiContainer prop and update will work again.

**Comment by fkhadra** [comment]
@ohayojp I found where the issue is coming from. I track only the latest declared ToastContainer. I'll work on it and try to fix it for this week.

**Comment by ohayojp** [comment]
@fkhadra Thanks!

**Comment by fkhadra** [comment]
Hey @ohayojp, just to let you know that I have to think more about the implementation. I didn't had enough time to try out some stuff.
I'll get back to you.

**Comment by ramospedro** [comment]
Hi, guys!
I was trying this out today and saw it wasn't fixed yet. So I took some time to solve it and opened a PR.
@fkhadra Let me know if you think this could be solved in a better way. The PR has more details.

**Comment by LybrialsGit** [comment]
Hi. Is this fix not included in version 5.3.2? Cause Im still facing that issue.
