### ISSUE TITLE
Question: Styling the shape of the toasts

### ISSUE THREAD

**Issue by MSAskew** [fkhadra/react-toastify#346]
I'm not sure if I am just missing it in the documentation, but from a styling perspective can we control the shape of the toasts, i.e. round off the corners or is the css customisation more of colouring etc?

If it can be done, do you have any samples on how this would be achieved?

**Comment by fkhadra** [comment]
Hello @MSAskew,

I have to improve this part of the documentation. There is several way to do that.

For instance, If you want round corner for your toast as shown below. You can do
```css
.Toastify__toast {
border-radius: 20px; 
}
``` 
<img width="329" alt="Screenshot 2019-05-02 at 12 46 25" src="https://user-images.githubusercontent.com/5574267/57070643-5e292000-6cd8-11e9-91b6-85b4573058fe.png">

Did you have a look at this part of the https://github.com/fkhadra/react-toastify#le-style ?

Was it helpful ?

Thanks
