### ISSUE TITLE
autoClose does not work if progress option is being used

### ISSUE THREAD

**Issue by EdmundMai** [fkhadra/react-toastify#347]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I use the progress option for a controller progress bar, autoClose seems to be ignored.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/yj64z8ox1z

**What is the expected behavior?**
I want to use the toast to track the progress of an upload bar. When the upload is finished (aka the `progress === 1`), i want the toast to automatically close after a few seconds.

          toast.update(id, {
            render: `${file.name} has finished uploading.`,
            progress: 1,
            autoClose: 3000
          });

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome, React v16.8.6

**Comment by fkhadra** [comment]
Hello @EdmundMai,

It make sense. Thanks for reporting !
