### ISSUE TITLE
Change autoClose from type `number | false`  to `number | boolean`

### ISSUE THREAD

**Issue by JRhyne** [fkhadra/react-toastify#349]
**Do you want to request a *feature* or report a *bug*?**
minor bug

**What is the current behavior?**
The `autoClose` property in `CommonOptions` is typed as `number | false`.

This is causing WebStorm to throw warnings when setting the `autoClose` option.
```
Type boolean is not assignable to type false
Type boolean is not assignable to type number
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
open `index.d.ts` line 125

**What is the expected behavior?**
The `autoClose` property in `CommonOptions` should be typed as `number | boolean`.

This will remove any warnings thrown.

Happy to submit a PR if you're ok with this change.

**Comment by fkhadra** [comment]
Hello @JRhyne,

`autoClose` only accept a `number` or `false`, if you pass `true` an error will be thrown. 
I created a codesandbox in TS https://codesandbox.io/embed/competent-shtern-572ys and I don't have issue with the compiler.

TBH, I don't know why Webstorm is complaining. I can try to install it and see what is happening maybe.

**Comment by JRhyne** [comment]
Yeah, the more I looked into it, the more I think it's an issue with Webstorm. Feel free to close this. By the way, awesome job with this component.  Works beautifully.
