### ISSUE TITLE
lag and InternalError: too much recursion 

### ISSUE THREAD

**Issue by MareoRaft** [fkhadra/react-toastify#350]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The toasts populate very slowly.  Further, I get the following in my console:
`Warning: React DevTools encountered an error: InternalError: too much recursion`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
in App.js:
`import {ToastContainer, toast} from 'react-toastify';`
and then
`toast.configure({
  autoClose: 8000,
  draggable: false,
  //etc you get the idea
});`
and then the following methods in my Component:
`	notify() {toast("Wow so easy !")}
	render() {
    return <button onClick={this.notify}>Notify !</button>;
  }
`

**What is the expected behavior?**
no lag and no warning message

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`"react": "^16.8.4"`
Firefox Quantum 66.0.4 (64 Bit)
This is my first time using it.

**Comment by fkhadra** [comment]
Hello @MareoRaft,

I'm not able to reproduce the issue. https://codesandbox.io/s/98q1kjy3ko
Do you have a repo with a reproduction case ?

**Comment by MareoRaft** [comment]
@fkhadra Sorry, but our repo is private.  We already moved forward with a different alert library.
