### ISSUE TITLE
Duplicate Toast when same customId is used

### ISSUE THREAD

**Issue by pavanreddy61** [fkhadra/react-toastify#352]
https://codesandbox.io/s/dark-browser-69ocz

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Even with customId ... duplicate toast is visible for a sec and then it is removed from dom in my app and here in the sandbox below u could see the strange behaviour

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/dark-browser-69ocz

**What is the expected behavior?**
It should actually not add a dom element at all when same toastId is given

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not sure about the previous versions but checked the react 16.5.2 and latest 16.8

**Comment by pavanreddy61** [comment]
Not sure if i missed configuring something

**Comment by fkhadra** [comment]
Hello @pavanreddy61,

Thanks for reporting the issue. What is happening is that internally I'm not checking if a toast is active before rendering it. I guess this should be the default behavior. I'm working on it right now
