### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by crobinson42** [fkhadra/react-toastify#355]
Please follow SEMVER with the package versioning.

In version 5.0.0 there were no BREAKING CHANGES documented or the reason for a major version bump - it seems to be an arbitrary major version increase and could have been a minor bump.

In version 5.2.0 there were BREAKING CHANGES which constitute a new major version and should have been 6.0.0.

https://www.npmjs.com/package/semver

**Comment by fkhadra** [comment]
Hey @crobinson42,

You're right  in version 5.0.0 there were no BREAKING CHANGES but I think that the points below justify the major version bump
- @babel/runtime is a new dependency. 
- Single file build just like react and react-router.
- Add a pre-optimized production builds.
- Add esm modules. The lib is now "tree-shakable"

But if we refer to the code only, it's true that a minor version bump should have been sufficient.

Regarding the version 5.2.0, I removed the ability to set a progress value while calling `toast.done`. 
This is a breaking change but the fact that you can define a progress value when calling `toast.done` is not documented this is why I decided to use a minor version bump.

Anyway, thank you for your concern. I will pay attention for the future releases.
