### ISSUE TITLE
How to clean up with useEffect (Warning: Can't perform a React state update on an unmounted component.)

### ISSUE THREAD

**Issue by basti-n** [fkhadra/react-toastify#357]
What is the proper way to clean up via useEffect after switching page? 

```js
import React, { useEffect } from 'react'
import { ToastContainer, toast, Flip } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { css } from 'glamor'

export default function Toast() {
  const goal = toast(<ToastText />, {
    toastId: 'goal',
    className: css({
      position: 'absolute',
      top: '80px',
      boxShadow: 'none',
      left: '0px',
      background: 'rgba(46, 139, 87, 0.9)',
      width: '100vw',
    }),
    bodyClassName: css({
      color: 'white',
      fontSize: '30px',
    }),
    progressClassName: css({
      background: 'white',
      height: '2px',
    }),
  })

  console.log(toast.isActive(goal))
  useEffect(() => {
    return () => toast.dismiss()
  }, [])

  return (
    toast.isActive(goal) || (
      <ToastContainer
        autoClose={5000}
        transition={Flip}
        position={toast.POSITION.TOP_LEFT}
      />
    )
  )
}

function ToastText() {
  return (
    <>
      <h6
        style={{
          margin: 0,
          fontSize: '15px',
          fontWeight: 'bold',
          paddingBottom: '5px',
        }}
      >
        Your daily goal reminder
      </h6>
      <p style={{ margin: 0, fontSize: '12px' }}>
        46 min left to achieve your daily goal. Go for it!
      </p>
    </>
  )
}```

**Comment by fkhadra** [comment]
Hey @basti-n,

You want to remove active notification on page change right ?

**Comment by basti-n** [comment]
No, that is not a problem. The problem is that on page change the notification is correctly being removed from the view (unmounted), however, the toast-component still tries to update (setState) causing a warning in the console that state cannot be set for an unmounted component. My assumption was that this is caused by the fact that I do not cancel all subscriptions on componentWillUnmount (i.e. the return function is useEffect()).

**Comment by kaayso** [comment]
You must declare `<ToastContainer />` in app **root**. For example in **App** component :

```
// app.jsx

import React, { Component } from "react";
import { ToastContainer } from "react-toastify";

class App extends Component {

  render() {
    return (
      <div>
        <ToastContainer />
        <OtherComponent>
        ...
      </div>
    );
  }
}

export App;

```

```
// index.js

import App from "./app";
import React from "react";
import ReactDOM from "react-dom";
import registerServiceWorker from "./registerServiceWorker";

ReactDOM.render(
    <App />,
  document.getElementById(`root`),
);
registerServiceWorker();

```

Now, you can call **toast** function in children components.

**Comment by prvucetic** [comment]
Hi, I have the same problem but with a single ToastContainer specified in App.js as suggested above. Here is the render method:
`render() {
        return (
            <div id="react-rooter-root">
                <div id="wrap">
                    <div className="container main-container">
                        <AppNavigation />

                        <div id="content">
                            <div className="container">
                                {this.props.children}
                            </div>
                        </div>
                    </div>
                </div>
                <LoadingOverlay />
                <AppFooter />
                <ToastContainer autoClose={8000} hideProgressBar transition={Slide} />
            </div>
        );
    }`

This all worked properly until I did some upgrades: React 16.10.2 (was 16.3.2), React Toastify 5.4.0

**Comment by colinwilson** [comment]
Experiencing this too. I'm using Gatsby [React 16.9.11, Toastify 5.4.1]. `<ToastContainer />` is declared in the app root with the help of [gatsby-plugin-layout](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/#gatsby-plugin-layout).

**Comment by laij84** [comment]
I have a custom component that uses the toast method. In jest with react-testing library, i render both the toast container and my custom component, and I get this error message:

```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.```

**Comment by kahnyoudiggit** [comment]
I have the same issue as @laij84.

**Comment by mattcarlotta** [comment]
This setState warning also occurs when using Webpack's inline hot reloading. It appears that the `eventManager.on` calls in the [ToastContainer](https://github.com/fkhadra/react-toastify/blob/master/src/components/ToastContainer.js#L179-L184) are being triggered in an unmounted/stale component. 

Here's a small reproduction of the warning (all 3 messages render as intended; remove the text, then check the console to see the React warning and now only 1 message displays):
[![Edit React Toastify Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-toastify-bug-qfz5c?fontsize=14&hidenavigation=1&theme=dark)

---

Working in combination with this PR #409, setting a `ref` on the `div` and using it as a conditional will prevent unmounted nodes from having their state updated:

```
 ...

  componentDidMount() {
    eventManager
      .on(ACTION.SHOW, (content, options) =>
        this.ref ? this.buildToast(content, options) : null
      )
      .on(ACTION.CLEAR, id =>
        !this.ref ? null : id == null ? this.clear() : this.removeToast(id)
      )
      .emit(ACTION.DID_MOUNT, this);
  }

 ...

 render() {
   return (
     <div ref={node => (this.ref = node)} className={`${RT_NAMESPACE}`}>
        {this.renderToast()}
      </div>
   );
```
