### ISSUE TITLE
Get toast parameters

### ISSUE THREAD

**Issue by QoobIY** [fkhadra/react-toastify#358]
Is it possible to add in new version ability to read toast parameters?
e.g.
```js
const a = toast('Hello');
const old_content = toast.get(a).content;
toast.update(a, {render: old_content + ' World'});
```

**Comment by fkhadra** [comment]
Hello @QoobIY,

IMHO I think that it's easier to do that at user level. I'll be happy to help if you don't how to :)

**Comment by QoobIY** [comment]
I already do this, but why not provide a ready container, which is already implemented

**Comment by aarontanzk** [comment]
anyone has done this ? can share a codesandbox?
