### ISSUE TITLE
Toast not autoclose in Safari Edge with custom CSS

### ISSUE THREAD

**Issue by nicolasletoublon** [fkhadra/react-toastify#359]
**Do you want to request a *feature* or report a *bug*?**
It's not a proper bug, more an issue that I report with the way of fixing it . 

In https://github.com/fkhadra/react-toastify/issues/223, you mentioned to put the minimum css to trigger the animationEnd and then the autoClose of the toast. But it doesn't work on Safari for example :) 

You might want to add the actual keyframe, and it will work then :) 
Here a sand box updated: https://codesandbox.io/s/eager-curie-x2tzj

**Comment by fkhadra** [comment]
Hello @nicolasletoublon,

Thank you for reporting the issue and also giving the way to fix it. 
I'm now thinking to add a file with the minimun css required. e.g.

```js
import 'react-toastify/dist/ReactToastify.minimal.css' // or a better name

content of the file:
@keyframes Toastify__trackProgress {
  0% {
    transform: scaleX(1);
  }
  100% {
    transform: scaleX(0);
  }
}

.Toastify__progress-bar {
  animation: Toastify__trackProgress linear 1;
}

```

What do you think ?

**Comment by nicolasletoublon** [comment]
I think thats an excellent idea ! Because in most of the cases, that will be the use case I think, people tend to re-style completely the component :)

**Comment by sikhote** [comment]
For emotion:

```
import { keyframes } from '@emotion/core';

const toast = keyframes({
  '0%': {
    transform: 'scaleX(1)',
  },
  '100%': {
    transform: 'scaleX(0)',
  },
});

const styles = {
  global: {
    '.Toastify__progress-bar': {
      animation: `${toast} linear 1`,
    },
  },
};
...
<Global styles={styles.global} />
```
