### ISSUE TITLE
Top-centre or bottom-centre with slide transition has wrong leave direction

### ISSUE THREAD

**Issue by Jab0rnal** [fkhadra/react-toastify#360]
Bug:

Set top-centre or bottom-centre with a transition of slide. The leave transition will go the 'wrong way'.

Seems to be simmilar to this, however this issue is closed. Has the bug crept back in?
https://github.com/fkhadra/react-toastify/issues/239

Top-center leave transition should see the toast leave the page by going up.
Bottom-center leave transition should see the toast leave the page by going down.

Currently the transitions seem to mixed up.

The problem can be seen on the demo site:
![toastIssue](https://user-images.githubusercontent.com/10100406/59149724-09806f80-8a11-11e9-826c-581b53bd3d9a.gif)

**Comment by fkhadra** [comment]
@Jab0rnal actually the demo is not using the latest version 😭. Shame on me...

**Comment by Jab0rnal** [comment]
@fkhadra Yes, i've downloaded the latest version and checked. It works as expected. Thanks.
