### ISSUE TITLE
How to close the toast externally?

### ISSUE THREAD

**Issue by Tainan404** [fkhadra/react-toastify#361]
Hi everyone, Is there any way to close the toast on an external button or a way to close without the close button on a custom button on the interface?

**Comment by fkhadra** [comment]
Hello @Tainan404, 
If you want to close the toast programmatically, you can use the `toast.dismiss` function as shown here: https://github.com/fkhadra/react-toastify#remove-a-toast-programmatically

**Comment by Tainan404** [comment]
That's works. Thanks
