### ISSUE TITLE
toast.configure, multiple containers created

### ISSUE THREAD

**Issue by mrceperka** [fkhadra/react-toastify#363]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Multiple containers are created.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox example below:**
Click button, and then click notification to disable it. You will see, that there it was stacked on top of another notification...
https://codesandbox.io/s/nen1g

**What is the expected behavior?**
There should be only one.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Probably does not matter. See codesandbox package.json.

**Comment by fkhadra** [comment]
@mrceperka good catch ! Thanks for reporting the issue.

**Comment by mrceperka** [comment]
Boolean flag `containerInserted`  or similar could probably resolve this issue.
Thanks for a fast reponse :)

**Comment by fkhadra** [comment]
Indeed, `containerInserted` should work or simple resetting `lazy` to `false`. I'll try both.

**Comment by ramospedro** [comment]
@fkhadra I could look into this if you haven't started yet : )
