### ISSUE TITLE
Allow ...ClassName properties to be functions

### ISSUE THREAD

**Issue by verheyenkoen** [fkhadra/react-toastify#367]
**Do you want to request a *feature* or report a *bug*?**

Feature 💫

**What is the current behavior?**

According to the docs the various `...ClassName` properties on both the `ToastContainer` component, and in the second parameter object of the `toast()` method, only accept either a string or an object. I haven't managed to figure out how that would work with an object there (maybe add an example for that).

**What is the expected behavior?**

It would be great if these properties also accept a callback function that lets you return CSS class names based on eg. the type of the alert.

As a concrete case: I'm using Bulma as the CSS framework. Bulma does have a notification element which (in combination with classes like `.is-primary`, `.is-success`, `.is-warning`, or `.is-danger`), provide a styled element that would be ideal to use within a toast. Now to make this work with react-toastify I need a service that overwrites the `toast.success()`, `toast.error()`,... methods or create different ToastContainers for each type of toast while I would prefer doing something like:

```
<ToastContainer toastClassName={({ type }) => {
    switch(type) {
        case 'error':
            return 'notification is-danger';
        case 'success':
            return 'notification is-success';
        // etc.
     }
</ToastContainer>
```

**Comment by fkhadra** [comment]
Hello @verheyenkoen,

For your use case, if you want to use the bulma style with the notification, I suggest to create a helper as shown below:
[![Edit zealous-villani-vlcv7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-villani-vlcv7?fontsize=14)

For the `className` property, you can pass an object if you use a cssinjs library like `glamor`, `styled-components` etc...

I'm not considering to accept a function for `toastClassName` for the moment but if more user think that it could be helpful i'll reconsider it. 

Does my answer help you solve your issue ?

**Comment by verheyenkoen** [comment]
Thanks for the reply. That helper is basically what I did for now. Let's see what anyone else thinks.

Not that I can promise to do so any time soon, but would you be willing to accept a PR for this?

**Comment by fkhadra** [comment]
Hello @verheyenkoen,

Sorry for the late reply.  Like I said,  I'm not considering to accept a function for `toastClassName` for the moment but if more user think that it could be helpful i'll reconsider it of course.

So wait and see 🙂.
