### ISSUE TITLE
Fix ie11 animation and close button 

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#37]
- Entrance and exit animation are buggy on ie11. 
- The close button is not well positioned when there is a progress bar

**Comment by der-lukas** [comment]
Thanks for the great library! Any news on fixing this issue?

**Comment by fkhadra** [comment]
Hey @der-lukas, 

Thank you, appreciate! I'll focus on it this week.

**Comment by fkhadra** [comment]
Yo @der-lukas  ! I pushed a new version.
