### ISSUE TITLE
Calling dismiss() on a delayed toast that is not yet visible still displays the notification

### ISSUE THREAD

**Issue by fightingmonk** [fkhadra/react-toastify#371]
Not sure if this a feature request of if I'm Doing It Wrong and failed at reading the docs.

**Current behavior**
When showing a delayed toast component, calling toast.dismiss() before the specified delay does not prevent display of the notification. 

```javascript
const toastId = toast('A delayed indicator', {delay: 300, autoClose: false });
setTimeout(() => {toast.dismiss(toastId);}, 100);
```

**Expected behavior**
This code snippet displays the toast after 300ms but I would expect the toast to not be displayed at all.

My use case is wanting to display an activity indicator only if an action takes enough time to impact the user's flow. In this case, it's accessing data on a server. The pattern I'd like to use in a React component is to queue the toast w/ a delay as I submit a request to the server and then dismiss the toast in the response handler. If the response is very fast there should be no indication shown to the user.

```javascript
onSubmit = () => {
    this.activityToastId = toast('Working...', {delay: 300, autoClose: false});
    /* Initiate data request */
}

onComplete = (result) => {
    if (this.activityToastId) toast.dismiss(this.activityToastId);
    this.activityToastId = undefined;
    /* Process results */
}
```

If there's another, better pattern for this please let me know. If not I'm happy to try pulling together a PR to implement this behavior if it seems reasonable.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.5, Firefox 67.

**Comment by fkhadra** [comment]
Hello @fightingmonk,

`toast.dismiss` won't work in that case because the toast will join the queue after the delay. For a future release I'll see how to address this use case.

To solve your issue I suggest that you handle the delay on your side as follow:
```js
onSubmit = () => {
    this.delayId = setTimeout(() => toast('Working...', { autoClose: false}), 300)
    /* Initiate data request */
}

onComplete = (result) => {
    if (this.delayId) clearTimeout(this.delayId);
    this.delayId = null;
    /* Process results */
}
```

**Comment by fightingmonk** [comment]
Thanks for confirming @fkhadra, that makes sense. 

For anyone else looking at this, here's a working solution. It's not perfect (calling onSubmit() while a request is in progress makes the toast disappear and reappear after 300ms) but for my case it solves the problem.

```javascript
showWorkingNotification = () => {
    const instance = this
    instance.delayId = setTimeout(() => {
        instance.workingNotificationId = toast('Working...', { autoClose: false})
        instance.delayId = undefined
    }, 300)
}

clearWorkingNotification = () => {
    if (this.delayId) {
        clearTimeout(this.delayId)
        this.delayId = null
    }
    if (this.workingNotificationId) {
        toast.dismiss(this.workingNotificationId)
        this.workingNotificationId = undefined
    }
}

onSubmit = () => {
    this.showWorkingNotification()
    /* Initiate data request */
}

onComplete = (result) => {
    this.clearWorkingNotification()
    /* Process results */
}
```

**Comment by fightingmonk** [comment]
I opened a README.md PR in case you're OK with clarifying this behavior in the docs.
