### ISSUE TITLE
Update Demo to have 'pauseOnFocusLoss' property instead of 'pauseOnVisibilityChange'

### ISSUE THREAD

**Issue by ReamRD** [fkhadra/react-toastify#376]
Le bug.

The demo on https://fkhadra.github.io/react-toastify/ contains this: 
![image](https://user-images.githubusercontent.com/29794826/61952736-53bbb100-afbd-11e9-892a-d2e7c5fbb181.png)
while it should be:
![image](https://user-images.githubusercontent.com/29794826/61952761-69c97180-afbd-11e9-9a2d-f991421d6ab7.png)
since the former doesn't seem to be a valid property anymore.

Related control: 
![image](https://user-images.githubusercontent.com/29794826/61952814-8b2a5d80-afbd-11e9-9677-711f7def2f30.png)

Might save somebody a minute or two in the future :) 
Nice lib, thank you :fist_raised:

**Comment by dumkanki** [comment]
Getting error on pauseOnFocusLoss using in react with typescript,

**Comment by fkhadra** [comment]
Hey @dumkanki could you create another ticket for your issue and provide a codesanbox with a reproduction please ?

**Comment by dumkanki** [comment]
> Hey @dumkanki could you create another ticket for your issue and provide a codesanbox with a reproduction please ?

done
