### ISSUE TITLE
toast.isActive will always return false when using multiContainer

### ISSUE THREAD

**Issue by ohayojp** [fkhadra/react-toastify#379]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
toast.isActive(someId) will always return false when using multiContainer

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/reactreduxreact-toastify-x9kvk
Click update and check console.

**What is the expected behavior?**
Return proper active state of toast

**Comment by TCezarRod** [comment]
It seems to be related to the order the containers are rendered. The function `isActive` seems to always consider only the last container instance. 

If in the given reproduction, the "second" `containerId` is used in the toast, the function seems to work properly.

**Comment by fkhadra** [comment]
Hello guys,

Sorry for the late reply. This is a known bug, not hard to solve at all. I'll try to work on the next release ASAP.

**Comment by cchoi94** [comment]
Thanks for adding and address this issue @fkhadra. 😎

**Comment by chinanderm** [comment]
Just ran into this issue and am looking forward to a resolution! Thank you @fkhadra for this wonderful library.

**Comment by fkhadra** [comment]
Hey the v5.4.1 fix the issue.
