### ISSUE TITLE
polyfill not being used for libs

### ISSUE THREAD

**Issue by pepepaco** [fkhadra/react-toastify#38]
the code installed using npm doesnt work for ie11, I had to transpile the react-toastify libs using babel-plugin-transform-object-assign polyfill to make it work.

could this be done on the main repo please?

thanks!

**Comment by fkhadra** [comment]
Indeed ! Thanks for the feedback. I push the fix Asap

**Comment by fkhadra** [comment]
Hey @pepepaco,
I released the version with the polyfill.
Thanks for sharing the issue btw :+1:
