### ISSUE TITLE
Can I use this in browser(without react)

### ISSUE THREAD

**Issue by LimeZky** [fkhadra/react-toastify#380]
Hello,I am not a react developer,but I want to use this project in my website.Can this project work in deault browser(javascript)?Thank you!

**Comment by Kolimar** [comment]
I would recommend to you this library  https://codeseven.github.io/toastr/demo.html for vanilla js

**Comment by fkhadra** [comment]
Hello @LimeZky 

The library works only with react. You can use toastr as suggested by @Kolimar
