### ISSUE TITLE
Styles not getting applied to the toast

### ISSUE THREAD

**Issue by LybrialsGit** [fkhadra/react-toastify#382]
I would like to raise a potential bug but im not quite sure if it is one or if im simply too stupid to read the documentation.

From the current documentation I dont really understand how Im supposed to apply a custom style to the toast because no matter what I do, the toasts style is not changing at all. 
I have the default toast container in my `App`:

```
  public render() {
    return (
      <div>
        <ToastContainer />
        {this.props.children}
      </div>
    );
  }
```

In one of my components I want to create a toast:

```
      toast(message, {
        autoClose: 3000,
        closeButton: false,
        pauseOnHover: true,
        position: toast.POSITION.TOP_CENTER,
      });
```

So this part is working fine. However I want to change the style. So I created styles and applied them like written in the documentation:

```
      toast(message, {
        autoClose: 3000,
        closeButton: false,
        pauseOnHover: true,
        position: toast.POSITION.TOP_CENTER,
        className: 'my-toast-class',
        bodyClassName: 'my-toast-body-class'
      });
```

In one issue report here it was mentioned that we could also override the toast classes like:

```
my-toast-class {
  background-color: #CFF000,
}

my-toast-body-class {
  font-family: var(--default-font-family);
}

.Toastify__toast {
  border-radius: 20px;
}
```

But that also does not change anything. Always the default style is used.
I would like to change a lot of the styles:

- background-color
- font-color
- font-family
- shadow
- border-radius
- size
- etc.

**Comment by m-alzaki** [comment]
Have you manged to resolve this?
I am also facing the same issue.
where i am trying to apply styles to toast using: 
`toast('message', {
        className: css({
          color: '#343a40',
          minHeight: '60px',
          borderRadius: '8px',
          background: '#2FEDAD',
          boxShadow: '2px 2px 20px 2px rgba(0,0,0,0.3)',
        }),
        progressClassName: css({
          background: '#007aff',
        }),
      })`

and its does not override the default one.

**Comment by tomgwasira** [comment]
The only way I've gotten them to override is by using `!important`.
