### ISSUE TITLE
onClose callback fires immediately 

### ISSUE THREAD

**Issue by Smaug333** [fkhadra/react-toastify#389]
**Do you want to request a *feature* or report a *bug*?**
bug onClose callback

**What is the current behavior?**
function fires immediately when toastr message comes up.

**What is the expected behavior?**
function fires when toastr is closing

Code looks- more or less- like this

```
notifyToastr({
      msg: "text",
      containerId: "WorkspaceToast",
      handleUndo: this.handleUndoDeleteTile,
      onClose: () => {
        setPageIndex(newPageIndexLength);
     }
})

const notifyToastr = ({ ... }) {

      ...
      toast( msgComponent(), {
           onOpen,
           onClose,      
           toastId,
           handleUndo,
           ...
      })
}

const msgComponent = () => {
    return (
      <ToastrMessage
        text={msg}
        onUndo={handleUndo ? handleUndo : undefined}
        hideUndo={hideUndo}
      />
    );
  };

```

I tried several aproaches but could not get a satisfying result.  Should be a simple one but...
Appreciate any help!

**Comment by fkhadra** [comment]
Hello @Smaug333 ,

May I ask you to provide a code sandbox showing the issue ?

Thanks

**Comment by ramospedro** [comment]
I tried reproducing it here but wasn't able to.
I played around a little with the onClose, but I couldn't find any bug on this.
https://codesandbox.io/s/throbbing-rgb-srvuy

I'm assuming the issue wasn't related to the lib and is already solved by @Smaug333 
Maybe close it?

**Comment by Smaug333** [comment]
Sorry for not reacting, I should have closed this one already. After clean reinstall of the project the problem dissapeared. Really weird glitch

**Comment by davidkeefe24** [comment]
I ran into this issue and I think it might be related to using a custom component for the notification?

I ended up solving it by adding passing all options to the custom notification component and then calling the `onClose` from the `useEffect` hook like so:

`useEffect(() => {
    return () => {
        if(options.onClose) {
            options.onClose();
        }
    };
}, []);`
