### ISSUE TITLE
Use toast.configure with multiple toast containers

### ISSUE THREAD

**Issue by tonix-tuft** [fkhadra/react-toastify#393]
**Do you want to request a *feature* or report a *bug*?**
feature

Is it possible to use:

```
toast.configure({
  autoClose: 8000,
  draggable: false,
  //etc you get the idea
});
```

together with multiple toast containers:

```
render() {
        return (
        <div>
            <ToastContainer enableMultiContainer containerId={'A'} position={toast.POSITION.BOTTOM_LEFT} />
            <ToastContainer enableMultiContainer containerId={'B'} position={toast.POSITION.TOP_RIGHT} />
     
            <button onClick={this.notifyA}>Notify A !</button>
            <button onClick={this.notifyB}>Notify B !</button>          
        </div>
  )
}
```

?

I would need the "global" `toast.configure()` container to be mounted in the body of the page, while having the possibility to add multiple customized toast containers nested in other JSX components.

Thank you!

**Comment by fkhadra** [comment]
Hello @tonix-tuft,

Currently the `toast.configure` is intended to work only with one `ToastContainer`. BTW if you use `toast.configure` the `ToastContainer` will be added for you.

**Comment by tonix-tuft** [comment]
Hi @fkhadra,

Thank you for your feedback. I am closing this issue because I ended up adding a custom `ToastContainer` for body-appended toasts using [react-append-to-body](https://www.npmjs.com/package/react-append-to-body):

```
import React from "react";
import { compose } from "redux";
import { componentWillAppendToBody } from "react-append-to-body";
import { ToastContainer } from "react-toastify";

const BodyToastContainer = compose(componentWillAppendToBody)(props => (
  <ToastContainer className={"body-toast-container"} {...props} />
));
export default BodyToastContainer;
```
