### ISSUE TITLE
Render multiple times when working with custom toast

### ISSUE THREAD

**Issue by mrnguyentrantam** [fkhadra/react-toastify#394]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
Custom toast renders multiple times

Example:
https://codesandbox.io/s/react-react-toastify-working-jd7xs

You can easily notice the log that it renders multiple time

**What is the expected behavior?**
Render only 1 time

**Comment by ramospedro** [comment]
Hi @mrnguyentrantam 
Try using the React Profiler in your codesandbox sample and you'll notice the Custom Component renders inside the `Transition` component, which changes its state a couple times during the Toast lifecycle, this triggers some extra render, which in turn triggers renders on your custom component too.

I'm not sure there's much we can do about it. Also, considering the number of toasts that usually render on the screen is very limited, it certainly won't cause any performance issues.
