### ISSUE TITLE
How do i stop displaying newest toast on top of other, newestOnTop prop is not working

### ISSUE THREAD

**Issue by shreyaHomelane** [fkhadra/react-toastify#401]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
toasts coming on top of each other covering whole screen in case multiple trigger points
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.9 linux ubuntu 16

**Comment by amamenko** [comment]
I had a similar issue. I just adjusted the CSS on the ToastContainer's class to include "position: absolute" and "bottom: 0".

**Comment by fkhadra** [comment]
Could you share a codesandbox with a reproduction please.

**Comment by shreyaHomelane** [comment]
if any toast message is triggered multiple times within the specified time duration in autoclose option, it'll keep popping up on top of each other, there should be a way to to control that. 

I somehow fixed that using toastID and not showing the message with same id.

`			if (! toast.isActive(1234)) {
				toast.warn("Please select a room first to view in 3D", { ...WarningToastOptions, ...{ toastId: 1234 } });
			}
`
