### ISSUE TITLE
Toaster doesn't show when it is triggered  inside componentDIdUpdate after navigating through a couple of routes

### ISSUE THREAD

**Issue by TheDhejavu** [fkhadra/react-toastify#404]
Toaster doesn't show when it is triggered  inside componentDIdUpdate after navigating between route using react router but it works when you get the page is manually reloaded

let's say we call this toaster
` toast("ZoomIn and ZoomOut", {
            autoClose: 5000
        });`
inside  componentDIdUpdate after navigating a couple of routes using react router, it doesn't show

**Comment by AirrBear** [comment]
Hey @TheDhejavu 

I solved this issue by putting the ToastContainer inside my highest level component (where my router is), that way all toast function calls are passed into that Container only. I'm guessing what's going on after debugging my app is that the toast message's aren't going to the correct Container when you switch between routes.

**Comment by TheDhejavu** [comment]
Thanks @AirrBear 

I fix this by installing a non-latest version of react-toastify

**Comment by fkhadra** [comment]
Hello,

You could try the v5.5.0 to see if it solve your issue.
