### ISSUE TITLE
Toast isn't showing in componentDidMount

### ISSUE THREAD

**Issue by developdeez** [fkhadra/react-toastify#405]
I have a settings page and when the settings are incomplete it shows an error. If they try to leave it sends them back to this page to show the error again.
Tried simply showing a toast to the user when they enter a page. It works fine the first time but after that nothing happens. Calling dismiss on component unmount didnt help either.

**Comment by Hakawa2** [comment]
code plz

**Comment by developdeez** [comment]
`componentDidMount() {
    const { history, errors } = this.props;
    history.replace({ state: {} });
    window.ALLOWCONTEXTMENU = true;
    window.addEventListener("beforeunload", () => {
      this.handleSubmit(this.updateSettings);
    });
    this.mounted = true;
    if (
      errors.about !== null ||
      errors.desires !== null ||
      errors.profilePic !== null
    ) {
      this.showPleaseComplete();
    }
  }

  showPleaseComplete = () => {
    if (!this.props.toast.isActive("plscomplete")) {
      this.props.toast.info("plscomplete",
        {
          toastId: "plscomplete"
        }
      );
    }
  };
`

**Comment by Hakawa2** [comment]
bro based in your code

https://codesandbox.io/s/practical-wing-ogrs4

**Comment by developdeez** [comment]
I think it was because the state reset caused toast to fault.It's not an issue any longer
