### ISSUE TITLE
triggering nested component updates from render is not allowed warning message

### ISSUE THREAD

**Issue by yzhaopost** [fkhadra/react-toastify#406]
I have code to test notification. I always get the following warning message.  
![image](https://user-images.githubusercontent.com/45929614/70262012-60f56300-1748-11ea-8b50-4c6786abf960.png)
![image](https://user-images.githubusercontent.com/45929614/70262044-766a8d00-1748-11ea-8975-c730b40fc75a.png)

If I use "onClick" to trigger notification as shown in your demo, is works great without any warning message.

But in my case I do want to trigger the notification based on the condition, like:
![image](https://user-images.githubusercontent.com/45929614/70262363-132d2a80-1749-11ea-8373-c5be90a307af.png)
Here is my showToast function
![image](https://user-images.githubusercontent.com/45929614/70262458-3e177e80-1749-11ea-957b-b5ff349d2d39.png)

How can I do notification without using any button click (I mean also no any warning messages). Any comments would be highly appreciated.

**Comment by yzhaopost** [comment]
Does anybody know how to trigger a react-toastify notification not using onClick? Like, I want to trigger different kind of notifications based on the state. In my project, I can see the correct notification triggered, but always have a warning message: "triggering nested component updates from render is not allowed". Does anybody know how to address this issue? Thank you!

**Comment by fkhadra** [comment]
Hello @yzhaopost ,

I created a sanbox which work just fine. 

[![Edit summer-cookies-ogb6j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/summer-cookies-ogb6j?fontsize=14&hidenavigation=1&theme=dark)

Could you reproduce your issue ?

**Comment by yzhaopost** [comment]
@fkhadra Thank you for your reply and thank you for providing test code in the Sandbox. I tried your code, I can still see the same issue in my environment.

Here is the warning message:
![image](https://user-images.githubusercontent.com/45929614/70639239-0e57f300-1bef-11ea-826a-7d64a45a88ab.png)

Here is the code:
![image](https://user-images.githubusercontent.com/45929614/70639281-1fa0ff80-1bef-11ea-9256-094317e3f9c9.png)

The difference between your code in the Sandbox (without warning message) and what I am experimenting (with warning message) is that I am using a **_create react app project_** and I use toast in `render( )` and your Sandbox is based on React function. That's why in my case it complains about the triggering nested component updates from render...and this is not allowed in React. So, the question is should I treat React-toastify like a regular JSX/TXS element? If should't, any advice regarding how to use toast in `render( )`?

In above test case, if I try to trigger the toast using `onClick`, there is no any issue. It works great.
![image](https://user-images.githubusercontent.com/45929614/70640930-a7880900-1bf1-11ea-9207-955d731c809b.png)

Thank you very much for your help.

**Comment by yzhaopost** [comment]
@fkhadra Any suggestions for my case? I just wanted to show a toast when the state changed. I appreciate your help.

**Comment by yzhaopost** [comment]
@fkhadra I think I figured out a workaround. Looks like react-tostify works with `onClick` event very well, I just need to simulate a `click` at the moment when I want to show toasts (via state for example). It works without any warning message. Thank you!
