### ISSUE TITLE
Toastify doesnt work on screens with html:overflow-x:hidden

### ISSUE THREAD

**Issue by developdeez** [fkhadra/react-toastify#407]
I use html:overflow-x:hidden to keep iPHone from horizontally scrolling (like many do).
I noticed once making this change react toastify doesn't focus below the fold. I'm not sure how they are related on the backend but it happens.

Any way to have both html/body overflow-x hidden, while still being able to use Toast? I've had to remove it from my app until its fixed

**Comment by fkhadra** [comment]
Hey, could you reproduce the issue in codesanbox please ?
