### ISSUE TITLE
custom event on "autoClose"

### ISSUE THREAD

**Issue by coutureJ** [fkhadra/react-toastify#410]
Hi,

I would like to add a feature.

At the moment, the autoClose param give us the ability to hide the toaster after a x amount of time.
In my scenario, I need to dispatch a redux event at the end of the delay, unfortunatly, this callback doesnt seems to exist.

Mind if I do a PR to add this optional feature?

Thanks,

**Comment by fkhadra** [comment]
Hey,

Sorry for the late reply. This is already available https://github.com/fkhadra/react-toastify#define-callback
