### ISSUE TITLE
Why the @babel/runtime dependency?

### ISSUE THREAD

**Issue by waynebrantley** [fkhadra/react-toastify#419]
Isn't this best left to the user of your component?
What if I use @babel/runtime-corejs2?
What if I target browsers that dont need this at all?

IMO just should not be a dependency that is included in your package?

**Comment by fkhadra** [comment]
Hello @waynebrantley,

Your comment makes a lot of sense. I'm currently working on the v6 I'll probably drop the dependency

**Comment by fkhadra** [comment]
Removed in v6
