### ISSUE TITLE
Persist toast despite navigation with context api

### ISSUE THREAD

**Issue by arso1er** [fkhadra/react-toastify#420]
Hi,
I'm a react/nextjs newbie and I was wondering if I could persist a toast between pages (toast will stay visible even if I navigate to another page).

So I've looked around and it seems react context can be used to persist state through pages. Is there a way to achieve that with react-toastify?
Thanks.

**Comment by fkhadra** [comment]
Hey,

With next under the `pages` folder you can create custom _app.js. If you import the `ToastContainer` here, the toast will remain even if you navigate. Link to the doc https://nextjs.org/docs/advanced-features/custom-app

The custom app file is useful for layout also

**Comment by arso1er** [comment]
Thanks. It's working great and I'm getting the desired behaviour.

Very cool package by the way. It has everything I need and more.

**Comment by EarlPappi** [comment]
How do I achieve this with React
