### ISSUE TITLE
Is there a way to use in React Native?

### ISSUE THREAD

**Issue by AllyssonAlas** [fkhadra/react-toastify#422]
I'm creating a basic CRUD, and I tried without success to use in React Native, now I am wondering if it is possible.

**Comment by fkhadra** [comment]
Hey, I've never tried with react-native. But maybe if more people are asking, I could look at it

**Comment by AllyssonAlas** [comment]
Would be great, since a great number of React libs have integration with React Native and this lib in particular is huge. Thanks for the answer!

**Comment by victorkl400** [comment]
I would like to have it on RN also.

**Comment by fkhadra** [comment]
I've worked on a prototype. It seems to be doable. Unfortunately, I need to find free time for this.

![toastify-native](https://user-images.githubusercontent.com/5574267/89464846-655b9b00-d771-11ea-82df-652e2e0bd231.gif)
