### ISSUE TITLE
How to add custom error/success/warning icons in front of the toast?

### ISSUE THREAD

**Issue by a-tonchev** [fkhadra/react-toastify#423]
I am wondering if it is possible to add custom icons like regular toastrs:

![Screenshot_1](https://user-images.githubusercontent.com/54528540/75034401-cdfdd680-54b5-11ea-81b8-d5ad4d9f3e92.jpg)

I could probably add the :before css to the bodyClassName in the ToastContainer, but it will be applyed to all body types, I want to have globally different icons at the success/warning/info/error etc..

In best case - I would use the material icons.

Thanks!
Regards Tony

**Comment by railto** [comment]
I'm also trying to figure this out. I'm using Material-UI Icons and have a base component where we configure colors etc for toast. Have been asked to add the icons, but can not see any way of doing this at present

**Comment by fkhadra** [comment]
Hey,

You can render a component instead of a simple string and put whatever you want inside 😀.

https://github.com/fkhadra/react-toastify#render-a-component

**Comment by a-tonchev** [comment]
> Hey,
> 
> You can render a component instead of a simple string and put whatever you want inside 😀.
> 
> https://github.com/fkhadra/react-toastify#render-a-component

Yes we got this, and it is cool, but we have to add/change icon on every single place where we have success/error/etc..., and tostr icon is quite a standard behavior. It would be nice to have something globally, like 

```
globalRenders = (nodeOrMsg) => {
 success: <div><SomeSuccessComponent />{nodeOrMsg}</div>,
 error: <div><SomeCustomNode />{nodeOrMsg}</div>,
....
}

toast.configure({ ... , globalRenders });
```

That you define globally, and When you call toast.success(<Msg />) you will just get the

<div><SomeSuccessComponent />{nodeOrMsg}</div> as content.

**Comment by fkhadra** [comment]
I take your consideration into account. 

As a workaround, I would suggest you wrap `toast.success` and `toast.error` with your own logic.
```js
export function success(nodeOrMsg) {
 return toast.success(<div><SomeSuccessComponent />{nodeOrMsg}</div>);
}
```

**Comment by a-tonchev** [comment]
> I take your consideration into account.
> 
> As a workaround, I would suggest you wrap `toast.success` and `toast.error` with your own logic.
> 
> ```js
> export function success(nodeOrMsg) {
>  return toast.success(<div><SomeSuccessComponent />{nodeOrMsg}</div>);
> }
> ```

Yeah, that is what I do right now :)

**Comment by railto** [comment]
> 
> 
> Hey,
> 
> You can render a component instead of a simple string and put whatever you want inside 😀.
> 
> https://github.com/fkhadra/react-toastify#render-a-component

Thanks, took this and added it to my own base config for Toast and it worked a treat. I'm experiencing another issue but will open a separate ticket for that.

**Comment by fatemeKholousi** [comment]
in version 9 you can:
toast.success("And of course a component of your choice", {
  icon: MyIcon
});

**Comment by wale-earnipay** [comment]
You can now do a one-time setup like this:

<ToastContainer
    autoClose={5000}
    position="top-center"
    icon={({ type }) => {
        if (type === "success") return <ToastIconSuccess />;
        if (type === "error") return "🚨";
        else return "ℹ️";
    }}
/>

Supports images, SVG icons, texts, emojis, etc.
Works great with "react-toastify": "^8.1.0"

**Comment by wale-earnipay** [comment]
You can now do a **one-time** setup like this:

```
<ToastContainer
    autoClose={5000}
    position="top-center"
    icon={({ type }) => {
        if (type === "success") return ;
        if (type === "error") return "🚨";
        else return "ℹ️";
    }}
/>
```

Supports images, SVG icons, texts, emojis, etc.
Works great with `"react-toastify": "^8.1.0"`

**Comment by wale-earnipay** [comment]
You can now do a **one-time** setup like this:

```
<ToastContainer
    autoClose={5000}
    position="top-center"
    icon={({ type }) => {
        if (type === "success") return <IconSuccess />;
        if (type === "error") return "🚨";
        else return "ℹ️";
    }}
/>
```

Supports images, SVG icons, texts, emojis, etc.
Works great with `"react-toastify": "^8.1.0"`

**Comment by Walex996** [comment]
You can now do a **one-time** setup like this:

```
<ToastContainer
    autoClose={5000}
    position="top-center"
    ...
    icon={({ type }) => {
        if (type === "success") return <IconSuccess />;
        if (type === "error") return "🚨";
        else return "ℹ️";
    }}
/>
```

Supports images, SVG icons, texts, emojis, etc.
Works great with `"react-toastify": "^8.1.0"`

**Comment by Jeysieeeee** [comment]
how can you change the size of the icons?

**Comment by MDziurakh** [comment]
> You can now do a **one-time** setup like this:
> 
> ```
> <ToastContainer
>     autoClose={5000}
>     position="top-center"
>     ...
>     icon={({ type }) => {
>         if (type === "success") return <IconSuccess />;
>         if (type === "error") return "🚨";
>         else return "ℹ️";
>     }}
> />
> ```
> 
> Supports images, SVG icons, texts, emojis, etc. Works great with `"react-toastify": "^8.1.0"`

it would be great if **undefined** showed a **default icon** as here or some like this
```

icon={({ type }) => {
  if (type === "success") return <IconSuccess />;
  if (type === "error") return "🚨";
  return undefined;
}}
```
