### ISSUE TITLE
Change transition show up from bottom

### ISSUE THREAD

**Issue by muscaiu** [fkhadra/react-toastify#424]
Hey, I have a small question (low experience with animations).
I'm using `styled-components` to show the toast and it works great. 

How can i make the toast to show up from bottom?
Something like this: https://github.com/fkhadra/react-toastify/issues/85 

```
import React from 'react';
import { ToastContainer } from 'react-toastify';
import styled from 'styled-components';
import 'react-toastify/dist/ReactToastify.css';

const StyledToastContainer = styled(ToastContainer)`
  /* customize all toast types here */
  .Toastify__toast-container {
  }
  .Toastify__toast {
  }
  .Toastify__toast--error {
  }
  .Toastify__toast--warning {
  }
  .Toastify__toast--success {
  }
  .Toastify__toast-body {
  }
  .Toastify__progress-bar {
  }
`;

const Notifier = () => (
  <StyledToastContainer
    position="bottom-right"
    autoClose={2000}
    pauseOnHover
    draggable={false}
    pauseOnFocusLoss={false}
  />
);

export default Notifier;

```

**Comment by fkhadra** [comment]
Hey @muscaiu,

One quick solution without creating a new transition would be to do as follow:

```js
import { ToastContainer, Slide } from 'react-toastify';

const StyledToastContainer = styled(ToastContainer)`
  /* customize all toast types here */
  .Toastify__toast-container--bottom-center {
    bottom: 1em;
    right: 1em;
    transform: none;
  }
`;

const Notifier = () => (
  <StyledToastContainer
    position="bottom-center"
    transition={Slide}
    autoClose={2000}
    pauseOnHover
    draggable={false}
    pauseOnFocusLoss={false}
  />
);
```

Doing so we use the Slide transition of the bottom-center position but with the toast positioned on the bottom-right.

![#424](https://user-images.githubusercontent.com/5574267/79268575-46bc5600-7e9b-11ea-9bd0-523640bd42fa.gif)

**Comment by muscaiu** [comment]
@fkhadra thanks for the help!
I also had to override the `left: 50%` and add `&&` before the class selector to ensure that styled-component styles are applied.

```
  &&.Toastify__toast-container--bottom-center {
    bottom: 1em;
    right: 1em;
    left: auto;
    transform: none;
  }
...
  <StyledToastContainer
    position="bottom-center"
    transition={Slide}
  />
```

**Comment by rutikwankhade** [comment]
> `&&`

doesn't seem to work for me. i am using tailwindcss and tried overriding the css but not working

**Comment by rutikwankhade** [comment]
> Hey @muscaiu,
> 
> One quick solution without creating a new transition would be to do as follow:
> 
> ```js
> import { ToastContainer, Slide } from 'react-toastify';
> 
> const StyledToastContainer = styled(ToastContainer)`
>   /* customize all toast types here */
>   .Toastify__toast-container--bottom-center {
>     bottom: 1em;
>     right: 1em;
>     transform: none;
>   }
> `;
> 
> const Notifier = () => (
>   <StyledToastContainer
>     position="bottom-center"
>     transition={Slide}
>     autoClose={2000}
>     pauseOnHover
>     draggable={false}
>     pauseOnFocusLoss={false}
>   />
> );
> ```
> 
> Doing so we use the Slide transition of the bottom-center position but with the toast positioned on the bottom-right.
> 
> ![#424](https://user-images.githubusercontent.com/5574267/79268575-46bc5600-7e9b-11ea-9bd0-523640bd42fa.gif) [ ![#424](https://user-images.githubusercontent.com/5574267/79268575-46bc5600-7e9b-11ea-9bd0-523640bd42fa.gif) ](https://user-images.githubusercontent.com/5574267/79268575-46bc5600-7e9b-11ea-9bd0-523640bd42fa.gif) [ ](https://user-images.githubusercontent.com/5574267/79268575-46bc5600-7e9b-11ea-9bd0-523640bd42fa.gif)


&&

doesn't seem to work for me. i am using tailwindcss and tried overriding the css but not working
