### ISSUE TITLE
types in index.d.ts are not exported

### ISSUE THREAD

**Issue by rodlukas** [fkhadra/react-toastify#426]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Type and interface declarations in `index.d.ts` don't have any exports for use, it's not possible to do ie.:
```ts
import { toast, ToastOptions, TypeOptions } from "react-toastify"
...
...
const notify = (message: React.ReactNode, level: TypeOptions): void => {
        const options: ToastOptions = {
            type: level,
            autoClose: level === toast.TYPE.ERROR ? 15000 : 4000
        }
        toast(message, options)
    }
```
-> eslint warnings:
* *ESLint: ToastOptions not found in 'react-toastify'(import/named)*
* *ESLint: TypeOptions not found in 'react-toastify'(import/named)*

**What is the expected behavior?**
importing of types/interfaces should work, IMO there's no reason for not exporting some of them

**Comment by fkhadra** [comment]
@rodlukas the v6 is fully written in TS. This should fix the issue
