### ISSUE TITLE
Set defaults by toast type

### ISSUE THREAD

**Issue by markwoon** [fkhadra/react-toastify#429]
**Do you want to request a *feature* or report a *bug*?**

Feature.

I would like to set defaults per toast type.

For example, I don't want `toast.error()` to autoclose, but I do for all the other types.  I would like to be able to set this globally.

Something like:

```
toast.configure({
  autoClose: 8000,
  error: {
    autoClose: false,
  }
});
```

**Comment by fkhadra** [comment]
Hey @markwoon,

I'm not considering adding this feature for now). For your use case, I would rely on composition instead.

```js
import { toast } from 'react-toastify';

export function displayError(content, options){
  return toast.error(content, {
    autoClose: false,
   ...options
  })
} 
```
The toast emitter can be used everywhere not only inside a react component.

**Comment by markwoon** [comment]
Thanks for the update.  That's what I'm doing at the moment.
