### ISSUE TITLE
ToastContainer not working with react Suspense

### ISSUE THREAD

**Issue by FarrukhShahid** [fkhadra/react-toastify#436]
When I use react lazy loading with Suspense like
import React, { Suspense } from 'react'
import { ToastContainer } from 'react-tostify'

They both don't work together. I cant understand the reason but the *CSS* for Toast is not working.

**Comment by Ifechukwudaniel** [comment]
OK which  version of lazy  loading are you using

**Comment by fkhadra** [comment]
Hey please provide a codesanbox reproducing the issue. Thanks.

**Comment by markhker** [comment]
Here, same issue. Latest version of react, tested with react-toastify 5.5.0 and RC: https://codesandbox.io/s/react-toastify-suspense-ewwkt?file=/src/App.js

**Comment by markhker** [comment]
Seems like importing the css directly works for now. In my case also needed a style-loader for webpack (since I'm using styled-components):

`import 'react-toastify/dist/ReactToastify.min.css'`

Still thinking that's an issue
