### ISSUE TITLE
Not working after deploying

### ISSUE THREAD

**Issue by mba8487143** [fkhadra/react-toastify#437]
I am deploying my reactjs app on Cpanel but after creating build using `npm run build`. plugin doesn't work. i am using React 16.12.
without deploying it works but after deploying not showing toast. Am i deploying correctly?

https://codesandbox.io/s/young-fire-jddy6

**Comment by mba8487143** [comment]
I found error. but how to solve it 
its working on avast secure browser but not on chrome

**Comment by fkhadra** [comment]
@mba8487143 could you share the url?

**Comment by tejasgoswami** [comment]
I'm facing the same issue and i got reason for the issue,
It's actually with the css, 
it's not able to find the CSS for the Toastify__toast-container from the node modules, 
after deploying the react app.

**Comment by fkhadra** [comment]
Hey @tejasgoswami, without knowing your setup is not easy to help you :(. Are you using css modules ? 
Could you try to inject the style on demand to see if it solve your issue ?
https://fkhadra.github.io/react-toastify/how-to-style/#inject-style-on-demand

**Comment by tejasgoswami** [comment]
@fkhadra   Thanks for the suggestion, it works fine for me.
