### ISSUE TITLE
.dismiss(toastId) does not working as aspected 

### ISSUE THREAD

**Issue by WhoIsDT** [fkhadra/react-toastify#439]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
console is empty, no errors, but toast does not disappear from screen.

Here is the code, that i'm using

```
import React, { useEffect } from 'react'
import './Dialer.sass'

import { connect } from 'react-redux'
import { Slide, toast, ToastContainer } from 'react-toastify'
import CallBar from './CallBar/CallBar'

function Dialer({ callBarStatus, activeCall }) {
  const componentId = 'callbar'
  const newCallBar = <CallBar {...activeCall} />

  useEffect(() => {
    toggleCallBar()
  }, [callBarStatus])

  const toggleCallBar = () => {
    if (callBarStatus) {
      if (toast.isActive(componentId)) {
        toast.update(componentId, { render: newCallBar, containerId: 'dialerContainer' })
      } else {
        toast(newCallBar, { componentId, containerId: 'dialerContainer' })
      }
    } else {
      console.log('toggleCallBar -> componentId', componentId)
      toast.dismiss(componentId)
    }
  }

  return (
    <ToastContainer
      enableMultiContainer
      containerId={'dialerContainer'}
      position={toast.POSITION.BOTTOM_CENTER}
      autoClose={false}
      closeButton={false}
      closeOnClick={false}
      className="Dialer-Container"
      toastClassName="Dialer-Bar"
      draggable={false}
      transition={Slide}
    />
  )
}

const mapStateToProps = state => ({
  activeCall: state.dialer.activeCall,
  callBarStatus: state.dialer.isActiveCallBar,
})

export default connect(mapStateToProps)(Dialer)

```

Only if i trie to toast.dismiss() without id, - toasts are gone. But that's not that i need, cause there are all toasts gone. I'm 100% guarantee, that i have only one toast with tat id!

**Comment by WhoIsDT** [comment]
This problem in case of using multi containers. If i have already toast in one container, and want to check if toast.isActive(eventId) - it's always returns false! i think you need to add check for containerId or fix bug

**Comment by fkhadra** [comment]
Hey,

This is something I'm working on for [v6](https://github.com/fkhadra/react-toastify/pull/432)

**Comment by WhoIsDT** [comment]
5.5.0v
Want to tell, that your plugin is so clear to understand and also it's enough powerful, that i'm continue to using it with happiness, but i need to deploy a new v of my app after 2 weeks. When we can get this bug fix to be resolved?

**Comment by fkhadra** [comment]
Thanks appreciate the feedback ! I'll try to reproduce the issue on codesanbox now. I'll get back to you.

**Comment by fkhadra** [comment]
@WhoIsDT I think I found the guilty line !
```js
toast(newCallBar, { componentId, containerId: 'dialerContainer' });
```

Must be replaced by
```js
toast(newCallBar, { toastId: componentId, containerId: 'dialerContainer' })
```

**Comment by fkhadra** [comment]
@WhoIsDT did you had time to test the fix ?

**Comment by WhoIsDT** [comment]
Yes, update method now works perfect, and don't generate a new toast, Sorry for spending your time, that was my bad, cause i forgot that i'm creating object prop:) before componentId it was toastiId, as a shortcut, and you know that {toastId} same as {toastId: toastId}, but after renaming i forgot to write full expression.

If you also about dismiss, there i didn't tested yet, i'll trie tomorrow and i'll notice you! Thanks so much for your help and attention to mu issue:)

**Comment by fkhadra** [comment]
Don't worry. Happy to help 👌

**Comment by fkhadra** [comment]
I'll close the issue. Feel free to reopen it if the issue persists. ✌️

**Comment by WhoIsDT** [comment]
thx so much for your help! Everything ok, i've tested yesterday! There is no problems there.
