### ISSUE TITLE
Multiple Toasts Stacking on single toast() call

### ISSUE THREAD

**Issue by danthegoodman1** [fkhadra/react-toastify#440]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

```js
<BrowserRouter>
      <Navbar />
      <ToastContainer />
        <Switch>
         ...
```

Called like: `toast.info('🦄 Wow so easy!')`

With `<ToastContainer />` in a higher level component, it will stack 4 times. With it in the lower level component that calls the `toast()`, it stacks 3 times.
![toasts](https://user-images.githubusercontent.com/17806508/76891648-ba008700-685f-11ea-89e2-2c732d9fa968.gif)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.12.0
Windows 10
Most updated Chrome

**Comment by danthegoodman1** [comment]
Ok it magically stopped doing that...

**Comment by fkhadra** [comment]
😅 are you using hot reload?

**Comment by talentedandrew** [comment]
I encountered this same issue.

**Comment by singhaishwarya** [comment]
any update?
