### ISSUE TITLE
Stop toast from closing at progress 100%

### ISSUE THREAD

**Issue by muscaiu** [fkhadra/react-toastify#441]
Any way to **stop the toast from closing when progress 100%**?

I'm using this and it always closes when the progress ends.

```
  toast.success(`Downloading ${titleId}`, { toastId: titleId, autoClose: false });

  toast.update(titleId, {
    progress: toastProgress,
    autoClose: false,
  });
```

If i comment this part `progress: toastProgress,` then it never closes, so the progress must be to blame.

**Comment by fkhadra** [comment]
Hey @muscaiu,

By design the toast trigger close when the progress is >= 1. As a workaround, can I suggest to set the progress to 0.99

**Comment by jabacrack** [comment]
In my opinion, there's a logical inconsistency between progress is >= 1 and autoClose: false.
If `autoClose: false` toast shouldn't automatically close under any conditions until the `done()` method is called.

Would you consider turning this behavior off with the `autoClose: false` option?
