### ISSUE TITLE
Cannot flush updates when React is already rendering.

### ISSUE THREAD

**Issue by malvinpatrick** [fkhadra/react-toastify#444]
I got that error after tried to 
`toast.update(ConfirmationToast._TOAST_ID, {
      render: (
        <ConfirmationToast
          type="delete"
          loading={true}
          onConfirm={() => handleDeleteCategory(category_id)}
        />
      )`

I used React 16, and functional component 
What should I do ?

**Comment by fkhadra** [comment]
Hey could you provide a codesandbox with a reproduction please.

**Comment by Jeremy-JM** [comment]
I also meet this problem.

**Comment by canselcik** [comment]
Not very clear from the description what's going on here but I believe I might be having a similar issue.

Likely not a very accurate description of what's going on from my end either but the toasts seem to block the pipeline that processes certain React events, leading to the queue building up and things happening delayed.
