### ISSUE TITLE
How can we make the toasts wider?

### ISSUE THREAD

**Issue by iansan5653** [fkhadra/react-toastify#445]
I believe this is already a feature but I can't find it anywhere. I thought I saw some older issues where a helper function was provided for modifying the width, but now I don't see that anywhere so I'm not sure.

We have figured out how to use custom styling to change the shape, colors, etc, but changing the width results in a number of alignment/animation/rendering errors as much of the default CSS is calculated based on the width. Is there any way we can change this? We find the default width to be much too small.

**Comment by fkhadra** [comment]
Hey @iansan5653, you can change the css  associated with the toast or a cleaner approach in your case would be to change the [sass variable] according to your needs and build the css.

**Comment by iansan5653** [comment]
Can you provide more information on SASS variables? I don't see that in the readme.

**Comment by fkhadra** [comment]
Sure. If you go in the [scss folder](https://github.com/fkhadra/react-toastify/tree/master/scss), there is a _variables.scss file. 
```scss
$rt-namespace: 'Toastify';
$rt-toast-width: 320px !default;
$rt-toast-background: #ffffff !default;
$rt-toast-min-height: 64px !default;
$rt-toast-max-height: 800px !default;

$rt-color-default: #fff !default;
$rt-color-info: #3498db !default;
$rt-color-success: #07bc0c !default;
$rt-color-warning: #f1c40f !default;
$rt-color-error: #e74c3c !default;

$rt-text-color-default: #aaa !default;

$rt-color-progress-default: linear-gradient(to right, #4cd964, #5ac8fa, #007aff, #34aadc, #5856d6, #ff2d55) !default;

$rt-mobile: "only screen and (max-width : 480px)" !default;
$rt-font-family: sans-serif !default;
$rt-z-index: 9999 !default;
```

My suggestion would be to adapt these variables to fit your needs and rebuild the style.
