### ISSUE TITLE
Getting error in ToastContainer i have installed react-toastify@4.0.1. 

### ISSUE THREAD

**Issue by varun3820** [fkhadra/react-toastify#448]
import * as React from 'react';
import { connect } from 'react-redux';
import {ToastContainer,toast} from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

class Login extends React.PureComponent<LoginProps> {

state = {
        isLoginOpen: true,
        }

submitOTPNo = () => {
       axios.get("/ghg")
        .then(res => {
            console.log(res);
        })
        .catch(err => {
            if (err) {
                toast("API Error", {
                    className: "error-toast",
                    draggable: true,
                    position: toast.POSITION.TOP_CENTER,
                    autoClose: 100000
                });
            }
        })
}

public render() {       
        
        return  (
            
            <React.Fragment>
                <ToastContainer/> /*Error TS2605(TS) JSX element type 'ToastContainer' is not a 
                                                        constructor function for JSX elements.
                                                   Type 'ToastContainer' is missing the following properties from type 
                                                   'ElementClass': render, context, setState, forceUpdate, and 3 more.*/
              {
                this.state.islogin?(

                 <div>
			<button type="button"
                                className="btn btn-block btn-lg btn-primary mb-4 w-50"
                                onClick={() => { this.submitOTPNo() }}>
                                Verify
                         </button>
                 </div>
                 
                 ):(

	         <div></div>	

		)
	      }
	    </React.Fragment>
           );
	}
}
export default connect()(Login);

**Comment by fkhadra** [comment]
Can you install the latest version ?
