### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: 

### ISSUE THREAD

**Issue by tumdav** [fkhadra/react-toastify#449]
The latest release of the React has added StrictMode functionality.
 
`StrictMode is a tool for highlighting potential problems in an application. Like Fragment, StrictMode does not render any visible UI. It activates additional checks and warnings for its descendants.`

So now it throws an error while using a toast function

![image](https://user-images.githubusercontent.com/10452309/78033125-04612800-7377-11ea-8f2a-3eda6f995963.png)

**Comment by fkhadra** [comment]
the error is not coming from react-toastify but from react-transition-group https://github.com/fkhadra/react-toastify/issues/388

**Comment by fkhadra** [comment]
Hey @tumdav,

The new RC of `react-toastify` support strict mode. You can install it as follow:
`yarn add react-toastify@next` or `npm i react-toastify@next`

I expect to launch the stable release next week if there is no bug.

**Comment by tumdav** [comment]
@fkhadra seems it does not work for me, I am getting the same error in the console

**Release version** : `"react-toastify": "^6.0.0-rc.2"`

![image](https://user-images.githubusercontent.com/10452309/81161389-8f4bc880-8f9c-11ea-8dfb-a9b61c30243a.png)

**Comment by dishcandanty** [comment]
I'm personally no longer seeing this with  `react-toastify": "^6.0.0-rc.3",`
