### ISSUE TITLE
Custom transition issue with animate out

### ISSUE THREAD

**Issue by ayoungh** [fkhadra/react-toastify#456]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using a custom transition I get a strange issue where on the out animation you see the default style animation as well as the one I have added. Is there a way to stop the default style transition / remove the inline style from being added? 

[Example of issue](https://codesandbox.io/s/react-styled-components-toastify-transition-issue-jm8v3?file=/src/App.js)

**What is the expected behavior?**

It should fade in and fade out using my custom transition, using the example from the main repo of how to do this. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

See the example above

**Comment by fkhadra** [comment]
Thank you for giving a sandbox I'll look at it asap.

**Comment by fkhadra** [comment]
@ayoungh the documentation is not up to date. But a new one is coming in the next days(v6 launching soon).

I forked your sandbox and adapted the your Transition component to make it work
[![Edit react-styled-components-toastify transition issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-styled-components-toastify-transition-issue-b9hon?fontsize=14&hidenavigation=1&theme=dark)

A few explanations. Besides `in` and `appear` props, `onExited` and `preventExitTransition` are passed down. 
- `preventExitTransition`  is an internal prop. It can be omitted
- `onExited` allow the toast to smooth out nicely(reducing the height to 0 when the toast is not visible on screen)

You also need to add `unmountOnExit` to well, unmount the component when the animation end :D.

```jsx
const FadeInAndOut = ({ children, position, ...props }) => {
  // delete uneeded props
  delete props.onExited;
  delete props.preventExitTransition;

  return (
    <Transition
      {...props}
      timeout={800}
      unmountOnExit
      onEnter={node => node.classList.add("fadeIn")}
      onExit={node => {
        node.classList.remove("fadeIn");
        node.classList.add("fadeOut");
      }}
    >
      {children}
    </Transition>
  );
};
```

**Comment by ayoungh** [comment]
Thanks, @fkhadra That's great!
