### ISSUE TITLE
Typescript issue - commonOptions and transition type not accepting P props

### ISSUE THREAD

**Issue by ayoungh** [fkhadra/react-toastify#458]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I am trying to use transition prop on the container and am getting a type issue because of the: 
` transition?: React.ComponentType;`
Not taking in <P>;

This is the typescript error I am getting:
`JSX.Element' is not assignable to type 'ComponentClass<{}, any> | FunctionComponent<{}> | undefined'.`

I have fixed it by hardcoding the types file to have:
`interface CommonOptions<P> {`
and
`transition?: React.ComponentType;<P>`

Do you know if this kind of issue will be fixed in V6?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`"react": "16.13.1",`
` "react-dom": "16.13.1",`
`"@types/react": "16.9.34",`
` "@types/react-dom": "16.9.6",`

**Comment by fkhadra** [comment]
Hey @ayoungh,

In v6 the type for Transition is `React.ReactNode` can you check if it works for you ?

**Comment by ayoungh** [comment]
Sorry @fkhadra I am fairly new to typescript, is V6 out now? 

I have now used the code from the [example](https://codesandbox.io/s/react-styled-components-toastify-transition-issue-b9hon?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js) to get the transition working but have the type issue. Thanks for your help

**Comment by fkhadra** [comment]
Hey you can try it [there](https://github.com/fkhadra/react-toastify/releases/tag/v6.0.0-rc.0) if you want
