### ISSUE TITLE
🔥 v6 rc0 feedback

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#459]
Hey,

This issue is dedicated to the v6 RC release. Also, any suggestions regarding the new documentation can be added here. Thanks all for your contribution!

Link to doc: https://fkhadra.github.io/react-toastify/introduction

```sh
npm install react-toastify@next

yarn add react-toastify@next
```

**Comment by twgraham** [comment]
Not so much a documentation suggestion since it's still TODO, but currently `useToast` isn't exported in the RC releases so we can't try play with creating our own toasts.

**Comment by fkhadra** [comment]
Hey @twgraham ,

I published the v6. The `useToast` is also exported. The documentation is still not up to date for the hooks. I'll need to free-up some time

**Comment by stoneRdev** [comment]
If someone can provide a quick gist of how `useToast` works, I can write documentation on it

**Comment by dvkndn** [comment]
@stoneRdev  https://github.com/fkhadra/react-toastify/pull/421
