### ISSUE TITLE
Problem in fullscreen

### ISSUE THREAD

**Issue by fgvicente** [fkhadra/react-toastify#461]
Im using [react-full-screen](https://www.npmjs.com/package/react-full-screen) but the toast are under the fullscreen

**Comment by fkhadra** [comment]
Hey @fgvicente,

Can you setup a codesanbox so I can help you. Thanks

**Comment by fgvicente** [comment]
https://codesandbox.io/s/lingering-sunset-2zy6v?file=/src/App.js:0-572 this is an example. but not work in codesanbox. you need to create it outside codesandbox to see it

**Comment by fkhadra** [comment]
I've tried with your example. It works, the only change that I made was to set the initial state for full screen to false. It is not possible to start in Fullscreen. Fullscreen must be enabled from a user. This is written in react-full-screen documentation 

Here is a video https://youtu.be/HOObtLLJStk

**Comment by mmesar** [comment]
I also have this problem. I have socket connection and data is coming at regular intervals over that connection. Sometimes data is bad and I notify user about that. When user is in full screen notifications are not shown, and when the user exits full screen notifications are waiting for him and are displayed.
