### ISSUE TITLE
Question: Is there a plain browser script resource or example available.

### ISSUE THREAD

**Issue by hipitihop** [fkhadra/react-toastify#462]
Thanks for this awesome library. I'm already using it successfully from other projects with ClojureScript which has no problem using the npm dependencies.

Question: If I want to use this in plain html without install via npm or yarn, how can I just use a plain html `<script>` tag to use this library ?

I have tried via ```https://unpkg.com/react-toastify/cjs/react-toastify.js``` but this still causes an error when this is loaded `Uncaught ReferenceError: exports is not defined`

Appreciate any pointer to nudge me over this hump.

**Comment by fkhadra** [comment]
Hey, 
Glad you like the library.

May I ask you to try with
`https://unpkg.com/react-toastify@6.0.0-rc.1/dist/react-toastify.cjs.production.min.js`

**Comment by hipitihop** [comment]
Hi @fkhadra apologies for my tardy response, I have been testing testing with other toast libraries which use plain JS and I have only just seen this. 

I  tried your suggestion but I still see the same error, see below.

Some more context:
I'm writing a module for [MagicMirror²](https://github.com/MichMich/MagicMirror) and would like to leverage this toast library. MagicMirror runs on npm and uses electron for the browser. Modules are a little restricted as to what they can do on the client side, e.g. no require statement in their client side JS, but arbitrary scripts and css can still be specified to be loaded from either cdn like unpkg or from the npm back-end which can use full npm install semantics too.

Below is a snippet of the logs of my module loading, as you see it has no issues loading the other deps.

```
Module registered: MMM-Toastify
loader.js:150 Bootstrapping module: MMM-Toastify
loader.js:179 Load script: modules/MMM-Toastify/react-v16.13.1.production.min.js
loader.js:179 Load script: modules/MMM-Toastify/react-dom-v16.13.1.production.min.js
loader.js:179 Load script: modules/MMM-Toastify/react-transition-group.min.js
loader.js:179 Load script: https://unpkg.com/react-toastify@6.0.0-rc.1/dist/react-toastify.cjs.production.min.js
react-toastify.cjs.production.min.js:1 Uncaught ReferenceError: exports is not defined
    at react-toastify.cjs.production.min.js:1
(anonymous) @ react-toastify.cjs.production.min.js:1
loader.js:155 Scripts loaded for: MMM-Toastify
loader.js:194 Load stylesheet: modules/MMM-Toastify/MMM-Toastify.css
loader.js:194 Load stylesheet: https://unpkg.com/react-toastify@6.0.0-rc.1/dist/ReactToastify.css
loader.js:157 Styles loaded for: MMM-Toastify
loader.js:159 Translations loaded for: MMM-Toastify
tracer-bundle.js:1 MMM-Toastify has started... (/http:/192.168.0.64:8080/modules/MMM-Toastify/MMM-Toastify.js:23 Class.start)
```
