### ISSUE TITLE
Feature Request: Dismiss All Toasts Displayed or Not.

### ISSUE THREAD

**Issue by zacknovosad** [fkhadra/react-toastify#463]
**Do you want to request a *feature* or report a *bug*?**
Feature request:
With the new limit toast feature we can dismiss all **displayed** toasts which is great but it would be nice to be able to dismiss all toasts whether they are displayed or not.

**Comment by fkhadra** [comment]
Hey @zacknovosad ,

I published a new RC version today. Where I added the ability to cleart the queue:
https://fkhadra.github.io/react-toastify/limit-the-number-of-toast-displayed/#how-to-clear-the-waiting-queue

**Comment by zacknovosad** [comment]
Oh man, thank you so much! Should have checked first.

Appreciate the library and all of your hard work!
