### ISSUE TITLE
Please add some assurances/explanations of how it handles accessibility issues to the docs?

### ISSUE THREAD

**Issue by jhackett1** [fkhadra/react-toastify#464]
Hello!

I'd like to use this library but I'm not sure how it handles accessibility issues (eg. screenreader announcements, keyboard navigation).

The React community seems to be normalising libraries that are accessible by default ([eg](https://reacttraining.com/reach-ui/)), so it would be good to know if that's the case for this one!

I can see a bit of explanation here that would be good to expand on? https://fkhadra.github.io/react-toastify/accessibility/

**Comment by fkhadra** [comment]
Hey,

By default, all toasts are displayed with the ARIA role alert. It's up to you to make the content of the toast accessible. The close button also has an aria-label set to 'close'. Both can be changed.

If you want to make the color of the notification AA or AAA compliant I suggest that you use the axe browser extension https://www.deque.com/axe/
