### ISSUE TITLE
$rt-color-progress-dark in _variables.scss should be !default

### ISSUE THREAD

**Issue by cduff** [fkhadra/react-toastify#466]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Can't override $rt-color-progress-dark Sass variable.

**What is the expected behavior?**

Should be able to specify own value for this as per all the other variables.

**Comment by fkhadra** [comment]
Thanks for the feedback.

**Comment by fkhadra** [comment]
@cduff fixed in latest RC
