### ISSUE TITLE
Typescript problem:  Cannot find module 'types'

### ISSUE THREAD

**Issue by Sauloxd** [fkhadra/react-toastify#469]
**Do you want to request a *feature* or report a *bug*?**
First, thanks for this awesome library! We've been using it so far without a problem, so thanks for everything :)

I'm trying to bump to the new major version 6.0.0, and found some problems when typescript checks my types! Probably a bad configuration on our side (would not be the first time :| ) but I would be glad if any one could help me...

**What is the current behavior?**
I'm getting this errors:

```
node_modules/react-toastify/dist/utils/propValidator.d.ts(1,20): error TS2307: Cannot find module 'types'.
node_modules/react-toastify/dist/utils/cssTransition.d.ts(2,38): error TS2307: Cannot find module 'types'.
```

which points to the absence of this module: `types` https://github.com/fkhadra/react-toastify/blob/master/src/utils/propValidator.ts#L3

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
To reproduce I'm just running `tsc -p tsconfig.json`, if needed I can paste my tsconfig

**What is the expected behavior?**
TS should work

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I don't think it's related, but: 6.1.1

Also, I cloned the repo and hoped my yarn install + vscode would point to me where is this module, but it couldn't find it :(

thanks!

**Comment by awwit** [comment]
I have the same problem.

And more errors with the flag `esModuleInterop`: `false`

We work in our projects without this flag, since it has its own shortcomings: https://twitter.com/sebmarkbage/status/1250284377138802689?s=21

**Comment by fkhadra** [comment]
@Sauloxd @awwit, I've pushed a new version. This should fix the issue.

**Comment by Sauloxd** [comment]
It works now! Thanks for your work :)

**Comment by fkhadra** [comment]
Perfect thanks for the feedback
