### ISSUE TITLE
[Types]: TS2322: Type 'string' is not assignable to type using `toast.POSITION.TOP_CENTER`

### ISSUE THREAD

**Issue by c-frater** [fkhadra/react-toastify#470]
**Do you want to request a *feature* or report a *bug*?**
Bug (with types)

**What is the current behavior?**
When passing `position` to `ToastContainer` using `toast.POSITION.TOP_CENTER`:
```bash
TS2322: Type 'string' is not assignable to type '"top-right" | "top-center" | "top-left" | "bottom-right" | "bottom-center" | "bottom-left" | undefined'.
```

The type of `toast.POSITION.TOP_CENTER` is `string` which can't then be passed as a property to `ToastContainer`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/react-toastify-type-mismatch-tjnrq?file=/src/index.tsx
```tsx
import * as React from "react";
import { render } from "react-dom";
import { toast, ToastContainer } from "react-toastify";

const App: React.FunctionComponent<{}> = () => {
  return <ToastContainer position={toast.POSITION.TOP_CENTER} />;
};

render(<App />, document.getElementById("root"));
```

**What is the expected behavior?**

`toast.POSITION.TOP_CENTER` should be compatible with `ToastPosition`

I'm currently having to cast it, or use the string directly but would prefer to continue using the POSITION:

```ts
position={toast.POSITION.TOP_CENTER as ToastPosition}

or

position="top-center"
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Purely TS related.
- `react-toastify` version *6.0.2*
- `typescript` *3.8.3*

**Comment by fkhadra** [comment]
@c-frater just pushed a fix right now.
