### ISSUE TITLE
Wrong Link??

### ISSUE THREAD

**Issue by K-Sato1995** [fkhadra/react-toastify#473]
There is a link that says "documentation" In `README.md`.
When I click the link, it brings me to the demo page(`https://fkhadra.github.io/react-toastify/introduction`). Is this intentional?

![image](https://user-images.githubusercontent.com/32632542/81927076-01b44c80-961e-11ea-9fe4-81a328b5bfa0.png)

**Comment by fkhadra** [comment]
May I ask you to try from a private tab. I think you need to clear the service worker

**Comment by K-Sato1995** [comment]
@fkhadra 
ohhhhh my mistake!! Thanks!!
