### ISSUE TITLE
Icon not appearing and text not aligned to middle?

### ISSUE THREAD

**Issue by ElixirMike** [fkhadra/react-toastify#474]
Hi, the toast I am using pops up correctly, however the formatting is wrong. I don't see any icons, and the text does not align in the middle?

I am using React 16.12 and react-toastify 5.5.0

![image](https://user-images.githubusercontent.com/34098742/81940894-195fe680-95c6-11ea-954f-dd6cbc873dbb.png)

It would seem like a CSS issue, but I am importing the css at top of my file
import 'react-toastify/dist/ReactToastify.css';

Any idea on how to fix?

**Comment by fkhadra** [comment]
Hey @ElixirMike,

There is no built-in icon. The thing is that the toast function accepts everything not only string. https://fkhadra.github.io/react-toastify/render-what-you-want

**Comment by ElixirMike** [comment]
Ok, i missed that. But is there any reason why text isn't centered in box?

**Comment by fkhadra** [comment]
I think this has been fixed with the latest version
