### ISSUE TITLE
onClose not executed on v6.0.4

### ISSUE THREAD

**Issue by AdrienLemaire** [fkhadra/react-toastify#476]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
onOpen works.
onClose doesn't.

**What is the expected behavior?**
onClose callback should be executed when the toast closes

**Comment by fkhadra** [comment]
The issue seems related to the new version of react-transition-group. My tests didn't catch it because react-transition-group is mocked. Thanks for reporting the issue
