### ISSUE TITLE
Documents is disabled?

### ISSUE THREAD

**Issue by theMasix** [fkhadra/react-toastify#482]
Hello. I can't find any documentation at [Documentation](https://fkhadra.github.io/react-toastify/introduction).
Why the documentation is disabled/removed?

**Comment by fkhadra** [comment]
Hey should be a cache issue. Work fine for me. Can you try with a private tab ?

**Comment by theMasix** [comment]
@fkhadra OMG man. Yeah it was a cache issue. Thanks.
