### ISSUE TITLE
Recreate Toast after hiding using toastId

### ISSUE THREAD

**Issue by theMasix** [fkhadra/react-toastify#483]
Hello. Thanks for great library.

I have an issue and don't know how to fix it.
I assumed that the ```toastId``` prevent toast to being duplicate while there is available toast currently.
But I took some tests and understood the ```toastId``` prevent duplicate toast even the previous toast which has same ```toastId``` isn't be shown currently.
So I wanna prevent duplication only if there is an available toast and if there isn't, I wanna show it again!
how could I do it?
My ```toastId```s are some numbers.(200, 201 etc)

**Comment by fkhadra** [comment]
Hey thank you.

You should be able to reuse the same toast id. Could you provide a [codesanbodx](https://codesandbox.io/index2) witht the issue ?

**Comment by gajjarnirmal0** [comment]
I have provided sample code [codesandbox](https://codesandbox.io/s/react-toastify-l1jmx?file=/src/app/components/auth/Login.js:2561-2622). 

When you login (admin, adm) and press `enter` it creates notification with "Internal Server Error.". 
But this works sometimes and sometimes it doesn't.

Also check console.log on `login.js:96` logs every time
`
console.log("MAIN_ERROR_MESSAGE", this.props.errors.message);
`

As per above discussion the notification should be shown again when notification with same `toastId` disappears.

**Comment by fkhadra** [comment]
It looks like there is a race condition somewhere.
