### ISSUE TITLE
Toaster disappears immediately when used with redirection using router.push

### ISSUE THREAD

**Issue by pravin7891** [fkhadra/react-toastify#485]
In successful response in Creating a post, need to show Toaster and simultaneously need to redirect to list page. Both works with limitation.

Whats happening: Toaster does not retain after redirect, it immediately disappear.

Expected: Toaster must be there even after redirect.

**Comment by fkhadra** [comment]
You should put the `ToastContainer` at the top of your app:

```js
<>
<Router>
<OtherComponent />
</Router>
<ToastContainer />
</>
```

**Comment by moiz-frost** [comment]
> You should put the `ToastContainer` at the top of your app:
> 
> ```js
> <>
> <Router>
> <OtherComponent />
> </Router>
> <ToastContainer />
> </>
> ```

This doesn't seem to fix the problem. I tested this by moving the toast container outside of <Switch> component and then also tested it by moving it outside <BrowserRouter>.

Whats <Router> here?
