### ISSUE TITLE
onClose delays statement called when after closing

### ISSUE THREAD

**Issue by mtadesse** [fkhadra/react-toastify#487]
I have an onClose function to call changeColor. It appears there is a delay before it changes the color.

toastClosed(){
	const myElement = document.getElementById("cool-button");

	if (myElement) {
		myElement.style.backgroundColor = "red"
	}
}     

componentDidUpdate() {   
    toast("I'm a cool toaster", {
      onClose: () => {
        this.toastClosed();
      },
    });
}

I expect the toast to close and and button to turn red. Instead the button turns red after about 1-2 second delay. Thank you

**Comment by fkhadra** [comment]
I'm not sure to understand what is the issue. Could you share a [codesanbox](https://codesandbox.io/index2)  with the issue?
