### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by shaunaas** [fkhadra/react-toastify#489]
What happened to the docs? everything now points to the demo.

**Comment by fkhadra** [comment]
Hey @shaunaas,

Try to  access from a private tab. I think the service worker of the old documentation is messing the cache. https://fkhadra.github.io/react-toastify/introduction/

**Comment by shaunaas** [comment]
Hey thanks for the quick response. That link sends me to the demo. I vaguely remember the docs listing a programatic way to close all toasts.. but i don't remember what it was.

**Comment by fkhadra** [comment]
YW! Are you talking about that part https://fkhadra.github.io/react-toastify/remove-toast

**Comment by shaunaas** [comment]
Yes, that looks like it! none of these urls are routing me anywhere but the demo. Hopefully attaching these images works. Thanks for your help.

<img width="1684" alt="Screen Shot 2020-06-04 at 10 50 33 AM" src="https://user-images.githubusercontent.com/727261/83772704-a93b0280-a651-11ea-961d-8199692f1224.png">
<img width="1680" alt="Screen Shot 2020-06-04 at 10 51 17 AM" src="https://user-images.githubusercontent.com/727261/83772720-acce8980-a651-11ea-9631-b3e9cd5390e0.png">

**Comment by shaunaas** [comment]
Oh.. i see.. private/incognito. Thanks!
