### ISSUE TITLE
How can I programatically pause all open toasts?

### ISSUE THREAD

**Issue by coltenkrauter** [fkhadra/react-toastify#491]
How can I programmatically pause all open toasts? I know that it is happening when the window loses focus, but is there a way I can trigger this functionality myself?

For example, I want to make a simple HTML element that, when hovered, will pause all of the active toasts.

<div className='pauseEverything' onMouseover='triggerPause()' onMouseout='resumeEverything()'>
</div>

**Comment by fkhadra** [comment]
Hey @coltenkrauter,

Maybe you can try to call `window.blur()`. Let me know if it works :)
