### ISSUE TITLE
not showing toast component in nextjs

### ISSUE THREAD

**Issue by ahmetbcakici** [fkhadra/react-toastify#493]
im using nextjs and installed the package in the project, im using right commands but when i call notify() function there is no any toast

i checked some issues opened before but they were not useful for me

**Comment by mattcarlotta** [comment]
Works fine: https://github.com/mattcarlotta/basic-toast

1.) `cd ~/Dekstop && git clone git@github.com:mattcarlotta/basic-toast.git`
2.) `yarn` or `npm i`
3.) `yarn dev` or `npm run dev`

**Comment by ahmetbcakici** [comment]
thank you so much @mattcarlotta
