### ISSUE TITLE
How to test toastify with react-testing, react-test-renderer and Jest

### ISSUE THREAD

**Issue by rohan-naik** [fkhadra/react-toastify#496]
Hello,
I've made a common component sort of thing for Rendering the toast.
This is what it returns.

```
<>
     {toast.error(displayToast,{
           hideProgressBar: hideProgressBar,
          position: position,
          closeOnClick:closeOnClick,
          draggable:draggable
     })}
     <ToastContainer/>
</>
```

I'm trying to write test cases for the above snippet where I just run the method that triggers the Toast 
### e.g:- Toast() will trigger the above function.

I'm testing it using ReactTestUtils and jest .

The test that I have written is :

```
describe('Notification', () => {
    it('should render Default Notification', () => {
        const result = Toast({displayContent:{text:'Without ProgressBar'},notifyProps:{ hideProgressBar:true },type:'default'})
        const tree = renderer.create(result);
        console.log(tree.toJSON());
    })
})
```

and when I try console log the **tree.toJSON()** this is what it returns

```
[
      'qcwt2sybdd',
      {
        type: 'div',
        props: { className: 'Toastify', id: undefined },
        children: null
      }
    ]
```

How do I test what is being rendered in the toast? Or what is the text that toast renders?

**Comment by fkhadra** [comment]
Hey @rohan-naik , you can have a look at https://github.com/fkhadra/react-toastify/blob/master/test/core/toast.test.tsx#L200
