### ISSUE TITLE
Update a toast in useEffect

### ISSUE THREAD

**Issue by muscaiu** [fkhadra/react-toastify#497]
Hello, i'm working on a React-Electron app and want to use react-toastify to show that the app has downloaded an update.

Inside the Root i added this useEffect, but it won't update the `🦄 Update available` toast.

I also made a  [Codesandbox Example](https://codesandbox.io/s/toasterupdate-kcs67?file=/src/index.js) 

Any idea why it doesn't update the toast?

```
  useEffect(() => {
    console.log('useEffect AutoUpdater');

    ipcRenderer.on('update_available', () => {
      toast.success(`🦄 Update available`, {
        toastId: 'update',
        autoClose: false,
        hideProgressBar: false,
      });
    });

      ipcRenderer.on('download_progress', (event, percentage) => {
        console.log('percentage:', percentage); // this works
        toast.update('update', {
          render: `🦄 Downloading update  ${percentage / 100}`,
          progress: percentage / 100,
          autoClose: false,
        });
      });

  }, []);
```

**Comment by fkhadra** [comment]
can you share a repository with the issue ?
