### ISSUE TITLE
Feature: An option to create a new toast if given update ID doesn't exist

### ISSUE THREAD

**Issue by meness** [fkhadra/react-toastify#499]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

`toast.update()` doesn't create a new toast if the given ID as the first param doesn't exist.

**What is the expected behavior?**

Sometimes we need to update an existing toast, but if it doesn't exist create a new one because User should be notified anyway.

There are two workarounds for this:
- To prevent closing the toast, but it doesn't feel good at all
- Check if the toast exists programmatically using `isActive()`, but it can be done natively as well :)

**Comment by fkhadra** [comment]
Hey @meness,

This is by design.  I'll think about it.

**Comment by fkhadra** [comment]
Hey @meness,

I've decided not to implement this feature. As you said, you can check if a toast `isActive` and do the necessary. 

Of course, I could do that in the library itself but from an API point of view, this can be confusing. Also, it would introduce a breaking change for something that is not expected by everyone.

**Comment by mohammad-a-immam** [comment]
Could be a useful feature and lead to much cleaner code :(
