### ISSUE TITLE
Question: is that possible to put a "Cancel" or "retry" button inside the toaster ?

### ISSUE THREAD

**Issue by Aarbel** [fkhadra/react-toastify#503]
![image](https://user-images.githubusercontent.com/25119847/86096780-050f7480-bab4-11ea-81b9-b56671a0c4ab.png)

Most toasters should include a Cancel action to allow users to go back from what they've done.

What is the best way to do it ? Do you have an example about it ?

Thanks a lot.

**Comment by Aarbel** [comment]
@ghusse @jgoux

**Comment by fkhadra** [comment]
Hey,
The process is described here https://fkhadra.github.io/react-toastify/add-an-undo-action-to-a-toast/. The example is an embeded codesanbox
