### ISSUE TITLE
How do you use useToastContainer?

### ISSUE THREAD

**Issue by stoplion** [fkhadra/react-toastify#505]
I'm trying to create a custom Toast using Tailwind css. 
It looks like `react-toastify` exposes `useToastContainer` for the purpose.
How do you use useToastContainer? Thanks.

**Comment by agcty** [comment]
I need this too but the documentation for this hasn't been updated in some months.

**Comment by IzakJackson** [comment]
Anyone managed to figure this out?

**Comment by fkhadra** [comment]
Sorry guys for the delay. The thing is that I'm working on several projects at the same time. I don't know when I'll be able to free some time(full-time jobs + covid + kids 😭).
I can suggest that you look at the source right now to see how it's used internally. 
With a step back, I'm not satisfied with the implementation, that's why I'm a bit reluctant to document it.

**Comment by IzakJackson** [comment]
No problem, it's completely understandable 😊

I'll have a look through the source code. Thanks!

**Comment by osamajandali** [comment]
@fkhadra Can I work on the documentation for `useToastContainer` as well as `useToast` ?

**Comment by Martinnord** [comment]
@fkhadra Are PRs about updating the documentations about useToast and useToastContainer welcome?

**Comment by agcty** [comment]
To be honest, I just use https://react-hot-toast.com/ nowadays, it's docs are superb and using the toast with custom styling works out of the box.

**Comment by fkhadra** [comment]
Hey @Martinnord, it would be awesome.

**Comment by fkhadra** [comment]
@agcty react-hot-toast is a really cool library. 

React-toastify provides more features just to name a few of them
- custom animation out of the box (even easier with the latest version)
- drag and drop
- controlled progress bar

Is react-toastify better than react-hot-toast? I don't think so. Open source is about diversity, use what works the best for you.

**Comment by Martinnord** [comment]
Okey cool. I've always wanted to contribute to OS. This could be a great start. Will try to submit a PR this weekend.

**Comment by shehan-mark** [comment]
Is there any update on this? I've looked through the current implementation of these two hooks. But I don't think we can do much using these hooks.

**Comment by fkhadra** [comment]
`useToastContainer` has been removed since the latest release (v11), it's explained here https://github.com/fkhadra/react-toastify/releases/tag/v11.0.0

**Comment by amarant** [comment]
Please bring back useToastContainer and useToast, it was fine, I can't even use them with direct import as their symbol are all mangled now.
