### ISSUE TITLE
Adding <ToastContainer /> fails with an error.

### ISSUE THREAD

**Issue by harsh-98** [fkhadra/react-toastify#509]
** Report a *bug* **

**What is the current behavior?**
<img width="822" alt="Screenshot 2020-07-26 at 3 44 02 PM" src="https://user-images.githubusercontent.com/23700929/88476753-97daec00-cf58-11ea-90a1-3d44d1bbb552.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
It should render

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Mac Os: Darwin Kernel Version 18.7.0
"react": ^16.6.3

**Comment by fkhadra** [comment]
Hey @harsh-98, you need to upgrade to React 16.8 at least.
