### ISSUE TITLE
Hold off showing toast until user is no longer idle

### ISSUE THREAD

**Issue by niksosf** [fkhadra/react-toastify#51]
Hi there, is there a plan to hold off the toast until the user moves its mouse if the window is already the foremost one or until the user brings the window back to the foreground?

**Comment by fkhadra** [comment]
hey sounds like a really nice feature. I will check how I can implement it. 
Thanks for the idea btw !

**Comment by niksosf** [comment]
Let me know if there's something/anything I can help!

**Comment by fkhadra** [comment]
Yep thank you 😄

**Comment by fkhadra** [comment]
Hey @niksosf,

The toast will pause when the page is not visible. I'm using the [page visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API).

I'm not tracking if the user if afk for the moment but I will probably implement it for the next release.

**Comment by niksosf** [comment]
hey @fkhadra,
That was awesome, I think the page visibility api would take care of a lot of the cases. Thanks for this package and all the work on it!
