### ISSUE TITLE
[FEATURE REQUEST] Config specify swipe to close direction

### ISSUE THREAD

**Issue by JakubKoralewski** [fkhadra/react-toastify#512]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

You can only swipe horizontally, left and right to close the toast.

**What is the expected behavior?**

It would be nice to be able to still have horizontal by default to not make any breaking changes, but still allow to pass an option for the swipe to be vertical.

**Comment by jerrybuks** [comment]
can I take on this @fkhadra?

**Comment by fkhadra** [comment]
Hey @jerrybuks,

Please do. I don't hesitate if you need some guidance.

**Comment by jerrybuks** [comment]
Okay, will give it a shot and let send in my questions when I need guidance

**Comment by erikujczo** [comment]
@fkhadra @jerrybuks Hey, I would like to take care of this issue.

**Comment by denydavy** [comment]
I've got a PR for this feature ready to be sent @fkhadra. I use your library in production and I really need this feature ASAP :)
