### ISSUE TITLE
[POLL] Would you like to have react-toastify ported to react-native ?

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#515]
[![](https://api.gh-polls.com/poll/01EF07CG6KAE8CP7ABC4RR889Q/Yes)](https://api.gh-polls.com/poll/01EF07CG6KAE8CP7ABC4RR889Q/Yes/vote)
[![](https://api.gh-polls.com/poll/01EF07CG6KAE8CP7ABC4RR889Q/No)](https://api.gh-polls.com/poll/01EF07CG6KAE8CP7ABC4RR889Q/No/vote)

![toastify-native](https://user-images.githubusercontent.com/5574267/89464846-655b9b00-d771-11ea-82df-652e2e0bd231.gif)

**Comment by fkhadra** [comment]
thanks for the feedback. I'll try to free time for this

**Comment by Abdoulrasheed** [comment]
Any update on this?

**Comment by kostas2231** [comment]
Does it work with react-native projects?

**Comment by seba9999** [comment]
Does this repo belongs to you ? https://github.com/zahidalidev/toastify-react-native

What are your thoughts ?
