### ISSUE TITLE
[HELP WANTED] Position toast in the center of the screen

### ISSUE THREAD

**Issue by burhanuday** [fkhadra/react-toastify#516]
**What is the current behavior?**
Toasts can only be positioned in the corners or top or bottom of the screen. I want to position toasts in the center of the screen, like toast notifications in mobile phones.

There is no available positioning option for doing so

**What is the expected behavior?**
An option to position the toast in the center of the screen. Centered vertically and horizontally

**Comment by fkhadra** [comment]
Hello, 

You can center it as well: https://fkhadra.github.io/react-toastify/positioning-toast/

**Comment by kkak10** [comment]
@fkhadra how can i it? position option is not have center-center..

**Comment by sunviwo** [comment]
@fkhadra how to center a toast ?
