### ISSUE TITLE
öhm, where is the documentation? 

### ISSUE THREAD

**Issue by zilahir** [fkhadra/react-toastify#519]
This might be a bit odd, but seriously, where it is? I can only get to the demo page.

**Comment by fkhadra** [comment]
Hello,

I think this is related to a cache issue caused by the service worker. May I ask you to clear the cache for the domain fkhadra.github.io or you can visit https://fkhadra.github.io/react-toastify/introduction/ in a private tab

**Comment by zilahir** [comment]
hehh :) indeed, private tab solved the issue. odd :) 

but thanks!
