### ISSUE TITLE
Error in DefaultTransition.js

### ISSUE THREAD

**Issue by pratikborsadiya** [fkhadra/react-toastify#52]
There is an error while running webpack in production mode `webpack -p` when using react-toastify. 

react-toastify version
```
+-- react-toastify@2.1.0 
  `-- react-transition-group@2.2.1 
```

Webpack Version: webpack 3.6.0

```
ERROR in ./node_modules/react-toastify/lib/DefaultTransition.js
Module not found: Error: Can't resolve 'react-transition-group/Transition' in '/home/pratik/Projects/watercart/node_modules/react-toastify/lib'
 @ ./node_modules/react-toastify/lib/DefaultTransition.js 13:18-62
 @ ./node_modules/react-toastify/lib/ToastContainer.js
 @ ./node_modules/react-toastify/lib/index.js
 @ ./client/admin/admin-app.js
 @ ./client/admin/admin.js
```

**Comment by fkhadra** [comment]
Hello,

Did you had an old version of react-transition-group installed previously ?

**Comment by pratikborsadiya** [comment]
No it's a fresh npm install

**Comment by fkhadra** [comment]
Indeed. But it's working on development right ?

**Comment by pratikborsadiya** [comment]
We are using npm and it's not working in devlopment either.

**Comment by pratikborsadiya** [comment]
Is there a way except manually installing `react-transition-group`.

**Comment by fkhadra** [comment]
You could try to use the react-toastify v2.0.0 so you won't have to do manual changes. 
The v2.1 is tested with enzyme 3, react16 and provide custom animation.

The other solution would be to use symlinks

**Comment by pratikborsadiya** [comment]
I have downgraded the version to `2.0.0` but the error is sill there.

**Comment by fkhadra** [comment]
Damn it. You will have to use symlink or replace ```react-addons-css-transition-group``` by ```react-transition-group``` since ```react-addons-css-transition-group``` is deprecated.

**Comment by pratikborsadiya** [comment]
The error is gone in `2.0.0` It was `^` in package which was installing `2.1.0`, I have replaced it with `~` and version `2.0.0` is working fine.

Thanks for the help.

**Comment by fkhadra** [comment]
Awesome !

**Comment by wesharehoodies** [comment]
This issue still exists.

**Comment by fkhadra** [comment]
Hello @wesharehoodies,

Could you give the version of react-toastify you are using?
Are you upgrading or is it a fresh install.

Thanks

**Comment by wesharehoodies** [comment]
`"react-toastify": "^3.2.2",`

It's a fresh install

**Comment by wesharehoodies** [comment]
I removed `react-transition-group` and replaced it with `react-addons-css-transition-group` and it works.

Both packages were the latest.

**Comment by hyperh** [comment]
Same issue.

I dont have `react-transition-group` in my npm dependencies. I already have `react-addons-css-transition-group` in my npm dependencies.
