### ISSUE TITLE
How I can use z-index

### ISSUE THREAD

**Issue by christiantigre** [fkhadra/react-toastify#520]
**How I can use z-indez *bug*?**

**Y try z-index: 99999;**

```
.Toastify {
    position: absolute;
    z-index: 999999;
}
```

**But dont result**

![toast](https://user-images.githubusercontent.com/17419095/90262240-ac056100-de13-11ea-9140-440755bf1891.png)

**Comment by mateushnsoares** [comment]
umm try to add to this bar a `z-index: 3` and to Toast a `z-index: 5;`
