### ISSUE TITLE
Question: Why does toast.dismiss() return void | false?

### ISSUE THREAD

**Issue by insuusvenerati** [fkhadra/react-toastify#522]
Possibly a feature request. Clarification in the docs.

**What is the current behavior?**
`toast.dismiss()` returns `false | void` 

## To repro:
- Create a CRA Typescript project
- Setup eslint with `eslint --init` and choose typescript
- Use `useEffect` to load a toast with deps
```typescript
useEffect(() => {
  loading
    ? toast("loading...", { position: "bottom-right" })
     : toast(error && error?.message, { position: "bottom-right" });
  return () => toast.dismiss();
}, [loading, error]);
```
- Use `toast.dismiss()` as a returned cleanup function
  `return () => toast.dismiss()` 

Eslint will complain `Type 'false | void' is not assignable to type 'void | undefined'.` unless you cast the function as `void`

**What is the expected behavior?**
`toast.dismiss()` returns void.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.13.1
Typescript 4.0.2
React Toastify 6.0.8

**Comment by insuusvenerati** [comment]
I wasn't able to use Codesandbox because I didn't know how to implement eslint for typescript. Sorry about that.

**Comment by fkhadra** [comment]
Hey @insuusvenerati,

`toast.dismiss` return `false` if it was not able to remove a notification and `void` if it succeded. 

You don't need to cast it at all. Simply surround your cleanup function with curly brace:
```js
return () => { toast.dismiss(); }
```
Hope this help

**Comment by insuusvenerati** [comment]
It does thank you :)
