### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by tbntdima** [fkhadra/react-toastify#524]
[https://fkhadra.github.io/react-toastify/how-to-style](https://fkhadra.github.io/react-toastify/how-to-style) 
It says `import 'react-toastify/dist/ReactToastify.minimal.css';` when it should be `import 'react-toastify/dist/ReactToastify.min.css';`

**Comment by KarenOk** [comment]
@fkhadra  I would like to fix this.
