### ISSUE TITLE
styles supplied to toast does not override defaults.

### ISSUE THREAD

**Issue by m-alzaki** [fkhadra/react-toastify#532]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After applying  css styles to the toast it does not override the default one.

**Steps to reproduce:**
1-  import `ToastContainer` and toastify style from `react-toastify/dist/ReactToastify.css`
2- Applied custom styles using `glomar` to `className` and `progressClassName` of`toast options` when calling `toast` function.

[code sandbox demo](https://codesandbox.io/s/react-toastify-styling-rf4kb)

**What is the expected behavior?**
To override default styles of the supplied classes.

**Comment by fkhadra** [comment]
Hey @m-alzaki,

Thank you for providing a codesanbox. With glamor you need to call `toString` to get the css className generated
![Screen Shot 2020-10-08 at 8 59 05 PM](https://user-images.githubusercontent.com/5574267/95501917-524f8c00-09a9-11eb-982b-0113651b9070.png)

The glamor library is not maintained anymore. You can find more details on how to style here https://fkhadra.github.io/react-toastify/how-to-style/
