### ISSUE TITLE
Inline styles passed to toast function disappear after a second

### ISSUE THREAD

**Issue by thomasjm** [fkhadra/react-toastify#536]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

If you pass inline styles to `toast`, they are present when the popup first appears but then they disappear within a second or so. I.e. something like

```javascript
toast("Wow so easy!", {
  style: {
    backgroundColor: "red",
    color: "yellow"
  }
});
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Click the button here: https://codesandbox.io/s/stupefied-bogdan-lqtik

**What is the expected behavior?**

The styles should not disappear.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

My repro is on React 17.0. I don't know if it ever worked

**Comment by belfz** [comment]
I've noticed the same bug,
