### ISSUE TITLE
Option to Replace Progress bar with Fade in and Fade out

### ISSUE THREAD

**Issue by dhirendrarathod2000** [fkhadra/react-toastify#54]
Is there anyway we can replace progress bar with fade out effect?

For my usage i want to fade out the toast slowly in the given time.
Is there any way to do it?

Thanks
D

**Comment by fkhadra** [comment]
I have an idea how to do it. But I won't be able to pause the animation on hover with the current implementation.

**Comment by dhirendrarathod2000** [comment]
Can you please share it?

**Comment by fkhadra** [comment]
Hello @dhirendrarathod2000,

Sorry for the late reply. Here the example, don't if it's what you are looking for
[fade out demo](https://codesandbox.io/s/ll0r2qmm37)

**Comment by dhirendrarathod2000** [comment]
@fkhadra 
thanks for that
