### ISSUE TITLE
pauseOnFocusLoss is not applied to windows already unfocused.

### ISSUE THREAD

**Issue by AdrienLemaire** [fkhadra/react-toastify#541]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a notification is triggered, already unfocused windows will see the notification play.
Receiving notifications while not already focusing the page can happen with websocket subscriptions for example.
[video example](https://www.youtube.com/watch?v=RWsRDRfASTE)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Here you go. Please unfocus the window within 3 secs after opening the page
https://codesandbox.io/s/cocky-keldysh-6yc7o?file=/src/App.js

**What is the expected behavior?**
Notifications should be paused until the window gets focused

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I believe the bug affects all versions and browsers, but didn't verify.
Using react concurrent and react toastify 6.1.0, and reproduced the bug with codesandbox using react 17

**Comment by fkhadra** [comment]
Hello @AdrienLemaire this will be fixed in the next release. Thanks for reporting
