### ISSUE TITLE
Notification stuck on dragging

### ISSUE THREAD

**Issue by sergeycw** [fkhadra/react-toastify#543]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
mouseup event doesn't fire when mousemove default event happens

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

1. click on the edge of the notification (mousedown whithout mouseup)
2. start dragging the notification (you need the case when all window is dragging)
3. mouse up

please see the demo

![bug](https://user-images.githubusercontent.com/36540337/99660928-1f061f80-2a74-11eb-96af-8188b099aa4a.gif)

**What is the expected behavior?**

expected result: notification is mouse free
actual result: the notification is steel controlled by mouse

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Chrome: latest
React: latest

**Comment by fkhadra** [comment]
Hey @sergeycw , your PR with the fix has been merged
