### ISSUE TITLE
Show only last toast

### ISSUE THREAD

**Issue by TeplyyMaksim** [fkhadra/react-toastify#545]
I am curious about are there an ability to show only one last toast and close others without using dismiss or other additional methods.

Library has huge amount of interesting features dedicated to different tasks. For my case I need to show only one and only last toast. Is there an ability to do it without calling dismiss, clearQueue or other great methods?

**Comment by fkhadra** [comment]
Hello @TeplyyMaksim,

There is no bult-in way to do that. This needs to be implemented in user land, sorry for that.
