### ISSUE TITLE
Support react 17

### ISSUE THREAD

**Issue by fcollonval** [fkhadra/react-toastify#546]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

The package does not support React 17. The dependency `^16.13.1 || ^17.0.0` should work as React 17 is almost transparent and did not introduce breaking changes https://reactjs.org/blog/2020/10/20/react-v17.html

**What is the expected behavior?**

The package does support React 17

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by fkhadra** [comment]
Hello,

It does work with react 17. https://codesandbox.io/s/ancient-currying-9ykpc?file=/src/App.js

**Comment by fcollonval** [comment]
Thanks for the quick reply and this awesome library!
