### ISSUE TITLE
How to position vertically centered?

### ISSUE THREAD

**Issue by willyrk1** [fkhadra/react-toastify#552]
**Do you want to request a *feature* or report a *bug*?**
TBD

**What is the current behavior?**
Per https://github.com/fkhadra/react-toastify/issues/516, toasts cannot be centered _vertically_, only horizontally. That issue was closed with just a link but the given link does not (currently) explain how to center a toast vertically.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Ability to center toasts vertically.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All known versions to my knowledge.

**Comment by fkhadra** [comment]
Hello @willyrk1, by vertically, you mean to center the toasts at the center of the screen as below?
<img width="946" alt="Screen Shot 2020-12-21 at 10 48 29 PM" src="https://user-images.githubusercontent.com/5574267/102825236-a7af0d00-43de-11eb-8df5-7f7923d58279.png">
 
In that case, there is no built-in way yet. I'll probably add it to the next release. Until then, one solution is to position the toast `top-center` and add the following css class to override the default style. 

```css
.Toastify__toast-container--top-center {
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
``` 

> I suggest using `zoom` or `flip` animation with that position.

**Comment by Duoquote** [comment]
Is this feature added?
