### ISSUE TITLE
Inject buttons in the toast message(Feature Request)

### ISSUE THREAD

**Issue by dhirendrarathod2000** [fkhadra/react-toastify#56]
First of all I want to say thank you for this package it is really good and simple to use.

Next This is more a feature request then an issue.
I want to inject buttons in the toast.
So if you can provide a way to inject React Components/array of buttons/HTML in to the toast it will be awesome.

The use case could be like each type of toast can be having different set of buttons
so putting it in the container may not be possible but may be options for the toast while calling it can handle it.

I guess from all other toast npm that is the only feature it is missing 😉

**Comment by fkhadra** [comment]
Hey @dhirendrarathod2000,

In case you miss it, you can already provide a custom close button, [check the example.](https://codesandbox.io/s/qzz1rojo84)

Is that what you are looking for ?

Thanks

**Comment by dhirendrarathod2000** [comment]
Actually I am looking to put buttons in it...
Like got it or undo...
Something like this...
![52cf93c5-cf38-4318-b7a1-3a1ff2849fac](https://user-images.githubusercontent.com/1930681/31497437-1a2e8a58-af2d-11e7-9f25-671e548109ad.jpeg)

**Comment by fkhadra** [comment]
Ok I understand now. Simply pass a react component instead of text as [follow](https://codesandbox.io/s/14ynmk7377)

**Comment by dhirendrarathod2000** [comment]
👍
