### ISSUE TITLE
After latest Update close Icon having Alignment issue

### ISSUE THREAD

**Issue by mskian** [fkhadra/react-toastify#562]
Updated to Latest Version `7.0.2`  close Icon having Alignment issue
I am using it with Bulma CSS
No issue with the Previous Version `6.2.0`

![gttstv](https://user-images.githubusercontent.com/10300271/106346199-46326600-62db-11eb-92d9-1f25b695922b.jpg)

**Comment by fkhadra** [comment]
Hello @mskian,

The codesanbox below uses bulma without any issue.
[![Edit relaxed-shadow-nwcn4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-shadow-nwcn4?fontsize=14&hidenavigation=1&theme=dark)

If you can provide a reproduction I could help
