### ISSUE TITLE
autoClose and closeOnClick not working in version 7 of react-toastify

### ISSUE THREAD

**Issue by egardner2019** [fkhadra/react-toastify#564]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The toast is no longer closing when using autoClose or closeOnClick after updating to version 7.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
After clicking on a button that displays the toast, clicking on the toast does not cause it to be removed from the page. And it doesn't close automatically after the set time.
https://codesandbox.io/s/react-toastifyissue-u5cdt

**What is the expected behavior?**
The toast should close when clicked and close automatically after the set amount of time.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using React version 17.0.1, but I have not changed the version that I am using. This previously worked when using this version of React. I am using Google Chrome on macOS, but I believe this is an issue across different browser and operating systems.

**Comment by fkhadra** [comment]
Hey @egardner2019,

You forgot to import the default stylesheet as well. Here is a working example.

[![Edit react-toastify_issue (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-toastifyissue-forked-92r5j?fontsize=14&hidenavigation=1&theme=dark)

**Comment by egardner2019** [comment]
Oh! Thank you so much!
