### ISSUE TITLE
webkit-transform error reported by VSCode

### ISSUE THREAD

**Issue by cseas** [fkhadra/react-toastify#567]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
VSCode shows red lines in the third line of `ReactToastify.css` with the following message:
![Selection_017](https://user-images.githubusercontent.com/29686866/107870529-28f6bd80-6ebf-11eb-81ec-edf6cef7ec57.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install react-toastify in a project
2. Navigate to `node_modules/react-toastify/dist/ReactToastify.css` and hover over the red swiggly line indicating a problem in the code.

**What is the expected behavior?**
No red lines/errors reported

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
    "react-toastify": "^6.1.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "^4.0.1",
    "typescript": "^4.1.3"

**Comment by fkhadra** [comment]
Hey @cseas, this is done due to a safari bug. https://github.com/fkhadra/react-toastify/pull/339 

I don't know if it's still relevant though.
