### ISSUE TITLE
How to pass props to a custom component in TypeScript

### ISSUE THREAD

**Issue by stanleyk** [fkhadra/react-toastify#568]
According to the [docs](https://fkhadra.github.io/react-toastify/render-what-you-want) I can create my own component and use it like this:

`toast(<Msg />)`

But when I create the component just like the docs suggest:

```
const Msg = ({ closeToast, toastProps }) => (
  <div>...</div>
)
```
I get the (pretty obvious) error: 

> TS2739: Type '{}' is missing the following properties from type '{ closeToast: any; toastProps: any; }': closeToast, toastProps

I can get it working by using the 

`toast(Msg)`

form, but how do I pass anything (like the actual text I want to show) to the component in such case?

Maybe I am missing something essential here, thanks for any help!

**Comment by Rafatcb** [comment]
This is more of a workaround than an answer, but I do it like this:

```jsx
function renderContent(text: string): JSX.Element {
  return <div><p>{text}</p></div>;
}

const content = renderContent('Ooops');
toast(content);
```

**Comment by stanleyk** [comment]
I thought of such a workaround too. But I want to be able to use the `toastProps` in my component too, for example to read the `toastProps.type` and style the component accordingly. I don't see a way to achieve that in such a workaround though.

**Comment by fkhadra** [comment]
@stanleyk does the following solve your issue ?

[![Edit toast-content-ts](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-euclid-3mtx4?fontsize=14&hidenavigation=1&theme=dark)

**Comment by stanleyk** [comment]
@fkhadra Yes, great, thank you!

For future readers (I noticed the CodeSandbox examples disappear after some time): Declaring the component props using the [Partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) utility type helps:

```
const Msg = ({ closeToast, toastProps }: Partial<ToastContentProps>) => {
  return (
    <div>
      Lorem ipsum dolor {toastProps?.position}
      <button>Retry</button>
      <button onClick={closeToast}>Close</button>
    </div>
  );
};
```

**Comment by fkhadra** [comment]
@stanleyk thanks for testing. I guess this should be added to the documentation.

**Comment by marc-at-brightnight** [comment]
> Just providing another implementation example as I was looking for this but I had to tweak it a bit.

That should 100% be added to the documentation, the documentation for the current TS example is impossible to follow for a real-world use case.
