### ISSUE TITLE
`closeToast` does not work

### ISSUE THREAD

**Issue by JesusTheHun** [fkhadra/react-toastify#569]
Here is a sample from the [doc](https://fkhadra.github.io/react-toastify/render-what-you-want), you can also try it on [codesandbox](https://codesandbox.io/s/strange-noyce-ii7yh?file=/src/App.js) : 

```js
import React from "react";
import { ToastContainer, toast } from "react-toastify";

const Msg = ({ closeToast, toastProps }) => (
  <div>
    Lorem ipsum dolor {toastProps.position}
    <button>Retry</button>
    <button onClick={closeToast}>Close</button>
  </div>
);

export default function App() {
  const displayMsg = () => {
    toast(<Msg />);
    // toast(Msg) would also work
  };

  return (
    <div>
      <button onClick={displayMsg}>Click me</button>
      <ToastContainer />
    </div>
  );
}
```

The toast should close when the __close button__ is clicked, but it's not. I tried in practice in my own code, it does not work either. 

```js
({ closeToast, toastProps }) => closeToast() // Broken
({ closeToast, toastProps }) => toastProps.closeToast() // Broken
({ closeToast, toastProps }) => toastProps.deleteToast() // Works, but there is no animation (it's expected I believe)
```

What's required to make this work ?

Versions : 
`react-toastify 7.0.3`
`react 17.0.1`

**Comment by JesusTheHun** [comment]
Does not work either :
```js
toast(props => <MyCustomToastComponent toastContentProps={props} type={type} title={content}  />, {
      autoClose: 1500,
    });
```
Nor :
```js
const toastId = toast(props => <Toast toastContentProps={props} type={type} title={content} simpleAction={'dismiss'} />);
setTimeout(() => {
  toast.dismiss(toastId);
}, 1500);
```

**Comment by fkhadra** [comment]
Hello @JesusTheHun ,

According to your codesanbox, the stylesheet is not imported. I forked you codesanbox  and added the stylesheet. It works as expected.

[![Edit vibrant-lumiere-5shso](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-lumiere-5shso?fontsize=14&hidenavigation=1&theme=dark)

**Comment by JesusTheHun** [comment]
Indeed it works with the css. So I understand that the all disparition thing is only based on the css animation, does it means the element is never removed from the queue ? or do you listen to the animation to dequeue the element at the end.

Since I use a fully custom toast, I just tried to import `import 'react-toastify/dist/ReactToastify.minimal.css';` but with this sheet it does not work.

**Comment by fkhadra** [comment]
Indeed, the lib listens to `onAnimatedEnd` event to remove the element from the queue. With the minimal stylesheet, the element is removed but after a delay. 
[![Edit autumn-frog-n5rj7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-frog-n5rj7?fontsize=14&hidenavigation=1&theme=dark)

Regarding your customization, isn't it something that can be done by overriding some existing classes?

**Comment by JesusTheHun** [comment]
I c/c'ed the css into my style sheet and I'm customizing it. Things gonna work out ! Thank you for your quick responses
