### ISSUE TITLE
Problems with testing toast.dismiss using react-testing-library

### ISSUE THREAD

**Issue by AriHrannar** [fkhadra/react-toastify#576]
**Do you want to request a *feature* or report a *bug*?**
Help testing with React-testing-library

**What is the current behavior?**

I am trying to write a test for toasting a message that doesnt go away by itself (closeButton={false}, autoClose={false}, closeOnClick={false}, draggable={false}) and the user has to explicitly dismiss the toast by clicking a button inside of the toast. This behaviour works fine normally, it just seems like the tests dont work

The test expects that the toast appears and then when the user clicks the "dismiss button", the toast is removed from the UI.

When I dont use fake timers, I can see the toast appearing, but clicking the "dismiss button" does not dismiss the toast. It fails in the `waitForElementToBeRemoved` function from React-testing-library. I tried increasing the timeout also but that doesnt seem to fix the issue.

When I use fake timers (from jest) I dont even see the toast appear. I have tried `jest.runAllTimers()` and `jest.advanceTimersByTime(1000)` but neither seem to work. Codesandbox fails with `jest.useFakeTimers is not a function`, which seems to be an issue on their part but I guess the test can be copied over to run locally to see that the toast does not appear. Running `debug()` from RTL also shows that the UI does not include any toast message - but I can see the toast container.

Am I doing something wrong here? I have looked at the tests in this project and tried to mimic them, but have not been successful
https://github.com/fkhadra/react-toastify/blob/cc011ea9f820d4282a0cbb211d3417afaf8cfb06/test/core/toast.test.tsx
https://github.com/fkhadra/react-toastify/blob/cc011ea9f820d4282a0cbb211d3417afaf8cfb06/test/components/ToastContainer.test.tsx

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/unruffled-dust-033f5

**What is the expected behavior?**

The tests from the CodeSandbox should run successfully, the toast should be visible in the UI and then when the user clicks "dismiss", it is removed from the UI.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I am running React 16 in my project, but the problem is also reproducible in React 17 (codesandbox uses that version).

**Comment by fkhadra** [comment]
Hey @AriHrannar,

You can have a look at this test https://github.com/fkhadra/react-toastify/blob/master/test/components/ToastContainer.test.tsx#L79-L101

The thing is that we also need to trigger the `animationEnd` event to complete the exit animation https://github.com/fkhadra/react-toastify/blob/master/test/components/ToastContainer.test.tsx#L97.

Hope this help

**Comment by AriHrannar** [comment]
@fkhadra thank you for the response

Its sadly still not working for me, ive updated the CodeSandbox above for the test that has no fake timers.

`jest.useFakeTimers()` doesnt work in CodeSandbox but I am running this test locally and the toast never appears after clicking the button that toasts

```javascript
jest.useFakeTimers()

it.only('should see toast message and be able to dismiss it', async () => {
   // I have the ToastContainer within this custom render so that its always there in all tests - thats why its not here
    render(
      <button
        onClick={() =>
          toast.info(
            <div>
              <p>Hello</p> <button onClick={() => toast.dismiss(23)}>Dismiss</button>
            </div>,
            { toastId: 23 }
          )
        }
      >
        Toast
      </button>
    )

    // Open toast
    userEvent.click(screen.getByRole('button', { name: 'Toast' }))

    act(() => {
      jest.runAllTimers()
    })

    // Should see Toast - Test fails here, the toast never appears
    expect(await screen.findByText('Hello')).toBeInTheDocument()

    // Close toast
    userEvent.click(screen.getByRole('button', { name: 'Dismiss' }))

    act(() => {
      jest.runAllTimers()
      fireEvent.animationEnd(screen.getByText('Hello').parentNode?.parentNode!)
      jest.runAllTimers()
    })

    // Wait for toast message to go away
    await waitForElementToBeRemoved(screen.queryByText('Hello'))

    expect(screen.queryByText('Hello')).not.toBeInTheDocument()
  })
```

![image](https://user-images.githubusercontent.com/6696198/111967082-e8aae080-8af7-11eb-8462-005410a7f9ec.png)

Am I misunderstanding something here? Any ideas whats wrong?

Could it have something to do with the version of `react-testing-library`? I am using v11 locally and it seems like v9 is used here?

**Comment by fkhadra** [comment]
@AriHrannar This is indeed really weird. I'm able to reproduce the issue locally. I'll check `react-testing-library` release notes. This is weird

**Comment by elGusto** [comment]
RTL has now support for fake timers working with async utils out of the box: [https://github.com/testing-library/react-testing-library/releases/tag/v10.4.0](https://github.com/testing-library/react-testing-library/releases/tag/v10.4.0)

So there is no more need to use `jest.useFakeTimers()` or `jest.runAllTimers()` if you use find:

```js
it("should display a notification", async () => {

    // Render the component with the toast container and trigger
    render(
      <ComponentWithToast />
    );

    // Fire event that triggers toast
    fireEvent.click(screen.getByRole("button", { name: /toast/i }));

    // This will pass
    expect(
      await screen.findByText("You cannot remove yourself from a pricount")
    ).toBeInTheDocument();
});
```

**Comment by Wraithraiser** [comment]
Hello @fkhadra, I have the same issue trying to test with RTL. Using the code above works fine to check the display of the toast but I can't check that the toast is being removed even using `waitForElementToBeRemoved` because it will timeout. I'm sorry to post in an issue that is closed, I can open a new issue about this problem or is it possible de reopen it ? Thank you.

**Comment by ImLunaHey** [comment]
sorry to bump this old thread. im hitting the similar issues. did anyone ever work out a solution? 🤔 

@alexandre-lim was there a follow up issue for this?
