### ISSUE TITLE
Active toast's counter

### ISSUE THREAD

**Issue by oswaldoacauan** [fkhadra/react-toastify#58]
It would be useful to know how many messages are being currently displayed so you can dynamically add a "Dismiss all".

**Comment by fkhadra** [comment]
hey @oswaldoacauan,

You could do that using the `onOpen` and `onClose` hooks as follow :

```javascript

class App extends React.Component {
  state = {
    toastCounter: 0
  };

  increment = () => {
    this.setState(state => ({ toastCounter: state.toastCounter + 1 }));
  };

  decrement = () => {
    this.setState(state => ({ toastCounter: state.toastCounter - 1 }));
  };

  noti = () => {
    toast("Hello", {
      onOpen: this.increment,
      onClose: this.decrement
    });
  };

  render() {
    return (
      <div>
        <h3>Toast Displayed: {this.state.toastCounter}</h3>
        <hr />
        <button onClick={this.noti}>Notify</button>
        <hr />
        <button onClick={() => toast.dismiss()} disabled={this.state.toastCounter === 0}>Dismiss ALL</button>
        <ToastContainer className="xxxx" />
      </div>
    );
  }
}
```

**Comment by Kalpan-Jasani** [comment]
How would we get the active toast ids?

Use case:
When the message is of a certain type (based on the title and the details), I do not want to display it if one toast which is equal is already "active" on the screen. This way, the user is not bombarded with 8 error messages of the same type. 

My way of solving this: For each tosat active, check the properties and if they match, do not display the toast.
