### ISSUE TITLE
Progress countdown stops on Mobile

### ISSUE THREAD

**Issue by mina-raina-choi** [fkhadra/react-toastify#580]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On mobile, it stops countdown when I attempt to dismiss toast but do not dismiss.
It works well on desktop. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://user-images.githubusercontent.com/28688788/111136107-b6adf180-85c0-11eb-8f4a-11bb47c0b8b1.mov

**What is the expected behavior?**
It restarts countdown

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by Nikhiladiga** [comment]
Works properly if pauseOnHover is set to false.

**Comment by minami-choi** [comment]
This error occurs when pauseOnHover is set to true.
