### ISSUE TITLE
Sound feature?

### ISSUE THREAD

**Issue by rrcdr** [fkhadra/react-toastify#581]
Is there a way to make a sound play with the notification?

**Comment by fkhadra** [comment]
Hey @rrcdr,

This should be doable.  

```js

const mySound = new Audio("path to my file or URL");

toast("Hello", {
      onOpen: () =>  mySound.play(),
      onClose: () => mySound.play()
})
```

https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio
