### ISSUE TITLE
Toastify works perfectly but it shows out of the visible area.

### ISSUE THREAD

**Issue by rodrigovilla** [fkhadra/react-toastify#585]
Hello guys,

Hope you guys are doing great. We've been using **react-toastify** in a production environment for almost 7 months: https://www.rooeda.com

It's a great library. I just spotted an inconvenient outcome in terms of UX, the Toast notification gets lost on top of the page. Please let me know if you there's a way we can we always keep the notifications showing in the visible area regardless of the height of the page.

Note: If we scroll-up where the notification is visible, then the component gets a fixed position as it should do all the time. 

Please let me know if you have a solution for this, looking forward to fix that issue / bug.

Thanks in advance,
Rodrigo

<img width="478" alt="toastify" src="https://user-images.githubusercontent.com/1043405/112789254-e7a71100-9019-11eb-844e-bd2e033c30d7.png">

**Comment by fkhadra** [comment]
Hey @rodrigovilla,

The `ToastContainer` uses a fixed position, so it should always be visible. Do you use an iframe or something similar for the visible area? If you could reproduce the issue on codesanbox that would be really helpful. 

https://user-images.githubusercontent.com/5574267/112794674-90c82880-9067-11eb-96d9-1d14025dbdfd.mov

**Comment by rodrigovilla** [comment]
Hey @fkhadra 

Thanks for your quick reply. I see it works perfect in your samples and documentation. We're not using an iframe, we are using a Design System by **IBM**: https://www.carbondesignsystem.com/guidelines/2x-grid/overview

I will check if I could reproduce the issue on **code-sandbox** but for now maybe you could get the idea by clicking 'Continuar' and resizing the window height and/or zooming-in: https://www.rooeda.com/forgotpass

Thanks again,
Rodrigo

**Comment by rodrigovilla** [comment]
Hey @fkhadra 

What's up again. Good news, the 'bug' was fixed by placing the component out of class="bx--content"

Now I just need to re-oder some things internally, probably I was using bad practices.

Thank you, excellent library. Have a good one!
Rodrigo

<img width="385" alt="bug" src="https://user-images.githubusercontent.com/1043405/112799896-2fcf2f00-902c-11eb-8d67-6522b3c6cb5b.png">

**Comment by rodrigovilla** [comment]
Hey guys,

It might help somebody in the future. I was mistakenly putting the **ToastContainer** component inside each class instead of only putting in the **App** component:

<img width="673" alt="Screen Shot 2021-03-30 at 1 03 14 AM" src="https://user-images.githubusercontent.com/1043405/112947348-ea763480-90f3-11eb-9426-eeaabe93b741.png">

Best regards,
Rodrigo
