### ISSUE TITLE
Invariant Violation: ToastContainer.render()

### ISSUE THREAD

**Issue by bardiaheshmati** [fkhadra/react-toastify#60]
I have two working version of my application, one is local host and one on aws ,
weirdly, notify function works fine on my local host by on the aws i get this error upon launch 

Invariant Violation: ToastContainer.render() ...

**Comment by jfsiebel** [comment]
Thats because on the last update the render is returning an Array which is only valid in React 16>.

Just fix the package version to 2.1.0 or update react.

**Comment by fkhadra** [comment]
hmm maybe it was not a good idea to return an array.

**Comment by Kepro** [comment]
@fkhadra, thanks for fixing #50 but for backward compatibility you need to wrap it to some <div>

**Comment by fkhadra** [comment]
I'll fix it now. I was a bit too optimistic.

**Comment by fkhadra** [comment]
Sorry for that change. It's fixed now.

**Comment by bardiaheshmati** [comment]
you're awesome
