### ISSUE TITLE
how to position to a specific position

### ISSUE THREAD

**Issue by sant527** [fkhadra/react-toastify#601]
**Do you want to request a *feature* or report a *bug*?**
request feature

**What is the current behavior?**
I can place at the bottom right

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I want to position the toast at the bottomright but with some offset from the bottom

example,.

![image](https://user-images.githubusercontent.com/6462531/119232020-3d42fa00-bb41-11eb-9f28-70f86a453318.png)

**Comment by fkhadra** [comment]
Hey @sant527,
You can override the css class as follow:
```css
.Toastify__toast-container--bottom-right {
   bottom: 20em;
}

```
