### ISSUE TITLE
Is there a way to add a button / link inside the toast message?

### ISSUE THREAD

**Issue by bharat787** [fkhadra/react-toastify#604]
I use the toast to display if an error has occurred and want to add a button to re-route the back user to the homepage in the toast itself. Is there a way to do so?

Thanks.

**Comment by imprfekt** [comment]
+1
can't find any reference to this in docs.
@bharat787 if you find a solution, please share it here. :)

**Comment by imprfekt** [comment]
@bharat787 you can pass React Node as an argument.
For example:
`toast(<span>This is a <a href="https://example.com">link</a></span>)`

**Comment by bharat787** [comment]
@imprfekt Thanks for the method, wasn't able to figure out this!

**Comment by imprfekt** [comment]
@bharat787 You're welcome, you can close the issue now. :)
