### ISSUE TITLE
Adding className to options does not have any affect on a toast style

### ISSUE THREAD

**Issue by Airomad** [fkhadra/react-toastify#61]
import style from './style.scss'
....
const options = {
  autoClose: 6000,
  hideProgressBar: false,
   position: toast.POSITION.TOP_LEFT,
  className: style.toast,
  pauseOnHover: true
};
toastID = toast('Test', options)
.... 
this not applying any changes. Toast shows with toastify-content--default style

react-toastify version: ^2.1.2

**Comment by fkhadra** [comment]
Hey @Airomad,

The `className` is merged with the default defined classNames.
