### ISSUE TITLE
Indeterminate or infinite progress bar

### ISSUE THREAD

**Issue by saravanabalagi** [fkhadra/react-toastify#615]
**Do you want to request a *feature* or report a *bug*?** 

Feature

**What is the current behavior?**

Currently we have determinate progress bar attached to the toast

**What is the expected behavior?**

![PuC7J](https://user-images.githubusercontent.com/8567893/124945986-8aeac780-e006-11eb-967a-533a9711e69d.gif)

Buffered requires two values, so can leave it out if that's too much.
Indeterminate behavior can be set using a flag though.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

N/A

**Comment by qasimmehdi** [comment]
+1

**Comment by vincentes** [comment]
+1

**Comment by AliRa22aq** [comment]
+1

**Comment by dejavu1987** [comment]
+1

**Comment by fkhadra** [comment]
Hey I've released a new major version, please look at https://fkhadra.github.io/react-toastify/how-to-style#custom-progress-bar for your use case. Don't forget to read the release note before upgrading 🙏🏽
