### ISSUE TITLE
How can we define custom types ?

### ISSUE THREAD

**Issue by AdrienLemaire** [fkhadra/react-toastify#617]
**Do you want to request a *feature* or report a *bug*?**
Feature or Question

**What is the current behavior?**
react-toastify makes 6 types of notification available
```ts
export declare type TypeOptions = 'info' | 'success' | 'warning' | 'error' | 'default' | 'dark';
```

**What is the expected behavior?**
I'd like to define a number of other types to show more notifications with different styles/options.

**Current strategy**
Please let me know if the current direction is correct or not.
Instead of adding more custom types, I'll add more containers with different toastClassName. Passing the correct container id to the toast should apply the desired style depending on its type.

**Comment by fkhadra** [comment]
Hey @AdrienLemaire, indeed using multiple containers is a way to solve your issue. I'll close the issue, don't hesitate if you have more questions
