### ISSUE TITLE
Example in "How to clear the waiting queue" is incomplete

### ISSUE THREAD

**Issue by AdrienLemaire** [fkhadra/react-toastify#619]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The [documentation](https://fkhadra.github.io/react-toastify/limit-the-number-of-toast-displayed#how-to-clear-the-waiting-queue) refers to creating a function `clearWaitingQueue`, but the function is never called anywhere.

**What is the expected behavior?**
See where the function is called to understand how to clear the waiting queue.

**Comment by AdrienLemaire** [comment]
Well, I must be tired ^^  The example just means that I need to call `toast.clearWaitingQueue()` from wherever I decide to clear it. 

But then I have a question.  I would like a queue of only 3 toasts, with new toasts replacing older ones in the queue.
Is it possible to do so with react-toastify ?

**Comment by xdebbie** [comment]
I get an error with this ```clearWaitingQueue``` as well.

```
Uncaught (in promise) TypeError: react_toastify__WEBPACK_IMPORTED_MODULE_15__.toast.clearWaitingQueue is not a function
```
