### ISSUE TITLE
Change notification position on mobile

### ISSUE THREAD

**Issue by hichemfantar** [fkhadra/react-toastify#620]
**Do you want to request a *feature* or report a *bug*?**
This is a feature request.

**What is the current behavior?**
Setting the notification position is the same for mobile and desktop.
On mobile I have a bottom navbar so the notification hides it.

**What is the expected behavior?**
I'd like to set the position on desktop to be bottom however on mobile I want it to be at the top.

A prop called "positionOnMobile" would be great. Should be the same as position but with a css breakpoint I guess.

**Comment by ekaradon** [comment]
Why not just conditionally set the position depending of the platform you are?

**Comment by fkhadra** [comment]
Hey @hichemfantar, as @ekaradon suggested you could adapt the position of the toast conditionally. For example this can be done using `matchMedia`.
```js
const isMobile = window.matchMedia('(max-width: 600px)');

toast("something", {
  position: isMobile ? "top-right" : "bottom-right" 
})

```

**Comment by zacharytyhacz** [comment]
```typescript
// useIsMobile.ts

import { useState, useEffect } from 'react'

export const useIsMobile = () => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    // @ts-ignore
    const userAgent = navigator.userAgent || navigator.vendor || window.opera;

    setIsMobile(/android|iphone|ipad|ipod|windows phone/i.test(userAgent));
  }, []);

  return isMobile;
}
```

```tsx
...

const RootApp = () => {
  const isMobile = useIsMobile()

  return (
    <AuthProvider>
      <ToastContainer position={isMobile ? "bottom-center" : "top-right"} />
      <Routes />
    </AuthProvider>
  )
}

const root = createRoot(container)
root.render(<RootApp />)
```
