### ISSUE TITLE
Translation strings not working with toasts?

### ISSUE THREAD

**Issue by JimmyBlundell** [fkhadra/react-toastify#621]
Possible feature, or just a misunderstanding on my part?

**What is the current behavior?**

I am using the formatjs library. We wrap our strings in components (or imperative api calls) and use that string as a predefined message. We eventually get an ID for that string, which maps to translations in different translation files.

**What is the expected behavior?**

I could do something like so:<br>
```
      .catch(error => {
        toast.error(
          intl.formatMessage({
            defaultMessage:
              "Failed to process card. An error occurred while processing",
            id: "gjk3RX"
          })
        );
```
and it would look for and display the translated message depending on my locale. However, it simply defaults to the string, and doesn't even look for the translation. Even if my locale is set to Portuguese, for which I have translations for, the toast still comes back as "Failed to process card. An error occurred while processing".

**Comment by fkhadra** [comment]
Hey @JimmyBlundell, are you 100% sure that the code below return the right string?
```js
intl.formatMessage({
            defaultMessage:
              "Failed to process card. An error occurred while processing",
            id: "gjk3RX"
          })
```
Adding a `console.log` right before the toast could help. The library itself does not touch the provided input. I'll close the issue by now. If you have a reproduciton I would be happy to help
