### ISSUE TITLE
Unable to pass in a React.Element[] to my toast?

### ISSUE THREAD

**Issue by JimmyBlundell** [fkhadra/react-toastify#622]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I have a pre-defined array and another element that I map that array onto to return several divs. I then throw that element into my toast, but nothing ever gets toasted. Is it possible to do this?
```
const testData = [
          { id: 1, name: "John Doe" },
          { id: 2, name: "Victor Wayne" },
          { id: 3, name: "Jane Doe" },
        ];

        const testElement: React.Element[] = testData.map((user) => (
          <div>{user.name}</div>
        ));


        toast.error(
          { testElement }
        );
```

**What is the expected behavior?**
Toast would pop up with the divs.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by fkhadra** [comment]
Hey @JimmyBlundell, it's supported. Just wrap your `testElement` with a fragment. See the example below
[![Edit exciting-sun-4yx3c](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-sun-4yx3c?fontsize=14&hidenavigation=1&theme=dark)
