### ISSUE TITLE
"The final argument passed to useEffect changed size between renders" thrown as Warning from toastify

### ISSUE THREAD

**Issue by usamedin** [fkhadra/react-toastify#625]
**Bug**

**Initial setup of react-toastify throws a warning**

```
export default function App({ children }: Props) {
  useEffect(() => {
    toast.info(<div>test</div>)
  })

  return (
    <div className="App">
      <ToastContainer
        position='top-right'
        closeOnClick
        pauseOnHover
        autoClose={5000}
        hideProgressBar={true}
        newestOnTop={true}
      />
      {children}
    </div>
  )
}
```

![image](https://user-images.githubusercontent.com/5623935/129733198-e0218f48-7fb1-4805-9ed6-4b962bae0688.png)

**Comment by fkhadra** [comment]
Hey @usamedin, I don't know what you are trying to accomplish but did you had a look at https://fkhadra.github.io/react-toastify/installation#the-gist ?

**Comment by usamedin** [comment]
@fkhadra my implementation is very simple, exactly as described in the video. i will try to create sandbox and share with you

**Comment by usamedin** [comment]
@fkhadra The issue was with `react-hot-loader`, once i removed this library the error is gone
Thanks
