### ISSUE TITLE
DevTools failed to load source map

### ISSUE THREAD

**Issue by alexander-vashchuk** [fkhadra/react-toastify#629]
How to get rid of this warning?

App warning:
![image](https://user-images.githubusercontent.com/86713661/130928964-268cca3b-e791-4ceb-8766-2fc590f204ac.png)

**Comment by fkhadra** [comment]
Hey @alexander-vashchuk can you provide a reproduction or a code snippet?

**Comment by alexander-vashchuk** [comment]
Nothing special, I guess

```js
import React from "react";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import Routes from "./Routes";

import "./scss/main.scss";

const App = () => {
 return (
    <div className="App">
      <Routes />
      <ToastContainer position={"bottom-left"} />
    </div>
  );
};

export default App;

```

**Comment by fkhadra** [comment]
I don't have this issue at all in codesanbox. I believe this has something to do with your build tools

**Comment by alexander-vashchuk** [comment]
I did my research

the issue occurs only while using vite bundler

to fix the issue, simply import "react-toastify/dist/ReactToastify.css" locally and remove 

this line
`/*# sourceMappingURL=ReactToastify.css.map */`

**Comment by dospolov** [comment]
Same for me
