### ISSUE TITLE
2.1.3 breaks TypeScript build

### ISSUE THREAD

**Issue by thchia** [fkhadra/react-toastify#63]
```
ERROR in [at-loader] ./node_modules/react-toastify/index.d.ts:23:16 
    TS2304: Cannot find name 'Transition'.
ERROR in [at-loader] ./node_modules/react-toastify/index.d.ts:37:37 
    TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

I think there need to be imports for React and Transition.

**Comment by LeopoldLerch** [comment]
same here

**Comment by thchia** [comment]
I tried to do a quick fix, but I ran into problems because (I think) the type declaration file for react-transition-group specifies a wildcard dependency for React. I am still on React v15.x so there's a collision with the latest (v16.x) version.

**Comment by fkhadra** [comment]
How can I validate my definition file? I'm a beginner with typescript

**Comment by thchia** [comment]
The gist of it is you need to
```typescript
import React from 'react'
import { Transition } from 'react-transition-group'
```

And make sure that both of these type files are listed as dependencies (`@types/react` `@types/react-transition-group`).

The problem I had was that although this fixes _this_ package, I got errors because `@types/react-transition-group` referenced `@types/react: "*"`, which caused the types for v16 to be included in my project when I am using v15.x still.

**Comment by fkhadra** [comment]
Ok thanks. 

But I think `@types/react @types/react-transition-group`  need to be listed as devDependencies instead of dependencies.

When I look at other packages most of the time `@types/*` is listed as DevDependencies.

**Comment by thchia** [comment]
Sorry yes I meant as devDependencies.

**Comment by fkhadra** [comment]
Thanks for your help !

**Comment by fkhadra** [comment]
Just pushed a new version. Can you tell me if it fix the issue please.

Thank you.

**Comment by LeopoldLerch** [comment]
last bug fuxed, but new error occuring now:

ERROR in [at-loader] ./node_modules/react-toastify/index.d.ts:1:8
    TS1192: Module '"C:/Projekte/DAP/DAP/Webkomponenten/node_modules/@types/react/index"' has no default export.

**Comment by fkhadra** [comment]
Really weird.

**Comment by thchia** [comment]
```
ERROR in [at-loader] ./node_modules/react-toastify/index.d.ts:2:24
    TS7016: Could not find a declaration file for module 'react-transition-group/Transition'. '/Users/thomaschia/argomi/node_modules/react-transition-group/Transition.js' implicitly has an 'any' type.
  Try `npm install @types/react-transition-group/Transition` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-transition-group/Transition';`
```

I think this is because `@types/react-transition-group` is a devDependency. It doesn't get included when installing this library.

**Comment by fkhadra** [comment]
Hmm. I'm wondering why it's not happening for React.

**Comment by thchia** [comment]
That's because I already have the type file for react. I do not have it for the transition library.

**Comment by fkhadra** [comment]
I'm wondering if it's not due to a cache issue

**Comment by LeopoldLerch** [comment]
no, because react.index.ts doesn´t have a default export. So you have to import it either using  "*" or single components in {}

**Comment by fkhadra** [comment]
Maybe I need to turn `import React from "react"` to `import React = require("react")`

**Comment by LeopoldLerch** [comment]
or 

import * as React from "react"

**Comment by fkhadra** [comment]
Can you check if it works for you when doing `import * as React from "react"` inside the node_modules/react-toastify/index.d.ts.

**Comment by fkhadra** [comment]
I saw in definitlyTypes that `import React = require('React')

**Comment by fkhadra** [comment]
Sure. Thank you for the test. I fix it now.

**Comment by fkhadra** [comment]
Fix pushed

**Comment by LeopoldLerch** [comment]
works now @me
