### ISSUE TITLE
Notifications on Safari iOS are large and have no icon

### ISSUE THREAD

**Issue by gvega3902** [fkhadra/react-toastify#635]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After updating to v8 the notification looks huge and with no icon on Safari for iOS.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Like you say, a picture will tell better:
![94DA3727-0D60-4946-A348-EE5FD460D701](https://user-images.githubusercontent.com/65842428/131039946-b21fb575-efd7-425d-a183-5f3039889e53.jpeg)

**What is the expected behavior?**
The notification should have an icon and be displayed in normal size.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 17.0.2
Safari iOS
Yes, it was working until I updated to react toastify v8

Thank you! I love the new icons!

**Comment by Ziqing19** [comment]
same here

**Comment by object1037** [comment]
I resolved the same issue by adding the following css.
```css
.Toastify__toast-icon {
  display: inline !important;
}
```
![IMG_4006](https://user-images.githubusercontent.com/22705084/131291955-0a035815-714a-438e-baf0-f2d46c8cfd01.jpg)

**Comment by fniessink** [comment]
> I resolved the same issue by adding the following css.
> 
> ```css
> .Toastify__toast-icon {
>   display: inline !important;
> }
> ```

Unfortunately, this didn't work for me.

**Comment by fkhadra** [comment]
Hello guys, sorry for that. I miss the notification just pushed a fix

**Comment by fniessink** [comment]
Thanks for the fix, can confirm 8.0.2 works fine on macOS Safari.

**Comment by eddsaura** [comment]
> I resolved the same issue by adding the following css.
> 
> ```css
> .Toastify__toast-icon {
>   display: inline !important;
> }
> ```
> 
> ![IMG_4006](https://user-images.githubusercontent.com/22705084/131291955-0a035815-714a-438e-baf0-f2d46c8cfd01.jpg)

you are the one
