### ISSUE TITLE
Animation is very fast, even ignored in Promise

### ISSUE THREAD

**Issue by MedzikUser** [fkhadra/react-toastify#636]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the animation is very fast, even ignored

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
if the promise is fulfilled quickly then the animation is skipped
e.g. my website https://www.pingbot.cf/delete (type anything in the input and then click the button several times or press "ENTER", you will see it after some time) [source code](https://github.com/MedzikUser/gatsby-pingbot/blob/main/src/pages/delete.js#L32)

**Comment by fkhadra** [comment]
@MedzikUser indeed, it's fulfilled quickly. Can you try to see if adding a delay as shown below solve your issue?
```js
toast.promise(
      axios.delete(`?url=${url}`),
      {
        pending: 'Sending request',
        success: {
          delay: 500,
          render({ data: { data } }) {
            return `Deleted ${data.url}!`
          },
        },
        error: {
          delay: 500,
          render(err){
            let e = ''
  
            if (err.data.response && err.data.response.data.message) {
              e = err.data.response.data.message
            } else {
              e = err.data.toString()
            }
  
            return `${e}`
          }
        }
      }
    )
```

**Comment by MedzikUser** [comment]
> @MedzikUser indeed, it's fulfilled quickly. Can you try to see if adding a delay as shown below solve your issue?
> 
> ```js
> toast.promise(
>       axios.delete(`?url=${url}`),
>       {
>         pending: 'Sending request',
>         success: {
>           delay: 500,
>           render({ data: { data } }) {
>             return `Deleted ${data.url}!`
>           },
>         },
>         error: {
>           delay: 500,
>           render(err){
>             let e = ''
>   
>             if (err.data.response && err.data.response.data.message) {
>               e = err.data.response.data.message
>             } else {
>               e = err.data.toString()
>             }
>   
>             return `${e}`
>           }
>         }
>       }
>     )
> ```

ok thanks that solved my problem
