### ISSUE TITLE
Styling a position of the container with styled components

### ISSUE THREAD

**Issue by terragady** [fkhadra/react-toastify#639]
Hi, I want to position the toasts in custom position but when I am overriding the classes in styled components it does not override them. I can override all the rest but not the position. What is the problem? I am using top-center and wanted to style that but I have also did not specify position and tried just container and also did not work.
here is my code: 

```
const toastProps:any= {
  autoClose: 4000,
  position: 'top-center',
  icon: false,
  closeButton: false,
  style: {
    width: 'auto',
  },
  hideProgressBar: true,
  closeOnClick: false,
};

const StyledToastContainer = styled(ToastContainer)`
  .Toastify__toast-container {
  }
  .Toastify__toast-container--top-center {
    top: 5em !important;
    left: 10%;
    transform: translateX(-50%);
  }
  .Toastify__toast {
    cursor: inherit;
    font-family: 'Circular';
    background: rgba(255, 255, 255,0);
    box-shadow: none;
    padding: 0;
    margin-bottom: 0.75em;
    min-height: 10px;
  }
  .Toastify__toast-body {
    padding: 0;
    margin: 0;
  }
`;

const App = () => {
  return (
    <Router>
      <ThemeProvider theme={theme}>
        <StyledToastContainer {...toastProps}/>
```

**Comment by clflo** [comment]
I have the same problem. I can override .Toastify__toast and .Toastify__toast--error (and the other types) but not position and container.

**Comment by keighleymcf** [comment]
It seems like styling the ToastContainer can only apply styles to classes for elements _inside_ of the ToastContainer, not the ToastContainer itself. Would be great if the documentation could be updated to explain how to change the ToastContainer styles themselves.

**Comment by fkhadra** [comment]
Hey a bit late for the answer. This is a specificity issue. https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity. You can fix your issue as follow.

```js
const StyledComp = styled(ToastContainer)`
  &&&.Toastify__toast-container {
    your style
  }
`
I've updated the documentation as well.

**Comment by TAGC** [comment]
For some reason this doesn't seem to work for me.

I'm trying to pad the toast container so that toasts are 20px offset from the edges of the page, but nothing I put in here gets picked up:

```ts
const StyledToastContainer = styled(ToastContainer)`
  padding: 20px;

  &&&.Toastify__toast-container {
    padding: 20px;
  }
`;
...

export default function AdminClient() {
  return (
    <AdminClientContainer>
      <StyledToastContainer
        position="bottom-right"
        toastClassName={(context) => getClassNameForToastType(context?.type) ?? context?.defaultClassName ?? ''}
        icon={false}
        hideProgressBar={true}
        closeButton={false}
        autoClose={4000}
      />
      <Header />
      <AdminClientContent>
        {renderSidebar()}
        {renderRouter()}
      </AdminClientContent>
    </AdminClientContainer>
  );
}
```

![image](https://user-images.githubusercontent.com/1588951/183628314-a8af59ab-4196-498b-9ced-910b24ee8e46.png)
