### ISSUE TITLE
Make the stages of toast.promise optional

### ISSUE THREAD

**Issue by wilson-webdev** [fkhadra/react-toastify#644]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`toast.promise` expects all three stages to be defined in `ToastPromiseParams` e.g. `success`, `pending` and `error`. 

**What is the expected behavior?**
As a developer, I want each of these properties to be optional so that I can utilise the `toast.promise` function for resolving promises but have more control over what toasts are shown.

For example, I may want to resolve a promise whereby only an error toast is required and so I would like to write:

```javascript
toast.promise(somePromiseFn, { error: 'Something went wrong!' });
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
N/A

**Comment by fkhadra** [comment]
Hey @wilson-webdev, your request makes total sense now that I think about it. Although, one can do
```tsx
promise.catch(() => toast.error("oops"))
```  
Anyway, it doesn't hurt to have it built-in the library

**Comment by wilson-webdev** [comment]
@fkhadra I have raised a PR against this issue. 😊

**Comment by wilson-webdev** [comment]
@fkhadra any update on this?

**Comment by fkhadra** [comment]
Hey @wilson-webdev, sorry for the late reply. I'll review the PR this weekend

**Comment by wilson-webdev** [comment]
@fkhadra no worries, thank you very much!
