### ISSUE TITLE
toast.update with onClose

### ISSUE THREAD

**Issue by callmejm** [fkhadra/react-toastify#645]
**Do you want to request a *feature* or report a *bug*?**
Bug

    const toastId = toast.dark("abc", toastConfig);
    setTimeout(() => {
      if(toast.isActive(toastId)){
        toast.update(toastId,{
          render:"ok",
          onClose:()=>{
            console.log("asdasdasd");
          }
        })
      }else{
        toast.dark("ok", toastConfig);
      }
    }, 1500);

The onClose callback, is not firing

**Comment by Goldskin** [comment]
Can confirm, doesn't work anymore

**Comment by TemoSulava** [comment]
autoClose is not working for me either, in the update the loading toast remains there unless i refresh the browser..

**Comment by itayseer** [comment]
Yes I faced that today 
```
const id = toast.info(<UpdateToast onUpdate={onUpdate} onCancel={onCancel} />, { autoClose: false, icon: false, draggable: false, closeOnClick: false,
        onClose: () => window.alert('Called when I close') })
toast.update(id,
        {
            render: <UpdateToast onUpdate={onUpdateWithClose} onCancel={onCancelWithClose} />,
            autoClose: false,
            draggable: false,
            icon: false,
            closeOnClick: false,
            onClose: onCancel
        });
```
it shows the alert of the first definition
