### ISSUE TITLE
react toastify autoclose not working for the second time

### ISSUE THREAD

**Issue by saeedth1214** [fkhadra/react-toastify#647]
hello .. i'm using react 17.0.2 and react-toastify 7.0.2 in my project .. 
when i want to show a message for the first time in a component ... everything is ok and works ...
but ...  when i  want to  show  a message for the second time in another component ... message is displayed  to me  but autoclose or closeonclick not working  and message does not remove on page ... 

pleases help me  :( .

**Comment by fkhadra** [comment]
Hey @saeedth1214 , can you provide a reproduction, thanks
