### ISSUE TITLE
Toast not showing time left in a song

### ISSUE THREAD

**Issue by BlobDotExe** [fkhadra/react-toastify#648]
the option is greyed out and when a song ends, the toast shows the previous song instead of the present one.

![image](https://user-images.githubusercontent.com/87003469/132278405-7db77098-74c7-45f1-87df-4da32aeb595e.png)

**Comment by fkhadra** [comment]
@BlobDotExe there is nothing like that in my demo. https://fkhadra.github.io/react-toastify/introduction/ could you send me the URL please :D

**Comment by BlobDotExe** [comment]
> @BlobDotExe there is nothing like that in my demo. https://fkhadra.github.io/react-toastify/introduction/ could you send me the URL please :D

URL of what exactly? I don't do coding at all.

**Comment by BlobDotExe** [comment]
I am so sorry I went to the wrong Toastify
