### ISSUE TITLE
toastify autoClose not working

### ISSUE THREAD

**Issue by yashgandhi303** [fkhadra/react-toastify#649]
bug

Tech Stack: Next js, React 

**What is the current behavior?**

autoClose is not working until user clicks on toast

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"react":17.0.2"
toast: tried with version 6 to 8

not sure but it was working with   `react: "^16.8.3"`

**Comment by znalexandr** [comment]
Yes, I have too not working

**Comment by fkhadra** [comment]
Hey guys, really hard to help without minimal reproduction

**Comment by znalexandr** [comment]
The problem was solved. It turned out that AutoClose depends on these styles. I returned this code to my css and autoClose worked

```
@keyframes Toastify__trackProgress {
    0% {
      transform: scaleX(1);
    }
    100% {
      transform: scaleX(0);
    }
  }
  .Toastify__progress-bar {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 5px;
    z-index: var(--toastify-z-index);
    opacity: 0.7;
    transform-origin: left;
  }

  .Toastify__progress-bar--animated {
    animation: Toastify__trackProgress linear 1 forwards;
  }
```

**Comment by yashgandhi303** [comment]
@znalexandr was the problem solved in production ?

**Comment by yashgandhi303** [comment]
@znalexandr Thanks, that solved my problem. Closing the issue.
