### ISSUE TITLE
Demo page checkbox to hide progress bar does not work

### ISSUE THREAD

**Issue by James-Crean** [fkhadra/react-toastify#65]
On the demo page, the checkbox for "Hide progress bar (less fanciness !)" does not select when clicked. This problem is present on both Firefox and Chrome. 

The "aria-pressed" appears to change properly, but the button does not show being selected, and the demo toasts always show the progress bar.

**Comment by fkhadra** [comment]
Indeed ! I'll fix it asap

**Comment by fkhadra** [comment]
It's fixed. I made a typo
