### ISSUE TITLE
Icon is not assignable to Toast Properties

### ISSUE THREAD

**Issue by chaserda** [fkhadra/react-toastify#650]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to add custom Icon to toast, error shows that:
```
Argument of type '{ icon: boolean; }' is not assignable to parameter of type 'ToastOptions'.
 Object literal may only specify known properties, and 'icon' does not exist in type 'ToastOptions'.
 ```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Icon is supposed to be assignable to add custom icons to toast.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 "react": "^17.0.2",

**Comment by fkhadra** [comment]
Hey @chaserda , I'm not able to reproduce your issue. It works fine here. Can you provide an example?
```tsx
const Com: React.FC = () => {
  return <div>Hello</div>;
};

toast('hello', {
  icon: Com
});

```
