### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by riteshnewal** [fkhadra/react-toastify#652]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Showing blank. toast when pass a component in toast.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Create a separate component like a model popup. pass this inside toast like. toast(myPopup). it will shop popup but you can see blank toast body also.

**What is the expected behavior?**
When a component is given, blank toast should. not be shown.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
8.0.2
<img width="1085" alt="Screenshot 2021-09-20 at 4 31 05 PM" src="https://user-images.githubusercontent.com/5128706/133992504-60e9b9fd-21f5-4b6a-8807-df073b2e0fe9.png">

**Comment by fkhadra** [comment]
Hey @riteshnewal, can you please share how you render your component?

**Comment by riteshnewal** [comment]
toast(<SessionTimeoutPopup />);

SessionTimeoutPopup is a functional component that shows this Modal popup,].
<Modal isOpen={true} className={className}>
...

**Comment by fkhadra** [comment]
@riteshnewal I think your issue is that the component you are passing to `toast` does not return anything.

**Comment by riteshnewal** [comment]
`import React, { useState } from 'react';
import ConfirmationPopup from './ConfirmationPopup';
import exclamationMark from '../../assets/img/icons/exclamation-mark-icon-blue.png';
import { Col, Row } from 'reactstrap';
import { setCookie } from '../../data/cookies/cookiesdataoperation';

const SessionTimeoutPopup = props => {
  const { showPopup, setShowPopup } = useState(props.showPopup);
  const description = (
    <div className="mt-3">
      <Row>
        <Col xs="auto" className="pl-4" style={{ textAlign: 'center', lineHeight: 5 }}>
          <img src={exclamationMark} alt="Exclamation" />
        </Col>
        <Col xs="auto">
          <p className="fs-2">Session Timeout</p>
          <p className="fs--1">Your session has expired. Please log in again.</p>
        </Col>
      </Row>
    </div>
  );

  **return** (
    <ConfirmationPopup
      showPopup={true}
      setShowPopup={() => {}}
      title={''}
      description={description}
      showCancel={false}
      okButtonText="Ok"
      handleStatus={() => {
        setCookie('Auth_Token', '', '');
        window.location.replace('/');
      }}
    />
  );
};

export default SessionTimeoutPopup;
`


`import React from 'react';
import { Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';

const ConfirmationPopup = props => {
  const {
    title,
    description,
    className,
    showPopup,
    setShowPopup,
    okButtonText = 'Ok',
    cancelButtonText = 'Cancel',
    showCancel = true,
    showOk = true,
    handleStatus
  } = props;

  return (
    <Modal isOpen={showPopup} className={className}>
      {title && <ModalHeader>{title}</ModalHeader>}
      <ModalBody>{description}</ModalBody>
      <ModalFooter>
        {showOk && (
          <Button color="primary" size="sm" className="shadow" onClick={handleStatus}>
            {okButtonText}
          </Button>
        )}
        {showCancel && (
          <Button color="secondary" size="sm" className="shadow" onClick={() => setShowPopup(false)}>
            {cancelButtonText}
          </Button>
        )}
      </ModalFooter>
    </Modal>
  );
};

export default ConfirmationPopup;
`

**Comment by fkhadra** [comment]
If you just want to display the modal the `toast` is not needed at all. 
That being said,  the toast is empty because you are trying to render the modal within it. This won't work because the modal uses a portal to be rendered.
