### ISSUE TITLE
customizing theme using SCSS - variables are not taking effect.

### ISSUE THREAD

**Issue by agigroup** [fkhadra/react-toastify#655]
I've copy and pasted the whole scss folder from the  node_modules/react-toastify and imported my _variables.scss to the toastify's _variable.scss file.  Please see my code below.

This is _abstracts/_variables.scss

```
$info: #007BFF;
$success: #28A745;
$warning: #FFC844;
$error: #DC3545;
```

Here's toastify _variable.scss

```
@import './../../abstracts/variables';

$rt-namespace: 'Toastify';
$rt-mobile: 'only screen and (max-width : 480px)' !default;

@debug "error colour is: #{$error}";

:root {
  --toastify-color-light: #fff;
  --toastify-color-dark: #121212;
  --toastify-color-info: $info;
  --toastify-color-success: $success;
  --toastify-color-warning: $warning;
  --toastify-color-error: $error;
  --toastify-color-transparent: rgba(255, 255, 255, 0.7);
....

```

My issue is that the imported variables doesn't work in toastify's scss. 

It's weird because `@debug` outputs the correct variable value(#DC3545) . 

On browser inspection tool this is what's rendered , `--toastify-color-error: $error;`. The `$error` variable was not converted to its value.

My expected compiled result is `   --toastify-color-error: #DC3545;` not  `   --toastify-color-error: $error;`

Anyone else experiencing this issue? Maybe this is not a toastify bug, it could be scss.  

Can someone help me on this? Thanks in advance!

**Comment by fkhadra** [comment]
Hey, this is related to sass. https://sass-lang.com/documentation/interpolation
