### ISSUE TITLE
Center content

### ISSUE THREAD

**Issue by ShardanaSoft** [fkhadra/react-toastify#657]
Hi

After [8.0.0](https://github.com/fkhadra/react-toastify/releases/tag/v8.0.0) update I cannot control where to position content.

```
<ToastContainer
        style={{textAlign:'end'}}
        .
        .
        .
      />
```

**What is the current behavior?**
 using textAlign doesn't control the content anymore

You can try it in [CodeSandbox ](https://codesandbox.io/s/determined-grass-fkpj6?file=/src/App.js:471-740)

You can swap react-toastify from 7.04 to 8.0.0 to see that content position doesn't change.

only with "Right to left layout" rtl I can move it left or right. Not center.

**What is the expected behavior?**
it should move the toast content, it used to be like this.

**Comment by fkhadra** [comment]
Hey thanks for reporting the issue

**Comment by 1xiscool** [comment]
This bug has come back with the latest release (version 11)
