### ISSUE TITLE
Switch to styled-component ?

### ISSUE THREAD

**Issue by fkhadra** [fkhadra/react-toastify#66]
Wondering if it would be useful to switch to styled-component.

- No need to import the Css file
- Inject only the used style

I'll try and see if it worth it.

**Comment by Zn4rK** [comment]
Have you made any progress on this?

**Comment by fkhadra** [comment]
Note yet. But I can see that the interest is growing so I'll start asap. 

I'm just wondering which implementation I should use:
- jss
- glamor
- emotion

You guys have any suggestions? Would love to hear it.

**Comment by fkhadra** [comment]
Implementation ongoing using glamor

**Comment by fkhadra** [comment]
Working version available [here](https://github.com/fkhadra/react-toastify/tree/feature/glamor)
