### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by l-mendes** [fkhadra/react-toastify#660]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When dragging toast (dismiss), I've got the following error

`
useToast.ts:162 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
`

The error has occurred only on Chrome.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 17.0.2
Chrome: 94.0.4606.61

**Comment by fkhadra** [comment]
Solved in latest
