### ISSUE TITLE
Addition of the colored theme in the toast options

### ISSUE THREAD

**Issue by greg59650** [fkhadra/react-toastify#663]
I use react-toastify to display my toast, I created a component that allows me to display the toast according to the type.
 ```
import { Slide, toast } from 'react-toastify';

  const options = {
  autoClose: 5000,
  position: toast.POSITION.TOP_CENTER,
  transition: Slide,
 closeOnClick: true,
  closeButton: false,

 };

   const Alert = (type: string, message: string) => {
  switch (type) {
case 'warning':
  return toast.warning(message);
case 'error':
  return toast.error(message, options);
case 'success':
  return toast.success(message);
case 'info':
  return toast.info(message);
case 'dark':
  return toast.dark(message);
default:
  return toast(message);
  }
 };
 export default Alert;
```

with the next call :

`Alert('error', 'Try Again');`

options determine all the options I want to configure

but if I add in the options theme: 'colored'

I end up with the following message :

```
Argument of type '{ autoClose: number; position: ToastPosition; transition: ({ 
  children, position, preventExitTransition, done, nodeRef, isIn }: 
 ToastTransitionProps) => JSX.Element; closeOnClick: boolean; closeButton: boolean; 
them
  e: string; }' is not assignable to parameter of type 'ToastOptions<{}>'.
 Types of property 'theme' are incompatible.
Type 'string' is not assignable to type 'Theme | undefined'.
```

On the other hand if I make the call differently

```
 case 'error':
    return toast.error(message, {
      theme: 'colored',
    });
```

I have no error message.

how to ensure that the theme is present in the options ?

**Comment by YuriLopesM** [comment]
I think this is a problem with types, 'cause the type `Theme` provided by **react-toastify** use Literal Types instead of string, and then when you create an object with a property `theme` and write a string, the compiler will understand this as string, and not a Literal Type:

```ts
// node_modules\react-toastify\dist\types\index.d.ts

export declare type Theme = 'light' | 'dark' | 'colored';

```

In JavaScript, I think the best way is creating a `enum` and them using it in the property:

```js
enum theme {
        colored = 'colored',
        light = 'light',
        dark = 'dark'
}

const options = {
        theme: theme.colored
        // ...other options
}

```

In TypeScript, you solve this by using an interface for options, like: 

```ts

interface IOptions {
        theme: 'colored' | 'light' | 'dark',
        // ...other options
}

const options: IOptions = {
        theme: 'colored' 
}

```

Let me know if it helped you 😄

**Comment by ceconcarlsen** [comment]
> 

thanks, worked for me :)
