### ISSUE TITLE
Overriding default styling

### ISSUE THREAD

**Issue by bbiney1** [fkhadra/react-toastify#672]
I'm basically trying to do the same thing in this post for my react app: https://github.com/fkhadra/react-toastify/issues/346

For the corresponding webpage, I have

```

import {ToastContainer, toast} from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';
import styles from './style.module.css';

const CatalogBetaNotif = () => {
  return (
    <Fragment>
      <div>
        This is <b>Catalog Beta.</b>
      </div>
    </Fragment>
  );
};

toast(<CatalogBetaNotif />, {
  autoClose: false,
  className: styles.toastrNotif,
  closeButton: false,
  closeOnClick: false,
});
```
I'm trying to do the custom styling in style.module.css. 
```
.toastrNotif {
    --toastify-toast-background:#FCEDF0;
    --toastify-color-light:#FCEDF0;
    border-radius:40px;


}

.Toastify__toast {
  border-radius:40px;
}

```
But in my browser I can see that the toastr notification is still getting the class assignments of `Toastify__toast Toastify__toast-theme--light Toastify__toast--default`. The `Toastify__toast` class seems to have all the default settings still and I don't see the change to border-radius that I want to add.

I might just be missing something basic but the styling guide still feels a little unclear.

**Comment by callisto1337** [comment]
I have the same problem

**Comment by Tamashii90** [comment]
Are you able to replicate this in codesandbox ?
I tried personally and it works fine: https://codesandbox.io/s/f7iis

What bundler are you using ?
