### ISSUE TITLE
How to dismiss a toast with multiple containers ?

### ISSUE THREAD

**Issue by AdrienLemaire** [fkhadra/react-toastify#673]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Cannot dismiss a toast when multiple containers exist

**If the current behavior is a bug, please providecontainerId the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
`toast.dismiss` should maybe access options to define the related containerId.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 17 , Chrome

**Comment by fkhadra** [comment]
A bit late to the party. This works just fine. Under the hood, the library checks every container. I'll probably add an option to specify the containerId. Closing for now. Feel free to reopen if you are able to reproduce the issue

[![Edit reverent-silence-mrbr7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-silence-mrbr7?fontsize=14&hidenavigation=1&theme=dark)
