### ISSUE TITLE
Demo page is missing theme setting

### ISSUE THREAD

**Issue by DjovDev** [fkhadra/react-toastify#675]
Toastify supports 3 basic themes: light, dark and colored.

When selecting the theme on https://fkhadra.github.io/react-toastify/introduction/ , nothing happens to the `<ToastContainer/>` sample code.

This should trigger the **theme attribute** to change.

**Comment by David2k13** [comment]
> Toastify 支持 3 个基本主题：浅色、深色和彩色。
> 
> 在https://fkhadra.github.io/react-toastify/introduction/上选择主题时，`<ToastContainer/>`示例代码没有任何反应。
> 
> 这应该会触发**主题属性**发生变化。

me too

**Comment by anand-edge** [comment]
it is 
`theme="colored"`

`
<ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar
          newestOnTop
          closeOnClick
          rtl={false}
          theme="colored"
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
`

**Comment by JoepdeJong** [comment]
@fkhadra is it possible to push the source of the `gh-pages`? i would like to resolve this issue.

**Comment by fkhadra** [comment]
Fixed
