### ISSUE TITLE
[Chore][Bug] Having troubles installing and running the example project to start contributing

### ISSUE THREAD

**Issue by AgustinJuarezN** [fkhadra/react-toastify#676]
## **Do you want to request a *feature* or report a *bug*?**
I want to request a chore and a bug to improve the starter to contribute.

## Missing step

When I followed all steps on the `CONTRIBUTING.MD `file I saw a missing step to install the example project before` run yarn start.` 

### Problem
Also when I was installed the example project and run the project I had an error with parcel (related to this [issue](https://github.com/parcel-bundler/parcel/issues/5955))

### Screenshot
![parcel-error](https://user-images.githubusercontent.com/43082143/143468515-795a36e7-2ac4-41d6-a756-5932cf0d6474.png)

### Solution
To resolve this problem I added a new dependency to the example project `"parcel-bundler": "1.12.3"`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

## **What is the expected behavior?**
Server running successfully
![server-running](https://user-images.githubusercontent.com/43082143/143469215-8b36b238-9159-4bfe-903f-34c9aaaa8c27.png)

**Comment by fkhadra** [comment]
Parcel has been bumped to the latest version. I'll move to vite in the next iteration
