### ISSUE TITLE
Documentation link seems to be incorrect ?

### ISSUE THREAD

**Issue by shirshendubhowmick** [fkhadra/react-toastify#679]
**Do you want to request a *feature* or report a *bug*?**
Possible issue with README

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

The documentation link in `README.md` takes to the same demo page. Unable to find detailed API documentation.

**What is the expected behavior?**
The documentation link should show details API documentation of the library ?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
n/a

**Comment by fkhadra** [comment]
Hey @shirshendubhowmick, maybe a cache issue on your side? The API documentation is on the left panel.
![Screenshot 2022-01-31 at 11 20 23](https://user-images.githubusercontent.com/5574267/151776535-abc413e9-f67b-4e87-b28d-91054e0e4903.png)
