### ISSUE TITLE
Basic Attention Token (BAT) Verified creator.

### ISSUE THREAD

**Issue by bronz3beard** [fkhadra/react-toastify#680]
**feature**
Completely unrelated to the code, but I really enjoy using this package and wish to tip the creator with BAT.
I know there are already some options for donation etc... but I would like to use this option if you can provide it.

current behaviour & recreate 
On brave browser when I click the brave rewards icon in the search bar the pop-up banner shows "Unverified creator"

**What is the expected behavior?**
Verified Creator

![Screen Shot 2021-12-06 at 10 10 56 am](https://user-images.githubusercontent.com/38899587/144769926-bc3f009a-c71c-4c60-9c86-c7390e94c9a6.png)

![Screen Shot 2021-12-06 at 10 16 51 am](https://user-images.githubusercontent.com/38899587/144769987-b88b2d81-1c76-462a-8520-d8092c91b9d1.png)

**Comment by fkhadra** [comment]
Hey @bronz3beard, thank you for the support. I've created a brave account now :). Thanks for sharing this!
