### ISSUE TITLE
[Feature Request] Clear All Button

### ISSUE THREAD

**Issue by JBaczuk** [fkhadra/react-toastify#686]
Feature Request

In order to clear the queue, it must be done using the [toast API](https://fkhadra.github.io/react-toastify/limit-the-number-of-toast-displayed/#how-to-clear-the-waiting-queue) (which is great). It would be good if the stack of toasts would also include a "Clear All" button at the bottom. For example, if there are 10 toasts, and the container is limited to 5, clicking clear all, would clear the stack (all 10). If there are many toasts, the user is stuck waiting a lot for them all to clear out, with no good way to manually clear them. The clear all button would display in the right position depending on the toast container limit. If there is an easy way to add this button in the correct spot every time, that would suffice.

Thanks! This lib is very helpful :)

Example:

![image](https://user-images.githubusercontent.com/8162417/147969945-d8e66245-6a43-4bfc-b1df-3ba937f344f7.png)

**Comment by wlcharlie** [comment]
@JBaczuk Hi, have you try `toast.dismiss()`? 

ref: https://fkhadra.github.io/react-toastify/api/toast

**Comment by JBaczuk** [comment]
Thanks, I'll take a look. Still would be nice to have a button placed in the list so it's internal to the lib not external.

**Comment by fkhadra** [comment]
Hey @JBaczuk, since v9 the lib support an addon system. You could contribute by providing this functionality as an addon. https://fkhadra.github.io/react-toastify/migration-v9

**Comment by fkhadra** [comment]
Closing as I think this should not be implemented in the core. Addons are welcome ofc
