### ISSUE TITLE
Promise without success hangs on the pending state

### ISSUE THREAD

**Issue by Luperi** [fkhadra/react-toastify#689]
@fkhadra I've pushed the changes suggested, along with removing the edits to the example page. I agree it's nice and simple!

One thing I have noticed is that if you provide a `pending` stage and not `success`/`error`, it hangs on the pending state. We could add a bit more logic to the promise then/catch chain to check what's defined, and then remove the toast if appropriate. Up to you! 😃

_Originally posted by @wilson-webdev in https://github.com/fkhadra/react-toastify/issues/646#issuecomment-927119019_

Is there the plan to extend this behavior? Thanks

**Comment by wilson-webdev** [comment]
@Luperi I have raised a PR that resolves this issue.
