### ISSUE TITLE
Documentation includes a type field being passed into the ToastContainer component, but it doesn't exist.

### ISSUE THREAD

**Issue by ashok-sc** [fkhadra/react-toastify#69]
Readme has the following example:

```
<ToastContainer 
                    position="top-right"
                    type="default"
                    autoClose={5000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    pauseOnHover
                />
```

Typescript compiler fails saying `[ts] Property 'type' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ToastContainer> & Readonly<{ children?: ReactNode;...'.`.

**Comment by fkhadra** [comment]
Hey @ashok-sc , this is an artifact from the past. I have to fix the doc.

**Comment by fkhadra** [comment]
btw @ashok-sc sorry for the trouble. I updated the documentation

**Comment by ashok-sc** [comment]
Not a problem! That was fast :).
