### ISSUE TITLE
toast.clearWaitingQueue does not clear the full queue - only clear visible messages

### ISSUE THREAD

**Issue by upadhyayprakash** [fkhadra/react-toastify#696]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When calling `toast.clearWaitingQueue()` method with a limit (eg. `limit = 3`), only the 1st 3 toast messages are cleared, but rest of the other messages (queued) still popup. The issue is re-producible on the demo page of react-toastify library.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
https://fkhadra.github.io/react-toastify/introduction

**What is the expected behavior?**
The entire queue of messages should get cleared when calling this method.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All the versions as it's a functional issue with the library.

**Steps to Reproduce**
1. Go to **[home page](https://fkhadra.github.io/react-toastify/introduction/)** of this library
2. Enter the `limiit = 2`
3. Click on the **Show Toast** button 10 times continuously.
4. Now, click on the **Clear All** button.
5. This will instantly remove the messages that are on the screen, but the other messages (8 of them in the queue) still come one after the other (in a pair of 2, as the `limit = 2`)

(Check the Video)
https://user-images.githubusercontent.com/19553655/150117119-118d4ea3-dd88-46d3-8e17-7ebf1a6aa6e8.mp4

**Comment by fkhadra** [comment]
Hey @upadhyayprakash, on the demo page, the `clear all` button does not invoke `toast.clearWaitingQueue()` but `toast.dismiss()`. Which would remove all active toasts. In order to remove all toasts (active + queued), you would have to do call `toast.clearWaitingQueue()` then `toast.dismiss()`
