### ISSUE TITLE
icon props in "ToastContainer" is not work when using custom icon in "toast" function.

### ISSUE THREAD

**Issue by dding-g** [fkhadra/react-toastify#701]
Hello! I really using useful your assume toastify. :)
Thank you so much.

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
1. pass icon props in "toast" function
```
  toast("msg", {
     icon : MyIcon
  })
```

2. disable icon in "ToastContainer"
```
  <ToastContainer icon={false}/>
```

I follow [migrate to v8 document](https://fkhadra.github.io/react-toastify/migration-v8).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
"icon" props can disabled in "ToastContainer" even using custom icon in "toast" function.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
`v8.1.0`

**Comment by zbuttram** [comment]
Can confirm this issue also exists in 9.0.0 and in that version there is no longer an available workaround for this issue (using `toast.configure()`)
