### ISSUE TITLE
Autoclose duration start before entrance animation completed

### ISSUE THREAD

**Issue by essential-randomness** [fkhadra/react-toastify#702]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Custom animation duration time is not respected. There is a default duration that is hardcoded (750ms).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Take the default sandbox for custom animation, and change any of the durations to e.g. `100s`. https://codesandbox.io/s/react-toastify-animatecss-jxrx9?from-embed

**What is the expected behavior?**

The transition actually lasts 100s.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Not relevant.

**Comment by fkhadra** [comment]
Hey @essential-randomness, it does work. If you open the style.css file you will see that I set the transition duration to 3sec.
```css
.swirl-in-fwd {
  animation: swirl-in-fwd 3s ease-out both;
}
```

[![Edit react-toastify-#702](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-toastify-702-qy45g?fontsize=14&hidenavigation=1&theme=dark) 


The example you linked contains 2 transitions, 1 from animate.css and another 1 from animista.
My guess is that you edited the transition duration for the animista transition but you still clicked on the first button which trigger the animation from animate.css

**Comment by essential-randomness** [comment]
Try setting the entry duration to 30s and you can see more clearly that the new duration is indeed not respected.

**Comment by fkhadra** [comment]
Ok, I see what's the issue now good catch :). I'll fix it with the release tomorrow.  The autoClose duration start before the entrance animation  is complete
