### ISSUE TITLE
How can I get callback for onClose on ToastContainer?

### ISSUE THREAD

**Issue by leadstar116** [fkhadra/react-toastify#705]
This can be a feature as well as a bug.

Feature Request:
Currently, <ToastContainer> is not exposing `onClose` callback, so I can't update my internal states and do some chores.
Please expose `onClose` callback in <ToastContainer> also, so I can handle the rest stuff.

**Comment by fkhadra** [comment]
I believe `toast.onChange` could be used for your use case
