### ISSUE TITLE
Toast promise it locked

### ISSUE THREAD

**Issue by matheuscamarques** [fkhadra/react-toastify#706]
My toast promise it locked but promisse sucess response

![image](https://user-images.githubusercontent.com/37029621/152713456-9886b446-faa9-4cf1-b987-fa50caef4557.png)

**Comment by matheuscamarques** [comment]
My toast promises to be locked, but it promises a successful response, the toast also crashes and I can't pause

**Comment by fkhadra** [comment]
@matheuscamarques please provide reproduce the issue on codesanbox so I can help you

**Comment by matheuscamarques** [comment]
i solved it, i was using the toast container in two parent and child components, in that i removed the one from the child component and it worked.
