### ISSUE TITLE
Promise toast does not close automatically if promise resolves too quickly

### ISSUE THREAD

**Issue by GibsDev** [fkhadra/react-toastify#707]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Promise toast requires manual interaction to close (when autoClose is defined) if the promise resolve time is less than the css enter animation time for the toast to appear.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/interesting-brook-zxx7w

**What is the expected behavior?**

The toast should automatically close after the promise resolves and the enter animation finishes.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 17.0.2
react-toastify: 8.1.1
Firefox for Linux: 95.0 64 bit

**Comment by Seijinx** [comment]
I confirm I have the same behavior, have to stick to `8.1.0` at this point.

**Comment by enisdenjo** [comment]
Me too, seems like the promise has to take at least 1 second.

A quick workaround:
```diff
const iResolveQuickly = new Promise((resolve) => {
  resolve();
});

toast.promise(
- iResolveQuickly,
+ Promise.all([
+   iResolveQuickly,
+   // run for at least 1 second, see: https://github.com/fkhadra/react-toastify/issues/707
+   new Promise((resolve) => setTimeout(resolve, 1000)),
+ ]),
  {
    success: '👍',
    pending: '⏳',
    error: '👎',
  },
);
```

**Comment by fkhadra** [comment]
Thanks, @GibsDev for the reproduction. It really helped me narrow down the issue. I'll release a new version with the fix ASAP.

**Comment by fkhadra** [comment]
v8.2.0 solve this issue
