### ISSUE TITLE
[Feature Request] prompt, confirm

### ISSUE THREAD

**Issue by jcho0216** [fkhadra/react-toastify#708]
It would be lovely if I could use prompt and confirm feature that react-toastify provides as well as the alert feature
thank you 💛

**Comment by jado66** [comment]
Did this get created? If so how would one go about implementing a prompt?
![image](https://user-images.githubusercontent.com/77120464/219509686-50d657e6-e8ea-454e-ac13-1b80e03d03c3.png)

**Comment by jcho0216** [comment]
reopened the issue since I dont think this feature is implemented yet

**Comment by fkhadra** [comment]
Can be implemented in the userland easily 

https://codesandbox.io/p/sandbox/laughing-easley-h207s7?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A20%2C%22startLineNumber%22%3A8%7D%5D
