### ISSUE TITLE
incorrect `z-index` in minified css

### ISSUE THREAD

**Issue by phil-r** [fkhadra/react-toastify#71]
In minified css that can be found here after installation:`node_modules/react-toastify/dist/ReactToastify.min.css` 
`z-index` on `.toastify` class is set to `1`, although it should be `999`

Not a big deal, but it was a bit confusing ;)

**Comment by fkhadra** [comment]
Hey @phil-r I had never paid attention, thank you

**Comment by hyperh** [comment]
Yup getting the same issue, so it appears below some things in my app with higher z-index

**Comment by fkhadra** [comment]
Yep, cssnano wanted to optimize the css too much 😁 . I was planning to do other stuff and pushing the fix at the same time. 

I'll push the fix for the z-index in a few minutes. Other stuff can wait

**Comment by fkhadra** [comment]
Fix piblished !

**Comment by mrbeen351** [comment]
Hi @fkhadra , I just update to version 2.2.1 but still got same issue. It still appears below modal pop-up form when using with react-strap-form

**Comment by fkhadra** [comment]
Hey @mrbeen351,

Did you try to remove npm cache maybe ? If you search the z-index you will see that the z-index is correct.

![image](https://user-images.githubusercontent.com/5574267/33166575-03d9b67c-d03b-11e7-9788-cfa5fe3740b5.png)

Tell me if it helps.

**Comment by mrbeen351** [comment]
Hi @fkhadra , yes I tried, I realized that 
![capture](https://user-images.githubusercontent.com/13146393/33168190-adc1fba4-d072-11e7-9c09-09ccbefbf027.PNG) z-index of modal form is 1050, but when I change z-index to 1051 or larger it still appears below. I don't know why

**Comment by fkhadra** [comment]
So If I understand you have overwritten the z-index of `.toastify` and still have the issue?
If yes could you provide a snippet so I can help you to debug?

**Comment by mrbeen351** [comment]
Hi @fkhadra , Sorry I think this fault is because of my code. I just create simple example with modal and it displays correctly. Thanks for your kindly support :)

**Comment by fkhadra** [comment]
Perfect ! Have a nice day
