### ISSUE TITLE
Add functionality to get all open toasts

### ISSUE THREAD

**Issue by rubenyeghikyan-highway** [fkhadra/react-toastify#713]
### [feature request]

Hi, it would be nice to have functionality to get all open toasts somehow, something like

```TS
toast.getOpenElements() // returns [{type: toast.TYPE.SUCCESS, content: 'Hello World!', id: 1, ... }]
``` 

### **Motivation**: 
So before showing and spamming lots of notifications, you could check first if there are some open toasts, then decide to show or not. The better scenario of this feature would be when you have auto-check functionality for example, which runs every second, so you could check if there is no active toasts then show errors, otherwise handle somehow.

I do know that ToastContainer has `limit` option, where you can limit how many open toast you would have, but still this is not exactly what I want

-------

Also this method would be handy
```TS
toast.isOpen() // returns boolean true/false
```

**Comment by rubenyeghikyan-highway** [comment]
Also would be nice to have functionality to add some custom data in toast, for example 

```TS
toast.error('Name must be unique', {
  myCustomPropery: 'something',
  foo: 'bar',
  errorType: 'uniqueness'
})
```

But this might be another **Feature Request** I guess

**Use Case**
```TS
toast.error('Name must be unique', {
  autoClose: 6000,
  myCustomPropery: 'something',
  foo: 'bar',
  errorType: 'uniqueness'
})

document.querySelctor('.save-button').addEventListener('click', (e) => {
  const  openToasts = toast.getOpenElements();

  if (openToasts.length > 0) {
     const hasUniquenessErrors = openToasts.some(toast => toast.errorType === 'uniqueness')
     if (!hasUniquenessErrors) toast.error('Name must be unique', ...)
  } else {
     toast.error('something')
  }
}, false)
```

**Comment by fkhadra** [comment]
Hey @rubenyeghikyan-highway, the v9 will rework the `toast.onChange` API. This is an excerpt of the documentation I'm currently working on. You could use this API to track the opened toasts.

```jsx
interface ToastItem<Data = {}> {
    id: Id;
    content: React.ReactNode;
    theme?: Theme;
    type?: TypeOptions;
    isLoading?: boolean;
    containerId?: Id;
    data: Data;
    icon?: React.ReactNode | false;
    status: "added" | "removed" | "updated" 
}

const unsubscribe = toast.onChange((payload: ToastItem) => {
  switch (payload.status) {
    case "added":
      // new toast added
      break;
    case "updated":
      // toast updated
      break;
    case "removed":
      // toast has been removed
      break;
  }
});
```

That being said, for your use case I would suggest that you use ids to prevent duplicate
> So before showing and spamming lots of notifications, you could check first if there are some open toasts, then decide to show or not.

For example, let's say you want to display a toast every time your autosave. You could do as follow
```js
toast("Saved", { toastId: "AUTO_SAVE" })
```
If you then reuse the same id and if the toast is already displayed nothing will happen.

Regarding your second request
> Also would be nice to have functionality to add some custom data in toast

Well, this is already possible 😆. It's not well documented https://fkhadra.github.io/react-toastify/migration-v8/#pass-data-even-when-you-are-not-rendering-a-react-component. I'll add something more visible to the documentation


Useful reference: https://fkhadra.github.io/react-toastify/prevent-duplicate/
