### ISSUE TITLE
A way to listen for autoClose complete event. 

### ISSUE THREAD

**Issue by Message-Akunna** [fkhadra/react-toastify#716]
Is there a way to listen for autoClose event which will be different from onClose event? This is to know if the toastify timer was completed or cut short due to some event say “cancel an action “.

**Comment by tanmay-gp** [comment]
This would be great. Just a parameter mentioning the source of the close event would the job I suppose.

**Comment by Stophface** [comment]
@Message-Akunna Did you solve this? I am having exactly the same problem!
