### ISSUE TITLE
[Bug] pauseOnFocusLoss is not working properly

### ISSUE THREAD

**Issue by rubenyeghikyan-highway** [fkhadra/react-toastify#717]
### ToastContainer with `pauseOnFocusLoss={false}` option is not working as expected.

When you are on that tab and switch to another monitor or application and do something there, it works fin., **BUT** when you switch browser tab and do something there, `pauseOnFocusLoss` is ignored, and when you return back to your tab you see tons of notifications appeared on screen.

I will explain my use case for a little more context. I have auto-saver which works every 10 seconds. After successfully saving I show toast to the user. So when you are on that tab and switch your app, notifications appear and disappear. But when you switch tab and work on that tab or switch app, and then go back to my application you see lots of toast notifications hanging there.

[![Screen-Shot-2022-02-25-at-5-42-13-PM.png](https://i.postimg.cc/1thsZSTM/Screen-Shot-2022-02-25-at-5-42-13-PM.png)](https://postimg.cc/2qwP4sCB)

**Comment by fkhadra** [comment]
@rubenyeghikyan-highway having a hard time reproducing it. I would suggest that for your autosave notification you always use the same id. This will prevent duplicate notification

```js
toast.success("Your changes are automatically saved", { toastId: "AUTO_SAVE" })
```
