### ISSUE TITLE
className option

### ISSUE THREAD

**Issue by therealtx** [fkhadra/react-toastify#72]
When toast container haven't className toast className option not work.
For example
Container 
<Toast.ToastContainer
    hideProgressBar={true}
/>
And toast
Toast.toast(<Component />, {
    className:      'global-note',
});
This className not work

**Comment by fkhadra** [comment]
Hello @therealtx ,

I'm not able to reproduce your issue. If you inspect the toast you will see that the className `testClass` is present.

[![Edit jz7mwo2505](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jz7mwo2505)
