### ISSUE TITLE
AutoClose on .update method doesn't work unless i point my cursor on it.

### ISSUE THREAD

**Issue by theaafofficial** [fkhadra/react-toastify#720]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
When using toast with update, autoClose doesn't work until i point the cursor on toast and then it starts closing. Otherwise it stays there.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
I've tried using option pauseonFocusLoss to false, but still doesn't work.

**What is the expected behavior?**
It should autoclose the toast after updating it.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-countdown@2.3.2
├── react-dom@17.0.2
├── react-hook-form@7.27.1
├── react-hot-toast@2.2.0
├── react-router-dom@6.2.1
├── react-scripts@5.0.0
├── react-toastify@8.2.0
├── react@17.0.2
├── tailwindcss@3.0.23
├── validator@13.7.0
└── web-vitals@2.1.4

**Comment by 18566246732** [comment]
same issue here, any solutions ?

**Comment by 18566246732** [comment]
@theaafofficial  I just fount a workaround here, move your update inside a setTimeout, and set the delay of setTimeout to 0.1 s, I don't know why but that just works .

**Comment by fkhadra** [comment]
@theaafofficial could it be the same as https://github.com/fkhadra/react-toastify/issues/725 ?

**Comment by fkhadra** [comment]
Fixed by #810 I believe
