### ISSUE TITLE
React Native 

### ISSUE THREAD

**Issue by kostas2231** [fkhadra/react-toastify#724]
Hello , very helpful library , I just wanted to ask one question cause I am not sure . 
Does this work with react native and in general with mobile devices?
Thanks in advance!

**Comment by fkhadra** [comment]
Hey it does not work in react-native. Wanted to port the lib but not enough resources to do so. It does work on mobile, though https://fkhadra.github.io/react-toastify/how-to-style/#mobile

**Comment by seba9999** [comment]
I may be late to the party but here's what i found : https://github.com/zahidalidev/toastify-react-native
