### ISSUE TITLE
The `success` toast on `promise` does not disappear.

### ISSUE THREAD

**Issue by toviszsolt** [fkhadra/react-toastify#725]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The `success` toast on `promise` does not disappear

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
To disappear.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 17.0.2 / OS: Windows 11 - Android 10 - iOS 15 / Browser: latest Chrome, Edge, Firefox, Safari Mobile

### The `success` toast on `promise` does not disappear, process bar also does not move.
No focus loss or hover state. The pending and error toasts work fine.
Other information: container and API calls are made in two different files.
Possible source of the problem: solve the Promise too quickly (almost immediately).
Now I notice that sometimes it works, sometimes it doesn't. Most of the time it gets stuck.
If it gets stuck and I move the mouse over it and then move the mouse out, the progress bar starts.

### Toast Container:
```jsx
<ToastContainer
    position="bottom-center"
    autoClose={5000}
    hideProgressBar={false}
    newestOnTop={false}
    closeOnClick
    rtl={false}
    pauseOnFocusLoss={false}
    draggable
    pauseOnHover
/>
```

### API Call with Axois:
```js
const promise = axios.post('/api/settings', formToObject(e.target), {
  headers: { Authorization: 'Bearer ' + user.token },
});

toast.promise(promise, {
  pending: 'Saving data...',
  success: 'Data saved.',
  error: 'Data saving error.',
});
```

### UPADTE
I have created a sample code, the link is below. You can see that with a 10ms promise the toast gets stuck.
My API average response time is 5-9ms in a live environment.
https://codesandbox.io/s/issue-725-raact-toastify-sxqcl5?file=/src/App.js

**Comment by toviszsolt** [comment]
Now I notice that sometimes it works, sometimes it doesn't. Most of the time it gets stuck.

**Comment by fkhadra** [comment]
Thanks, @toviszsolt for the reproduction. I think I have a race condition. Until I find a proper way to fix the issue, you can use the following workaround

```js
const promise = axios.post('/api/settings', formToObject(e.target), {
  headers: { Authorization: 'Bearer ' + user.token },
});

toast.promise(promise, {
  pending: {
   render: 'Saving data...',
   // disable the delay for pending state
   delay: undefined
  },
  success: 'Data saved.',
  error: 'Data saving error.',
}, {
delay: 500
});
```

**Comment by toviszsolt** [comment]
@fkhadra Thanks for reply.
I delayed the `success` and `error`, now it's work.
You might be able to delay the `Promise` resolver by `100ms` by default.
```js
toast.promise(promise, {
  pending: 'Saving data...',
  success: { render: 'Data saved.', delay: 100 },
  error: { render: 'Data saving error.', delay: 100 },
});
```

**Comment by fkhadra** [comment]
@toviszsolt a fix will land in the next version

**Comment by mattxerini** [comment]
FYI - This workaround isn't really working, at least not for a very fast response. I have a request that comes back in 60ms and the toast is stuck at the pending animation.

**Comment by toviszsolt** [comment]
Hi @mattxerini!
Could you perhaps provide an example on one of the sandbox sites? I don't have a problem anymore, I use this library constantly.
Just to be sure, please check that you are passing a `Promise` object to `toastify`. And also whether the `Promise` will be `resolved` well.

**Comment by hcmutemimi** [comment]
> @fkhadra Thanks for reply. I delayed the `success` and `error`, now it's work. You might be able to delay the `Promise` resolver by `100ms` by default.
> 
> ```js
> toast.promise(promise, {
>   pending: 'Saving data...',
>   success: { render: 'Data saved.', delay: 100 },
>   error: { render: 'Data saving error.', delay: 100 },
> });
> ```

I want to show about 200ms, delay this context, what mean?
