### ISSUE TITLE
How to add or hook Undo option in toaster

### ISSUE THREAD

**Issue by mhannan** [fkhadra/react-toastify#73]
May users may be looking for this options and would assist many of us. I am wondering how we can add or hook "Undo" option in the toaster. Would be nicer if given an example or change.

Thanks.

**Comment by fkhadra** [comment]
Hello @mhannan ,

The example feature state only approach but it could be done even easier with redux or mobx.
Feel free to ask more questions if it's not clear enough. 

[![Edit l2qkywz7xl](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2qkywz7xl)

**Comment by theredwillow** [comment]
It would be nice if we could just pass an undo function to toast.success in order for it to show up. Having to create a whole utility component for it feels superfluous for an action as used in a library like this.
