### ISSUE TITLE
Replace ReactDom.render with root.render

### ISSUE THREAD

**Issue by nb89** [fkhadra/react-toastify#736]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/14173819/162494218-766c4eed-18d5-48b1-bce1-85bae399756f.png)
This message is shown when a toast is appears on React 18.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
No warning should show if uses of ReactDom.render are replaced with root.render as the official documentation suggests.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 18

**Comment by fkhadra** [comment]
@nb89 the v9 has migrated to react18. It's still in RC but pretty stable if you want to give it a try.
`npm installl react-toastify@next`

You can find the release note here https://fkhadra.github.io/react-toastify/migration-v9

**Comment by nb89** [comment]
Thanks for the info.  Closing this.
