### ISSUE TITLE
pauseOnFocusLoss={false} not working

### ISSUE THREAD

**Issue by mattleonowicz** [fkhadra/react-toastify#740]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I have `pauseOnFocusLoss={false}` set on Container.
When the tab is not active, there are couple of toasts triggered.
When the browser tab is active again, I am flooded with all the notifications, like they were waiting for the tab to be active to play out.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/react-toastify-background-5cgwbl
Hit the button, make some other tab active, go back to the CodeSandbox after 10 seconds.

**What is the expected behavior?**

Notifications should play out even if the tab is not active, so that I don't get flooded with all the notifications that were triggered while the tab was inactive.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Seems independent of React and browser versions

**Comment by McSam94** [comment]
is there any update to this matter?

**Comment by fkhadra** [comment]
Hey @mattleonowicz, the `pauseOnFocusLoss` only has effects on displayed notifications
- With `pauseOnFocusLoss` enabled
https://user-images.githubusercontent.com/5574267/179411349-1c45a377-b604-4d2c-b60f-f605e1caaf4f.mov

- With `pauseOnFocusLoss` disabled, notifications keep running even when focusing on another window
https://user-images.githubusercontent.com/5574267/179411399-f460b33c-3132-4b66-b027-9f8a1f6cee7e.mov

So `pauseOnFocusLoss` won't fix your issue. Let's understand why.

Calling `toast("something")` is asynchronous, so user code has a higher priority than react-toastify, it adds a new task to the event loop. Under the hood `setTimeout(fn, 0)` is used to schedule the task.

Inactive tabs have low priority execution which affects js timers, in our case `setTimeout`. This is why you are seeing what you described
> When the browser tab is active again, I am flooded with all the notifications, like they were waiting for the tab to be active to play out.

That being said, there are a couple of ways to solve your issue.
- Display notifications only when the document is focused
```tsx
// you can write a wrapper to avoid repeating this logic
if (document.hasFocus()) {
  toast("hello")
}
```
- if you are using v9, you can listen for `onChange` and dismiss notifications if the document is not focused
```tsx
useEffect(() => {
  // onChange return the callback to unsubscribe, hence the return
   return toast.onChange(({ status, id }) => {
      if (status === "added" && !document.hasFocus()) {
        toast.dismiss(id);
      }
    });
  }, []);
```

**Comment by mattleonowicz** [comment]
Thanks for the explanation!. I ended up using `document.hidden` for my usecase and it works well.
