### ISSUE TITLE
autoClose=5000 not working anymore

### ISSUE THREAD

**Issue by yoyos** [fkhadra/react-toastify#742]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Toast isn't sliding out after 5s anymore. Bug found on 8.1.1 and 8.2.0. 
Is working on 8.1.0

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/embed/thirsty-archimedes-zfz844?fontsize=14&hidenavigation=1&theme=dark

**What is the expected behavior?**
Toast should begin 5s animation then close.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on React 17.0.2 and 18.0.0

**Comment by fkhadra** [comment]
I think I've fixed it in v9. It's still in RC but pretty stable if you want to give it a try.
`npm installl react-toastify@next`

You can find the release note here https://fkhadra.github.io/react-toastify/migration-v9
