### ISSUE TITLE
Disable piling toast 

### ISSUE THREAD

**Issue by malatini42** [fkhadra/react-toastify#746]
Hello, sorry I am a noob (and french !), is it possible to disabled "piling" toasts (can only have one displayed)

**Comment by fkhadra** [comment]
Hey @malatini42, you can use an id for example
```tsx
const myId =  "anId"

toast("Hello", { toastId: myId  })
// because the id is the same it won't be shown again
toast("Hello", { toastId: myId  })
```
https://fkhadra.github.io/react-toastify/prevent-duplicate

ps: Vive la France 🇫🇷
