### ISSUE TITLE
React Toastify is  broken while showing. How can I show react toastify correctly in the top of the page?

### ISSUE THREAD

**Issue by uttamsaha** [fkhadra/react-toastify#749]
## React toastify now showing properly.

Hi i am trying to show react toastify but it is not showing correctly. It's broken while showing.

Here is my code.
```
import React from 'react';
import { toast, ToastContainer } from 'react-toastify';

    const Toast = () => {
        const showToast = () => {
            toast('Hi there! I am react toastify.');
        }
      return (
        <div>
            <button onClick={showToast} className="btn btn-danger mt-5 d-block mx-auto">Click Here</button>
            <ToastContainer/>
        </div>
      )
    }
```
    
    export default Toast;

And it is output
[Here is the output][1]

  [1]: https://i.ibb.co/1dJrNwS/toast.png

If I click on the button it's showing broken toast and it's not moving from the screen.
How can I solve this problem please help me.
Thanks in advance. <3

**Comment by QuiiBz** [comment]
Hi, have you imported the default CSS? From the [docs](https://fkhadra.github.io/react-toastify/installation#the-gist):

```ts
import 'react-toastify/dist/ReactToastify.css';
// minified version is also included
// import 'react-toastify/dist/ReactToastify.min.css';
```

**Comment by uttamsaha** [comment]
It worked before without import css. I didn't import the css. I imported &
its working fine now.

**Comment by QuiiBz** [comment]
That shouldn't work without importing any CSS 🤔  Feel free to close the issue if it's resolved.

**Comment by uttamsaha** [comment]
Okay thank you..
