### ISSUE TITLE
Icons always show the default in v9

### ISSUE THREAD

**Issue by QuiiBz** [fkhadra/react-toastify#750]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When specifying a custom `icon` (globally or per `toast` call), `react-toastify` always shows the default one. Even disabling completely the icon with `false` still shows the default icon.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/musing-hopper-5rw3bi?file=/src/App.tsx

**What is the expected behavior?**
We should be able to specify a custom icon, as from the [docs](https://fkhadra.github.io/react-toastify/icons):
- A string
- A component
- Or `false` to disable it

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Test with React 17 and 18, all tested browsers, and macOS. It was working fine with `react-toastify@8.2.0`

**Comment by rfgmac14** [comment]
I am facing the same issue.. in version 9.0 of react-toastify is no longer possible to set custom icons.
Also, in order to remove the default icons it is now needed to render a toast without any type...
There is no mention to these changes in https://fkhadra.github.io/react-toastify/migration-v9 so this must be a bug @fkhadra

**Comment by QuiiBz** [comment]
Looks like a regression from https://github.com/fkhadra/react-toastify/pull/731/commits/a3ba9dd7b5db4da08428796a64231ad4f3ccc6e0#diff-4b84ae4e863e8ba70ebdd6767b0bc38e30f6cbc25ce40dae0377a8ac7b6d0395L61-L75 were the logic has been moved to `src/hooks/useToastContainer.ts`.

Specifically, the [old version](https://github.com/fkhadra/react-toastify/pull/731/commits/a3ba9dd7b5db4da08428796a64231ad4f3ccc6e0#diff-4b84ae4e863e8ba70ebdd6767b0bc38e30f6cbc25ce40dae0377a8ac7b6d0395L65) is comparing with the `icon` coming from the props, whereas the [new version](https://github.com/fkhadra/react-toastify/pull/731/commits/a3ba9dd7b5db4da08428796a64231ad4f3ccc6e0#diff-c4e0ee4dab8f54957e389aeee5876cf425b0a866c6dc7211c9fb4706f0d4c105R226) is comparing with `toastProps.icon` which is assigned just above.

I've been able to fix the issue by replacing `toastProps.icon` with the `icon` from `options`, as investigated above:

From:
<img width="482" alt="Screenshot 2022-05-05 at 14 34 09" src="https://user-images.githubusercontent.com/43268759/166923895-11357786-37d7-4493-9e0a-f3ca09910a7e.png">

To:
<img width="465" alt="Screenshot 2022-05-05 at 14 33 08" src="https://user-images.githubusercontent.com/43268759/166923754-630c4944-7f9a-489c-bf4d-2f232c67b40a.png">

**Comment by fkhadra** [comment]
Damn good catch. @QuiiBz want to submit a PR?

**Comment by QuiiBz** [comment]
> Damn good catch. @QuiiBz want to submit a PR?

Thanks. I can open a PR for this fix if you want (already done), but looks like you're already working on it.

**Comment by QuiiBz** [comment]
You're welcome, thanks for the release :)
