### ISSUE TITLE
Toast emitter stopped working in v9 ?

### ISSUE THREAD

**Issue by tbjerknes** [fkhadra/react-toastify#751]
Hi

I may be missing something very obious, but the toast emitter stopped working when I upgraded from 8.2.0 to 9.0.1

Here is a codesandbox for 8.2.0 where it is working fine:
https://codesandbox.io/s/toastify-8-2-0-1n3if7-1n3if7?file=/src/App.js

sandbox for 9.0.1. The only difference is that i have removed toast.configure();
https://codesandbox.io/s/toastify-9-0-1-z9tgqv-z9tgqv?file=/src/App.js

**Comment by fkhadra** [comment]
Hi @tbjerknes, `toast.configure` has been removed. You have to use the `ToastContainer` at the root of your app.

```tsx
import { toast, ToastContainer } from "react-toastify";
import "./styles.css";
import "react-toastify/dist/ReactToastify.css";

// toast.configure();

export default function App() {
  return (
    <div className="App">
      <h1>Toastify example v 9.0.1</h1>
      <button
        type="button"
        onClick={() => {
          toast("Test", { autoClose: 2000 });
        }}
      >
        Alert
      </button>
      <ToastContainer />
    </div>
  );
}

```
