### ISSUE TITLE
The draggable doesn't work because of extra animate styles

### ISSUE THREAD

**Issue by konstantincheban** [fkhadra/react-toastify#752]
I noticed that one of the container that is responsible for draggable (translateX) does not remove the animation style that prevents the correct work translateX. Because of this, I only have opacity working.

I don't understand why in CodeBox everything works with the same version, maybe the problem is in something else. Help to understand.

Chrome: Version 101.0.4951.54 (Official Build) (x86_64)
MacOS: Catalina
react-toastify: v9.0.1

<img width="639" alt="Screenshot 2022-05-07 at 6 30 17 PM" src="https://user-images.githubusercontent.com/66566780/167261228-8729076c-d983-4192-a666-480c06dfc37d.png">

**Comment by fkhadra** [comment]
Hey @konstantincheban, if I'm not mistaken you are using react18 with strict mode. React18 with strict mode will run effects twice in development, that's why you have the issue, but it's not visible on code sandbox, which uses a production build of react.

Can you check with a production build?
