### ISSUE TITLE
Is there any option to hide the previous toast message?

### ISSUE THREAD

**Issue by biswajit-adhikary** [fkhadra/react-toastify#753]
**Is there any option to hide the previous toast message?**

**I added a toast message when I click deliver button. After clicking the deliver button first toast message displaying. When I'm clicking the another deliver button, the second toast message is displayed at the bottom of the previous message.  Is there any option to hide the first one automatically or need to wait sometime?  (https://ibb.co/rx2BSLw) error image:**
![errors-submit](https://user-images.githubusercontent.com/55616161/167298268-4031a98e-39cb-4d3c-8b4a-63c54cc18646.jpg)

**Comment by IliaGolubenko** [comment]
You can try to set toast to toastId variable and dismiss it when needed
`const toastId = toast("Hello", options)`
`toast.dismiss(toastId)`
