### ISSUE TITLE
No toast

### ISSUE THREAD

**Issue by jcubic** [fkhadra/react-toastify#756]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

I've just installed the library and it doesn't work.

this is my code, I've followed the documentation:

```javascript
  useEffect(() => {
    if (saveError) {
      console.log(saveError);
      toast(saveError, {
        position: "bottom-right",
        autoClose: 2000,
        hideProgressBar: true,
        closeOnClick: true,
        progress: undefined
      });
    }
  }, [saveError]);
```

```jsx
<ToastContainer
          position="bottom-right"
          autoClose={2000}
          hideProgressBar={true}
          newestOnTop={false}
          closeOnClick
        />
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

I have a bigger application that I'm working on.

![Peek 2022-05-13 19-39](https://user-images.githubusercontent.com/280241/168338237-23104211-9cb9-4992-8242-6675f1e9f90e.gif)

Here is the repository: https://github.com/jcubic/snapp but it will not work easily since you need to register an account and create notes. I may later create a simplified example.

When I press CTRL+S to save the note error appears in the console but no toaster.

**What is the expected behavior?** I expect to see a toaster.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** 17.0.2

**Additional Notes** I use Vite, TypeScript, and CSS modules.

**Comment by fkhadra** [comment]
Hey @jcubic, it would be easier for me to help if you could share a simplified example. Meanwhile, it seems that `saveError` contains an `Error`. The `toast` function expect  valid `ReactNode: string | components | function`. 
```js
     // replace saveError to check
      toast("Error triggered", {
        position: "bottom-right",
        autoClose: 2000,
        hideProgressBar: true,
        closeOnClick: true,
        progress: undefined
      });
```

**Comment by jcubic** [comment]
Thanks for your help, that was it adding `saveError.toString()` solved the issue.
