### ISSUE TITLE
Style option doesn't work in 9.0.1

### ISSUE THREAD

**Issue by grit96** [fkhadra/react-toastify#760]
I recently decided to upgrade react-toastify from 8.x to 9.x in our app and in doing so I discovered that the `toastStyle` prop and the `style` options no longer work.

Code sandbox using react-toastify 8.2.0 - works using either `toastStyle` prop on `ToastContainer` or the `style` option passed to `toast.error`.
https://codesandbox.io/s/headless-leaf-pvl8ep

Code sandbox using react-toastify 9.0.1 - doesn't work using either of the methods above.
https://codesandbox.io/s/snowy-rain-v5rly4

According to the docs on how to style the toast this should still work in 9.x - https://fkhadra.github.io/react-toastify/how-to-style/

**Comment by madcido** [comment]
I just had the same issue. I think the toast styles are being overwritten [here](https://github.com/fkhadra/react-toastify/blob/175ef403aecc339af27bf67602e9a392b1b6dad3/src/components/ToastContainer.tsx#L63)

**Comment by grit96** [comment]
@madcido could you give my PR a go to see if it sorts it

**Comment by madcido** [comment]
Oh, I'm no maintainer of this repo. I was just poking around and suggested a possible solution 🙂 - not sure how to help/test your PR

**Comment by grit96** [comment]
I've tested it in my app with patch-package and it seems to work fine, let's hope someone can merge it
