### ISSUE TITLE
i think you forget the theme

### ISSUE THREAD

**Issue by roozbeh95m** [fkhadra/react-toastify#765]
hi in your website 
i think you forget the theme 
in this page https://fkhadra.github.io/react-toastify/introduction/

when you change the theme , the theme changes doesn't appear in the code . 
it took a while for me to find out what should i change

**Comment by tomal02** [comment]
It's been reported here - https://github.com/fkhadra/react-toastify-doc . Just needs to be merged

**Comment by fkhadra** [comment]
fixed now
