### ISSUE TITLE
Toast not updating properly after update() method is called with the corresponding toast id

### ISSUE THREAD

**Issue by tropicbliss** [fkhadra/react-toastify#770]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
1. I create a new toast like this:
```js
const id = toast.loading("Processing...");
```
2. I then update it like so:
```js
toast.update(id, {
          render: "Completed!",
          type: "success",
          isLoading: false,
          autoClose: 5000,
          closeOnClick: true,
        });
```
The toast still has the loading animation besides the text after it's updated. The toast text updates as per normal

Current toast container setup:
```js
<ToastContainer theme={theme} hideProgressBar transition={Slide} />
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

This happened the moment after updating from 9.0.1 to 9.0.2 without any change in code. When I switched back to 9.0.1 the bug is still there. I disabled browser caching.

**What is the expected behavior?**

A success toast will be shown with the green check mark after it's updated

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Currently using React 18.1.0/all browsers and platforms

**Comment by DFearing** [comment]
This still isn't working for me using version 9.0.3. Either using toast.loading or toast.promise, the loading spinner just doesn't disappear.

**Comment by rrain0** [comment]
Hello, i have experienced same problem when trying to update type from `loading `to` 'success'`. And also update from `autoClose=false` to `autoClose=2000` doesn't work.
react-toastify v9.1.3, react 18.2.0.
Regards, this library is very good.

**Comment by ysageev** [comment]
Hi,

I am having this exact issue with version 10.0.5.

```js
const delay = (ms) => new Promise((res) => setTimeout(res, ms))

const func = async () => {
  const toastId = toast.loading("Loading.." { type: "info" })
  await delay(2000)
  toast.update(toastId, { render: "Done!", type: "success", autoClose: 3000, transition: Flip })
}
await func()
```

https://github.com/user-attachments/assets/f7de2417-0a3e-4d79-83f0-6648c10b0098

Per the screen grab, the update function doesn't change the icon and doesn't change the `autoClose`, so the success message never goes away.

**Comment by sovann72-dev** [comment]
if anyone stuck finding the root of the problem, you can check the `delay` option.
```tsx
const handleClick = async () => {
  const id = toast.loading('Doing something...');
  try {
    functionCall();
    toast.update(id, {
      render: 'Success',
      type: 'success',
      isLoading: false,
      autoClose: 3000,
      delay: 0, // Add this line to eliminate delay
    });
  } catch (error) {
    toast.update(id, {
      render: 'Error',
      type: 'error',
      isLoading: false,
      autoClose: 3000,
      delay: 0, // Add this line to eliminate delay
    }),
  }
};

```
