### ISSUE TITLE
flexbox CSS breaks in IE11

### ISSUE THREAD

**Issue by cypherfunc** [fkhadra/react-toastify#774]
`flex: 1;` causes toasts to collapse in IE, it should be `flex: 1 1 auto;`

https://github.com/fkhadra/react-toastify/blob/deb681ba363a80fd36982cecfbbf16e5168c62f8/scss/_toast.scss#L26

**Comment by fkhadra** [comment]
Hey @cypherfunc, I don't fix issues related to ie11 anymore given that EOL is on 15 June of this year. You can always override the default style.

**Comment by cypherfunc** [comment]
Ok, no problem. Unfortunately my company needs to support IE for at least another year, but it was easy enough to override this. Thanks for the great library!
