### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by justin-mcclain** [fkhadra/react-toastify#778]
When I call on the function to show the toast notification, the styling of the notification is missing (green check mark, red x).

This is what I have for my code: 

```tsx
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

    const notifySuccess = () => {
        toast.success("Email sent!", {
            position: "bottom-center",
            autoClose: 1500,
            hideProgressBar: true,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
        });
    };

    const notifyError = () => {
        toast.error("Please submit name and message.", {
            position: "bottom-center",
            autoClose: 1500,
            hideProgressBar: true,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
        });
    };

    const sendEmail = (e) => {
        e.preventDefault();
        if (name.length > 1 && email.length > 1 && message.length > 1) {
            emailjs
                .sendForm(
                    ".......................",
                    "................",
                    form.current,
                    ".........."
                )
                .then(
                    (result) => {
                        console.log(result.text);
                        setName("");
                        setEmail("");
                        setMessage("");
                        notifySuccess();
                    },
                    (error) => {
                        console.log(error.text);
                    }
                );
        } else {
            notifyError();
        }
    };
```

The sendEmail function is tied to a button, and the notifications appear, just not styled.
![toast](https://user-images.githubusercontent.com/95764373/173665087-c92bb89c-d459-4681-9970-03601da59847.png)

React version 18.1.0 and react-toastify version 9.0.4

edit: i don't know why my code isn't showing the correct formatting, it looks fine when I paste it here?

**Comment by fkhadra** [comment]
Hey @justin-mcclain, sound weird to me. Works just fine on codesanbox. Can you try to reproduce your issue there or share a repository so I'll be able to help you :)

**Comment by justin-mcclain** [comment]
Have at it.  I am beyond confused on what's going on.  I've used it on a previous project with no issues and it was wonderful.  I also tried it on Code Sandbox and it worked there without issue too.

https://github.com/justin-mcclain/portfolio/tree/main/portfolio/client/src

Thanks!

**Comment by fkhadra** [comment]
Hey @justin-mcclain, so the issue is coming from some global css rules that you have 😁
https://github.com/justin-mcclain/portfolio/blob/main/portfolio/client/src/App.scss#L239 
```css
svg {
  left: 0;
  top: 0;
  position: absolute;
}
``` 
This one will prevent the close button and the notification icon to be positioned as expected

I've also noticed that the text of the notification is centered, I don't know if it's intended but if it's not the case, it's due to the fact that the `ToastContainer` is inheriting the style of `.contact`. In that case `text-align: center`.

```tsx
 <div className="contact">
                <ToastContainer />
</div>
```

If you want to avoid this issue, I suggest that you move the `ToastContainer` to the root of the app.

```js
function App() {
  return (
    <BrowserRouter>
      <div className="App" id="app">
        <NavBar/>
        <div className="middle">
          <h1>JUSTIN</h1>
          <h1>MCCLAIN</h1>
        </div>
        <About/>
        <Projects/>
        <Contact/>
        <Footer />
      </div>
      <ToastContainer />
    </BrowserRouter>
  );
}

Voila 😁. Happy coding and thanks for using the lib
```
