### ISSUE TITLE
Not support react array

### ISSUE THREAD

**Issue by xkomiks** [fkhadra/react-toastify#785]
```js
toast(["Some text with a", <span>span</span>, "in it"]) // does't work
toast(<>{["Some text with a", <span>span</span>, "in it"]}</>) // work
```

**Comment by fkhadra** [comment]
`toast(<>{["Some text with a", <span>span</span>, "in it"]}</>) // work` -> valid jsx

`toast(["Some text with a", <span>span</span>, "in it"]) // does't work` -> unvalid jsx
