### ISSUE TITLE
Swipe to dismiss animation not working correctly when using React 18

### ISSUE THREAD

**Issue by ferfrey** [fkhadra/react-toastify#788]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Animation (translate x) of the swipe to dismiss functionality is not working on React 18, introducing some weird behavior

Here is a codesandbox: https://codesandbox.io/s/green-rain-xnccs2
Steps to repro:
1. Click 'click me'
2. Try to dismiss the toast by performing a swipe to the right.
3. Notice that toast opacity changes but the toast is not following the cursor direction (translate in X axis does not work)

![toastify](https://user-images.githubusercontent.com/2099565/178017402-578135c7-2670-42ff-84bf-381b54da9aa4.gif)

**What is the expected behavior?**
Given a toast, swipe to right should move the toast to the right until it disappears.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 18, Chrome, Firefox

**My guess**
I have noticed that the class `Toastify__bounce-enter--top-right` is not being correctly removed after the toast appears as you can see here below:
![image](https://user-images.githubusercontent.com/2099565/178017726-8f08736e-3bbf-48a4-b7d7-67298d333fca.png)

so my guess is that error could be in `cssTransition.tsx`, related to how React18 dispatches events or similar.

Thanks,
Fernando

**Comment by fkhadra** [comment]
Hey @ferfrey, this issue is caused by the fact that react18 run useEffect 2 times in dev mode. It won't happen in the production bundle.  

https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state

I have yet to find a way to fix this

**Comment by ferfrey** [comment]
Thank you for your reply, I can confirm that is not happening in the production bundle.
