### ISSUE TITLE
2.2.2 requires glamor

### ISSUE THREAD

**Issue by the-spyke** [fkhadra/react-toastify#79]
Just updated `react-toastify` to `2.2.2` from npm and it broke my build:

```
ERROR in ./node_modules/react-toastify/lib/ProgressBar.js
Module not found: Error: Can't resolve 'glamor' in '/home/.../node_modules/react-toastify/lib'
 @ ./node_modules/react-toastify/lib/ProgressBar.js 17:14-31
 @ ./node_modules/react-toastify/lib/Toast.js
 @ ./node_modules/react-toastify/lib/ToastContainer.js
 @ ./node_modules/react-toastify/lib/index.js
 @ ./lib/.../action/notificationsactions.js
 @ ./lib/.../action/notificationsactions_test.js
 @ ./testfiles/unit_tests.js
webpack: Failed to compile.

```

**Comment by mrbeen351** [comment]
Same issue with version 2.2.0 and toastify display incorrect with me, although it ran fine on last week

**Comment by the-spyke** [comment]
`2.2.1` runs fine for me.

**Comment by csvan** [comment]
A temporary fix is adding `glamor` as a dep for your own project.

**Comment by fkhadra** [comment]
sorry guys I'll fix it asap. You could upgrade to the v3

**Comment by FallenAngel666** [comment]
Same issue with `2.2.1` on my side.

**Comment by fkhadra** [comment]
@FallenAngel666 can you upgrade to the latest version(v3) ?

**Comment by FallenAngel666** [comment]
Yeah, I guess "Can't resolve 'react-toastify/dist/ReactToastify.min.css' in" is just version related ^^

**Comment by fkhadra** [comment]
Indeed, since v3 I switched to glamor so no need to import the css. I'll check if there is a way to add deprecation notice when npm update the package.

**Comment by FallenAngel666** [comment]
Thank you :)
