### ISSUE TITLE
Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by fhrryDeveloper** [fkhadra/react-toastify#790]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I can see following bug when I install this module
Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I followed guide exactly. But when I import this module, I can see this error(attached screenshot)
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react version image
![image](https://user-images.githubusercontent.com/72539001/178074171-414113cd-f801-47bf-b0bf-c4d863efc403.png)
bug image
![image](https://user-images.githubusercontent.com/72539001/178074190-ae99b978-972a-4c2a-9385-0965ec748db7.png)

**Comment by fkhadra** [comment]
Hey @fhrryDeveloper what are you using to bundle your app? CRA, nextjs?

**Comment by bkern** [comment]
I am having the same issue with same version of react/react-dom and I use CRA

**Comment by bkern** [comment]
It was that CRA was old. I created project with v4 and now its on v5 which has solved this issue. By updating react-scripts in my project I was able to use this library.

**Comment by fkhadra** [comment]
Hey @fhrryDeveloper, https://github.com/bezkoder/redux-toolkit-example-crud-hooks uses an old version of react-scripts. Using the latest should fix your issue.
