### ISSUE TITLE
Progress bar overflow on iOS devices and safari browser

### ISSUE THREAD

**Issue by mehdi-developer** [fkhadra/react-toastify#791]
The progress bar gets outside the toastbar on iOS devices and Safari browser on macbook .

<img width="424" alt="Screen Shot 1401-04-19 at 15 46 57" src="https://user-images.githubusercontent.com/63982703/178142822-fb64f288-03fb-41cb-82dc-5b171655769a.png">

This is how I modify it with tailwindcss : 

```
 <ToastContainer
        position="top-center"
        autoClose={3500}
        bodyClassName="font-Regular text-xs md:text-sm m-0 p-0"
        toastClassName="rounded-full bg-slate-800 my-5 mx-4 md:mx-0"
        progressClassName="bg-brand h-0.5"
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl
        pauseOnFocusLoss
        draggable
        theme="dark"
        pauseOnHover
      />
```

Versions :

next 12.0.7
react 17.0.2
react-dom 17.0.2
react-toastify 9.0.5
Macbook Safari Version 14.1.2 (16611.3.10.1.6)
iPhone 13 pro max iOS 15.5

**Comment by goldmont** [comment]
Same here, only on iOS after progressbar animation starts:
![image](https://user-images.githubusercontent.com/6855692/179707907-0f33a308-d74c-4e4b-ae28-3d043055e365.png)

**Comment by fkhadra** [comment]
Hey guys, it's a known issue with webkit. I managed to find a fix. Will be released in the next patch version
