### ISSUE TITLE
add "i got it" bottom button to close component

### ISSUE THREAD

**Issue by loveyandex** [fkhadra/react-toastify#794]
x button is good but is not "i got it " concept
![image](https://user-images.githubusercontent.com/53381292/178550122-ecedb736-892b-4615-af32-6050962a5888.png)

**Comment by fkhadra** [comment]
Hey @loveyandex, you can render whatever you want. You are not limited to string. https://fkhadra.github.io/react-toastify/render-what-you-want/

```tsx

const MyComponent  = () => {

  return <div>
Content goes here
<button>I got it</button>
</div>
}

toast(MyComponent)
```
