### ISSUE TITLE
I am experiencing this issue currently as of react-toastify: ^6.2.0. Is there a planned date or quarter when this bugfix will go live? Thanks!

### ISSUE THREAD

**Issue by dhebert-dev** [fkhadra/react-toastify#795]
I am experiencing this issue currently as of react-toastify: ^6.2.0. Is there a planned date or quarter when this bugfix will go live? Thanks!

_Originally posted by @dhebert-dev in https://github.com/fkhadra/react-toastify/issues/550#issuecomment-1183411690_

**Comment by fkhadra** [comment]
Hey @dhebert-dev, what prevents you from upgrading to a newer version? v6 is quite old now

**Comment by dhebert-dev** [comment]
Hey I have found the info needed and which version the bugfix was implemented. We are looking into upgrading. Thanks so much for reaching out and for all the hard work that has gone into this component. 

fix [#550] Unable to select text inside inputs when a toast is open was pushed in version 7.0.0
