### ISSUE TITLE
Generic type is not passed to NotificationCenterItem in UseNotificationCenter interface

### ISSUE THREAD

**Issue by goldmont** [fkhadra/react-toastify#796]
Hi there,

As anticipated in the title, there is a type definition error that prevent me from specifing the type of the notification `data` payload. The problem is that the generic type `Data` is not passed [here](https://github.com/fkhadra/react-toastify/blob/master/src/addons/use-notification-center/useNotificationCenter.ts#L59). Thus, the result is that each notification has the following type `NotificationCenterItem<{}>` instead of the one I specified. Thanks for your efforts.

**Comment by fkhadra** [comment]
@goldmont thanks for reporting the issue. I've published the fix

**Comment by goldmont** [comment]
Thank you man.
