### ISSUE TITLE
Error: React is not defined

### ISSUE THREAD

**Issue by imranbarbhuiya** [fkhadra/react-toastify#797]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Using [react-toastify](https://github.com/fkhadra/react-toastify) with `@vitejs/plugin-react v2.0.0` and `vite v3.0.0` throws 
`ReferenceError: React is not defined` only in **Production**.

After getting the error, I enabled sourcemap and found the error in `react-toastify` esm build.
![image](https://user-images.githubusercontent.com/74945038/179387493-0d89dfd6-b239-47b3-ba0b-d9eebae110a5.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Use `@vitejs/plugin-react v2.0.0` and `vite v3.0.0` and use `toast.error('message')` and you'll get the error

**What is the expected behavior?**
It shouldn't throw.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
It works in both react 17 and 18 when using vite v2 but it's throwing in vite 3 as vite 3 uses esm. 

I'm not sure if it's a vitejs plugin but or react-toastify. Lmk should I create the issue in vitejs plugin instead.

**Comment by fkhadra** [comment]
hey, @imranbarbhuiya which version of react-toastify are you using? A fix has been pushed in v9.0.4 to fix an issue with vite

**Comment by imranbarbhuiya** [comment]
I'm using v9.0.5

**Comment by mehmetonder** [comment]
I get the same error using the newly released v9.0.6` @vitejs/plugin-react v2.0.0` and `vite v3.0.0`.

**Comment by fkhadra** [comment]
@imranbarbhuiya would it be possible to reproduce your issue in code sandbox or share a repo? Thanks

**Comment by fkhadra** [comment]
It seems to work just fine for me, so I believe it has something to do with the configuration

https://github.com/fkhadra/vite-toastify

**Comment by pitang1965** [comment]
I ran into the same problem and couldn't solve it, so I switched to a different notification library, but the problem occurs before I switched.

* https://github.com/pitang1965/pitang-todo/commit/a85ecb251baa8775882d06b0fef3553b506e0922
* [Enter email and press button](https://62d3ec7f7f85b10009e9d32b--pitang-todo.netlify.app/)

**Comment by imranbarbhuiya** [comment]
> It seems to work just fine for me, so I believe it has something to do with the configuration
> 
> [fkhadra/vite-toastify](https://github.com/fkhadra/vite-toastify)

I'll try with your repo btw have you tried in production build or dev build? Because dev build works fine the issue comes in production build.

**Comment by pitang1965** [comment]
I have seen no issues in the development environment, only with Netlify.

**Comment by fkhadra** [comment]
You're right @imranbarbhuiya didn't see that the issue was just happening in production.

**Comment by fkhadra** [comment]
@imranbarbhuiya may I ask you to try to install `yarn add react-toastify@9.0.6-vite-1` and see if it fixes your issue without changing the jsxRuntime. Thank you

**Comment by imranbarbhuiya** [comment]
No still the same error. I just upgraded my vite to `3.0.2` as I saw they fixed an esm issue but still, `react-toastify@9.0.6-vite-1` with `vite@3.0.2` throws the same error.

**Comment by imranbarbhuiya** [comment]
Yeah yarn was resolving it to `9.0.6`. I just tried by pinning the version and it worked. Thanks.

**Comment by fkhadra** [comment]
Awesome I'll publish a new version tomorrow then

**Comment by fkhadra** [comment]
@imranbarbhuiya pushed v9.0.7

**Comment by szymonhel** [comment]
I have the same issue in version 9.1.1. 9.0.7 works fine.

**Comment by vincentteyssier** [comment]
Same issue on 9.1.2. Happens only after build once pushed to firebase, on local dev it works fine
