### ISSUE TITLE
useNotificationCenter: marking all as read or clearing notifications does not update all components using this hook

### ISSUE THREAD

**Issue by goldmont** [fkhadra/react-toastify#798]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Having two components `A` and `B`, clearing notifications from `B` does not update `A` component state. Currently, component `A` renders a badge showing the count of unread notifications; `B`, instead, is my implementation of the notification center. Clearing all notifications or marking them as read from `B`, does not update the badge rendered by `A`.

**What is the expected behavior?**
Getting the badge remounted.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 17.0.2

Thank you for your efforts.

**Comment by fkhadra** [comment]
Hey @goldmont, may I ask you to reproduce the issue in codesanbox? Thanks

**Comment by goldmont** [comment]
Sure, I can. I'll do it later this afternoon or tomorrow.

**Comment by goldmont** [comment]
Here you are: [CodeSandbox](https://codesandbox.io/s/react-typescript-forked-ln02qy)

ToastContainer is hidden in this example via `display: none`. In order to reproduce the issue, you have to click on the notifications and look at the `unreadCount` value.

**Comment by fkhadra** [comment]
@goldmont thanks for the reproduction.  Using `useNotificationCenter` is like `useState` because they are totally independent when used in different components.

eg: every `useNotificationCenter` keeps track of his own state.

- When you add a notification it works because the hook relies on `toast.onChange` to update his state.
- When you use `markAsRead`, `toast.onChange` is not involved at all, it's just a plain state update (setState).

If you want to share `useNotificationCenter` values among multiples components, you can call it in the parent component and pass the value to the children
```tsx
function Parent(){
const notificationCenter = useNotificationCenter()

    return (
         <div>
              {/* passing everything down but you could select only what needed */}
              <A  notiCenter={notificationCenter} />
              <B  notiCenter={notificationCenter}/> 
              <OtherCOmponent />
          </div>
    )
}

```

Another approach would be to wrap `useNotificationCenter` value with a context. This way you access it from anywhere within the provider.

```tsx
const NotificationCenterContext = createContext<UseNotificationCenter>({});

function useNotificationCenterContext() {
  return useContext(NotificationCenterContext);
}

function NotificationCenterProvider(props) {
  const v = useNotificationCenter();

  return <NotificationCenterContext.Provider {...props} value={v} />;
}

function App(){
    return (
         <NotificationCenterProvider>
{/* use useNotificationCenterContext inside the components to access the value*/}
              <A  />
              <B  /> 
          </NotificationCenterProvider>
    )
}

```

Hope it helps, I'll clarify the documentation when I get times

**Comment by goldmont** [comment]
Is it possible to add the ability to notify all the notification centers? For example, each notification center could register internally to a shared object and force the relative component to re-render when the "notifyAll" function is invoked. Something like this

**Comment by goldmont** [comment]
Another solution could be to add a new property to the ToastContainer. For example, the property `sharedNotificationCenter` of boolean type. Setting this property to true, it makes all notification centers centralized. What do you think about?

**Comment by goldmont** [comment]
Hi there,

I made my own implementation of `useSharedNotificationCenter` and it works as expected. Maybe it could be useful to someone

```typescript
import { useCallback, useEffect, useState } from 'react';
import { useNotificationCenter } from 'react-toastify/addons/use-notification-center';
import { UseNotificationCenter } from 'react-toastify/addons/use-notification-center/useNotificationCenter';

interface NotificationManager {
	callbacks: (() => void)[];
	register: (callback: () => void) => void;
	unregister: (callback: () => void) => void;
	notifyAll: () => void;
}

const notificationManager: NotificationManager = {
	callbacks: [],
	register(callback) {
		this.callbacks.push(callback);
	},
	unregister(callback) {
		this.callbacks = this.callbacks.filter((x) => x !== callback);
	},
	notifyAll() {
		for (const callback of this.callbacks) {
			callback();
		}
	}
};

const useForceUpdate = () => {
	const [ _, setState ] = useState({});
	return useCallback(() => setState({}), []);
};

export const useSharedNotificationCenter = <Data = {}>(): UseNotificationCenter<Data> => {

	const forceUpdate = useForceUpdate();
	const notificationCenter = useNotificationCenter<Data>();

	const markAllAsRead = useCallback(() => {
		notificationCenter.markAllAsRead();
		notificationManager.notifyAll();
	}, [ notificationCenter ]);

	const markAsRead = useCallback((...args: Parameters<UseNotificationCenter<Data>['markAsRead']>) => {
		notificationCenter.markAsRead(...args);
		notificationManager.notifyAll();
	}, [ notificationCenter ]);

	const clear = useCallback(() => {
		notificationCenter.clear();
		notificationManager.notifyAll();
	}, [ notificationCenter ]);

	useEffect(() => {
		const handler = () => forceUpdate();
		notificationManager.register(handler);
		return () => notificationManager.unregister(handler);
	}, [ forceUpdate ]);

	return { ...notificationCenter, markAllAsRead, markAsRead, clear };
};
```

**Comment by fkhadra** [comment]
Hey @goldmont, thanks a lot for sharing your solution. I guess at some point I can add something similar to the addon so it's available out of the box

**Comment by goldmont** [comment]
> Hey @goldmont, thanks a lot for sharing your solution. I guess at some point I can add something similar to the addon so it's available out of the box

Hi, news about this? Thanks

**Comment by goldmont** [comment]
Hi @fkhadra,

I've solved by using Context API. Here it is an example in case someone needs it:
```jsx
import { createContext, FunctionComponent, useContext } from 'react';
import { useNotificationCenter } from 'react-toastify/addons/use-notification-center';

interface Props {}

const NotificationsContext = createContext<ReturnType<typeof useNotificationCenter>>({} as any);

export const NotificationsProvider: FunctionComponent<Props> = ({ children }) => {
	return (
		<NotificationsContext.Provider value={useNotificationCenter()}>
			{children}
		</NotificationsContext.Provider>
	);
};

export const useSharedNotificationCenter = () => useContext(NotificationsContext);
```

Then use the `useSharedNotificationCenter` hook to have all child components in sync.

**Comment by tersor** [comment]
@goldmont Would absolutely love a working example of your solution using the Context API.

**Comment by goldmont** [comment]
> @goldmont Would absolutely love a working example of your solution using the Context API.

Hi,

Just pass the JSX of your `index` as child of the `NotificationsProvider`. Then in any of your components use the `useSharedNotificationCenter` hook.
