### ISSUE TITLE
./node_modules/react-toastify/dist/react-toastify.esm.mjs Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by iambhautik** [fkhadra/react-toastify#799]
i have installed react toastify 9.0.6
it through error like this...
./node_modules/react-toastify/dist/react-toastify.esm.mjs Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)

**Comment by iambhautik** [comment]
> i have installed react toastify 9.0.6 it through error like this... ./node_modules/react-toastify/dist/react-toastify.esm.mjs Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)

**Comment by kelvinelove** [comment]
Did you figure out what the issue was? 

I am experiencing the same error in one of my projects: 

> Failed to compile.
> ./node_modules/react-toastify/dist/react-toastify.esm.mjs
> Can't import the named export 'cloneElement' from non EcmaScript module (only default export is available)

**Comment by sohhamm** [comment]
how did you resolve this?

**Comment by kelvinelove** [comment]
I recall i removed /node_modules and package-lock.json, and downgraded my node version (to 14.x), and that seemed to solve it

**Comment by yusufkayaer** [comment]
Hello Everyone,
Is there any other solution without upgrade or downgrade node version?

**Comment by fires3as0n** [comment]
This is funny how in the library documentation you read `toast("Wow so easy!");`. And seconds after that end up not being able even to install it. Looks like not so easy, right?

**Comment by sshmaxime** [comment]
Same issue here. Node v18.12.1

**Comment by EvilaMany** [comment]
I'm using storybook, Node v16.
Setting builder: "webpack5" fixed the problem

**Comment by ViniiSouza** [comment]
Any solution to fix this?
