### ISSUE TITLE
Does not work in Vite v3 prod build

### ISSUE THREAD

**Issue by cnelms** [fkhadra/react-toastify#800]
When I upgraded to Vite v3, toastify started bombing on my production build due to a React.createElement statement causing "Reference error: React is not defined"

I have rolled back quickly so can't really show exactly where it happened, but I'm guessing you just need to be sure to `import React` in all your view components.

**Comment by fkhadra** [comment]
Hey @cnelms the latest release fixes this issue. See https://github.com/fkhadra/react-toastify/issues/797 for more details

**Comment by cnelms** [comment]
Awesome. That was quick. Thanks!
________________________________
