### ISSUE TITLE
Module parse failed with `react-scripts-ts`

### ISSUE THREAD

**Issue by nuthinking** [fkhadra/react-toastify#803]
I've a fairly old app initially created years ago with Create React App for Typescript. I basically don't have access to the Webpack config unless I eject it.

Trying to use the library I get:
```
./node_modules/react-toastify/dist/react-toastify.esm.mjs
Module parse failed: Unexpected token (232:4)
You may need an appropriate loader to handle this file type.
|     theme,
|     type,
|     ...rest
|   } = _ref;
|   return React.createElement("svg", {
```

Looking around the issues, the only solution I found that worked was using version 4.5.2. Not a very appealing strategy since now it's very old. What else could I try? Thanks a lot! 🙏

**Comment by fkhadra** [comment]
Hey @nuthinking, it's happening because CRA pre v5  does not support esm module. Upgrading to the latest `react-scripts` should fix the issue

**Comment by nuthinking** [comment]
Ok, thanks! I think I will try to re-create the project from start with CRA and Typescript. Wish me luck!

**Comment by nuthinking** [comment]
@fkhadra too many issues upgrading CRA. I guess I'm stuck to my version.
