### ISSUE TITLE
Update existing toast?

### ISSUE THREAD

**Issue by jwheeler-gs** [fkhadra/react-toastify#81]
Is there any way to update a toast that is already visible?

For example, I want to create a toast with no auto-close timeout and type=info to show that a user-requested action is pending. Then when the action is determined to be successful or failed, I want to update that existing toast to change the type to success or failure and enable the auto-close timeout. This could be achieved by closing and opening new toasts, but that gets confusing for the user if they have multiple pending actions.

From what I've seen in the API there is currently only a method for dismissing a toast by ID and not updating it by ID.

**Comment by fkhadra** [comment]
Hello @jwheeler-gs,

There is no such thing, I could implement it, it would be useful.

Regarding the api, I'm wondering if it's best to implement an explicit method like:

```js
toast.update({
  id: toastId
  content: "We could update content",
  type: "Update type",
  ... and so on
});
```
or :

```js
// The normal api, if you pass an id it's an update otherwise create a new toast
cont id = toast("hello");

// update
toast({
  id: id,
  type: "new type here",
   ...otherOptions
});
```

Both approach makes sense. I need to think a bit 😁

**Comment by fkhadra** [comment]
Indeed, I started to implement something.
If I use an explicit api like `toast.update(id, newOptions);` it will be easier for me. 
Thanks for your feedback.

**Comment by jwheeler-gs** [comment]
Awesome! Thanks for the quick response on this. It will be very useful.

**Comment by fkhadra** [comment]
Hey @jwheeler-gs,

WIP, what do you think? I need to fix the exit animation.

![toastify-update](https://user-images.githubusercontent.com/5574267/33404408-800a228a-d564-11e7-8dae-5fc63390e890.gif)

**Comment by jwheeler-gs** [comment]
Hey @fkhadra,

Looking good so far! Will there be an option to override the update animation? It looks really nice for general use as you have it in your demo right now, but for my specific use case, I just want to be able to update auto-close, close-on-click, close button, and the background color without any transition (or maybe a custom transition that will allow the background color to do a fade transition).

Thanks!

**Comment by fkhadra** [comment]
Hey @jwheeler-gs,

The new version is almost ready. Got a question.

When updating a toast do you expect it to refresh the autoClose delay in case autoClose where set?

**Comment by jwheeler-gs** [comment]
That's a good question. So you're ask if an existing toast has autoClose="7" and the update has autoClose="8", should it reset the timer back up to 8 or just let it keep running down from where it was before the update?

I think I'd expect an update to reset the timer *if* the autoClose option changes to a new value in the update. So if both the original and update have autoClose="7", I'd expect the timer to keep running normally, but if the value of autoClose changes, I'd expect that to reset the timer to the new value (otherwise what's the point of changing it?).

**Comment by fkhadra** [comment]
Thank you for the constructive answer. That's the kind of answer I like to hear.

**Comment by fkhadra** [comment]
@jwheeler-gs v3.1 is live

**Comment by jwheeler-gs** [comment]
Works like a charm! Thank you! 👍

**Comment by rezmoth** [comment]
Toast Update not working:
```
... Component omited for brevity ...
notifyNewEnterprise(enterprise) {
    let toastId = toast.info('Hello', { position: toast.POSITION.TOP_RIGHT });
    Enterprises.insert(enterprise, (err) => {
       if(!err) {
           toast.update(toastId, {
            render: 'Enterprise Created Successfully.',
            type: toast.TYPE.SUCCESS,
            className: css({
              transform: "rotateY(360deg)",
              transition: "transform 0.6s"
            })
          });
       }
   });
}
```
It just displays Hello Toast it doesn't change. Why and how could I change it to work. Thanks.

**Comment by TravisKool** [comment]
has this been releaseed?
