### ISSUE TITLE
Programmatically dismissed toasts while container is unmounted still appear when the container is mounted

### ISSUE THREAD

**Issue by trylle** [fkhadra/react-toastify#811]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Programmatically dismissing a toast while the container is unmounted has no effect. The toast still shows up when the container is mounted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/dismiss-toast-bug-ykxptu

1. Press `Add toast` button
2. Press `Dismiss toast` button
3. Press `Toggle container` button to mount container

**What is the expected behavior?**
Toast does not appear when the container is mounted.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested on React 17.0.2, Firefox, Linux. I am not aware that it has ever worked.

**Comment by fkhadra** [comment]
Hey @trylle, thanks for opening the issue. I never thought about this use case before :).  Regarding your PR, it's more a feature than a bug 😆.

**Comment by trylle** [comment]
Thanks for the quick response, @fkhadra. 🙂 I agree it's a bit of a edge case. In our case it did seem like a bug, because we had an unclosable toast (a load indicator) which would sometimes be initiated and dismissed programmatically before the toast container was mounted, and the toast was then left in a stuck/unusable state cluttering the user's view.

Our toast container was in a different part of the component tree from that which triggered the toast, so that exacerbated the issue.
