### ISSUE TITLE
useNotificationCenter with localStorage

### ISSUE THREAD

**Issue by 85ar** [fkhadra/react-toastify#815]
Good afternoon. Tell me please. In my react application, I use useNotificationCenter - that is, your Notification Center. But I need that after refreshing the page (F5) the data is not reset. I tried to do it through localStorage, but when the page is updated, notifications are still reset, because. const { notifications } = useNotificationCenter(). If I do this: const { notifications } = useNotificationCenter(JSON.parse(localStorage.getItem('notifications'))), then it still doesn't work. How can I store all notifications in localStorage correctly?

**Comment by fkhadra** [comment]
Hey @85ar, you have to pass the items to data

```js
const { notifications } = useNotificationCenter({
  data: JSON.parse(localStorage.getItem('notifications')
})
```
