### ISSUE TITLE
If  ToastContainer is created by createPortal, the toast message cannot be closed manually or automatically

### ISSUE THREAD

**Issue by yaoyang2** [fkhadra/react-toastify#817]
If  ToastContainer is created by createPortal, the toast message cannot be closed manually or automatically

**Comment by fkhadra** [comment]
Hey @yaoyang2 could you share a codesanbox with the issue please? Thank you

**Comment by yaoyang2** [comment]
[https://codesandbox.io/s/goofy-sea-j32qmr](url)

**Comment by fkhadra** [comment]
@yaoyang2 your exmaple is not using portal but creating a new react tree
```js
 const container = document.createDocumentFragment();
    const root = ReactDOM.createRoot(container);
    root.render(<ToastContainer />);
```

**Comment by yaoyang2** [comment]
//ok
  const container = document.createElement("div");
  document.body.append(container);
  const portal = createPortal(<ToastContainer />, container);

  //not work
  const container = document.createDocumentFragment();
  const portal = createPortal(<ToastContainer />, container);
  setTimeout(()=> {
    DocumentFragment.body.append(container);
  })

**Comment by fkhadra** [comment]
So it does work with react portal. The issue is coming from `document.createDocumentFragment`. Why are you using a document fragment? This is not working with a `DocumentFragment` because it's not attached to the actual DOM, so the events won't be propagated

**Comment by yaoyang2** [comment]
In my project, I need the ToastContainer to be at the top level of the dom, otherwise the toast message will be obscured
