### ISSUE TITLE
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export. For example: import pkg from 'react'; const { isValidElement, useRef, useLayoutEffect, useEffect, cloneElement, useReducer, useState, forwardRef } = pkg;

### ISSUE THREAD

**Issue by darshantank1995** [fkhadra/react-toastify#820]
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const { isValidElement, useRef, useLayoutEffect, useEffect, cloneElement, useReducer, useState, forwardRef } = pkg;

**Comment by fkhadra** [comment]
Hey @darshantank1995 it would be difficult for me to help you without a reproduction. Repository, setup etc... thanks

**Comment by zephimir** [comment]
I'm having a kinda similar error in a nextjs project with preact as a dep instead of react. Are you having anything similar @darshantank1995?

**Comment by Lodennn** [comment]
Did you fix the problem ?
