### ISSUE TITLE
useNotificationCenter and localStorage

### ISSUE THREAD

**Issue by 85ar** [fkhadra/react-toastify#826]
Good afternoon. In my react application I use useNotificationCenter. I need to make sure that messages and the number of unread messages are stored in localStorage. It is necessary that after reloading the page, you can view messages - read or unread, see the number of messages. And so that after reloading the page, I could again correctly delete messages and make them read. Here is an example code :

```
import React, { useEffect } from "react";
import { useNotificationCenter } from "react-toastify/addons/use-notification-center";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Dash = () => {
  const { clear, markAllAsRead, markAsRead } = useNotificationCenter();
  const { notifications } = useNotificationCenter({
    data: JSON.parse(localStorage.getItem("notifications")),
  });
  const { unreadCount } = useNotificationCenter(
    JSON.parse(localStorage.getItem("unreadCount"))
  );
  const showToast = () => {
    toast("Hello World", {
      data: {
        title: "Hello World Again",
        text: "We are here again with another article",
      },
    });
  };

  const showErrorToast = () => {
    toast.error("Hello World", {
      data: {
        title: "Error toast",
        text: "This is an error message",
      },
    });
  };

  useEffect(() => {
    if (notifications.length !== 0) {
      localStorage.setItem("notifications", JSON.stringify(notifications));
    }
  }, [notifications]);

  useEffect(() => {
    if (unreadCount !== 0) {
      localStorage.setItem("unreadCount", JSON.stringify(unreadCount));
    }
  }, [unreadCount]);

  return (
    <div>
      <p>{notifications.length}</p>
      <button onClick={showToast}>Default</button>
      <button onClick={showErrorToast}>Error</button>
      <br />
      <br />
      <button onClick={clear}>Clear Notifications</button>
      <button onClick={() => markAllAsRead()}>Mark all as read</button>
      <ul>
        {notifications.map((notification: any) => (
          <li
            onClick={() => markAsRead(notification.id)}
            key={notification.id}
            style={
              notification.read
                ? { background: "green", color: "silver", padding: "0 20px" }
                : {
                    border: "1px solid black",
                    background: "navy",
                    color: "#fff",
                    marginBottom: 20,
                    cursor: "pointer",
                    padding: "0 20px",
                  }
            }
          >
            <span>id: {notification.id}</span>
            <p>title: {notification.data.title}</p>
            <p>text: {notification.data.text}</p>
            <p>unreadCount: {unreadCount}</p>
          </li>
        ))}
      </ul>
      <ToastContainer />
    </div>
  );
};
export default Dash;

```

As a result, the 'notifications' messages and the number of 'unreadCount' messages end up in localStorage. After updating the page, they are there. But firstly, the value of the unread Count is displayed incorrectly, and secondly, the delete message buttons and the "make read" button do not work with all old messages. Please tell me how to make the code work correctly with localStorage.

**Comment by fkhadra** [comment]
Hey @85ar,

I made a working example here
[![Edit notification-center-local-storage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-frog-6moocn?fontsize=14&hidenavigation=1&theme=dark)

Now let's deep dive into some explanation to understand what was the issue.

In your case, you were calling `useNotificationCenter` 3 times. It behaves like `useState`, meaning it will give you a fresh state everytime
```js
const { clear, markAllAsRead, markAsRead } = useNotificationCenter();
  const { notifications } = useNotificationCenter({
    data: JSON.parse(localStorage.getItem("notifications")),
  });
  const { unreadCount } = useNotificationCenter(
    JSON.parse(localStorage.getItem("unreadCount"))
  );
```
Instead, we need to call it only once and grab all the info from there.
```js
const {
    clear,
    markAllAsRead,
    markAsRead,
    unreadCount,
    notifications
  } = useNotificationCenter({
    data: JSON.parse(localStorage.getItem("notifications"))
  });
```

Regarding the `unreadCount`, no need to store it. It's computed from the notifications that you've stored. You have to drop this `useEffect`
```js
// This is not needed
useEffect(() => {
    if (unreadCount !== 0) {
      localStorage.setItem("unreadCount", JSON.stringify(unreadCount));
    }
  }, [unreadCount]);
```

I'll probably update the documentation to make it clear that `useNotificationCenter` behave like `useState`

**Comment by 85ar** [comment]
Thank you very much

**Comment by 85ar** [comment]
Yes, everything is working as it should now. But only unreadCount does not work correctly. If we create, for example, 5 notifications (unread Count = 5) and mark 3 of them as read. Then refresh the page, then the unread Count will still show 5, not 2. After all, now we have only 2 unread messages.

**Comment by fkhadra** [comment]
Hey @85ar, the first number uses `notifications.length`, not `unreadCount`. I've updated the example to make it more clear.

https://user-images.githubusercontent.com/5574267/185567209-9fc3a494-87d0-4531-b464-abb0ce64dbef.mov

**Comment by 85ar** [comment]
Now I understand. Thank you

**Comment by 85ar** [comment]
And what should I do if I want to send a message with a link? That is, I want there to be a link in the message, and you can click on it. And then it was in the notification center - so that you could also click on it.
I did something like this:

```
const showToastWithLink = () => {
    toast.info(
      <NavLink to {`/myLink/`}>
        * My link
      </NavLink>,
      {
      data: {
        title: "My link",
        text: (
          <NavLink to {`/myLink`}>
            * My link
          </NavLink>
        )
      },
      hideProgressBar: true,
      autoClose: false,
      transition: Slide,
    });
  };
```

As a result, a message with a link arrives, it appears in the notification center. But if you reload the page and reopen the notification center, an error appears: "Objects are not valid as a React child"

**Comment by fkhadra** [comment]
@85ar I've updated the example
[![Edit notification-center-local-storage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-frog-6moocn?fontsize=14&hidenavigation=1&theme=dark)

Everything that you'll store in the local storage must be serializable. So instead of passing a react component in data, pass an object or a string. 
```js
data: {
        title: "My link",
        link: "your link"
      }
```
Then, when you render your notification center, you can use your nav link component :)
```jsx
<NavLink to={notificaiton.data.link}>My link</Navlink>
```

**Comment by 85ar** [comment]
Thanks. You're helping me a lot. And how can I pass such a link:

```
const [name, setName] = useState('');

 const showToast = () => {
    toast("Hello World", {
      data: {
        link: {
          title: "I'm a link",
          url: `/project/${name}`
        }
      }
    });
  };
```
I get the 'name' variable from the state in the same component and want to pass it as part of the link.
And then in the notification center:

```
{notification.data.link && (
              <p>
                <NavLink link={notification.data.link} />
              </p>
            )}

```

**Comment by fkhadra** [comment]
Hey @85ar, indeed it should work with the code above.

**Comment by 85ar** [comment]
> @85ar I've updated the example [![Edit notification-center-local-storage](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/mystifying-frog-6moocn?fontsize=14&hidenavigation=1&theme=dark)
> 
> Everything that you'll store in the local storage must be serializable. So instead of passing a react component in data, pass an object or a string.
> 
> ```js
> data: {
>         title: "My link",
>         link: "your link"
>       }
> ```
> 
> Then, when you render your notification center, you can use your nav link component :)
> 
> ```js
> <NavLink to={notificaiton.data.link}>My link</Navlink>
> ```

Found a problem. If you clear all notifications and reload the page, then all the same notifications are loaded into the notification center anyway. They are not cleared from localStorage

**Comment by fkhadra** [comment]
@85ar this is happening because we only touch the localstorage when there are some notifications
```js

 useEffect(() => {
    if (notifications.length !== 0) {
      console.log(notifications);
      localStorage.setItem("notifications", JSON.stringify(notifications));
    }
  }, [notifications]);
```

Just clear the localstorage when you clear all notifications
```js
const clearNotificationCenter = () => {
  clear();
  localStorage.deleteItem("notifications")
}

<button onClick={clearNotificationCenter}>Clear Notifications</button>
```

**Comment by 85ar** [comment]
Awesome Everything works. Just need it like this:
`localStorage.removeItem("notifications")`
Thank you.

**Comment by 85ar** [comment]
There is such a task. A certain function triggers the creation of data on the backend. The result is recorded as a response when a get request is sent to the endpoint. After starting the function, I need to knock on the endpoint, and depending on the status, output first: the process is started, the process is successfully completed or an error.

```
const myFunction = () => {
  ...
  myPromise(id);
}

async function myPromise(myId: number) {
  const toastId = toast.loading("Loading data");
  const response = await myService.getStatus({
    params: {
      id: myId,
    },
  });
  if(response.status === 'running') {
    toast.update(toastId, {
      render: () => 'In progress',
      type: 'info'
    })
  }
  if(response.status === 'success') {
    toast.update(toastId, {
      render: () => 'Done',
      type: 'success'
    })
  }
}
```

I don't understand how in this case I can send a get request to the endpoint several times, change the toast status in the process and stop the request after the status becomes success. But in this example, I only make a get request once, and that's wrong.

**Comment by bogdan-ivan** [comment]
> @85ar I've updated the example [![Edit notification-center-local-storage](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/mystifying-frog-6moocn?fontsize=14&hidenavigation=1&theme=dark)
> 
> Everything that you'll store in the local storage must be serializable. So instead of passing a react component in data, pass an object or a string.
> 
> ```js
> data: {
>         title: "My link",
>         link: "your link"
>       }
> ```
> 
> Then, when you render your notification center, you can use your nav link component :)
> 
> ```js
> <NavLink to={notificaiton.data.link}>My link</Navlink>
> ```

Hi @fkhadra , in your example the toasts have ids like `8be8n2m`, but in my app using v9.1.3 I have incremental digit ids starting from 1. I don't see you setting a custom toastId anywhere, so what is happening and how can I get ids like yours ?

Also in your example, when you press `Mark all as read` everything works fine using JSON.stringify and JSON.parse, but for me using your example, I get the following error: 
`Converting circular structure to JSON
    --> starting at object with constructor 'HTMLButtonElement'
    |     property '__reactFiber$ha0mbdyiw17' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle`
How to get around this ?
