### ISSUE TITLE
Notification content not showing in toast

### ISSUE THREAD

**Issue by znat** [fkhadra/react-toastify#827]
Hi there :) 

**Do you want to request a *feature* or report a *bug*?**
A bug or a question

**What is the current behavior?**
I simply npm installed and implemented as follows:

```
return (
    <Admin>
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <form onSubmit={handleSubmit(onSubmit)}>
        ...
      </form>
    </Admin>
  );
```
But the toast content is directly shown in the page
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3694634/185356483-48dda342-f560-4966-8d69-8c45fef05bce.png">

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest versions, using next.js

**Comment by fkhadra** [comment]
@znat looks like you didn't import the required CSS
```js
  import { ToastContainer, toast } from 'react-toastify';

  import 'react-toastify/dist/ReactToastify.css';
```
