### ISSUE TITLE
react-toastify v9.0.8 autoClose not working on update

### ISSUE THREAD

**Issue by JoyCood** [fkhadra/react-toastify#830]
here is the code on [sandbox](https://codesandbox.io/s/react-toastify-update-bug-forked-or7iq7?file=/src/index.js)

**Comment by fkhadra** [comment]
Hey @JoyCood , when transitioning from `loading` to `update` you have to explicitly tell that the notification is not loading anymore
```js
    toast.update(id, {
      render: "New content",
      type: toast.TYPE.INFO,
      autoClose: 10000,
     // the important part
      isLoading: false
    });
```
