### ISSUE TITLE
`onChange` callback `data` type definition

### ISSUE THREAD

**Issue by alexandredev3** [fkhadra/react-toastify#837]
**Awesome tool!**

Currently, the type of the `onChange` callback data is always an empty object, so if you try to access any prop from the data object, Typescript would complain.
![image](https://user-images.githubusercontent.com/61118233/188314613-895dfe6f-067c-469c-a53b-e70aff43876f.png)

It would be nice if the `onChange` method accepted a generic to type the `data` object.
![image](https://user-images.githubusercontent.com/61118233/188314757-3ca70641-40f7-48d0-ad44-aa95afab5cf8.png)

**I'm willing to open a PR to implement this!**

**Comment by fkhadra** [comment]
Hey @alexandredev3, glad you like it. You can do as follow :) 

```tsx
import { toast } from "react-toastify";
import type { ToastItem } from "react-toastify";

interface MyData {
  someProps: string;
}

toast.onChange((toastItem: ToastItem<MyData>) => {
  console.log(toastItem.id, toastItem.content);
 console.log(toastItem)
});

``` 

This is documented here https://fkhadra.github.io/react-toastify/listen-for-changes/
