### ISSUE TITLE
closeOnClick cursor

### ISSUE THREAD

**Issue by JBaczuk** [fkhadra/react-toastify#839]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `closeOnClick` is set to `false` the cursor is still a pointer, indicating that the toast can be clicked.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
[https://codesandbox.io/s/trusting-cdn-zcxqxf?file=/src/App.js](https://codesandbox.io/s/trusting-cdn-zcxqxf?file=/src/App.js)

**What is the expected behavior?**
The cursor is a normal (default) cursor.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I don't know, but for sure `18.2.0`

**Comment by fkhadra** [comment]
Thanks for reporting this issue, makes total sense :)
