### ISSUE TITLE
Allow for relatively positioned toasts

### ISSUE THREAD

**Issue by ecirish** [fkhadra/react-toastify#84]
It may break the 'toast' paradigm, but the ability to use a toast more like a banner would be nice. It would minimally involve positioning the `ToastContainer` relatively from what I can tell in my tinkering.

**Comment by fkhadra** [comment]
Hey @ecirish,

I'm not sure to understand correctly what do you mean. When you said more like a banner, you are thinking about something like that ?
<img width="807" alt="screen shot 2017-11-29 at 20 08 23" src="https://user-images.githubusercontent.com/5574267/33394033-55868422-d541-11e7-9ddc-cae942210aed.png">

Please correct me if I'm wrong.

**Comment by ecirish** [comment]
Well, I think we're on the same page then? A little hard to see without context. Basically the toast div having `position: relative` instead of position fixed? Just so that you can put it below and attach it to, say, your nav header instead of _on top_ of it?

**Comment by fkhadra** [comment]
Hey @ecirish,

You can already override the position from `fixed` to `relative`, you can pass a className or use glamor for that:

```js
import { css } from "glamor";

const containerStyle = css({
  position: "relative"
});

// pass it to ToastContainer
<ToastContainer className={containerStyle} />
```

**Comment by ecirish** [comment]
Ah, great. Thank you!
