### ISSUE TITLE
Toaster is reappearing even it is manually closed

### ISSUE THREAD

**Issue by haripriya9209** [fkhadra/react-toastify#840]
I am using react-Toastify for displaying a toaster when my app goes offline mode. To detect offline mode, I am using react-detect-offline. I am successfully able to display the toaster in offline mode, but the toaster is reappearing on click on the cross button. On click on the cross button For the 3rd reappeared toaster message, the toaster message completely disappears. Attaching sandbox with my code, to reproduce the issue (make sure you are in offline mode): https://codesandbox.io/s/modest-oskar-jq2ust?file=/src/App.js

**Comment by waellaataoui** [comment]
Any news with this issue, I feel like it's not getting enough attention. This is probably a bug related to react 18. 😞

**Comment by haripriya9209** [comment]
Yeah may be

**Comment by fkhadra** [comment]
Hey @haripriya9209! A few remarks, you should render the `ToastContainer` directly and also avoid calling `notify` during rendering

```js
// avoid this, not needed
const DisplayToaster = () => {
    // notify();
    return <ToastContainer position="top-right" autoClose={false} limit={1} />;
  };


// Instead render the container like any other components

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <ToastContainer position="top-right" autoClose={false} limit={1} />

      <Offline onChange={notify}>{console.log("offline")}</Offline>
    </div>
  );
``` 

https://user-images.githubusercontent.com/5574267/194726882-d568ea7b-a794-4963-986e-e526c5050c53.mov
