### ISSUE TITLE
toast.promise - can't hide the spinner animation during pending

### ISSUE THREAD

**Issue by salmanQualogy** [fkhadra/react-toastify#841]
Not sure if this is possible with this package but I am trying to hide the spinner animation when pending a promise resolve.

Cant hide the animation with package props

**What is the expected behaviour?**
Using a prop to hide the spinner animation during resolve

Is it possible and yes how?

**Comment by halvor07** [comment]
```js
const resolveAfter3Sec = new Promise((resolve) => setTimeout(resolve, 3000));
toast.promise(resolveAfter3Sec, {
  pending: { render: 'Promise is pending', icon: false },
  success: { render: 'Promise resolved', icon: true },
  error: { render: 'Promise rejected', icon: true },
});
```
