### ISSUE TITLE
Close toast by clicking anywhere outside

### ISSUE THREAD

**Issue by datainvestor** [fkhadra/react-toastify#842]
Is there a way to close the Toast by clicking anywhere outside the toast itself? Can't find this in documentation and not sure what should be the best approach when implementing custom solution for that?

**Comment by fkhadra** [comment]
Hey @datainvestor, there are several ways to achieve that based on your needs. For example, you could do something like

```js
function notify() {
    toast("hello");
    // after displaying the toast, we attach a click event to the body
   // it will remove all the toats
    document.body.addEventListener("click", toast.dismiss, {
      once: true
    });
  }

<button onClick={notify}>Notify</button>

```
