### ISSUE TITLE
Toast must stay if hovered !

### ISSUE THREAD

**Issue by gvkhirwadkar** [fkhadra/react-toastify#845]
****************************************************************** BUG ***********************************************************

CURRENT BEHAVIOUR - 

If the user hovers on toast message it pauses and stays in same position unless user hovers out !

Now if the user clicks on some action repeatedly, it results in showing several toast message.

Let us suppose there were 10 toast messages and user hovers on 3 one from TOP (Stack) then the third one will stop the timer but as soon as the other toast messages (4 to 10 in stack ) completed their timer they will disappear and leave the void space which will push this toast message (3rd one on which user hovered) to the last position due to which hovering will be lost and timer will start and toaster will go off the screen !

EXPECTED  BEHAVIOUR - 

This is not expected the toast message should stay at same position and other toast messages should not interfere with its functionality (here hovering in)

Hoping the team will resolve this issue.

**Comment by gvkhirwadkar** [comment]
Hello Fkhadra/React-Toastify,

Did we fix the issue or just closed it ??

**Comment by fkhadra** [comment]
Hey, I've closed the issue as no reproduction was provided. I can reopen it as soon as I get a codesandbox

**Comment by gvkhirwadkar** [comment]
Oh I was not aware of that, will share the code sandbox link
