### ISSUE TITLE
Dispatch toast outside of react component doesn't work, it isn't showing

### ISSUE THREAD

**Issue by fanorenantsoa** [fkhadra/react-toastify#846]
I followed the instructions here https://fkhadra.github.io/react-toastify/dispatch-toast-outside-of-react-component/

Then when I switch browser to offline (in Applicaiton tab of dev tools), no toast was appear.

Any idea please ?

**Comment by fkhadra** [comment]
Hey @fanorenantsoa, sorry but I cannot help without a repo or a reproduction. You can reproduce your issue in codesanbox and share it there
