### ISSUE TITLE
Two toast overlapping issue while we have used Two or more containers

### ISSUE THREAD

**Issue by asif-simform** [fkhadra/react-toastify#848]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When we have two containers and at a time while displaying toast from both container toast are overlapped.

Container One Toast - Click here to add more details...
Container Two Toast - Your profile has been updated

<img width="208" alt="overlapp" src="https://user-images.githubusercontent.com/62657766/194234133-0054ca34-41ee-4c8c-ad9c-26f50ac10eda.png">

When will display the toast from different containers face the overlapping issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Reproduce step:

When we have two containers and at a time while displaying toast from both container toast are overlapped.

Container One Toast - Click here to add more details...
Container Two Toast - Your profile has been updated

<img width="208" alt="overlapp" src="https://user-images.githubusercontent.com/62657766/194234133-0054ca34-41ee-4c8c-ad9c-26f50ac10eda.png">

When will display the toast from different containers face the overlapping issue.

**What is the expected behavior?**
Toast should not be overlapped

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React - 17.0.2
browser / OS - Chrome latest (Version 106.0.5249.91 (Official Build) (arm64))
Did this work in previous versions of React? - Nope

**Comment by fkhadra** [comment]
Hey @asif-simform any reason to use multiple containers instead of one?

**Comment by asif-simform** [comment]
Hi @fkhadra 

I've some special requirements and cases so I need to use multiple containers instead of one for handling the stuff.

**Comment by fkhadra** [comment]
Hey @asif-simform, in your case both containers use the same position, hence the overlapping issue. Honestly, I don't think I'll fix this issue, the amount of work needed for it is not worth IMO.

In general, I advise against using multiple containers. Most of the time having just one container is enough. May I ask you to share your special requirements, so I could maybe help you

**Comment by asif-simform** [comment]
Hi @fkhadra 

Thanks for the update. I've fixed this issue on my end writing some CSS on the wrapper class and its working as expected.

Example :

```
<div className='custom-toast'>
    <ContainerOne />
    <ContainerTwo />
</div>
```

```
.custom-toast {
  ...some CSS
}
```

**Comment by fkhadra** [comment]
Hey @asif-simform thanks for the update. Do you mind sharing your CSS ? So anyone facing the same issue as you might use your solution.

**Comment by fkhadra** [comment]
Thanks for sharing
