### ISSUE TITLE
useNotificationCenter redirect issue

### ISSUE THREAD

**Issue by bhorc** [fkhadra/react-toastify#850]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When going to any other page, useNotificationCenter does not save data.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Notification fields are empty, as well as the badge counter.
Example: https://codesandbox.io/s/mui-notification-center-forked-rws1wi?file=/index.tsx

**What is the expected behavior?**
That alert data will continue to be stored in a storage.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: v18.2.0
Browser: Opera (91.0.4516.65)
OS: Windows 10 64-bit

**Comment by fkhadra** [comment]
Hey @bhorc, you have to hydrate the notification center, here is an example using localStorage. 
[![Edit notification-center-local-storage](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/notification-center-local-storage-6moocn?fontsize=14&hidenavigation=1&theme=dark)

The data can come from anywhere as long as there are serializable and have the correct shape :)

**Comment by bhorc** [comment]
thank you very much for the answer, I apparently haven’t fully figured out the module yet, I didn’t know that it was possible
