### ISSUE TITLE
Clsx is not a function

### ISSUE THREAD

**Issue by scrumptiousdev** [fkhadra/react-toastify#854]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error thrown as below:
```
react-toastify.esm.mjs:1035 Uncaught TypeError: clsx__WEBPACK_IMPORTED_MODULE_1__ is not a function
    at getClassName (react-toastify.esm.mjs:1035:1)
    at react-toastify.esm.mjs:1068:1
    at react-toastify.esm.mjs:549:1
    at Function.from (<anonymous>)
    at getToastToRender (react-toastify.esm.mjs:549:1)
    at react-toastify.esm.mjs:1062:1
    at renderWithHooks (react-dom.development.js?45b9:14985:1)
    at updateForwardRef (react-dom.development.js?45b9:17044:1)
    at beginWork (react-dom.development.js?45b9:19098:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?45b9:3945:1)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Current setup is running with vite and typescript

**What is the expected behavior?**
No error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@17.0.2
react-toastify@9.0.8

**Comment by fkhadra** [comment]
Hey @scrumptiousdev, I believe your issue is coming from your setup, could you share a repo with the reproduction or a codesanbox? Thank you
