### ISSUE TITLE
Make the zIndex of the Toast container to be maximum

### ISSUE THREAD

**Issue by nimish-gupta** [fkhadra/react-toastify#86]
Make the zIndex of the Toast container to be maximum so that it always come at top of the components, we can prevent this behaviour by adding a flag 

https://github.com/fkhadra/react-toastify/blob/32b27454fcd2ad90bbd4fc4703793bba05e5b6b7/src/ToastContainer.js#L21

**Comment by fkhadra** [comment]
Hey @nimish-gupta,

For the next release, this is the case. I'll launch it today
