### ISSUE TITLE
Not working with rails cssbundling-rails and jsbundling-rails

### ISSUE THREAD

**Issue by benlieb** [fkhadra/react-toastify#860]
In this setup css (usually scss) is imported outside of react components.

I have two options for importing `import "react-toastify/dist/ReactToastify.css"`, importing css into react component, or into the scss file, but neither work for me.

When I import into react component, all my other css is overwritten (I think) and no styles apear on my page, except the toast notification works and has proper styles.

When I import via @import in scss file, I have varified that the CSS is indeed imported, but the styles are not applied to the toast component, and seemingly no behavior either.

I'm not quite sure what is going on here, but it's a bummer. I'd really like to use this library, but I've had to settle for a different option that works out of the box.

Help?

**Comment by fkhadra** [comment]
Hey @benlieb, sorry to hear that. I'm not familiar with your stack at all. Could you share a repo, so maybe I'll be able to help?
