### ISSUE TITLE
sh: parcel: command not found

### ISSUE THREAD

**Issue by sarahsga** [fkhadra/react-toastify#862]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

`yarn run start` fails with error `sh: parcel: command not found`

Steps to reproduce:
1. Clone the project: `git clone https://github.com/fkhadra/react-toastify.git`
2. `cd react-toastify`
3. `yarn install`
4. `yarn setup`
5. `yarn start`. This should fail with the following error message:

<img width="564" alt="Screenshot 2022-10-26 at 10 44 31 PM" src="https://user-images.githubusercontent.com/10798986/198101020-e472fe8d-0036-44bf-9bfc-327970bd1ebd.png">

This causes confusion for someone new to the repo, trying to follow the [Contribution guidelines](https://github.com/fkhadra/react-toastify/blob/main/CONTRIBUTING.md) to setup the repo and launch the playground for the first time.

**What is the expected behavior?**
`yarn start` should complete successfully so that the playground could be opened on the browser.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React Version N/A
MacOS

**Comment by fkhadra** [comment]
This is happening because you need to install the packages first, the documentation is lacking. We should consider adding a readme :0
