### ISSUE TITLE
[next-i18next] 9.0.8 -> 9.1.0: Type 'unknown' is not assignable to type 'never'.

### ISSUE THREAD

**Issue by Zerebokep** [fkhadra/react-toastify#869]
My toast() calls complain about the type now, especially when using next-i18next's t():

toast(t('test.test'))

casting to string works, but isn't that pretty. Any chance to get the old behaviour back or was this a typescript optimization?

```
Argument of type 'ToastContent<never>' is not assignable to parameter of type 'ToastContent<unknown>'.
  Type '(props: ToastContentProps<never>) => ReactNode' is not assignable to type 'ToastContent<unknown>'.
    Type '(props: ToastContentProps<never>) => ReactNode' is not assignable to type '(props: ToastContentProps<unknown>) => ReactNode'.
      Types of parameters 'props' and 'props' are incompatible.
        Type 'ToastContentProps<unknown>' is not assignable to type 'ToastContentProps<never>'.
          Type 'unknown' is not assignable to type 'never'.
```

**Comment by fkhadra** [comment]
Hey @Zerebokep, I'm investigating the issue. It's really strange though.

```tsx
// OK
 const tt = t("foo")
 toast(tt)

// NOK
toast(t("foo"))

// OK
function x(){ return 'hello' }
toast(x())
```

 Anyway I'll push a fix :)

**Comment by fkhadra** [comment]
@Zerebokep while I figure out the proper fix you can do  write `toast<void>(t("foo"));` instead of using type assertion.

**Comment by fkhadra** [comment]
So, after checking the source of next-i18next, they added `extends infer A ? A : never` as a workaround for this issue https://github.com/i18next/react-i18next/issues/1222.

Still investigating what would be a proper fix and if it needs to be fixed.

```tsx
/**
 * Due to a limitation/bug on typescript 4.1 (https://github.com/microsoft/TypeScript/issues/41406), we added
 * "extends infer A ? A : never" in a few places to suppress the error "Type instantiation is excessively deep and possibly infinite."
 * on cases where users have more than 22 namespaces. Once the issue is fixed, we can remove all instances of the workaround used.
 *
 * Reference of the bug reported: https://github.com/i18next/react-i18next/issues/1222
 */
```

**Comment by Zerebokep** [comment]
Really appreciate your effort, you rock.

**Comment by raulcrisan** [comment]
Hey guys, any news regarding this issue? When will be available a version with this fix?

**Comment by Zerebokep** [comment]
next-i18next v13 seems to fix this issue.

**Comment by fkhadra** [comment]
Thanks for the update. I'll close the issue
