### ISSUE TITLE
Correct Ts for the toastify module

### ISSUE THREAD

**Issue by nimish-gupta** [fkhadra/react-toastify#87]
using `type.position`, ts is throwing error `Property position does not exist on type Toast`

**Comment by fkhadra** [comment]
Hey @nimish-gupta,

Indeed `type.position` doesn't exist. toast expose a `POSITION` property than can be accessed like:
```js
toast.POSITION.BOTTOM_RIGHT //helper to set the position
```
And if you want to set the position for a toast you can do the following:
```js
toast("hello", {
position: toast.POSITION.BOTTON_RIGHT
});
```

**Comment by nimish-gupta** [comment]
@fkhadra even `toast.POSITION` is also giving the same error `Property POSITION does not exist on type TOAST`
