### ISSUE TITLE
Style property applied to toast container and toast itself

### ISSUE THREAD

**Issue by reinfi** [fkhadra/react-toastify#870]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Style Property is applied twice since 9.1.0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/react-toastify-style-error-sksr4h

**What is the expected behavior?**

The margin top property should not applied to the toast container and the toast itself. Documentation is not quite specific what the style property should affect. But as it is set on the toastContainer it should be only set on the container itself.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Every react version.

**Comment by reinfi** [comment]
This was changed here https://github.com/fkhadra/react-toastify/pull/763but I would say the implementation is not correct. Toast Container styles should not be propagated to the toast.

**Comment by fkhadra** [comment]
Hey @reinfi thanks for reporting the issue. I've published a new version with the fix v9.1.1

**Comment by reinfi** [comment]
Thanks for the fast response! great library!
