### ISSUE TITLE
onClick()	Called when click inside Toast notification of body only

### ISSUE THREAD

**Issue by robin-plus-peter** [fkhadra/react-toastify#871]
**Do you want to request a *feature* or report a *bug*?**
i want to onClick onClose both as same time but onClick should not called with i click on close button.

**What is the current behavior?**
but with current implementation if pass a callback function onClick of toast notification it also called when i click on close button.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

if someone click on body of toast then call onClick and if someone click on close button call onClose.

**What is the expected behavior?**
but with close button i don't want to invoke the onClick function.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
    "react": "^17.0.2",
chome/Mac OS

**Comment by fkhadra** [comment]
Hey @robin-plus-peter, `onClick` and `onClose` callbacks will be removed in the next major release. A solution for your use case would be [![Edit onclick-with-closeOnClick](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-glitter-y4hhlz?fontsize=14&hidenavigation=1&theme=dark)

Hope it helps
