### ISSUE TITLE
Dismiss click passes event through and causes Modal to close incorrectly

### ISSUE THREAD

**Issue by uicrafts** [fkhadra/react-toastify#876]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a Modal is rendered using HeadlessUI React, and a toast is dismissed manually by clicking on the X button, **it causes the modal to close as well**.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

Codesandbox: https://codesandbox.io/s/react-toastify-headlessui-modal-2xt3bz?file=/src/App.tsx

1. Click to open Modal
2. Click button to trigger toast
3. Click X button on toast to dismiss it
4. Both toast AND modal will close. The `onClose` handler on the Modal is being called, and this seems like a bug

**What is the expected behavior?**

Only the toast should close, NOT the modal.

I even tried the multi container feature, but the same issue/behavior is observed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
See Codesandbox. React 17, latest version of `react-toastify`

**Comment by fkhadra** [comment]
This is not an issue with react-toastify but more likely with your implementation. 
When you close the toast, the event is propagated, and at some point, it's catched by the Modal, hence removing it. 
By default, the state of the modal(visible or not) is managed internally. In your case, you must use the `static` props see https://headlessui.com/react/dialog#dialog.
