### ISSUE TITLE
ToastContainer autoclose callback

### ISSUE THREAD

**Issue by a03z** [fkhadra/react-toastify#879]
Feature request

autoClose currently accepts number value

Basically, the idea is to make it accept either number or callback with an argument of message we want to put in notification. 
`autoClose={(message) => { if (message.length > 50) {return 5000} else { return 3000 } }`
or just `autoClose={3000}`

This way, it will be one line of code instead of checking the length of the message string in every single use.

**Comment by dagbay** [comment]
Hey, is anyone working on this feature? If not, I'd like to contribute by doing this. Unless you are @a03z 😄

**Comment by fkhadra** [comment]
Hey, this is not something we will implement. Thank you for your understanding!
