### ISSUE TITLE
Glamor in v3.*

### ISSUE THREAD

**Issue by kbrtrm** [fkhadra/react-toastify#88]
Hey there, looking to use `react-toastify` and I see that `glamor` is now a dependency with `v3.*`. We won't be using `glamor` in our project because we already have a css solution and don't want to pull it in for just one package. Is there a way to use `react-toastify` without `glamor`?

**Comment by fkhadra** [comment]
Hey @kbrtrm ,

Sorry to hear that. Unfortunately, if you want to use `react-toastify` without glamor you have to stick with the `v2` but you will miss the next updates.

Which css solution are you using ?

**Comment by kbrtrm** [comment]
Bummer! Optional glamor would've been great. We're still employing a more traditional CSS approach and our CSS-in-JS situation is still in flux.
