### ISSUE TITLE
pauseOnHover: true works only when hovering on close button

### ISSUE THREAD

**Issue by IIARROWS** [fkhadra/react-toastify#881]
Calling the toast with `autoClose` and `pauseOnHover` doesn't pause the timer.
It works only when hovering the close button.

**What is the current behaviour?**
https://codesandbox.io/s/compassionate-raman-qj5qdm?file=/src/App.js

**What is the expected behaviour?**
It doesn't close when hovering on the whole toast notification.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 17.0.2, but the same behaviour can be observed in the sandbox with 18.2.0.
It works on **react-toastify 9.0.7-fix-autoclose-2** (surprised pikachu). I'm not sure why this is not present on the current version

**Comment by IIARROWS** [comment]
I need pretty urgent, but I can't even find the branch or commit that generated the working version to see what's the difference.

**Comment by fkhadra** [comment]
Could it be that you have a cache issue on your side. I tested your example and the issue is not present.

https://user-images.githubusercontent.com/5574267/224219282-ce2b6ec8-d1d0-463d-ac85-8dab30800633.mov
