### ISSUE TITLE
Close all button at then end of the nofication

### ISSUE THREAD

**Issue by jeevasusej** [fkhadra/react-toastify#886]
Do we have any feature like,
If we have more than one but, need to show button at the bottom of the message to close the notification?

**Comment by Mohammadxoja2005** [comment]
This is actually good idea but queue limit has been added where you can control max number of notifications. And the question is, do we need this feature?

**Comment by jeevasusej** [comment]
Yes I need this feature. Can we do any customization by our own without expecting the plugin to implement this?

![image](https://user-images.githubusercontent.com/19813131/206836358-6279734d-6513-434b-9278-a1fdf86daa80.png)

**Comment by andreuka** [comment]
Definitely need that

**Comment by fkhadra** [comment]
Closing as it can be easily implemented on the user land.
