### ISSUE TITLE
How do I implement the "flip" transition?

### ISSUE THREAD

**Issue by benlieb** [fkhadra/react-toastify#890]
The demo shows a UI to make the tost flip instead of bounce, but when selected, the code doesn't actually change. So not sure how to implement the flip...

Also fyi I'm using the `toast()` method to send config...

Please help thanks!

**Comment by VoitihovichP** [comment]
I just used Flip and it works. Can you give a screenshot with your ToastContainer code?

**Comment by VoitihovichP** [comment]
> The demo shows a UI to make the tost flip instead of bounce, but when selected, the code doesn't actually change. So not sure how to implement the flip...
> 
> Also fyi I'm using the `toast()` method to send config...
> 
> Please help thanks!

I just used Flip and it works. Can you give a screenshot with your ToastContainer code?

**Comment by 1sonjm** [comment]
Use like this.
Specify the transition prop and import flip and set it.

```reactjs
import { Flip, ToastContainer } from 'react-toastify'

function App({ Component, pageProps }: AppProps) {

	return (
		<div className={classes.app}>
			<ToastContainer
				position="bottom-right"
				autoClose={5000}
				draggable={false}
				closeOnClick={false}
				transition={Flip}
			/>

			<Component {...pageProps} />
		</div>
	)
}
```
