### ISSUE TITLE
Document using options with toast.promise (WAS: toast.promise doesn’t work with multi containers.)

### ISSUE THREAD

**Issue by guillaumebrunerie** [fkhadra/react-toastify#901]
EDIT: it works fine, the issue was that I thought the `containerId` needed to be supplied as part of the second argument. I couldn’t see it documented anywhere on the website though, so I think it should be.

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

`toast.promise` doesn’t seem to work with multi containers, toasts just do not show up at all and there is no error message. See the example here
https://codesandbox.io/s/weathered-field-80hh9u?file=/src/App.js
Only the toast without a promise shows up.
When removing `enableMultiContainer`, both toasts show up (but of course then it wouldn’t work with several containers).

**What is the expected behavior?**

It should work just fine to use `toast.promise` together with `enableMultiContainer`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 18.2.0, react-toastify 9.1.1, and I'm on Mac OS with Chrome.
But I assume it affects all OSs/browsers/versions.

**Comment by guillaumebrunerie** [comment]
Actually it works, it’s just that the `options` argument is the third one :)
But I couldn’t find anywhere in the docs an example of `toast.promise` using options, maybe this should be documented somewhere?

**Comment by fkhadra** [comment]
Cool I'll close the issue and add a doc label so it can be added
