### ISSUE TITLE
Make it possible to specify the window in which to inject the styles with `inject-styles`

### ISSUE THREAD

**Issue by guillaumebrunerie** [fkhadra/react-toastify#902]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the expected behavior?**

I’m trying to use react-toastify in a multi-window app (windows are open with `window.open` and render a subtree using React portals). The issue I’m having is that I need to inject the styles in all windows but there doesn’t seem to be a way to do that.

Hence my feature request: make `inject-styles` take an optional argument of type `typeof window` to specify in which window to inject the styles (defaulting to `window`, of course).

**Comment by fkhadra** [comment]
v11 will drop inject style and the style will be injected automatically.
