### ISSUE TITLE
Missing css file

### ISSUE THREAD

**Issue by simondevries** [fkhadra/react-toastify#91]
I just pulled the source using npm install react-toastify and I am getting the error that 'react-toastify/dist/ReactToastify.min.css' cannot be found. I have looked in the dist folder and cannot find any css file. I also looked in the Github repo and cannot find any css file

**Comment by simondevries** [comment]
It looks like you don't even need to specify the css file! Maybe the docs need updating?

**Comment by fkhadra** [comment]
Hey @simondevries,

Actually the doc on github is up to date. But the one on the demo is deprecated.

Im working on it !
