### ISSUE TITLE
StackedContainer progress

### ISSUE THREAD

**Issue by reinos** [fkhadra/react-toastify#912]
Hi there,

According to the documentation, there will be a StackedContainer addon released (https://fkhadra.github.io/react-toastify/migration-v9/#stacked-toasts). Any ETA on this addons?

**Comment by fkhadra** [comment]
Hey, I'll be off in 1 week and half, which means that I've have time to focus on open source stuff again :), but I cannot promise any release date so far but I'll do my best

**Comment by nareshpingale** [comment]
Hi, any active branch where this is being worked upon ?  @fkhadra

**Comment by mzovag** [comment]
Hi! Could you clarify when would be release for a StackedContainer?

**Comment by fkhadra** [comment]
Hey I'm actively working on it. Not pushed yet. https://github.com/fkhadra/react-toastify/pull/968. I'm currently rewriting all tests to use component testing

**Comment by fkhadra** [comment]
Any volunteer to try a beta version ?

**Comment by alexandernst** [comment]
@fkhadra Me! Are there any breaking changes? Do you plan on releasing the beta on npm?

**Comment by mzovag** [comment]
Good afternoon! I'm on vacation right now, but as soon as I will get home,
I will test and check it and write a feedback for u

вт, 1 авг. 2023 г., 20:36 Alexander Nestorov ***@***.***>:

**Comment by fkhadra** [comment]
Thanks a lot, @alexandernst @mzovag. I'll finish wrapping up 2,3 things. Then push a package tomorrow or Friday. I keep you posted

**Comment by fkhadra** [comment]
Hey @lucasspra thanks for asking, we are currently using `react-toastify@beta`(v10) and haven't noticed any issue so far. TBH, the code is done but I still need to update the documentation. Fortunately, I'm off starting today so I'll be able to finish the doc and release it ASAP. I cannot give an exact date but I'll do my best to ship it for the last week of october of first of november. 
You can already try the beta to share your feedback
