### ISSUE TITLE
Keep onClick or provide alternative to achieve the same for whole toast

### ISSUE THREAD

**Issue by cduff** [fkhadra/react-toastify#913]
I see that `onClick` has been marked as deprecated, to be removed in the next major release. This is worrying as I'm using it in a way that doesn't seem achievable via the suggested alternative.

I currently use `react-toastify` toasts as part of a service worker update process. Once the underlying service worker is updated, a toast is displayed asking the user to 'click here to update', which just refreshes the page.

I've created a CodeSandbox to demonstrate: https://codesandbox.io/s/react-toastify-onclick-cbnhl5?file=/src/App.js

The "notify (current method)" button demonstrates how it currently works, using the deprecated method. The "notify (suggested new method)" button demonstrates how it would work under the suggested alternative approach, which isn't ideal as it's better for the user to be able to click anywhere on the toast.

**Comment by herzog0** [comment]
Totally agree! I'm having to make my inner div larger to increase the chance that the user clicks in a clickable area.

**Comment by fkhadra** [comment]
@cduff @herzog0 I'll keep this feature, I'll remove the deprecation notice in v10
