### ISSUE TITLE
Background tabbed window delays display; Multiple toasts when limit and delay set

### ISSUE THREAD

**Issue by gudlyf** [fkhadra/react-toastify#919]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. When a toast is set to display in a Chrome or Firefox tab, and one clicks on another tab before that toast displays, coming back to the tab will display all queued toasts.
2. If a `limit` of toasts is set and a `delay` is set for the toast, it displays twice.

CodeSandbox: https://codesandbox.io/s/infallible-cannon-tqk2dh?file=/src/App.jsx

(Note when clicking any "With Delay" button, then opening a new browser tab and waiting over 5 seconds, then coming back to the CodeSandbox tab, you will see the toast appear as if it just got triggered.)

**What is the expected behavior?**

1. A tab that is not active should be considered out-of-focus and not queue up toasts. If the user did not have the tab active, it should not display toasts and be considered out of focus.
2. Toasts should not display multiple times if a `limit` is set.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 8.2.0

Browsers tested: Firefox 109.0.1 (Mac OS), Chrome 110.0.5481.100 (Mac OS)

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!
