### ISSUE TITLE
toast.update: reseting option with null to inherit it from toastContainer ignores toastContainer props

### ISSUE THREAD

**Issue by mrudowski** [fkhadra/react-toastify#921]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
in version higher then 9.0.8 when using `toast.update` and reseting option with null to inherit it from toastContainer we ignore toastContainer props

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

complete codesandbox example:
https://codesandbox.io/s/toast-update-113fjb?file=/src/App.jsx

**What is the expected behavior?**
like in 9.0.8 version and in docs where we can reset an option by passing null

docs:
https://fkhadra.github.io/react-toastify/update-toast#reset-option-or-inherit-from-toastcontainer

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
all version of react/browser/os

**Comment by fkhadra** [comment]
Hey @mrudowski, first of all, thanks a lot for reporting the issue with the details and the reproduction. This really helps a lot as a maintainer 🙏 .
The root cause of this issue is the same as #920. I have a fix ready already.
