### ISSUE TITLE
Transitions are dropped for fast promises

### ISSUE THREAD

**Issue by Svish** [fkhadra/react-toastify#922]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `notify.promise` the default bounce-transition seems to be ignored/skipped/dropped whenever the promise completes "too quickly". This makes the notification much less noticeable. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/vibrant-maria-g5ki1b?file=/src/App.js

**What is the expected behavior?**

The toast should bounce regardless of how fast the promise completes.

**Comment by fkhadra** [comment]
Hey, @Svish the promise resolve too fast, hence causing the animation not to finish. I have to dig deeper to see what would be the best way to fix this issue given that if you use a custom animation it can become trickier. It's similar to #725. You can use this workaround for now
```tsx
  <button
        onClick={() =>
          toast.promise(new Promise((_, reject) => setTimeout(reject, 200)), {
            success: "Success",
            pending: "Pending ...",
            //adding artificial delay here
            error: {render: "Error", delay: 500}
          })
        }
      >
        No bounce
      </button>

// can be done for all states as well
 <button
        onClick={() =>
          toast.promise(new Promise((_, reject) => setTimeout(reject, 200)), {
            success: "Success",
            pending: "Pending ...",
            error: "Error",

          }, {
            delay: 500
          })
        }
      >
        No bounce
      </button>
```
