### ISSUE TITLE
Can someone explain this 'px' here 

### ISSUE THREAD

**Issue by andelkocvjetkovic** [fkhadra/react-toastify#925]
https://github.com/fkhadra/react-toastify/blob/80bf024d2f72fe6ac55a437ae334f3e8393ec59f/scss/_toastContainer.scss#L3

**Comment by shikhar360** [comment]
The pixel in the end indicate that the value of the --toastify-z-index will be measured in pixels . It is just normal css like (transform : translateX(50px)) , instead here we have used -webkit-transform with translate3d which takes 3 arguments x ,y , z axis.

**Comment by fkhadra** [comment]
@andelkocvjetkovic indeed.

**Comment by andelkocvjetkovic** [comment]
I wouldn't say so https://codepen.io/andelkocvjetkovic/pen/JjaMRYw

**Comment by fkhadra** [comment]
@andelkocvjetkovic actually you're right, I don't remember where this `px` is coming from. Fixing it in my current PR. Thanks for spotting it

**Comment by xsjcTony** [comment]
Removing `px` seems still doesn't make it a valid CSS from my perspective, as `translate3d(0, 0, 100)` (assume it's `100`) in this case without a unit does totally nothing right?
