### ISSUE TITLE
react-toastify.esm.mjs:1 Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by peipei818** [fkhadra/react-toastify#935]
- "react-toastify": "^9.0.8",
+ "react-toastify": "^9.1.2",

when i upgrade react-toastify V9.0.8 to V9.1.2，i click the toast about success to closing this toast，it will report an error。

      toast.success('复制成功', {
        position: 'top-center',
        autoClose: 3000,
        transition: Slide,
      });

error: Unable to preventDefault inside passive event listener invocation.

**Comment by thangcx-3383** [comment]
I face the same issue, somehow package have conflict between closeOnClick and draggable
Made it work by set `draggable = false`

**Comment by NaranjargalXD** [comment]
I've got the same, @peipei818 did you find a way to fix

**Comment by groom7** [comment]
> Я сталкиваюсь с той же проблемой, как у пакета есть конфликт между closeOnClick и draggale. Заставил его работать по набору`draggable = false`

This solved the problem "toast.error(error.message, { draggable: false });"

**Comment by vctormb** [comment]
> same here, would like to keep draggable feature.

same here

**Comment by HyopeR** [comment]
This problem persists in version 9.1.3.
There is no such problem in version 8.2.0. The drag and click action works. You can use this version temporarily.
