### ISSUE TITLE
 Cannot read properties of null (reading 'useReducer')  at useReducer (react.development.js:1626:1) - The above error occurred in the <ToastContainer> component:

### ISSUE THREAD

**Issue by PayalSasmal10** [fkhadra/react-toastify#936]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am getting the below error when I am adding the ToastConatiner component in my code 
```javascript
react.development.js:209 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useReducer @ react.development.js:1625
C @ useToastContainer.ts:52
(anonymous) @ ToastContainer.tsx:15
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react.development.js:1626 Uncaught TypeError: Cannot read properties of null (reading 'useReducer')
    at useReducer (react.development.js:1626:1)
    at C (useToastContainer.ts:52:1)
    at ToastContainer.tsx:15:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
useReducer @ react.development.js:1626
C @ useToastContainer.ts:52
(anonymous) @ ToastContainer.tsx:15
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performConcurrentWorkOnRoot @ react-dom.development.js:25750
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <ToastContainer> component:

    at http://localhost:3000/static/js/bundle.js:77016:11
    at Registration (http://localhost:3000/static/js/bundle.js:120:88)
    at div
    at App

Consider adding an error boundary to your tree to customize error-handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
1. NPM version- 7.6.2
2. React version - 18.2.0
3. React-dom version - 18.2.0
4. react-toastify version- 9.1.2

**What is the expected behavior?**
It should not give the error with all the latest versions.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
18.2.0 and Ubuntu(20.04)

**Comment by anhminhtran235** [comment]
I had the same issue. Turns out, I installed `react-toastify` in my server directory instead of client

**Comment by PayalSasmal10** [comment]
This is not a solution I guess. I am using it for my client, why should we install react-toastify under server?

**Comment by anhminhtran235** [comment]
No, I meant that I installed it wrong. I should have installed it under client, but I did it under server which is the cause of my issue

**Comment by PayalSasmal10** [comment]
Oh OK. No, I haven't installed it under server folder.

**Comment by SudhanshuTiwari** [comment]
Is this issue resolved?
Even i am facing the same issue.
react:  18.2.0
react-dom :  8.2.0
react-toastify:  9.1.1

**Comment by SudhanshuTiwari** [comment]
Downgrading react-toastify: 9.1.1 to react-toastify: 8.2.0 worked for me.

**Comment by yyd1142** [comment]
If you used with Next.js, [check this out](https://github.com/fkhadra/react-toastify/issues/889)

**Comment by PayalSasmal10** [comment]
It worked for me. I followed the below steps but I did not understand the logic.

I uninstalled react-toastify first. 
Then used the yarn package to install it again.
Then uninstalled the yarn-package too.
Install the react-toastify using the npm package again.

**Comment by Amaan-Samar** [comment]
I am getting the same error in blitzjs app but I am not using react-toastify.

**Comment by Amaan-Samar** [comment]
Server Error
TypeError: Cannot read properties of null (reading 'useReducer')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
React
useReducer
file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/next/node_modules/react/cjs/react.development.js (1626:21)
Next.js
useErrorOverlayReducer
file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/next/dist/client/components/react-dev-overlay/shared.js (87:34)
ReactDevOverlay
file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/next/dist/client/components/react-dev-overlay/pages/ReactDevOverlay.js (31:66)
ReactDevOverlay
file:///C:/Users/Administrator/AppData/Roaming/npm/node_modules/next/dist/server/dev/next-dev-server.js (100:12)
React
renderWithHooks
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderIndeterminateComponent
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5731:15)
renderElement
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:///C:/Users/Administrator/Music/dump/placemark/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
