### ISSUE TITLE
{type} not defined on toastClassName

### ISSUE THREAD

**Issue by omar-qayum** [fkhadra/react-toastify#939]
In the docs it says this for styling:
**const contextClass = {
  success: "bg-blue-600",
  error: "bg-red-600",
  info: "bg-gray-600",
  warning: "bg-orange-400",
  default: "bg-indigo-600",
  dark: "bg-white-600 font-gray-300",
};

const App = ()=> {
  return (
   <Main />
   <ToastContainer
      toastClassName={({ type }) => contextClass[type || "default"] +
        " relative flex p-1 min-h-10 rounded-md justify-between overflow-hidden cursor-pointer"
      }
      bodyClassName={() => "text-sm font-white font-med block p-3"}
      position="bottom-left"
      autoClose={3000}
    />
  )
}**

I am running v9 but {type} does not exist on toastClassName. Is the doc correct?

**Comment by omar-qayum** [comment]
It works but TS is throwing this error:
Property 'type' does not exist on type '{ type?: TypeOptions | undefined; defaultClassName?: string | undefined; position?: ToastPosition | undefined; rtl?: boolean | undefined; } | undefined'.ts(2339)

**Comment by fkhadra** [comment]
@omar-qayum could yu share a sandbox with you issue please.

**Comment by Joel-Mercier** [comment]
Hello thank you for this cool library ! 
Here is a link to a [sandbox ](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCtEljgG84AVCFAZxgGEIA7GFMF5IoAGjgw2nOAF842XASLoYAWkkcYwTAE8yNcNHiFiajZ206A9ABNgnK8hWtNlgHRp27fdUpo+0v78SAAe3AA2HOxwALyMVHCJcOwArmhoSF4AXHAARABGAOaq+eEpSKoAbAAM1bmiCUkiOFA5BcVENlW19Y2JQpgQbUWqhVAoOt11DZRJcADuKFC8QoXDxdAovIUVACw9M3M2SJgoKeEw66pCdoUQU72zSTZLANZX8wAWwDAVNdXyPhqMYTVQAZgOVBkFF8VEwKV4GGAfDgAEEwGAABQASgYfTgQWkvAgWl0sTgONiAD4JFIYJjcgB1CDzZIQOCodg6ACEuWxMPxRBgKWWFPxiQAPHYAG5U8VJCX5FIwSS8OB8LjhYBoV4xBjE0k6GRUgByJMs3IlViVKr4cqec0lLk4PH4gmEUHljtpmk1URNKBASD1mKYMB0YCQsmx1IJQNCESiAG1w5G4AAfdN5Y6nc4wXIAXTgAGovd6krk4ERIlppVHMOFQnAwKoAIxwEBCVSfNsAnAI45dEA2OAAKxSFl0JSQMHmSCQaogdagDZZ3eANmOarQIvY0FUkCEvyguTLcxkZ6S+QgNh0fq8AaDIZjMRpuV+YVU7Dwg34qi+Pz1kCqhBiOpQQDqzbgrkF4OuWiSQOwPzIrwMQFCSkggKojaYPml6JGckiahA7DBgwEK1LB8FWPa3pWjKtFJPyUJAA) showing the typescript error (right panel under the "Errors" tab)

The example is taken from your documentation [here](https://fkhadra.github.io/react-toastify/how-to-style#css-classes-as-function)

**Comment by matthewmcintyre** [comment]
Try doing something like this:

```
<ToastContainer
  position="top-center"
  toastClassName={(context) =>
    contextClass[context?.type ?? 'default'] +
    ' relative flex p-1 min-h-10 rounded-lg justify-between overflow-hidden cursor-pointer'
  }
  bodyClassName={() => 'text-sm font-white font-med block p-3'}
/>
```

credit to this issue: https://github.com/fkhadra/react-toastify/issues/914
