### ISSUE TITLE
{FEATURE} Add title to notifications

### ISSUE THREAD

**Issue by Sheikh-JamirAlam** [fkhadra/react-toastify#940]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently notifications look really good, but I wonder if there was a feature where we can add a title to the notifications? I think it would look good.
![image](https://user-images.githubusercontent.com/48979376/229607950-32e14630-6fd1-476c-bfef-5db77f95c5b9.png)

**What is the expected behavior?**
Here is an example from react-semantic-toasts.
![image](https://user-images.githubusercontent.com/48979376/229607911-69024a67-c901-4d5f-aedc-079801f3040a.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by bunnyxt** [comment]
Maybe customize render component is enough?

https://github.com/fkhadra/react-toastify/issues/243
