### ISSUE TITLE
Are useToastContainer and useToast hooks usable?

### ISSUE THREAD

**Issue by ling1726** [fkhadra/react-toastify#941]
Hi,

I've evaluating react-toastify for the Fluent UI design system at Microosft. There's huge feature set and it looks like it could handle most of our use cases, really great job 👍.

I do see that there is a lot of code in the components, that determine the different slots and layouts of the Toast. I know that it's possible to render an entire JSX toast with `toast(<MyToast />)` however, a lot of the unused internal code in this case would still be in the bundle. We would be looking to create completely different kinds of Toast content and styles, so reducing the amount of unused code is quite important to us.

Are the headless hooks ready to be used, and is there going to be future support for them? We'd be happy to help report any issues and help contributing if you intend to keep the hooks and keep working on them.

**Comment by fkhadra** [comment]
Hey @ling1726, better late than never. Sorry if I didn't take the time to answer back then and thank you for considering using my library back then 🙏🏽.  
Most likely you addressed your issue 😆, I'll close the issue and wish you the best.
