### ISSUE TITLE
onClick function for a toast?

### ISSUE THREAD

**Issue by khawerrind** [fkhadra/react-toastify#95]
Thank you for the great plugin. It will be nice to have an `onClick` function for a toast so if it is defined than `closeOnClick` will be ignored and user can perform manual operations on a toast. 

```
Assume i am creating a messaging application,
User has 3 new messages notifications (toasts)
User click on toast 1
User may want to dismiss all other toasts and take the user to the clicked message
```

This is currently not possible and can be possible if we can have `onClick` function for a toast. Thoughts?

**Comment by khawerrind** [comment]
Thank you @fkhadra i figured that out later 😄 I have another question should i ask it in this thread?

**Comment by fkhadra** [comment]
Go ahead 😁

**Comment by khawerrind** [comment]
Is it currently possible to limit the total number of toasts? If not, do you think it is something that can be considered to work on?

**Comment by fkhadra** [comment]
You mean the total number of toast being displayed at the same time, right?

**Comment by khawerrind** [comment]
yes right

**Comment by fkhadra** [comment]
@khawerrind here is how you can accomplish it:

[![Edit 0orx2wjkyn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0orx2wjkyn)

I'm considering adding it

**Comment by khawerrind** [comment]
Thanks @fkhadra when you add it to library i think it will be better if you don't block the new toasts and instead have it the following way 

If newestOnTop {
    append at top and remove the last toast
} else {
   append at bottom and remove the first one
}

Thanks!
