### ISSUE TITLE
Documentation is incomplete and insufficient

### ISSUE THREAD

**Issue by thujone** [fkhadra/react-toastify#954]
**Do you want to request a *feature* or report a *bug*?**
I would say it's more a bug than a feature

**What is the current behavior?**
The API documentation is incomplete, it's kind of hard to learn how to use it exactly. There is a page with a bunch of examples, but this should only be in addition to the API reference definitions -- not to supplant them entirely. For example, there are no method definitions, and it's unclear that you can pass a component as the toast itself, except a couple of single-line examples thrown in random order in one of the doc pages.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
Take the time and complete and improve the documentation.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by fkhadra** [comment]
Contributions are welcome! 🙂
