### ISSUE TITLE
Can't change zIndex

### ISSUE THREAD

**Issue by bogdansoare** [fkhadra/react-toastify#96]
Hey there.

Is there anyway to change the zIndex ? I want it bigger than 999.

I've tried with 
```
style({
  zIndex: 9999
});
```
but no luck.

Thanks.

**Comment by fkhadra** [comment]
Hey @bogdansoare,

You will be able to adjust the zIndex like you did in the next release.

**Comment by bogdansoare** [comment]
Awesome, thanks @fkhadra ❤️
