### ISSUE TITLE
No toast shown in Nextjs 13

### ISSUE THREAD

**Issue by qnxdev** [fkhadra/react-toastify#963]
Report Bug

No toast shown

Nextjs 13 

Install package
Import react-toastify css in /src/app/layout.tsx
Import <ToastContainer/> and place it in JSX in /src/app/layout.tsx
Call  toast("hi) in any page.

Toast should appear

Nextjs 13
Brave browser

**Comment by qnxdev** [comment]
Solution: I was able to solve this by adding <ToaastCContainer/>  to the current page at /app/myPage/page.tsx

Seems like a temporary solution but fine with me

**Comment by matheusgit1** [comment]
don't forget to import toast css

**Comment by matheusgit1** [comment]
don't forget to import toast css


`
"use client";
import "react-toastify/dist/ReactToastify.css"; //add this line

import { ToastContainer } from "react-toastify";

interface ToastProviderProps {
  children: React.ReactNode;
}

export default function ToastProvider({ children }: ToastProviderProps) {
  return (
    <>
      {children}
      <ToastContainer />
    </>
  );
}

**Comment by MarcinSkic** [comment]
Simplest solution is to not even use `{children}`,  just create client side wrapper and put it in root wherever you need (layout for example). CSS import is very important, without it nothing happens
```tsx
"use client";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function ToastContainerWrapper() {
    return (
        <ToastContainer position={toast.POSITION.BOTTOM_CENTER} theme="dark" />
    );
}
```
Example usage:
```tsx
export default function Layout({ children }: React.PropsWithChildren) {

    return (
        <div className={styles["component-default-layout"]}>
            <aside>
                <a href="/">Home</a>
                <a href="/all">Everything list</a>
                <a href="/movie/all">Movies table</a>
                <a href="/person/all">People table</a>
            </aside>
            <main className="content">{children}</main>
            <ToastContainerWrapper />
        </div>
    );
}
```

**Comment by Ngash01** [comment]
@nokwin your I did exactly how you implemented it and it worked!

**Comment by IvanAdmaers** [comment]
> Simplest solution is to not even use `{children}`, just create client side wrapper and put it in root wherever you need (layout for example). CSS import is very important, without it nothing happens
> 
> ```tsx
> "use client";
> 
> import { ToastContainer, toast } from "react-toastify";
> import "react-toastify/dist/ReactToastify.css";
> 
> export default function ToastContainerWrapper() {
>     return (
>         <ToastContainer position={toast.POSITION.BOTTOM_CENTER} theme="dark" />
>     );
> }
> ```
> 
> Example usage:
> 
> ```tsx
> export default function Layout({ children }: React.PropsWithChildren) {
> 
>     return (
>         <div className={styles["component-default-layout"]}>
>             <aside>
>                 <a href="/">Home</a>
>                 <a href="/all">Everything list</a>
>                 <a href="/movie/all">Movies table</a>
>                 <a href="/person/all">People table</a>
>             </aside>
>             <main className="content">{children}</main>
>             <ToastContainerWrapper />
>         </div>
>     );
> }
> ```

I believe this is the best solution. Provider from @nokwin looks kinda redundant like for me

**Comment by rusty120** [comment]
@nokwin Won't including `'use client'` in the `ToastProvider` prevent server-side rending for most of your app? This seems like a big disadvantage, unless I'm missing something?

@MarcinSkic solution isolates the client rendering to just the toast wrapper, which would preferable for most cases.

**Comment by MarcinSkic** [comment]
@rusty120 no, there can be server side rendered components as children of client side components, otherwise any ContextProvider would prevent most of the app from being SSR, you can find more information here:
https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props and here
 https://github.com/vercel/next.js/discussions/43153
