### ISSUE TITLE
ERROR in ./node_modules/react-toastify/lib/ToastContainer.js

### ISSUE THREAD

**Issue by JaLe29** [fkhadra/react-toastify#97]
I am getting error after call npm start in my project with react-toastify,

Solution for this problem is install "glamor": "^2.20.40" to my project, but why? Its your dependency, not my.

> ERROR in ./node_modules/react-toastify/lib/DefaultCloseButton.js
> Module not found: Error: Can't resolve 'glamor' in 'C:\GIT\osobni\red-face\node_modules\react-toastify\lib'
>  @ ./node_modules/react-toastify/lib/DefaultCloseButton.js 18:14-31
>  @ ./node_modules/react-toastify/lib/ToastContainer.js
>  @ ./node_modules/react-toastify/lib/index.js
> .
> .
> .
>

**Comment by fkhadra** [comment]
Hey,

I saw that for red-face you were using react-toastify v2. What you could do is the following:

```js
npm remove react-toastify
npm install --save react-toastify@latest
```

**Comment by JaLe29** [comment]
Thank you.

It fixed problem with 'glamor' lib.

But now, I am getting error about ReactToastify.min.css after npm run is called.
Actual version (after install lastest version) "react-toastify": "^3.0.0"

Full log:

> ERROR in ./src/components/common/Footer.jsx
> Module not found: Error: Can't resolve 'react-toastify/dist/ReactToastify.min.css' in 'C:\GIT\osobni\red-face\src\components\common'
>  @ ./src/components/common/Footer.jsx 17:0-52
>  @ ./src/components/pages/App.jsx
>  @ ./src/components/pages/Router.jsx
>  @ ./src/main.jsx
>  @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/main.jsx
>

**Comment by fkhadra** [comment]
@JaLe29,

Since v3 I switched to glamor. There is no more css files involved now, so you don't need to import the css file anymore.

**Comment by JaLe29** [comment]
Thank you for your help.

Now, it working correctly.
