### ISSUE TITLE
Warning: ToastContainer: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by marquesm91** [fkhadra/react-toastify#970]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When I am trying to use `react-toastify` with `react@18.2.0` I am getting this warning. The React [MR](https://github.com/facebook/react/pull/25699) to print this warning on console is here.

I am pretty sure this is a small refactor to remove this warning and I could work on that 😄 

![Captura de Tela 2023-06-07 às 14 36 20](https://github.com/fkhadra/react-toastify/assets/7120471/0e3d71be-2c0a-427c-ab69-854e187b7c36)

```
Warning: ToastContainer: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

**What is the expected behavior?**
No warning should appear

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 18.2

**Comment by fkhadra** [comment]
Hey this is addressed in v10, I'm currently working on it

**Comment by maiveasna24** [comment]
got this issues in next-js version 14

**Comment by rwb196884** [comment]
Still broken in 10.0.5

**Comment by ajmeese7** [comment]
@fkhadra is there any movement on this? It does not impede my dev in any way, but if we could get rid of the console warning that would be super cool 😄 

I don't see any open issues or PRs, otherwise I would try to assist.

**Comment by fkhadra** [comment]
Hey @ajmeese7, defaultProps have been removed already 🤔

**Comment by ajmeese7** [comment]
You're absolutely right, I forgot to update my dep 😭 my mistake
