### ISSUE TITLE
Boilerplate Next.js 13.4 Not Working

### ISSUE THREAD

**Issue by douglasrcjames** [fkhadra/react-toastify#977]
Hi!

First off, love the library, appreciate what you've built. Has worked create for me on my CRA projects. 

I am moving to Next.js and found that my fav alert library isn't working out of the box. Is there some special config for Next.js 13.4 we need? This could be a bug!

Reproduced by this code pen: https://codesandbox.io/p/sandbox/cocky-meninsky-q264zj?file=%2Fapp%2Fpage.tsx%3A2%2C1

**Expected Behavior**
Show alert on button press.

**Stack**
Next.js 13.4.0
TypeScript
Chrome
Windows

**Comment by fkhadra** [comment]
Hey @douglasrcjames, thanks for using the library, and sorry to hear that you encountered some issues. I'm actively working on the next major release, the documentation will be updated simultaneously.

Meanwhile, you can check this https://github.com/fkhadra/react-toastify/issues/963#issuecomment-1562754379

**Comment by douglasrcjames** [comment]
Awesome, thanks for the reference, sorry I missed that post! I have it up and running in Next.js 13 now following that post!
