### ISSUE TITLE
Export the decorate function

### ISSUE THREAD

**Issue by morozovamv** [fkhadra/react-toastify#979]
**Do you want to request a *feature* or report a *bug*?**
Request a feature.

**What is the current behavior?**
When adding an initial data to the notification center all items have to be decorated, in the current implementation it can be done only manually.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
[CodeSandbox: react-toastify-decorate](https://codesandbox.io/s/react-toastify-decorate-pksnvl)

**What is the expected behavior?**
The `decorate` function is exported so it's possible to reuse it.

**Comment by fkhadra** [comment]
Hey @morozovamv, I'll export it in v10 :)
