### ISSUE TITLE
Can toasts display over a video playing in fullscreen?

### ISSUE THREAD

**Issue by catalinandreipreda** [fkhadra/react-toastify#982]
**Do you want to request a *feature* or report a *bug*?**

Question/feature request

**What is the current behavior?**

I have a video player ([Shaka](https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) if it makes a difference) and I display a toast when people toggle captions. Works well with the video minimised, but if it's playing in fullscreen the notifications don't overlay on top of the video so the user doesn't notice my disclaimer.

Can you please advise if react-toastify can do this? or you know other workarounds?

**What is the expected behavior?**

Toast is visible over fullscreen videos

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"react": "^17.0.2",
"next": "^12.1.0",
"react-toastify": "^9.1.3",

Chrome macos

**Comment by fkhadra** [comment]
Hey @catalinandreipreda, have you tried playing with z-index ? If you can share a codesanbox with the issue or share a repo I could take a look

**Comment by Ruttmann** [comment]
You can also use a portal. Search for createPortal on React docs.
