### ISSUE TITLE
Type Error in Readme documentation

### ISSUE THREAD

**Issue by ObaidAshiq** [fkhadra/react-toastify#983]
**Confusion In Feature Section for Progress bar bullet**

### In feature section for this particular bullet
You can control the progress bar **a la nprogress** 😲
What is it supposed to mean?

**Comment by fkhadra** [comment]
Hey @ObaidAshiq, the progress bar can be controlled. Useful to implement upload progress for example. See https://fkhadra.github.io/react-toastify/use-a-controlled-progress-bar/
