### ISSUE TITLE
Server components

### ISSUE THREAD

**Issue by HironTez** [fkhadra/react-toastify#984]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
No "use client" at the top of the ToastContainer file therefore it cannot be used in Server Components for example in layout.tsx if it's a Server Component

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 18/Nextjs 13

**Comment by fkhadra** [comment]
Hey @HironTez since last release, "use client" is added. You can also check https://github.com/fkhadra/react-toastify/issues/963
