### ISSUE TITLE
How do I exclude messages that I don't want to appear in the notification center?

### ISSUE THREAD

**Issue by maorz555** [fkhadra/react-toastify#988]
How do I exclude messages that I don't want to appear in the notification center?

**Comment by BhumikP** [comment]
Hi @maorz555  Can you explain your issue briefly so I can help you?
Please also share a codesandbox link with the given issue if possible.

**Comment by fkhadra** [comment]
Hey @maorz555, you could pass some custom property using the `data` prop and use that to filter out the one that you don't want to display.

```tsx
toast("hello", {
  data: {
    exclude: true
  }
})


function App(){
  const { notifications } = useNotificationCenter({
    filter: (item) => item.data.exclude === false
  })
}
```
