### ISSUE TITLE
[Feature Request] Fully centered position (not just top-center/bottom-center)

### ISSUE THREAD

**Issue by FFdhorkin** [fkhadra/react-toastify#994]
Feature request:

**What is the current behavior?**
`One of: 'top-right', 'top-center', 'top-left', 'bottom-right', 'bottom-center', 'bottom-left'`

**What is the desired behavior?**
I'd like an option that centers the toast that is centered both horizontally and vertically. Basically, mix bottom-center and top-center.

I realize this can probably be done with `css`, but an integrated option would be preferable.

**Comment by ShahriarKh** [comment]
+1 for this. I'm also thinking of `middle`, so we get 9 positions: `{top/middle/bottom}-{left/center/right}`

**Comment by fkhadra** [comment]
I'll close the issue for now as this can be achieved with css. I'll reconsider it if I have more requests for it.
