### ISSUE TITLE
 Bug - Incorrect Decreasing Limit Behavior for Toasts

### ISSUE THREAD

**Issue by mahmoudAcm** [fkhadra/react-toastify#996]
**Description:**
When setting the `limit` prop for toasts initially, the behavior of the limit is not working as expected. After displaying the initial set of toasts, the limit appears to decrease by one each time a toast disappears, which results in an unexpected and incorrect display of toasts.

**Steps to Reproduce:**
1. Configure the toast component with an initial `limit` prop, e.g., `limit={4}`.
2. Trigger multiple toasts to be displayed so that the limit is reached and 4 toasts are shown.
3. Observe the displayed toasts and the remaining limit.
4. Wait for the toasts to disappear one by one.

**Expected Behavior:**
- When the `limit` prop is set initially, the toast component should display the specified number of toasts as expected, e.g., 4 toasts.
- The `limit` prop should not decrease automatically as toasts disappear, ensuring the consistent display of toasts according to the initial limit.

**Actual Behavior:**
- Initially, the toast component displays the specified number of toasts correctly, e.g., 4 toasts.
- As toasts disappear, the `limit` prop appears to decrease by one each time, leading to an unexpected reduction in the number of displayed toasts.

This bug affects the intended behavior of the `limit` prop for the toast component and should be addressed to ensure a consistent and accurate display of toasts based on the specified limit.

**Comment by fkhadra** [comment]
I think this issue is addressed in the v10. Mind giving a try ? 
```sh
npm i react-toastify@beta
```

**Comment by mahmoudAcm** [comment]
I tried it, and it works perfectly fine! This issue has been resolved. Thank you @fkhadra for the fix.

**Comment by fkhadra** [comment]
Awesome thanks for testing I'm finishing the doc and I'll publish the v10 this week
